-- 
-- Table: conf.alarm_configs
--
INSERT INTO conf.alarm_configs
(alarm_config_id, alarm_type_id, alarm_level_id, element_type_id, element_id, element_type_state_id, mine, treatment, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
--Alarmas DAI, se evalúan a través de groovy --> CameraDetectorDaiAdapter.groovy
(1301, 2, 4, 2, NULL, 3, true, true, 'VEHICULO SENTIDO CONTRARIO', 'VEHICULO SENTIDO CONTRARIO', 'LBL_ALARM_CONFIGS_VEHICULO_SENTIDO_CONTRARIO', 'LBL_ALARM_CONFIGS_VEHICULO_SENTIDO_CONTRARIO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1302, 2, 4, 2, NULL, 3, true, true, 'OBJETO EN ARCEN IZQUIERDO', 'OBJETO EN ARCEN IZQUIERDO', 'LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_IZQUIERDO', 'LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_IZQUIERDO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1303, 2, 4, 2, NULL, 3, true, true, 'OBJETO EN ARCEN DERECHO', 'OBJETO EN ARCEN DERECHO', 'LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_DERECHO', 'LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_DERECHO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1304, 2, 4, 2, NULL, 3, true, true, 'VEHICULO LENTO EN ARCEN IZQUIERDO', 'VEHICULO LENTO EN ARCEN IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_IZQUIERDO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1305, 2, 4, 2, NULL, 3, true, true, 'VEHICULO LENTO EN ARCEN DERECHO', 'VEHICULO LENTO EN ARCEN DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_DERECHO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1306, 2, 4, 2, NULL, 3, true, true, 'OBJETO EN CARRIL IZQUIERDO', 'OBJETO EN CARRIL IZQUIERDO', 'LBL_ALARM_CONFIGS_OBJETO_EN_CARRIL_IZQUIERDO', 'LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_IZQUIERDO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1307, 2, 4, 2, NULL, 3, true, true, 'OBJETO EN CARRIL DERECHO', 'OBJETO EN CARRIL DERECHO', 'LBL_ALARM_CONFIGS_OBJETO_EN_CARRIL_DERECHO', 'LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_DERECHO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1308, 2, 4, 2, NULL, 3, true, true, 'VEHICULO LENTO EN CARRIL IZQUIERDO', 'VEHICULO LENTO EN CARRIL IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_CARRIL_IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_IZQUIERDO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1309, 2, 4, 2, NULL, 3, true, true, 'VEHICULO LENTO EN CARRIL DERECHO', 'VEHICULO LENTO EN CARRIL DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_CARRIL_DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_DERECHO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1310, 2, 4, 2, NULL, 3, true, true, 'PEATONES EN EL TUNEL', 'PEATONES EN EL TUNEL', 'LBL_ALARM_CONFIGS_PEATONES_TUNEL', 'LBL_ALARM_CONFIGS_PEATONES_TUNEL_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1311, 2, 4, 2, NULL, 3, true, true, 'VEHICULO DETENIDO EN ARCEN IZQUIERDO', 'VEHICULO DETENIDO EN ARCEN IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_ARCEN_IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_ARCEN_IZQUIERDO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1312, 2, 4, 2, NULL, 3, true, true, 'VEHICULO DETENIDO EN ARCEN DERECHO', 'VEHICULO DETENIDO EN ARCEN DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_ARCEN_DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_ARCEN_DERECHO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1313, 2, 4, 2, NULL, 3, true, true, 'VEHICULO DETENIDO EN CARRIL IZQUIERDO', 'VEHICULO DETENIDO EN CARRIL IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_CARRIL_IZQUIERDO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_CARRIL_IZQUIERDO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1314, 2, 4, 2, NULL, 3, true, true, 'VEHICULO DETENIDO EN CARRIL DERECHO', 'VEHICULO DETENIDO EN CARRIL DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_CARRIL_DERECHO', 'LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_CARRIL_DERECHO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 
-- Table: conf.alarm_configs.CAMERA
--
UPDATE conf.alarm_configs SET alarm_level_id = 1, enabled = True, treatment = False WHERE element_type_id = 2 AND alarm_config_id = 29; --LBL_ALARM_CONFIGS_ALARM_CAMERA_NO_CONNECTION
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1301; --LBL_ALARM_CONFIGS_VEHICULO_SENTIDO_CONTRARIO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1302; --LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_IZQUIERDO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1303; --LBL_ALARM_CONFIGS_OBJETO_EN_ARCEN_DERECHO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1304; --LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_IZQUIERDO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1305; --LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_ARCEN_DERECHO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1306; --LBL_ALARM_CONFIGS_OBJETO_EN_CARRIL_IZQUIERDO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1307; --LBL_ALARM_CONFIGS_OBJETO_EN_CARRIL_DERECHO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1308; --LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_CARRIL_IZQUIERDO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1309; --LBL_ALARM_CONFIGS_VEHICULO_LENTO_EN_CARRIL_DERECHO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1310; --LBL_ALARM_CONFIGS_PEATONES_TUNEL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1311; --LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_ARCEN_IZQUIERDO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1312; --LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_ARCEN_DERECHO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1313; --LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_CARRIL_IZQUIERDO
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1314; --LBL_ALARM_CONFIGS_VEHICULO_DETENIDO_EN_CARRIL_DERECHO
