UPDATE conf.alarm_configs SET alarm_level_id = 1, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 180065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_SHUTDOWN_IMMINENT
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 10065; --LBL_ALARM_CONFIGS_ALARM_SAI_NO_CONNECTION
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 20065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_BATTERY_BAD
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 30065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_ON_BATTERY
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 60065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_TEMPERATURE_BAD_DESC
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 80065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_OUTPUT_OVERLOAD
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 100065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_CHARGER_FAILED
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 110065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_UPS_OUTPUT_OFF
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 120065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_FAN_FAILURE
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 130065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_FUSE_FAILURE
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 140065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_DIAGNOSTIC_TEST_FAILED
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 170065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_SHUTDOWN_PENDING
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 190065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_TEST_IN_PROGRESS
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 200065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_GENERAL
UPDATE conf.alarm_configs SET alarm_level_id = 6, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 50065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_DEPLETED_BATTERY
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 40065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_LOW_BATTERY
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 70065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_INPUT_BAD
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 160065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_AWAITING_POWER
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 03000065; --LBL_ALARM_CONFIGS_ALARM_SAI_AUTONOMY_LESS_50
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 03010065; --LBL_ALARM_CONFIGS_ALARM_SAI_AUTONOMY_LESS_5
