DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'nogales_gip') THEN
  
INSERT INTO nogales_gip.sg_i18n_labels (locale_code, "label", "translation", created_at, updated_at) VALUES

-- Type_detection
--es_ES
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_ID', 'Id', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_CATEGORY', 'Categoría', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_TYPE', 'Tipo', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_TITLE', 'Título', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_ROAD_IMPACT', 'Afección', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_ROAD', 'Carretera', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_LOCATION', 'Localización', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_DATE', 'Fecha de creación', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_UPDATE_DATE', 'Fecha de actualización', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
	('es_ES','LBL_EXT_ENTITY_C4_COLUMN_STATE', 'Estado', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

	END IF;
END $$;