INSERT INTO conf.vms_graphic_groups (graphic_group_id, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(12, 'af', 'af', NULL, NULL, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.vms_graphic_groups_elements (graphic_group_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(12, 71, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 11, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 12, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 14, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 21, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 22, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 23, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 24, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 25, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 26, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 27, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 28, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 29, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 30, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 63, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 64, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 65, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 66, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 67, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 68, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 80, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 81, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 82, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 83, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 71, 84, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);



INSERT INTO conf.vms_graphic_graphic_group_values (graphic_type_id, graphic_id, graphic_group_id, value, enabled, visible, created_at, updated_at) VALUES
(1, 745,  12, '1' ,true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 746,  12, '2' ,true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 
