UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 10065; --LBL_ALARM_CONFIGS_ALARM_SAI_NO_CONNECTION
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 20065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_BATTERY_BAD
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 30065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_ON_BATTERY
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 40065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_LOW_BATTERY
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 50065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_DEPLETED_BATTERY
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 60065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_TEMPERATURE_BAD
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 80065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_OUTPUT_OVERLOAD
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 100065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_CHARGER_FAILED
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 110065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_UPS_OUTPUT_OFF
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 200065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_GENERAL
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 20010065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_BYPASS
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 20020065; --LBL_ALARM_CONFIGS_ALARM_SAI_CRITICAL
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 20030065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_OPEN_SWITCH_BB1
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 20040065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_OPEN_SWITCH_BB2
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 20050065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_BATTERY_IN_DISCHARGE
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 20060065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_LOW_LEVEL
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 20070065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_MEDIUM_LEVEL
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 65 AND alarm_config_id = 20080065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_CRITICAL_LEVEL
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 20090065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_HIGH_TEMPERATURE
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 65 AND alarm_config_id = 20100065; --LBL_ALARM_CONFIGS_ALARM_SAI_ALARM_EXCESIVE_LOAD
