element_type_id=translation
1=Estación meteorológica
2=Cámara
3=Detector
4=SECCIÓN
5=Servidor de megafonía
6=SEGMENTO
7=ZONE
8=Barrera
9=Ventilador
11=Poste SOS
12=Luxómetro
13=Semáforo 3 grupos
14=Luminancímetro
15=Zona de incendios
16=Zona de megafonía
17=GALIBO
18=Anemómetro interior
19=CO
20=NO
21=OPAC
22=Válvulas
23=Batería
24=BIE
25=EC
26=Switch
27=PLC
28=NAS
29=Central Fibrolaser
30=Sistema radio
31=Fotocélula
32=Presurización
33=Trafo
34=EC_SCN
36=Baliza
37=IPL
38=BUS-VAO
41=EC_ATC
42=EC_NRL
43=EC_NRS
44=EC_TFA_3D
45=EC_TFA_LOOPS
46=EC_TOLL
47=EC_TU
50=Vías
51=ETD
52=Servidor DAI
53=Semáforo 2 Grupos
54=ATC
55=Local técnico
56=Unifilar
57=Interruptor
58=Pulsador
59=Detector de humo
60=Sirena
61=Central puntual de incendios
65=SAI
66=Veleta
68=TFA_3D
70=Analizador de red
71=Panel de Mensaje Variable
74=ERU
75=Grupo electrógeno
81=VISIBILÍMETRO
82=ACELERÓMETRO
83=RADAR
84=Circuito eléctrico
85=Dali
86=Bomba
87=Depósito
88=Sensór pérdida de agua
89=Puerta
91=Bus Dali
93=Grupo de trasiego
94=Sistema de llamada
96=¿¿LBL_ELEMENT_TYPE_PA_GROUP??
1000=CC
2000=TUBO
2001=VENTILACIÓN
2002=ILUMINACIÓN
