INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(11, 1, 1, 0010011, NULL, NULL, 'RV-SOSE-1CA', 'RV-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 2, 0020011, NULL, NULL, 'RV-SOSE-2CA', 'RV-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 3, 0030011, NULL, NULL, 'RV-SOSE-1MA', 'RV-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 4, 0040011, NULL, NULL, 'RV-SOSE-2MA', 'RV-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 5, 0050011, NULL, NULL, 'RV-SOS-1CA', 'RV-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 6, 0060011, NULL, NULL, 'RV-SOS-1MA', 'RV-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 7, 0070011, NULL, NULL, 'MM-SOSE-2CA', 'MM-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 8, 0080011, NULL, NULL, 'MM-SOSE-1MA', 'MM-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 9, 0090011, NULL, NULL, 'MM-SOSE-1CA', 'MM-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 10, 0100011, NULL, NULL, 'MM-SOSE-2MA', 'MM-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 11, 0110011, NULL, NULL, 'MM-SOS-1MA', 'MM-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 12, 0120011, NULL, NULL, 'MM-SOS-2MA', 'MM-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 13, 0130011, NULL, NULL, 'MM-SOS-3MA', 'MM-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 14, 0140011, NULL, NULL, 'MM-SOS-1CA', 'MM-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 15, 0150011, NULL, NULL, 'MM-SOS-2CA', 'MM-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 16, 0160011, NULL, NULL, 'MM-SOS-3CA', 'MM-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 17, 0170011, NULL, NULL, 'STMI-SOSE-1MA', 'STMI-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 18, 0180011, NULL, NULL, 'STMI-SOSE-2CA', 'STMI-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 19, 0190011, NULL, NULL, 'STMI-SOSE-1CA', 'STMI-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 20, 0200011, NULL, NULL, 'STMI-SOSE-2MA', 'STMI-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 21, 0210011, NULL, NULL, 'STMI-SOS-1CA', 'STMI-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 22, 0220011, NULL, NULL, 'STMI-SOS-1MA', 'STMI-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 23, 0230011, NULL, NULL, 'LQ-SOS-1CA', 'LQ-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 24, 0240011, NULL, NULL, 'LQ-SOS-2CA', 'LQ-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 25, 0250011, NULL, NULL, 'LQ-SOS-3CA', 'LQ-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 26, 0260011, NULL, NULL, 'LQ-SOS-4CA', 'LQ-SOS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 27, 0270011, NULL, NULL, 'LQ-SOS-5CA', 'LQ-SOS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 28, 0280011, NULL, NULL, 'LQ-SOSE-1CA', 'LQ-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 29, 0290011, NULL, NULL, 'LQ-SOSE-2CA', 'LQ-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 30, 0300011, NULL, NULL, 'LQ-SOS-1MA', 'LQ-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 31, 0310011, NULL, NULL, 'LQ-SOS-2MA', 'LQ-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 32, 0320011, NULL, NULL, 'LQ-SOS-3MA', 'LQ-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 33, 0330011, NULL, NULL, 'LQ-SOS-4MA', 'LQ-SOS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 34, 0340011, NULL, NULL, 'LQ-SOSE-1MA', 'LQ-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 35, 0350011, NULL, NULL, 'LQ-SOSE-2MA', 'LQ-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 36, 0360011, NULL, NULL, 'CH-SOSE-1CA', 'CH-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 37, 0370011, NULL, NULL, 'CH-SOSE-2MA', 'CH-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 38, 0380011, NULL, NULL, 'CH-SOSE-2CA', 'CH-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 39, 0390011, NULL, NULL, 'CH-SOSE-1MA', 'CH-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 40, 0400011, NULL, NULL, 'CH-SOS-1MA', 'CH-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 41, 0410011, NULL, NULL, 'CH-SOS-2MA', 'CH-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 42, 0420011, NULL, NULL, 'CH-SOS-3MA', 'CH-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 43, 0430011, NULL, NULL, 'CH-SOS-1CA', 'CH-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 44, 0440011, NULL, NULL, 'CH-SOS-2CA', 'CH-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 45, 0450011, NULL, NULL, 'CH-SOS-3CA', 'CH-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 46, 0460011, NULL, NULL, 'NG-SOS-1CA', 'NG-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 47, 0470011, NULL, NULL, 'NG-SOS-2CA', 'NG-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 48, 0480011, NULL, NULL, 'NG-SOS-3CA', 'NG-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 49, 0490011, NULL, NULL, 'NG-SOS-4CA', 'NG-SOS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 50, 0500011, NULL, NULL, 'NG-SOS-5CA', 'NG-SOS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 51, 0510011, NULL, NULL, 'NG-SOS-6CA', 'NG-SOS-6CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 52, 0520011, NULL, NULL, 'NG-SOS-7CA', 'NG-SOS-7CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 53, 0530011, NULL, NULL, 'NG-SOS-8CA', 'NG-SOS-8CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 54, 0540011, NULL, NULL, 'NG-SOSE-1CA', 'NG-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 55, 0550011, NULL, NULL, 'NG-SOSE-2CA', 'NG-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 56, 0560011, NULL, NULL, 'NG-SOS-1MA', 'NG-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 57, 0570011, NULL, NULL, 'NG-SOS-2MA', 'NG-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 58, 0580011, NULL, NULL, 'NG-SOS-3MA', 'NG-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 59, 0590011, NULL, NULL, 'NG-SOS-4MA', 'NG-SOS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 60, 0600011, NULL, NULL, 'NG-SOS-5MA', 'NG-SOS-5MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 61, 0610011, NULL, NULL, 'NG-SOS-6MA', 'NG-SOS-6MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 62, 0620011, NULL, NULL, 'NG-SOS-7MA', 'NG-SOS-7MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 63, 0630011, NULL, NULL, 'NG-SOS-8MA', 'NG-SOS-8MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 64, 0640011, NULL, NULL, 'NG-SOSE-1MA', 'NG-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 65, 0650011, NULL, NULL, 'NG-SOSE-2MA', 'NG-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 66, 0660011, NULL, NULL, 'CAS-SOSE-1MA', 'CAS-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 67, 0670011, NULL, NULL, 'CAS-SOSE-2CA', 'CAS-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 68, 0680011, NULL, NULL, 'CAS-SOSE-2MA', 'CAS-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 69, 0690011, NULL, NULL, 'CAS-SOSE-1CA', 'CAS-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 70, 0700011, NULL, NULL, 'CAS-SOS-1MA', 'CAS-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 71, 0710011, NULL, NULL, 'CAS-SOS-2MA', 'CAS-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 72, 0720011, NULL, NULL, 'CAS-SOS-3MA', 'CAS-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 73, 0730011, NULL, NULL, 'CAS-SOS-4MA', 'CAS-SOS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 74, 0740011, NULL, NULL, 'CAS-SOS-5MA', 'CAS-SOS-5MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 75, 0750011, NULL, NULL, 'CAS-SOS-1CA', 'CAS-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 76, 0760011, NULL, NULL, 'CAS-SOS-2CA', 'CAS-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 77, 0770011, NULL, NULL, 'CAS-SOS-3CA', 'CAS-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 78, 0780011, NULL, NULL, 'CAS-SOS-4CA', 'CAS-SOS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 79, 0790011, NULL, NULL, 'CAS-SOS-5CA', 'CAS-SOS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 80, 0800011, NULL, NULL, 'COR-SOS-1CA', 'COR-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 81, 0810011, NULL, NULL, 'COR-SOS-2CA', 'COR-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 82, 0820011, NULL, NULL, 'COR-SOS-3CA', 'COR-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 83, 0830011, NULL, NULL, 'COR-SOS-4CA', 'COR-SOS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 84, 0840011, NULL, NULL, 'COR-SOS-1MA', 'COR-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 85, 0850011, NULL, NULL, 'COR-SOS-2MA', 'COR-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 86, 0860011, NULL, NULL, 'COR-SOS-3MA', 'COR-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 87, 0870011, NULL, NULL, 'COR-SOS-4MA', 'COR-SOS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 88, 0880011, NULL, NULL, 'COR-SOSE-1MA', 'COR-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 89, 0890011, NULL, NULL, 'COR-SOSE-2MA', 'COR-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 90, 0900011, NULL, NULL, 'COR-SOSE-1CA', 'COR-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 91, 0910011, NULL, NULL, 'COR-SOSE-2CA', 'COR-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 92, 0920011, NULL, NULL, 'EST-SOSE-1CA', 'EST-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 93, 0930011, NULL, NULL, 'EST-SOSE-2CA', 'EST-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 94, 0940011, NULL, NULL, 'EST-SOSE-1MA', 'EST-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 95, 0950011, NULL, NULL, 'EST-SOSE-2MA', 'EST-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 96, 0960011, NULL, NULL, 'EST-SOS-1CA', 'EST-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 97, 0970011, NULL, NULL, 'EST-SOS-1MA', 'EST-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 98, 0980011, NULL, NULL, 'STM2-SOS-1CA', 'STM2-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 99, 0990011, NULL, NULL, 'STM2-SOS-2CA', 'STM2-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 100, 1000011, NULL, NULL, 'STM2-SOS-3CA', 'STM2-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 101, 1010011, NULL, NULL, 'STM2-SOS-1MA', 'STM2-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 102, 1020011, NULL, NULL, 'STM2-SOS-2MA', 'STM2-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 103, 1030011, NULL, NULL, 'STM2-SOS-3MA', 'STM2-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 104, 1040011, NULL, NULL, 'STM2-SOSE-1MA', 'STM2-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 105, 1050011, NULL, NULL, 'STM2-SOSE-2MA', 'STM2-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 106, 1060011, NULL, NULL, 'STM2-SOSE-1CA', 'STM2-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 107, 1070011, NULL, NULL, 'STM2-SOSE-2CA', 'STM2-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(11, 1003, 1, 1, NULL, 'RV-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 2, NULL, 'RV-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 3, NULL, 'RV-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 4, NULL, 'RV-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 5, NULL, 'RV-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 6, NULL, 'RV-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 7, NULL, 'MM-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 8, NULL, 'MM-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 9, NULL, 'MM-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 10, NULL, 'MM-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 11, NULL, 'MM-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 12, NULL, 'MM-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 13, NULL, 'MM-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 14, NULL, 'MM-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 15, NULL, 'MM-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 16, NULL, 'MM-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 17, NULL, 'STMI-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 18, NULL, 'STMI-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 19, NULL, 'STMI-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 20, NULL, 'STMI-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 21, NULL, 'STMI-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 22, NULL, 'STMI-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 23, NULL, 'LQ-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 24, NULL, 'LQ-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 25, NULL, 'LQ-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 26, NULL, 'LQ-SOS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 27, NULL, 'LQ-SOS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 28, NULL, 'LQ-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 29, NULL, 'LQ-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 30, NULL, 'LQ-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 31, NULL, 'LQ-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 32, NULL, 'LQ-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 33, NULL, 'LQ-SOS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 34, NULL, 'LQ-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 35, NULL, 'LQ-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 36, NULL, 'CH-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 37, NULL, 'CH-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 38, NULL, 'CH-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 39, NULL, 'CH-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 40, NULL, 'CH-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 41, NULL, 'CH-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 42, NULL, 'CH-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 43, NULL, 'CH-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 44, NULL, 'CH-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 45, NULL, 'CH-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 46, NULL, 'NG-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 47, NULL, 'NG-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 48, NULL, 'NG-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 49, NULL, 'NG-SOS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 50, NULL, 'NG-SOS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 51, NULL, 'NG-SOS-6CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 52, NULL, 'NG-SOS-7CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 53, NULL, 'NG-SOS-8CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 54, NULL, 'NG-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 55, NULL, 'NG-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 56, NULL, 'NG-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 57, NULL, 'NG-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 58, NULL, 'NG-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 59, NULL, 'NG-SOS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 60, NULL, 'NG-SOS-5MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 61, NULL, 'NG-SOS-6MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 62, NULL, 'NG-SOS-7MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 63, NULL, 'NG-SOS-8MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 64, NULL, 'NG-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 65, NULL, 'NG-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 66, NULL, 'CAS-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 67, NULL, 'CAS-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 68, NULL, 'CAS-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 69, NULL, 'CAS-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 70, NULL, 'CAS-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 71, NULL, 'CAS-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 72, NULL, 'CAS-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 73, NULL, 'CAS-SOS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 74, NULL, 'CAS-SOS-5MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 75, NULL, 'CAS-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 76, NULL, 'CAS-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 77, NULL, 'CAS-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 78, NULL, 'CAS-SOS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 79, NULL, 'CAS-SOS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 80, NULL, 'COR-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 81, NULL, 'COR-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 82, NULL, 'COR-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 83, NULL, 'COR-SOS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 84, NULL, 'COR-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 85, NULL, 'COR-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 86, NULL, 'COR-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 87, NULL, 'COR-SOS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 88, NULL, 'COR-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 89, NULL, 'COR-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 90, NULL, 'COR-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 91, NULL, 'COR-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 92, NULL, 'EST-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 93, NULL, 'EST-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 94, NULL, 'EST-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 95, NULL, 'EST-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 96, NULL, 'EST-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 97, NULL, 'EST-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 98, NULL, 'STM2-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 99, NULL, 'STM2-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 100, NULL, 'STM2-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 101, NULL, 'STM2-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 102, NULL, 'STM2-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 103, NULL, 'STM2-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 104, NULL, 'STM2-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 105, NULL, 'STM2-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 106, NULL, 'STM2-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 107, NULL, 'STM2-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(11, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 41, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 42, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 43, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 44, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 45, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 46, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 47, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 48, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 49, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 50, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 51, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 52, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 53, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 54, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 55, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 56, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 57, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 58, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 59, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 60, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 61, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 62, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 63, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 64, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 65, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 66, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 67, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 68, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 69, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 70, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 71, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 72, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 73, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 74, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 75, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 76, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 77, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 78, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 79, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 80, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 81, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 82, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 83, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 84, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 85, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 86, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 87, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 88, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 89, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 90, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 91, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 92, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 93, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 94, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 95, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 96, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 97, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 98, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 99, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 100, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 101, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 102, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 103, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 104, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 105, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 106, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 107, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
