INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(60, NULL, 1, 0010060, NULL, NULL, 'RV-CT-CGBT-SIR-1', 'RV-CT-CGBT-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 2, 0020060, NULL, NULL, 'RV-CT-PCI-SIR-1', 'RV-CT-PCI-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 3, 0030060, NULL, NULL, 'MM-CT-CGBT-SIR-1', 'MM-CT-CGBT-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 4, 0040060, NULL, NULL, 'MM-CT-PCI-SIR-1', 'MM-CT-PCI-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 5, 0050060, NULL, NULL, 'STMI-CT-CGBT-SIR-1', 'STMI-CT-CGBT-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 6, 0060060, NULL, NULL, 'CAS-CT-PCI-SIR-1', 'CAS-CT-PCI-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 7, 0070060, NULL, NULL, 'CAS-CT-CGBT-BC-SIR-1', 'CAS-CT-CGBT-BC-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 8, 0080060, NULL, NULL, 'CAS-CT-CGBT-BM-SIR-1', 'CAS-CT-CGBT-BM-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 9, 0090060, NULL, NULL, 'CH-CT-CGBT-SIR-1', 'CH-CT-CGBT-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 10, 0100060, NULL, NULL, 'CH-CT-PCI-SIR-1', 'CH-CT-PCI-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 11, 0110060, NULL, NULL, 'EST-CT-CGBT-SIR-1', 'EST-CT-CGBT-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 12, 0120060, NULL, NULL, 'LQ-CT-CGBT-SIR-1', 'LQ-CT-CGBT-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 13, 0130060, NULL, NULL, 'LQ-CT-PCI-SIR-1', 'LQ-CT-PCI-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 14, 0140060, NULL, NULL, 'NG-CT-CGBT-SIR-1', 'NG-CT-CGBT-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 15, 0150060, NULL, NULL, 'NG-CT-PCI-SIR-1', 'NG-CT-PCI-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 16, 0160060, NULL, NULL, 'COR-CT-CGBT-BM-SIR-1', 'COR-CT-CGBT-BM-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 17, 0170060, NULL, NULL, 'COR-CT-CGBT-BC-SIR-1', 'COR-CT-CGBT-BC-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, NULL, 18, 0180060, NULL, NULL, 'COR-CT-PCI-SIR-1', 'COR-CT-PCI-SIR-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(60, 1003, 1, 1, NULL, 'RV-CT-CGBT-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 2, NULL, 'RV-CT-PCI-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 3, NULL, 'MM-CT-CGBT-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 4, NULL, 'MM-CT-PCI-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 5, NULL, 'STMI-CT-CGBT-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 6, NULL, 'CAS-CT-PCI-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 7, NULL, 'CAS-CT-CGBT-BC-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 8, NULL, 'CAS-CT-CGBT-BM-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 9, NULL, 'CH-CT-CGBT-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 10, NULL, 'CH-CT-PCI-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 11, NULL, 'EST-CT-CGBT-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 12, NULL, 'LQ-CT-CGBT-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 13, NULL, 'LQ-CT-PCI-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 14, NULL, 'NG-CT-CGBT-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 15, NULL, 'NG-CT-PCI-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 16, NULL, 'COR-CT-CGBT-BM-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 17, NULL, 'COR-CT-CGBT-BC-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(60, 1003, 1, 18, NULL, 'COR-CT-PCI-SIR-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(60, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(60, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
