DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'alarms_backoffice') THEN
  
    INSERT INTO alarms_backoffice.sg_i18n_labels (locale_code, "label", "translation", created_at, updated_at) VALUES

	-- 
  	-- alarms_backoffice.sg_metadata_columns
  	--
    --es_ES
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT_TYPE', 'Tipo de equipo', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ALARM', 'Alarma', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_NORMALIZE_PROCEDURES', 'Procedimiento para normalizar', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_POSSIBLE_CAUSES', 'Posibles causas', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_RESPONSIBILITIES', 'Responsable', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_COMMENTS', 'Comentarios', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_REVISED_ALARM', 'Alarma reisada', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ACTIVATION', 'Fecha de activación', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT', 'Equipo', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_REVISED_ALARMS', 'Mantenimiento', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

    --en_GB
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT_TYPE', 'Element type', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ALARM', 'Alarms', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_NORMALIZE_PROCEDURES', 'Normalize procedure', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_POSSIBLE_CAUSES', 'Possible causes', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_RESPONSIBILITIES', 'Resposibles', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_COMMENTS', 'Comments', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_REVISED_ALARM', 'Revised alarm', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ACTIVATION', 'Activation date', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT', 'Element', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_REVISED_ALARMS', 'Maintenance', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
         
    --es_CL
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT_TYPE', 'Tipo de equipo', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ALARM', 'Alarma', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_NORMALIZE_PROCEDURES', 'Procedimiento para normalizar', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_POSSIBLE_CAUSES', 'Posibles causas', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_RESPONSIBILITIES', 'Responsable', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_COMMENTS', 'Comentarios', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_REVISED_ALARM', 'Alarma reisada', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ACTIVATION', 'Fecha de activación', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT', 'Equipo', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_REVISED_ALARMS', 'Mantenimiento', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
       
	END IF;
END $$;