spring.resources.static-locations=classpath:/project/dev_envy,classpath:/project/dev,classpath:/static/
#server.port=8787
server.port=8443

# The format used for the keystore. It could be set to JKS in case it is a JKS file
#server.ssl.key-store-type=PKCS12
server.ssl.keyStoreType=PKCS12
# The path to the keystore containing the certificate
server.ssl.key-store=classpath:openits.server+1.p12
# The password used to generate the certificate
server.ssl.key-store-password=changeit
# The alias mapped to the certificate
#server.ssl.key-alias=openits