#
# Entities cache configuration section
#
cache.enabled=true
cache.cron=0 0 1 1/1 * ? *
cache.datasources=
cache.retry.times=3
cache.retry.timeout_secs=30

#
# User sessions configuration section
#
session.enabled=true
session.cron=0 0/1 * 1/1 * ? *

#
# Server configuration section
#
server.enabled=false
server.cron=0 0/1 * 1/1 * ? *
server.graphql=false
server.required_processes=io-controller.jar,ep-pub-stomp.jar,equipment-manager.jar,service-graphql.jar
server.optional_processes=plan-manager.jar,incident-manager.jar,virtual-equipment-manager.jar,historical-manager.jar


usermgr.enabled=true
usermgr.sql.jdbc=jdbc:postgresql://192.168.243.30:5430/rits
usermgr.sql.user=rits
usermgr.sql.password=uMuD7Uy0gpCRL4Jo1w6SOQ==

#
# BackOffice configuration section
#
backoffice.enabled=true
backoffice.show_sql=true
backoffice.trace_table=true
backoffice.run_jobs=true
backoffice.csv_ascii_separator=59

#
# Graphql adapter constants section
#
type.graphql_query=1
type.graphql_mutation=3
type.spring_service=4

graphql_query.url=1
graphql_query.method=2
graphql_query.params=3
graphql_query.content=4

graphql_mutation.url=8
graphql_mutation.method=9
graphql_mutation.params=10
graphql_mutation.param_types=11
graphql_mutation.content=12

spring_service.class=13
spring_service.method=14

#
# DB Entities
#

log_type_param_state=LogTypeParam:1:1
log_type_param_arg_1=LogTypeParam:1:2

log_subtype_incident_report_created=LogSubtype:7
log_subtype_incident_report_confirmed=LogSubtype:8
log_subtype_incident_report_change_state=LogSubtype:9
log_subtype_incident_report_canceled=LogSubtype:10
log_subtype_assigned_user=LogSubtype:11
log_subtype_assigned_cause=LogSubtype:12
log_subtype_finalized_task=LogSubtype:13
log_subtype_executed_task_plan=LogSubtype:14
log_subtype_attached_document=LogSubtype:15
log_subtype_deleted_document=LogSubtype:16
log_subtype_incident_report_changed=LogSubtype:18
log_subtype_change_road_impact=LogSubtype:41

#
# EntityType codes (same that static/data/constants.js)
#
entityType.alarmConfig=5
entityType.element=7
