#
# Datasources section
#
get_elements_by_element_type=1
get_element_types=2

get_element_type=4
get_elements=5
get_element=6
get_generic_datas=7
get_generic_data=8
get_users=9
get_user=10
update_user=11
get_locales=12
get_locale=13
get_translations_by_locale=14
get_translations_by_locale_and_module=15
get_label_translated=16
get_label_translated_using_fields=17
get_plans=18
get_alarm_types=19
get_alarm_type=20
get_alarm_levels=21
get_alarm_level=22
get_alarm_configs=23
get_alarm_config=24
get_elements_array=25
get_elements_array_states_synoptic=26
get_elements_array_states_measures_alarms_synoptic=27
get_locations_summary=28
get_location=29
get_elements_array_states_map=30
get_elements_array_states_measures_alarms_map=31
get_alarms=32
get_alarms_by_alarm_type=33
get_alarm=34
delete_user=35
create_user=36
get_threshold_operations=37
get_threshold_operation=38
get_alarm_filtereds=39
get_alarm_filtered=40
get_alarm_filtereds_by_alarm_config=41
get_alarm_filtereds_by_element=42
get_element_values_states=43
get_roles=44
get_role=45
get_system_permissions=46
get_system_permission=47
get_roads=48
get_road=49
get_stretchs=50
get_stretch=51
get_stretch_by_road=52
get_incident_groups=54
get_incident_group=55
get_incident_types=56
get_incident_type=57
get_incident_type_states=58
get_next_state=59
get_road_impacts=60
get_road_impact=61
get_init_road_impacts=62
get_road_impacts_by_incident=63
get_incidents_source=64
get_incident_source=65
get_ext_incidents=66
get_ext_incident=67
get_ext_incident_types=68
get_ext_incident_type=69
get_incident_documents=70
get_incident_document=71
get_incident_document_types=72
get_incident_document_type=73
get_log_types=74
get_log_type=75
get_plan=76
get_plan_types=77
get_plan_type=78
get_plan_subtypes=79
get_plan_subtype=80
get_plan_order_types=81
get_plan_order_type=82
get_plan_state_types=83
get_plan_order_state_types=84
get_plan_schedule_state_types=85
get_plan_schedules=86
get_plan_schedule=87
get_plan_schedule_by_plan=88
get_plan_orders=89
get_plan_order=90
create_alarm_config=91
update_alarm_config=92
delete_alarm_config=93
create_element=94
update_element=95
clone_element=96
delete_element=97
create_role=98
update_role=99
delete_role=100
create_plan=101
update_plan=102
delete_plan=103
create_plan_order=104
update_plan_order=105
delete_plan_order=106
create_plan_type=107
update_plan_type=108
delete_plan_type=109
create_plan_subtype=110
update_plan_subtype=111
delete_plan_subtype=112
send_plan_schedule_actions=113
get_alarms_by_source=114
get_alarms_by_source_and_alarm_type=115
get_alarm_configs_by_alarm_type=116
get_alarm_configs_by_alarm_level=117
get_location_by_stretch=118
send_audit_logs=119
send_play_plan=120
send_alarm_filtered_actions=121
send_alarms=122
send_recognize_alarm=123
send_deactivation_alarms=124
send_kill_user=125
send_command_element=126
get_incident_reports=127
get_incident_report=128
get_incident_states=129
get_incident_state=130
get_incident_levels=131
get_incident_level=132
get_task_types=133
get_task_type=134
get_incident_task_plans=135
get_task_plans_by_stretch_and_incident_type_and_incident_type_task=136
get_incident_type_tasks=137
get_incident_type_task_by_incident_type_and_incident_state=138
get_incident_report_summary=139

send_confirm_incident_report=141
send_forward_incident_report=142
send_cancel_incident_report=143
send_assign_user_incident_report=144
send_finalize_task_incident_report=145
send_execute_task_plan_incident_report=146

get_audit_logs_by_log_type=147
send_change_incident_report=174

get_users_with_role=148
get_elements_array_states_measures_synoptic=149
get_elements_array_states_alarms_synoptic=150
send_recognize_audit_logs=151

get_plans_summary=153

get_alarms_array=155

add_log_incident_report=156
delete_log_incident_report=157

get_incident_type_stretchs=158
create_incident_report=159

get_system_params=160

get_hierarchies=161

get_elements_array_states_measures_map=162
get_elements_array_states_alarms_map=163
send_assign_cause_incident_report=164

send_execute_plan=166

get_elements_with_childs_by_element_type=167

get_cctv_scenario=168
get_cctv_scenario_hierarchies=169

get_plan_hierarchies=170
get_plan_nodes=171
create_plan_node=172
delete_plan_node=173
get_incident_reports_summary=175
get_incident_type_stretch=176
get_element_without_childs=177
get_stretch_by_location=178
get_locations=179

get_audit_logs=180
get_audit_log=181

get_elements_by_element_type_for_grid=182
get_elements_array_commands=183
get_plans_plan_library=184
get_plan_plan_library=185
get_plan_order_plan_library=186
get_elements_by_element_type_summary=187
send_command_element_sync=188
get_locations_by_stretchs=189
get_elements_by_stretchs=190
get_element_with_parents=191
add_command_element=192
delete_command_element=193
enable_priority=194
disable_priority=195
get_processes_info=196
get_server_time=197
get_alarm_configs_by_element_type=198
get_server_resources=199
create_incident_type=200
update_incident_type=201
delete_incident_type=202
create_incident_type_stretch=203
update_incident_type_stretch=204
delete_incident_type_stretch=205
create_incident_alarm_condition=206
update_incident_alarm_condition=207
delete_incident_alarm_condition=208
create_incident_type_task=209
update_incident_type_task=210
delete_incident_type_task=211
create_incident_task_plan=212
update_incident_task_plan=213
delete_incident_task_plan =214
create_incident_type_state_transition=215
update_incident_type_state_transition=216
delete_incident_type_state_transition=217
get_incident_type_stretchs_by_incident_type=218
get_threshold_by_state_machine_id=219
update_threshold=220
get_threshold_by_state_machine=221
get_spaths=222
send_backward_incident_report=223
send_change_road_impact_incident_report=224
get_element_trees_by_user=225
get_element_tree=226
get_stretch_by_stretchs_stretch=227
get_alarms_by_alarm_config=228
stop_processes=229
get_historical_alarms=230
get_historical_element_states=231
get_historical_element_values=232
send_change_element_state=233

get_user_by_name=236

get_management_areas=237
get_iocontroller_modules=238

create_location=239
update_location=240
delete_location=241

create_cctv_scenario_node=242
delete_cctv_scenario_node=243
create_cctv_scenario=244
update_cctv_scenario=245
delete_cctv_scenario=246
get_cctv_scenario_nodes=247
get_cctv_scenarios=248

get_delayed_incident_reports=249
get_delayed_incident_report=250
send_delayed_incident_actions=251

get_location_types=252

get_ext_entities=253
get_ext_entities_by_ext_entity_type_id=254
get_ext_entity=255
get_ext_entity_types=256
get_ext_entity_type=257

get_routes=258
get_route=259
create_route=260
update_route=261
delete_route=262
add_avoid_polygon_incident_report=263
delete_avoid_polygon_incident_report=264
get_transits=265
get_transit=266
get_transit_types=267
get_vehicle_classes=268