redis.host=10.251.248.152
redis.port=6379
redis.timeout=60000
redis.password=rits
redis.database=0
redis.reconnection_attempts=5
redis.reconnection_timeout_ms=5000
redis.datacache_type=3
redis.commandcache_bin=true
redis.scan_count=10000
redis.max_pools_by_db = 1
