INSERT INTO ui.modules(id, module_type_id, "name", description, js_file, js_method_draw, js_method_callbacks, data_query, wss_topic, enabled, visible) VALUES
(5, 1, 'Equipments', 'Equipments module', './equipments2.js', 'getViewEquipments', 'assingEquipmentCallbacks', NULL, NULL, true, true),
(6, 2, 'Plans', 'Plans module', './generic_grid.js', 'getGenericGridView', 'assingGenericGridCallbacks', NULL, NULL, true, true),
(7, 1, 'Module 3', 'Module 3', NULL, NULL, NULL, NULL, NULL, true, true),
(8, 1, 'Module 4', 'Module 4', NULL, NULL, NULL, NULL, NULL, true, true),
(9, 1, 'Module 5', 'Module 5', NULL, NULL, NULL, NULL, NULL, true, true),
(10, 1, 'Module 6', 'Module 6', NULL, NULL, NULL, NULL, NULL, true, true),
(11, 6, 'Time service', 'Time service', './js/services/time.js', 'getDrawServiceTime', 'assingCallbackServiceTime', NULL, NULL, true, true),
(12, 6, 'Alarm service', 'Alarm service', './js/services/alarm.js', 'getDrawServiceAlarm', 'assingCallbackServiceAlarm', NULL, NULL, true, true),
(13, 1, 'Generic equipment editor', 'Generic equipment editor', './generic_equipment_editor.js', 'getGenericEquipmentEditorView', 'assingGenericEquipmentEditorCallbacks', NULL, NULL, true, true);

INSERT INTO ui.module_values(module_id, module_param_id, value) VALUES
(11, 1, '2'),
(12, 1, '1'),
(12, 2, '{"stats":{"rest":{"active_alarms":"generic_datas/GenericData:1","no_recognize_alarms":"generic_datas/GenericData:2","muted_alarms":"generic_datas/GenericData:3"},"ws":{"active_alarms":"/topic/generic_data.GenericData:1","no_recognize_alarms":"/topic/generic_data.GenericData:2","muted_alarms":"/topic/generic_data.GenericData:3"}},"levels_notif":[3,4,5,6],"level_acustic":[6],"default_sound":"alarm.wav"}'),
(6, 3, '4');

INSERT INTO ui.window_values(module_id, window_param_id, value) VALUES
(5, 1, 'true'),
(5, 2, 'true'),
(5, 3, 'false'),
(5, 4, '720'),
(5, 5, '1400'),
(5, 6, ''),
(5, 7, ''),
(5, 8, 'true'),
(5, 9, 'img/module/equipments_default.png'),
(5, 10, 'img/module/equipments_icon.png'),
(5, 11, '#464646'),
(5, 12, 'LBL_MENU_ITEM_EQUIPMENTS'),
(5, 13, 'true'),
(5, 14, 'true'),

(6, 1, 'true'),
(6, 2, 'true'),
(6, 3, 'false'),
(6, 4, '720'),
(6, 5, '1400'),
(6, 6, ''),
(6, 7, ''),
(6, 8, 'true'),
(6, 9, 'img/module/plan_default.png'),
(6, 10, 'img/module/plan_icon.png'),
(6, 11, '#464646'),
(6, 12, 'LBL_PLANS'),
(6, 13, 'true'),
(6, 14, 'true'),

(13, 1, 'true'),
(13, 2, 'false'),
(13, 3, 'false'),
(13, 4, '600'),
(13, 5, '1000'),
(13, 6, ''),
(13, 7, ''),
(13, 8, 'true'),
(13, 9, 'img/module/module_default.png'),
(13, 10, 'img/module/window_icon.png'),
(13, 11, '#464646'),
(13, 12, 'LBL_GENERIC_EQUIPMENT_EDITOR'),
(13, 13, 'false'),
(13, 14, 'false');