-- 
-- Table: conf.element_hierarchies
--
INSERT INTO conf.element_hierarchies
(parent_element_type_id, parent_element_id, child_element_type_id, child_element_id, child_inheritable_state_id, enabled, visible, created_at, updated_at) VALUES

(5, 1, 16, 1, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 16, 2, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 16, 3, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 16, 4, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 16, 25, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 2, 16, 5, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 6, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 7, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 8, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 9, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 10, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 11, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 12, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 16, 68, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 3, 16, 13, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, 16, 14, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, 16, 15, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, 16, 16, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, 16, 69, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 4, 16, 17, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 18, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 19, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 20, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 21, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 22, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 23, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 24, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 16, 37, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


(5, 5, 16, 38, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 39, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 40, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 41, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 42, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 43, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 44, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 45, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 16, 46, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 6, 16, 26, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 27, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 28, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 29, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 30, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 31, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 32, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 33, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 34, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 35, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 16, 36, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 7, 16, 47, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 16, 48, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 16, 49, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 16, 50, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 16, 51, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 16, 52, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 16, 53, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 8, 16, 59, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 60, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 61, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 62, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 63, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 64, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 65, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 66, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 16, 67, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 9, 16, 70, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 71, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 72, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 73, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 74, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 75, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 76, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 77, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 16, 78, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 25, 16, 54, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 25, 16, 55, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 25, 16, 56, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 25, 16, 57, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 25, 16, 58, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 1, 96, 1, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 96, 2, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 96, 3, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 2, 96, 4, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 96, 5, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, 96, 6, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 3, 96, 13, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, 96, 14, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, 96, 15, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 4, 96, 7, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 96, 8, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 4, 96, 9, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 5, 96, 16, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 96, 17, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 5, 96, 18, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 6, 96, 22, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 96, 23, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 6, 96, 24, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 7, 96, 19, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 96, 20, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 7, 96, 21, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 8, 96, 10, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 96, 11, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 8, 96, 12, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 9, 96, 28, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 96, 29, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 96, 30, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 25, 96, 25, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 25, 96, 26, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 25, 96, 27, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);





