
INSERT INTO ui.vo_entities(id, vo_entity_type_id, enabled, visible) VALUES
('ElementType:1', 'ElementTypeUI', true, true),
('ElementType:2', 'ElementTypeUI', true, true),
('Element:2:233', 'ElementTypeUI', true, true),
('Element:2:234', 'ElementTypeUI', true, true),
('Element:2:235', 'ElementTypeUI', true, true),
('Element:2:236', 'ElementTypeUI', true, true),
('Element:2:237', 'ElementTypeUI', true, true),
('Element:2:238', 'ElementTypeUI', true, true),
('Element:2:239', 'ElementTypeUI', true, true),
('Element:2:240', 'ElementTypeUI', true, true),
('Element:2:241', 'ElementTypeUI', true, true),
('Element:2:242', 'ElementTypeUI', true, true),
('Element:2:243', 'ElementTypeUI', true, true),
('Element:2:244', 'ElementTypeUI', true, true),
('Element:2:245', 'ElementTypeUI', true, true),
('Element:2:246', 'ElementTypeUI', true, true),
('Element:2:247', 'ElementTypeUI', true, true),
('Element:2:248', 'ElementTypeUI', true, true),
('Element:2:249', 'ElementTypeUI', true, true),
('Element:2:250', 'ElementTypeUI', true, true),
('Element:2:251', 'ElementTypeUI', true, true),
('Element:2:252', 'ElementTypeUI', true, true),
('Element:2:253', 'ElementTypeUI', true, true),
('Element:2:254', 'ElementTypeUI', true, true),
('Element:2:255', 'ElementTypeUI', true, true),
('Element:2:256', 'ElementTypeUI', true, true),
('Element:2:257', 'ElementTypeUI', true, true),
('Element:2:258', 'ElementTypeUI', true, true),
('Element:2:259', 'ElementTypeUI', true, true),
('Element:2:260', 'ElementTypeUI', true, true),
('Element:2:261', 'ElementTypeUI', true, true),
('Element:2:262', 'ElementTypeUI', true, true),

('ElementType:3', 'ElementTypeUI', true, true),
('ElementType:4', 'ElementTypeUI', true, true),
('ElementType:23', 'ElementTypeUI', true, true),
('ElementType:25', 'ElementTypeUI', true, true),
('ElementType:34', 'ElementTypeUI', true, true),
('ElementType:39','ElementTypeUI' ,True,True),
('ElementType:40','ElementTypeUI' ,True,True),
('ElementType:41', 'ElementTypeUI', true, true),
('ElementType:42', 'ElementTypeUI', true, true),
('ElementType:43', 'ElementTypeUI', true, true),
('ElementType:44', 'ElementTypeUI', true, true),
('ElementType:45', 'ElementTypeUI', true, true),
('ElementType:46', 'ElementTypeUI', true, true),
('ElementType:47', 'ElementTypeUI', true, true),
('ElementType:51', 'ElementTypeUI', true, true),
('ElementType:54', 'ElementTypeUI', true, true),
('ElementType:68', 'ElementTypeUI', true, true),
('ElementType:71', 'ElementTypeUI', true, true),
('ElementType:89','ElementTypeUI' ,True,True),
('ElementType:97', 'ElementTypeUI', true, true),

('ElementSubtype:1:1', 'ElementSubtypeUI', true, true),
('ElementSubtype:2:1', 'ElementSubtypeUI', true, true),

('ElementTypeParam:1:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:11', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:12', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:14', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:15', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:16', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:17', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:18', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:19', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:20', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:21', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:22', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:25', 'ElementTypeParamUI', true, true),

('ElementTypeParam:2:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:5', 'ElementTypeParamUI', true, true),

('ElementSubtype:1:3', 'ElementSubtypeUI', true, true),
('ElementSubtype:2:3', 'ElementSubtypeUI', true, true),
('ElementSubtype:3:3', 'ElementSubtypeUI', true, true),
('ElementSubtype:4:3', 'ElementSubtypeUI', true, true),

('ElementTypeParam:3:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:11', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:17', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:20', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:21', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:22', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:40', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:41', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:42', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:60', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:61', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:80', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:81', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:82', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:100', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:101', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:102', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:103', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:104', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:105', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:106', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:107', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:108', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:109', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:110', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:111', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:112', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:113', 'ElementTypeParamUI', true, true),

('ElementSubtype:1:4', 'ElementSubtypeUI', true, true),
('ElementSubtype:2:4', 'ElementSubtypeUI', true, true),

('ElementTypeParam:4:1:100', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:1:101', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:18', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:100', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:101', 'ElementTypeParamUI', true, true),

('ElementTypeParam:25:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:25:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:34:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:34:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:39:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:40:1:3', 'ElementTypeParamUI', true, true),


('ElementTypeParam:41:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:41:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:42:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:42:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:43:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:43:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:44:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:44:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:45:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:45:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:46:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:46:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:47:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:47:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:51:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:51:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:54:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:54:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:68:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:68:1:2', 'ElementTypeParamUI', true, true),

('ElementSubtype:1:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:2:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:3:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:4:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:5:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:6:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:7:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:8:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:9:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:10:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:11:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:12:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:13:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:14:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:15:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:17:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:23:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:24:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:25:71', 'ElementSubtypeUI', true, true),

('ElementTypeParam:71:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:6', 'ElementTypeParamUI', true, true),

('ElementTypeParam:71:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:14', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:15', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:17', 'ElementTypeParamUI', true, true),

('ElementTypeParam:97:1:4', 'ElementTypeParamUI', true, true),

('CommandElementType:2:71', 'CommandElementTypeUI', true, true),

('Location:1', 'LocationUI', true, true),
('Location:2', 'LocationUI', true, true),
('Location:3', 'LocationUI', true, true),
('Location:4', 'LocationUI', true, true),

('ElementValueState:1', 'ElementValueStateUI', true, true),
('ElementValueState:2', 'ElementValueStateUI', true, true),
('ElementValueState:3', 'ElementValueStateUI', true, true),
('ElementValueState:4', 'ElementValueStateUI', true, true);

INSERT INTO ui.vo_entity_values(vo_entity_id, vo_entity_field_id, value) VALUES
('ElementType:1', 1, '1'),
('ElementType:1', 14, 'grid/element_type_01.png'),

('ElementType:2', 1, '2'),
('ElementType:2', 14, 'grid/element_type_02.png'),

('ElementType:3', 1, '3'),
('ElementType:3', 14, 'grid/element_type_03.png'),

('ElementType:4', 1, '4'),
('ElementType:4', 14, 'grid/element_type_04.png'),

('ElementType:23', 1, '23'),
('ElementType:23', 14, 'grid/element_type_23.png'),

('ElementType:25', 1, '25'),
('ElementType:25', 14, 'grid/element_type_25.png'),

('ElementType:34', 1, '34'),
('ElementType:34', 14, 'grid/element_type_34.png'),

('ElementType:39', 1, '39'),
('ElementType:39', 14, 'grid/element_type_39.png'),

('ElementType:40', 1, '40'),
('ElementType:40', 14, 'grid/element_type_40.png'),

('ElementType:41', 1, '41'),
('ElementType:41', 14, 'grid/element_type_41.png'),

('ElementType:42', 1, '42'),
('ElementType:42', 14, 'grid/element_type_42.png'),

('ElementType:43', 1, '43'),
('ElementType:43', 14, 'grid/element_type_43.png'),

('ElementType:44', 1, '44'),
('ElementType:44', 14, 'grid/element_type_44.png'),

('ElementType:45', 1, '45'),
('ElementType:45', 14, 'grid/element_type_45.png'),

('ElementType:46', 1, '46'),
('ElementType:46', 14, 'grid/element_type_46.png'),

('ElementType:47', 1, '47'),
('ElementType:47', 14, 'grid/element_type_47.png'),

('ElementType:51', 1, '51'),
('ElementType:51', 14, 'grid/element_type_51.png'),
('ElementType:54', 1, '54'),
('ElementType:54', 14, 'grid/element_type_54.png'),

('ElementType:68', 1, '68'),
('ElementType:68', 14, 'grid/element_type_68.png'),

('CommandElementType:2:71', 39, 'true'),
('ElementType:71', 1, '71'),
('ElementType:71', 14, 'grid/element_type_71.png'),
('ElementType:71', 23, '102601'),
('ElementType:71', 30, '102602'),

('ElementType:89', 1, '89'),
('ElementType:89', 14, 'grid/element_type_89.png'),

('ElementType:97', 1, '97'),
('ElementType:97', 14, 'grid/element_type_51.png'),

('ElementTypeParam:1:2:1', 26, 1),
('ElementTypeParam:1:2:2', 26, 1),
('ElementTypeParam:1:2:3', 26, 1),
('ElementTypeParam:1:2:4', 26, 1),
('ElementTypeParam:1:2:5', 26, 1),
('ElementTypeParam:1:2:6', 26, 1),
('ElementTypeParam:1:2:7', 26, 1),
('ElementTypeParam:1:2:8', 26, 1),
('ElementTypeParam:1:2:9', 26, 1),
('ElementTypeParam:1:2:10', 26, 1),
('ElementTypeParam:1:2:11', 26, 1),
('ElementTypeParam:1:2:12', 26, 1),
('ElementTypeParam:1:2:13', 26, 1),
('ElementTypeParam:1:2:14', 26, 1),
('ElementTypeParam:1:2:15', 26, 1),
('ElementTypeParam:1:2:16', 26, 1),
('ElementTypeParam:1:2:17', 26, 1),
('ElementTypeParam:1:2:18', 26, 1),
('ElementTypeParam:1:2:19', 26, 1),
('ElementTypeParam:1:2:20', 26, 1),
('ElementTypeParam:1:2:21', 26, 1),
('ElementTypeParam:1:2:22', 26, 1),

('ElementTypeParam:3:2:1', 26, 1),
('ElementTypeParam:3:2:2', 26, 1),
('ElementTypeParam:3:2:4', 26, 1),
('ElementTypeParam:3:2:6', 26, 1),
('ElementTypeParam:3:2:7', 26, 1),
('ElementTypeParam:3:2:8', 26, 1),
('ElementTypeParam:3:2:9', 26, 1),

('ElementTypeParam:4:2:1', 26, 1),
('ElementTypeParam:4:2:2', 26, 1),
('ElementTypeParam:4:2:5', 26, 1),
('ElementTypeParam:4:2:6', 26, 1),
('ElementTypeParam:4:2:9', 26, 1),
('ElementTypeParam:4:2:10', 26, 1),
('ElementTypeParam:4:2:18', 26, 1),

('ElementSubtype:1:71', 23, '102601'),
('ElementSubtype:2:71', 23, '102601'),
('ElementSubtype:3:71', 23, '102601'),
('ElementSubtype:4:71', 23, '102601'),
('ElementSubtype:6:71', 23, '102601'),
('ElementSubtype:17:71', 23, '102601'),
('ElementSubtype:5:71', 23, '102601'),
('ElementSubtype:23:71', 23, '102601'),
('ElementSubtype:24:71', 23, '102601'),

('ImsIncidentLevel:1', 36, 'false'),
('ImsIncidentLevel:2', 36, 'false'),
('ImsIncidentLevel:3', 36, 'false'),
('ImsIncidentLevel:4', 36, 'false'),

('Location:1', 5, '40.50192872888957'),
('Location:1', 6, '-3.5075150487690823'),
('Location:2', 5, '40.50601573088965'),
('Location:2', 6, '-3.5115705015736878'),
('Location:3', 5, '40.49601573088965'),
('Location:3', 6, '-3.5015705015736878');

--('AlarmLevel:6', 8, 'true'),
--('AlarmLevel:6', 9, 'alarm.mp3');

INSERT INTO ui.vo_entity_hierarchies(parent_id, child_id, "position") VALUES
('Location:4', 'Location:2', 1),
('Location:4', 'Location:3', 2);
