INSERT INTO ui.grids(id, adapter_id, "label", enabled, visible) VALUES
(1, 2, 'LBL_WS', true, true),
(2, 2, 'LBL_CAM', true, true),
(3, 2, 'LBL_DETECTORS', true, true),
(4, 2, 'LBL_SECTION', true, true),
(23, 2, 'LBL_ELEMENT_TYPE_IMANAGER', true, true),
(25, 2, 'LBL_ELECTRICAL_CABINET', true, true),
(34, 2, 'LBL_ELECTRICAL_CABINET_SCN', true, true),
(39, 2, 'LBL_HORIZONTAL_ACCESS', true, true),
(40, 2, 'LBL_PRESDENCE_DETECTION', true, true),
(41, 2, 'LBL_ELECTRICAL_CABINET_ATC', true, true),
(42, 2, 'LBL_ELECTRICAL_CABINET_NRL', true, true),
(43, 2, 'LBL_ELECTRICAL_CABINET_NRS', true, true),
(44, 2, 'LBL_ELECTRICAL_CABINET_TFA_3D', true, true),
(45, 2, 'LBL_ELECTRICAL_CABINET_TFA_Loops', true, true),
(46, 2, 'LBL_ELECTRICAL_CABINET_TOLL', true, true),
(47, 2, 'LBL_ELECTRICAL_CABINET_TU', true, true),
(51, 2, 'LBL_ETD', true, true),
(54, 2, 'LBL_ATC', true, true),
(64, 2, 'LBL_VMS_SNOW', true, true),
(68, 2, 'LBL_TFA3D', true, true),
(71, 2, 'LBL_PANELES', true, true),
(89, 2, 'LBL_GATE', true, true),
(97, 2, 'LBL_RTMS', true, true);



INSERT INTO ui.grid_fields(id, grid_id, grid_field_data_type_id, "position", required, parameterized, extended, filtered, "label", label_tooltip, source_field, is_pk, is_epoch_milli, align, needs_translation, grouping_summary, width_px, grid_field_group_operation_id, enabled, visible, adjust, header_vertical, fixed_column, replacement_function, precision_filter) VALUES

---METEO---
(1, 1, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, true, NULL, NULL, NULL),
(2, 1, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 100, NULL, true, true, NULL, false, true, NULL, NULL),
(3, 1, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 100, NULL, true, true, NULL, false, NULL, NULL, NULL),
(4, 1, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, false, NULL, NULL, NULL),
(5, 1, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, false, NULL, NULL, NULL),
(6, 1, 3, 6, true, false, false, false, 'LBL_FREEZE_POINT', 'LBL_FREEZE_POINT', 'ElementTypeParam:1:2:3', false, false, 'left', false, false, 75, NULL, true, true, NULL, true, NULL, NULL, 1),
(7, 1, 3, 7, true, false, false, false, 'LBL_SNOW_FALL_INTENSITY', 'LBL_SNOW_FALL_INTENSITY', 'ElementTypeParam:1:2:12', false, false, 'left', false, false, 80, NULL, true, true, NULL, true, NULL, NULL, 1),
(8, 1, 3, 8, true, false, false, false, 'LBL_PRECIPITATION_INTENSITY', 'LBL_PRECIPITATION_INTENSITY', 'ElementTypeParam:1:2:11', false, false, 'left', false, false, 80, NULL, true, true, NULL, true, NULL, NULL, 1),
(9, 1, 3, 9, true, false, false, false, 'LBL_ROAD_CONDITION', 'LBL_ROAD_CONDITION_DESC', 'ElementTypeParam:1:2:9', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(10, 1, 3, 10, true, false, false, false, 'LBL_CONCENTRATION_CACL', 'LBL_CONCENTRATION_CACL', 'ElementTypeParam:1:2:8', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(11, 1, 3, 11, true, false, false, false, 'LBL_CONCENTRATION_MGCL2', 'LBL_CONCENTRATION_MGCL2', 'ElementTypeParam:1:2:7', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(12, 1, 3, 12, true, false, false, false, 'LBL_CONCENTRATION_NACL', 'LBL_CONCENTRATION_NACL', 'ElementTypeParam:1:2:6', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(14, 1, 3, 13, true, false, false, false, 'LBL_AVERAGE_WIND_DIRECTION', 'LBL_AVERAGE_WIND_DIRECTION', 'ElementTypeParam:1:2:14', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(15, 1, 3, 14, true, false, false, false, 'LBL_AVERAGE_WIND_SPEED', 'LBL_AVERAGE_WIND_SPEED', 'ElementTypeParam:1:2:13', false, false, 'left', false, false, 100, NULL, true, true, NULL, true, NULL, NULL, 1),
(16, 1, 3, 15, true, false, false, false, 'LBL_GUST_WIND_SPEED', 'LBL_GUST_WIND_SPEED', 'ElementTypeParam:1:2:15', false, false, 'left', false, false, 100, NULL, true, true, NULL, true, NULL, NULL, 1),
(17, 1, 3, 16, true, false, false, false, 'LBL_RELATIVE_HUMIDITY', 'LBL_RELATIVE_HUMIDITY', 'ElementTypeParam:1:2:10', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(18, 1, 3, 17, true, false, false, false, 'LBL_BLACK_ICE_SIGNAL', 'LBL_BLACK_ICE_SIGNAL_DESC', 'ElementTypeParam:1:2:21', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(19, 1, 3, 18, true, false, false, false, 'LBL_GUST_WIND_DIRECTION', 'LBL_GUST_WIND_DIRECTION', 'ElementTypeParam:1:2:16', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(20, 1, 3, 19, true, false, false, false, 'LBL_SUB_SURFACE_TEMPERATURE', 'LBL_SUB_SURFACE_TEMPERATURE', 'ElementTypeParam:1:2:2', false, false, 'left', false, false, 75, NULL, true, true, NULL, true, NULL, NULL, 1),
(21, 1, 3, 20, true, false, false, false, 'LBL_SURFACE_TEMPERATURE', 'LBL_SURFACE_TEMPERATURE', 'ElementTypeParam:1:2:1', false, false, 'left', false, false, 75, NULL, true, true, NULL, true, NULL, NULL, 1),
(22, 1, 3, 21, true, false, false, false, 'LBL_DEW_POINT_TEMPERATURE', 'LBL_DEW_POINT_TEMPERATURE', 'ElementTypeParam:1:2:18', false, false, 'left', false, false, 75, NULL, true, true, NULL, true, NULL, NULL, 1),
(23, 1, 3, 22, true, false, false, false, 'LBL_AIR_TEMPERATURE', 'LBL_AIR_TEMPERATURE', 'ElementTypeParam:1:2:17', false, false, 'left', false, false, 75, NULL, true, true, NULL, true, NULL, NULL, 1),
(24, 1, 3, 23, true, false, false, false, 'LBL_AIR_PRESSURE', 'LBL_AIR_PRESSURE', 'ElementTypeParam:1:2:4', false, false, 'left', false, false, 75, NULL, true, true, NULL, true, NULL, NULL, 1),
(25, 1, 3, 24, true, false, false, false, 'LBL_PRECIPITATION_TYPE', 'LBL_PRECIPITATION_TYPE_DESC', 'ElementTypeParam:1:2:19', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(26, 1, 3, 25, true, false, false, false, 'LBL_PREDICTION_ALARM_CODE', 'LBL_PREDICTION_ALARM_CODE', 'ElementTypeParam:1:2:22', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, 1),
(27, 1, 3, 26, true, false, false, false, 'LBL_VISIBILITY', 'LBL_VISIBILITY', 'ElementTypeParam:1:2:20', false, false, 'left', false, false, 105, NULL, true, true, NULL, true, NULL, NULL, 1),
(28, 1, 3, 27, true, false, false, false, 'LBL_WATER_DEPTH', 'LBL_WATER_DEPTH', 'ElementTypeParam:1:2:5', false, false, 'left', false, false, 75, NULL, true, true, NULL, true, NULL, NULL, 1),
(29, 1, 1, 28, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:1:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL, NULL),
(32, 1, 1, 31, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:1:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL, NULL),
--CAMERA--
(34, 2, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 100, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(35, 2, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(36, 2, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(37, 2, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(38, 2, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(39, 2, 1, 6, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:2:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(40, 2, 1, 7, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:2:1:2', false, false, 'left', false, false, 130, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(43, 2, 1, 10, false, false, true, false, 'LBL_SELECTION_CODE_KEYBOARD', 'LBL_SELECTION_CODE_KEYBOARD', 'ElementTypeParam:2:1:4', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(46, 2, 1, 13, false, false, true, false, 'LBL_ASSOCIATED_CABINET', 'LBL_ASSOCIATED_CABINET', 'ElementTypeParam:2:1:5', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
--DETECTOR--
(47, 3, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, null, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(48, 3, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, null, false, false, 150, NULL, true, true, NULL, NULL, true, NULL,  NULL),
(49, 3, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, null, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(50, 3, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, null, false, false, 30, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(51, 3, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, null, true, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(52, 3, 4, 6, true, false, false, false, 'LBL_DATE', 'LBL_DATE', 'ElementTypeParam:3:2:1', false, true, 'left', false, false, 200, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(53, 3, 3, 7, true, false, false, false, 'LBL_SPEED', 'LBL_SPEED', 'ElementTypeParam:3:2:9', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(54, 3, 3, 8, true, false, false, false, 'LBL_N_VEHICLES', 'LBL_N_VEHICLES', 'ElementTypeParam:3:2:4', false, false, 'left', false, false, 200, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(55, 3, 3, 9, true, false, false, false, 'LBL_LENGTH', 'LBL_LENGTH', 'ElementTypeParam:3:2:17', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(56, 3, 3, 10, true, false, false, false, 'LBL_GAP', 'LBL_GAP', 'ElementTypeParam:3:2:10', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(57, 3, 3, 11, true, false, false, false, 'LBL_OCCUPANCY', 'LBL_OCCUPANCY', 'ElementTypeParam:3:2:6', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(58, 3, 3, 12, true, false, false, false, 'LBL_VEH_LENGTH_1', 'LBL_VEH_LENGTH_1', 'ElementTypeParam:3:2:20', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(59, 3, 3, 13, true, false, false, false, 'LBL_VEH_LENGTH_2', 'LBL_VEH_LENGTH_2', 'ElementTypeParam:3:2:21', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(60, 3, 3, 14, true, false, false, false, 'LBL_VEH_SPEED_1', 'LBL_VEH_SPEED_1', 'ElementTypeParam:3:2:40', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(61, 3, 3, 15, true, false, false, false, 'LBL_VEH_SPEED_2', 'LBL_VEH_SPEED_2', 'ElementTypeParam:3:2:41', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(62, 3, 3, 16, true, false, false, false, 'LBL_VEH_SPEED_3', 'LBL_VEH_SPEED_3', 'ElementTypeParam:3:2:42', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  1),
(63, 3, 1, 17, true, false, false, false, 'VEH_PA_1', 'VEH_PA_1', 'ElementTypeParam:3:2:100', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(64, 3, 1, 18, true, false, false, false, 'VEH_PA_2', 'VEH_PA_2', 'ElementTypeParam:3:2:101', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(65, 3, 1, 19, true, false, false, false, 'VEH_PA_3', 'VEH_PA_3', 'ElementTypeParam:3:2:102', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(66, 3, 1, 20, true, false, false, false, 'VEH_PA_4', 'VEH_PA_4', 'ElementTypeParam:3:2:103', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(67, 3, 1, 21, true, false, false, false, 'VEH_PA_5', 'VEH_PA_5', 'ElementTypeParam:3:2:104', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(68, 3, 1, 22, true, false, false, false, 'VEH_PA_6', 'VEH_PA_6', 'ElementTypeParam:3:2:105', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(69, 3, 1, 23, true, false, false, false, 'VEH_PA_7', 'VEH_PA_7', 'ElementTypeParam:3:2:106', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(70, 3, 1, 24, true, false, false, false, 'VEH_PA_8', 'VEH_PA_8', 'ElementTypeParam:3:2:107', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(71, 3, 1, 25, true, false, false, false, 'VEH_PA_9', 'VEH_PA_9', 'ElementTypeParam:3:2:108', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(72, 3, 1, 26, true, false, false, false, 'VEH_PA_10', 'VEH_PA_10', 'ElementTypeParam:3:2:109', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(73, 3, 1, 27, true, false, false, false, 'VEH_PA_11', 'VEH_PA_11', 'ElementTypeParam:3:2:110', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(74, 3, 1, 28, true, false, false, false, 'VEH_PA_12', 'VEH_PA_12', 'ElementTypeParam:3:2:111', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(75, 3, 1, 29, true, false, false, false, 'VEH_PA_13', 'VEH_PA_13', 'ElementTypeParam:3:2:112', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(76, 3, 1, 30, false, false, true, false, 'LBL_ORDER', 'LBL_ORDER', 'ElementTypeParam:3:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(77, 3, 1, 31, false, false, true, false, 'LBL_PK', 'LBL_PK', 'ElementTypeParam:3:1:10', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(78, 3, 1, 32, false, false, true, false, 'LBL_ROAD', 'LBL_ROAD', 'ElementTypeParam:3:1:11', false, false, 'left', false, false, 180, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(79, 3, 1, 33, false, false, true, false, 'LBL_SECTION', 'LBL_SECTION', 'ElementTypeParam:3:1:12', false, false, 'left', false, false, 200, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),

(80, 4, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(81, 4, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 180, NULL, true, true, NULL, NULL, true, NULL,  NULL),
(82, 4, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 180, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(83, 4, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(84, 4, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(85, 4, 4, 6, true, false, false, false, 'LBL_DATE', 'LBL_DATE', 'ElementTypeParam:4:2:1', false, true, 'left', false, false, 200, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(86, 4, 1, 7, true, false, false, false, 'LBL_INTENSIDAD', 'LBL_INTENSIDAD', 'ElementTypeParam:4:2:5', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL,  NULL),
(87, 4, 1, 8, true, false, false, false, 'LBL_OCCUPANCY', 'LBL_OCCUPANCY', 'ElementTypeParam:4:2:6', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL,  NULL),
(88, 4, 1, 9, true, false, false, false, 'LBL_SPEED', 'LBL_SPEED', 'ElementTypeParam:4:2:9', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL,  NULL),
(89, 4, 1, 10, true, false, false, false, 'LBL_GAP', 'LBL_GAP', 'ElementTypeParam:4:2:10', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL,  NULL),
(90, 4, 1, 11, true, false, false, false, 'LBL_LENGTH', 'LBL_LENGTH', 'ElementTypeParam:4:2:18', false, false, 'left', false, false, 200, NULL, true, true, NULL, true, NULL, NULL,  NULL),
(91, 4, 1, 12, true, false, false, false, 'LBL_VEH_LENGTH_1_PERCENT', 'LBL_VEH_LENGTH_1_PERCENT', 'ElementTypeParam:4:2:160', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL,  NULL),
(92, 4, 1, 13, true, false, false, false, 'LBL_VEH_LENGTH_2_PERCENT', 'LBL_VEH_LENGTH_2_PERCENT', 'ElementTypeParam:4:2:161', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL,  NULL),

(93, 23, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(94, 23, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(95, 23, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(96, 23, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(97, 23, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),

(106, 25, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(107, 25, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(108, 25, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(109, 25, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(110, 25, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(111, 25, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:25:1:2', false, false, 'left', false, false, 230, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(112, 25, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:25:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(159, 34, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(160, 34, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(161, 34, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(162, 34, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(163, 34, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(164, 34, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:34:1:2', false, false, 'left', false, false, 230, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(165, 34, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:34:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(287, 39, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(288, 39, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(290, 39, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(291, 39, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(292, 39, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(293, 39, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:39:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(294, 39, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:39:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(303, 39, 1, 8, false, false, true, false, 'LBL_ASSOCIATED_CABINET', 'LBL_ASSOCIATED_CABINET', 'ElementTypeParam:39:1:3', false, false, 'left', false, false, 150, NULL, true, true, NULL, false, NULL, NULL, NULL),

(295, 40, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(296, 40, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(297, 40, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(298, 40, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(299, 40, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(300, 40, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:40:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(301, 40, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:40:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(302, 40, 1, 8, false, false, true, false, 'LBL_ASSOCIATED_CABINET', 'LBL_ASSOCIATED_CABINET', 'ElementTypeParam:40:1:3', false, false, 'left', false, false, 150, NULL, true, true, NULL, false, NULL, NULL, NULL),


(167, 41, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(168, 41, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(169, 41, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(170, 41, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(171, 41, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(172, 41, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:41:1:2', false, false, 'left', false, false, 230, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(173, 41, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:41:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(175, 42, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(176, 42, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(177, 42, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(178, 42, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(179, 42, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(180, 42, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:42:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(181, 42, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:42:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(183, 43, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(184, 43, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(185, 43, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(186, 43, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(187, 43, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(188, 43, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:43:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(189, 43, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:43:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(191, 44, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(192, 44, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(193, 44, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(194, 44, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(195, 44, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(196, 44, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:44:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(197, 44, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:44:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(199, 45, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(200, 45, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(201, 45, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(202, 45, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(203, 45, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(204, 45, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:45:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(205, 45, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:45:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(207, 46, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(208, 46, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(209, 46, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(210, 46, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(211, 46, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(212, 46, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:46:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(213, 46, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:46:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(215, 47, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(216, 47, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(217, 47, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(218, 47, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(219, 47, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(220, 47, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:47:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(221, 47, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:47:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(223, 51, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(224, 51, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 180, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(225, 51, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 180, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(226, 51, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(227, 51, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(228, 51, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:51:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(229, 51, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:51:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(231, 54, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(232, 54, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(233, 54, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(234, 54, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(235, 54, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(236, 54, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:54:1:2', false, false, 'left', false, false, 230, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(237, 54, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:54:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(239, 64, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(240, 64, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(241, 64, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(242, 64, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(243, 64, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(245, 64, 1, 7, false, false, true, false, 'LBL_SENTIDO', 'LBL_SENTIDO', 'ElementTypeParam:64:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(247, 64, 1, 9, false, false, true, false, 'LBL_SECTION', 'LBL_SECTION', 'ElementTypeParam:64:1:4', false, false, 'left', false, false, 270, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(248, 64, 1, 10, false, false, true, false, 'LBL_ASSOCIATED_CABINET', 'LBL_ASSOCIATED_CABINET', 'ElementTypeParam:64:1:6', false, false, 'left', false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(249, 64, 1, 11, false, false, true, false, 'LBL_ASSOCIATED_METEO', 'LBL_ASSOCIATED_METEO', 'ElementTypeParam:64:1:7', false, false, 'left', false, false, 100, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),

(250, 68, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(251, 68, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(252, 68, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(253, 68, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(254, 68, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(259, 68, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:68:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(258, 68, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:68:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(260, 71, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(261, 71, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(262, 71, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(263, 71, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(264, 71, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(268, 71, 1, 10, false, false, true, false, 'LBL_ELECTRICAL_CABINET', 'LBL_ELECTRICAL_CABINET', 'ElementTypeParam:71:1:6', false, false, 'left', false, false, 200, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(269, 71, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:71:1:2', false, false, 'left', false, false, 150, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(270, 71, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:71:1:1', false, false, 'left', false, false, 150, NULL, true, true, NULL, false, NULL, NULL, NULL),

(280, 89, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(281, 89, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(282, 89, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(283, 89, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(284, 89, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(285, 89, 1, 6, false, false, true, false, 'LBL_MODEL', 'LBL_MODEL', 'ElementTypeParam:89:1:2', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(286, 89, 1, 7, false, false, true, false, 'LBL_BRAND', 'LBL_BRAND', 'ElementTypeParam:89:1:1', false, false, 'left', false, false, 100, NULL, true, true, NULL, false, NULL, NULL,  NULL),

(271, 97, 1, 1, true, false, false, false, 'LBL_ID', 'LBL_ID', 'id', true, false, NULL, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL,  NULL),
(272, 97, 1, 2, true, false, false, true, 'LBL_NAME', 'LBL_NAME', 'alias', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(273, 97, 1, 3, true, false, false, false, 'LBL_DESCRIPTION', 'LBL_DESCRIPTION', 'description', false, false, NULL, false, false, 150, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(274, 97, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 50, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(275, 97, 1, 5, true, true, false, true, 'LBL_STATE_LABEL', 'LBL_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(276, 97, 1, 6, false, false, true, false, 'LBL_ROUTE', 'LBL_ROUTE', 'ElementTypeParam:97:1:1', false, false, 'left', false, false, 210, NULL, true, true, NULL, NULL, NULL, NULL,  NULL),
(277, 97, 1, 7, false, false, true, false, 'LBL_USER', 'LBL_USER', 'ElementTypeParam:97:1:2', false, false, 'left', false, false, 150, NULL, true, true, NULL, false, NULL, NULL,  NULL),
(278, 97, 1, 8, false, false, true, false, 'LBL_PASSWORD', 'LBL_PASSWORD', 'ElementTypeParam:97:1:3', false, false, 'left', false, false, 150, NULL, true, true, NULL, false, NULL, NULL, NULL),
(279, 97, 1, 9, false, false, true, false, 'LBL_ASSOCIATED_CABINET', 'LBL_ASSOCIATED_CABINET', 'ElementTypeParam:97:1:4', false, false, 'left', false, false, 150, NULL, true, true, NULL, false, NULL, NULL, NULL);

UPDATE ui.grid_option_values SET value = 'false' WHERE grid_id IN (1000, 1001, 1003, 1004, 1005, 1010) AND grid_option_id IN (25, 26);

INSERT INTO ui.grid_option_values(grid_id, grid_option_id, value) VALUES
(1, 1, 'true'),
(1, 2, 'true'),
(1, 7, 'true'),
(1, 8, 'true'),
(1, 9, 'false'),
(1, 10, 'true'),
(1, 11, 'true'),
(1, 12, 'true'),
(1, 13, 'true'),
(1, 14, 'false'),
(1, 15, 'false'),
(1, 16, 'img/grid/element_type_01.png'),
(1, 17, 'true'),
(1, 20, 'true'),
(1, 22, 160),

(2, 1, 'true'),
(2, 2, 'true'),
(2, 7, 'true'),
(2, 8, 'true'),
(2, 9, 'false'),
(2, 10, 'true'),
(2, 11, 'true'),
(2, 12, 'true'),
(2, 13, 'true'),
(2, 14, 'false'),
(2, 15, 'false'),
(2, 16, 'img/grid/element_type_02.png'),
(2, 17, 'true'),
(2, 20, 'true'),

(3, 1, 'true'),
(3, 2, 'true'),
(3, 7, 'true'),
(3, 8, 'true'),
(3, 9, 'false'),
(3, 10, 'true'),
(3, 11, 'true'),
(3, 12, 'true'),
(3, 13, 'true'),
(3, 14, 'false'),
(3, 15, 'false'),
(3, 16, 'img/grid/detector.png'),
(3, 17, 'true'),

(4, 1, 'true'),
(4, 2, 'true'),
(4, 7, 'true'),
(4, 8, 'true'),
(4, 9, 'false'),
(4, 10, 'true'),
(4, 11, 'true'),
(4, 12, 'true'),
(4, 13, 'true'),
(4, 14, 'false'),
(4, 15, 'false'),
(4, 16, 'img/grid/element_type_04.png'),
(4, 17, 'true'),
(4, 20, 'true'),
(4, 22, 120),

(23, 1, 'true'),
(23, 2, 'true'),
(23, 7, 'true'),
(23, 8, 'true'),
(23, 9, 'false'),
(23, 10, 'true'),
(23, 11, 'true'),
(23, 12, 'true'),
(23, 13, 'true'),
(23, 14, 'false'),
(23, 15, 'false'),
(23, 16, 'img/grid/element_type_23.png'),
(23, 17, 'true'),
(23, 20, 'true'),

(25, 1, 'true'),
(25, 2, 'true'),
(25, 7, 'true'),
(25, 8, 'true'),
(25, 9, 'false'),
(25, 10, 'true'),
(25, 11, 'true'),
(25, 12, 'true'),
(25, 13, 'true'),
(25, 14, 'false'),
(25, 15, 'false'),
(25, 16, 'img/grid/element_type_25.png'),
(25, 17, 'true'),
(25, 20, 'true'),

(34, 1, 'true'),
(34, 2, 'true'),
(34, 7, 'true'),
(34, 8, 'true'),
(34, 9, 'false'),
(34, 10, 'true'),
(34, 11, 'true'),
(34, 12, 'true'),
(34, 13, 'true'),
(34, 14, 'false'),
(34, 15, 'false'),
(34, 16, 'img/grid/element_type_34.png'),
(34, 17, 'true'),
(34, 20, 'true'),

(39, 1, 'true'),
(39, 2, 'true'),
(39, 7, 'true'),
(39, 8, 'true'),
(39, 9, 'false'),
(39, 10, 'true'),
(39, 11, 'true'),
(39, 12, 'true'),
(39, 13, 'true'),
(39, 14, 'false'),
(39, 15, 'false'),
(39, 16, 'img/grid/element_type_39.png'),
(39, 17, 'true'),
(39, 20, 'true'),

(40, 1, 'true'),
(40, 2, 'true'),
(40, 7, 'true'),
(40, 8, 'true'),
(40, 9, 'false'),
(40, 10, 'true'),
(40, 11, 'true'),
(40, 12, 'true'),
(40, 13, 'true'),
(40, 14, 'false'),
(40, 15, 'false'),
(40, 16, 'img/grid/element_type_40.png'),
(40, 17, 'true'),
(40, 20, 'true'),


(41, 1, 'true'),
(41, 2, 'true'),
(41, 7, 'true'),
(41, 8, 'true'),
(41, 9, 'false'),
(41, 10, 'true'),
(41, 11, 'true'),
(41, 12, 'true'),
(41, 13, 'true'),
(41, 14, 'false'),
(41, 15, 'false'),
(41, 16, 'img/grid/element_type_41.png'),
(41, 17, 'true'),
(41, 20, 'true'),

(42, 1, 'true'),
(42, 2, 'true'),
(42, 7, 'true'),
(42, 8, 'true'),
(42, 9, 'false'),
(42, 10, 'true'),
(42, 11, 'true'),
(42, 12, 'true'),
(42, 13, 'true'),
(42, 14, 'false'),
(42, 15, 'false'),
(42, 16, 'img/grid/element_type_42.png'),
(42, 17, 'true'),
(42, 20, 'true'),

(43, 1, 'true'),
(43, 2, 'true'),
(43, 7, 'true'),
(43, 8, 'true'),
(43, 9, 'false'),
(43, 10, 'true'),
(43, 11, 'true'),
(43, 12, 'true'),
(43, 13, 'true'),
(43, 14, 'false'),
(43, 15, 'false'),
(43, 16, 'img/grid/element_type_43.png'),
(43, 17, 'true'),
(43, 20, 'true'),

(44, 1, 'true'),
(44, 2, 'true'),
(44, 7, 'true'),
(44, 8, 'true'),
(44, 9, 'false'),
(44, 10, 'true'),
(44, 11, 'true'),
(44, 12, 'true'),
(44, 13, 'true'),
(44, 14, 'false'),
(44, 15, 'false'),
(44, 16, 'img/grid/element_type_44.png'),
(44, 17, 'true'),
(44, 20, 'true'),

(45, 1, 'true'),
(45, 2, 'true'),
(45, 7, 'true'),
(45, 8, 'true'),
(45, 9, 'false'),
(45, 10, 'true'),
(45, 11, 'true'),
(45, 12, 'true'),
(45, 13, 'true'),
(45, 14, 'false'),
(45, 15, 'false'),
(45, 16, 'img/grid/element_type_45.png'),
(45, 17, 'true'),
(45, 20, 'true'),

(46, 1, 'true'),
(46, 2, 'true'),
(46, 7, 'true'),
(46, 8, 'true'),
(46, 9, 'false'),
(46, 10, 'true'),
(46, 11, 'true'),
(46, 12, 'true'),
(46, 13, 'true'),
(46, 14, 'false'),
(46, 15, 'false'),
(46, 16, 'img/grid/element_type_46.png'),
(46, 17, 'true'),
(46, 20, 'true'),

(47, 1, 'true'),
(47, 2, 'true'),
(47, 7, 'true'),
(47, 8, 'true'),
(47, 9, 'false'),
(47, 10, 'true'),
(47, 11, 'true'),
(47, 12, 'true'),
(47, 13, 'true'),
(47, 14, 'false'),
(47, 15, 'false'),
(47, 16, 'img/grid/element_type_47.png'),
(47, 17, 'true'),
(47, 20, 'true'),

(51, 1, 'true'),
(51, 2, 'true'),
(51, 7, 'true'),
(51, 8, 'true'),
(51, 9, 'false'),
(51, 10, 'true'),
(51, 11, 'true'),
(51, 12, 'true'),
(51, 13, 'true'),
(51, 14, 'false'),
(51, 15, 'false'),
(51, 16, 'img/grid/element_type_51.png'),
(51, 17, 'true'),
(51, 20, 'true'),

(54, 1, 'true'),
(54, 2, 'true'),
(54, 7, 'true'),
(54, 8, 'true'),
(54, 9, 'false'),
(54, 10, 'true'),
(54, 11, 'true'),
(54, 12, 'true'),
(54, 13, 'true'),
(54, 14, 'false'),
(54, 15, 'false'),
(54, 16, 'img/grid/element_type_54.png'),
(54, 17, 'true'),
(54, 20, 'true'),

(68, 1, 'true'),
(68, 2, 'true'),
(68, 7, 'true'),
(68, 8, 'true'),
(68, 9, 'false'),
(68, 10, 'true'),
(68, 11, 'true'),
(68, 12, 'true'),
(68, 13, 'true'),
(68, 14, 'false'),
(68, 15, 'false'),
(68, 16, 'img/grid/element_type_68.png'),
(68, 17, 'true'),
(68, 20, 'true'),

(71, 1, 'true'),
(71, 2, 'true'),
(71, 7, 'true'),
(71, 8, 'true'),
(71, 9, 'false'),
(71, 10, 'true'),
(71, 11, 'true'),
(71, 12, 'true'),
(71, 13, 'true'),
(71, 14, 'false'),
(71, 15, 'false'),
(71, 16, 'img/grid/element_type_71.png'),
(71, 17, 'true'),
(71, 20, 'true'),

(89, 1, 'true'),
(89, 2, 'true'),
(89, 7, 'true'),
(89, 8, 'true'),
(89, 9, 'false'),
(89, 10, 'true'),
(89, 11, 'true'),
(89, 12, 'true'),
(89, 13, 'true'),
(89, 14, 'false'),
(89, 15, 'false'),
(89, 16, 'img/grid/element_type_89.png'),
(89, 17, 'true'),
(89, 20, 'true'),


(97, 1, 'true'),
(97, 2, 'true'),
(97, 7, 'true'),
(97, 8, 'true'),
(97, 9, 'false'),
(97, 10, 'true'),
(97, 11, 'true'),
(97, 12, 'true'),
(97, 13, 'true'),
(97, 14, 'false'),
(97, 15, 'false'),
(97, 16, 'img/grid/element_type_51.png'),
(97, 17, 'true'),
(97, 20, 'true');

INSERT INTO ui.grid_commands(grid_id, "position", "label", icon, "default", module_action_id, args, view_type_id, multiselect, show_text, item_required) VALUES
(1, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(1, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(1, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(2, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(2, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(2, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(3, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(3, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(3, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(4, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(4, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(4, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(23, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(23, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(23, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(25, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(25, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(25, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(34, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(34, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(34, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(39, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(39, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(39, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(40, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(40, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(40, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),


(41, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(41, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(41, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(42, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(42, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(42, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(43, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(43, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(43, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(44, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(44, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(44, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(45, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(45, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(45, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(46, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(46, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(46, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(47, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(47, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(47, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(51, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(51, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(51, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(54, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(54, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(54, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(64, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(64, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(64, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(68, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(68, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(68, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(71, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(71, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(71, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),


(89, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(89, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(89, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true),

(97, 1, 'LBL_CMD_VIEW', 'mdi mdi-pencil', true, 101401, NULL, NULL, false, false, false),
(97, 2, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true),
(97, 3, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, NULL, 2, true, true, true);


INSERT INTO ui.grid_field_icons(grid_field_id, icon, value, show_value, badge_color, avatar, enabled, label_value) VALUES
(4, './img/state/stateUnknown.png', 'ElementTypeState:1:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(4, './img/state/stateUp.png', 'ElementTypeState:1:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),
(4, './img/state/stateDown.png', 'ElementTypeState:1:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),
(4, './img/state/stateAlarm.png', 'ElementTypeState:1:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),

(37, './img/state/stateUnknown.png', 'ElementTypeState:2:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(37, './img/state/stateUp.png', 'ElementTypeState:2:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(37, './img/state/stateDown.png', 'ElementTypeState:2:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(37, './img/state/stateAlarm.png', 'ElementTypeState:2:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(50, './img/state/stateUnknown.png', 'ElementTypeState:3:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(50, './img/state/stateUp.png', 'ElementTypeState:3:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(50, './img/state/stateDown.png', 'ElementTypeState:3:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(50, './img/state/stateAlarm.png', 'ElementTypeState:3:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(83, './img/state/stateUnknown.png', 'ElementTypeState:4:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(83, './img/state/stateUp.png', 'ElementTypeState:4:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(83, './img/state/stateDown.png', 'ElementTypeState:4:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(83, './img/state/stateAlarm.png', 'ElementTypeState:4:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(96, './img/state/stateUnknown.png', 'ElementTypeState:23:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(96, './img/state/stateUp.png', 'ElementTypeState:23:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),         
(96, './img/state/stateAlarm.png', 'ElementTypeState:23:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),  

(109, './img/state/stateUnknown.png', 'ElementTypeState:25:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(109, './img/state/stateUp.png', 'ElementTypeState:25:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(109, './img/state/stateDown.png', 'ElementTypeState:25:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(109, './img/state/stateAlarm.png', 'ElementTypeState:25:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(162, './img/state/stateUnknown.png', 'ElementTypeState:34:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(162, './img/state/stateUp.png', 'ElementTypeState:34:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(162, './img/state/stateDown.png', 'ElementTypeState:34:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(162, './img/state/stateAlarm.png', 'ElementTypeState:34:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(291, './img/state/stateUnknown.png', 'ElementTypeState:39:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(291, './img/state/stateUp.png', 'ElementTypeState:39:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(291, './img/state/stateDown.png', 'ElementTypeState:39:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(291, './img/state/stateAlarm.png', 'ElementTypeState:39:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(298, './img/state/stateUnknown.png', 'ElementTypeState:40:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(298, './img/state/stateUp.png', 'ElementTypeState:40:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(298, './img/state/stateDown.png', 'ElementTypeState:40:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(298, './img/state/stateAlarm.png', 'ElementTypeState:40:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(170, './img/state/stateUnknown.png', 'ElementTypeState:41:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(170, './img/state/stateUp.png', 'ElementTypeState:41:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(170, './img/state/stateDown.png', 'ElementTypeState:41:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(170, './img/state/stateAlarm.png', 'ElementTypeState:41:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(178, './img/state/stateUnknown.png', 'ElementTypeState:42:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(178, './img/state/stateUp.png', 'ElementTypeState:42:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(178, './img/state/stateDown.png', 'ElementTypeState:42:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(178, './img/state/stateAlarm.png', 'ElementTypeState:42:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(186, './img/state/stateUnknown.png', 'ElementTypeState:43:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(186, './img/state/stateUp.png', 'ElementTypeState:43:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(186, './img/state/stateDown.png', 'ElementTypeState:43:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(186, './img/state/stateAlarm.png', 'ElementTypeState:43:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(194, './img/state/stateUnknown.png', 'ElementTypeState:44:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(194, './img/state/stateUp.png', 'ElementTypeState:44:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(194, './img/state/stateDown.png', 'ElementTypeState:44:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(194, './img/state/stateAlarm.png', 'ElementTypeState:44:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(202, './img/state/stateUnknown.png', 'ElementTypeState:45:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(202, './img/state/stateUp.png', 'ElementTypeState:45:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(202, './img/state/stateDown.png', 'ElementTypeState:45:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(202, './img/state/stateAlarm.png', 'ElementTypeState:45:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(210, './img/state/stateUnknown.png', 'ElementTypeState:46:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(210, './img/state/stateUp.png', 'ElementTypeState:46:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(210, './img/state/stateDown.png', 'ElementTypeState:46:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(210, './img/state/stateAlarm.png', 'ElementTypeState:46:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(218, './img/state/stateUnknown.png', 'ElementTypeState:47:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(218, './img/state/stateUp.png', 'ElementTypeState:47:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(218, './img/state/stateDown.png', 'ElementTypeState:47:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(218, './img/state/stateAlarm.png', 'ElementTypeState:47:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(226, './img/state/stateUnknown.png', 'ElementTypeState:51:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(226, './img/state/stateUp.png', 'ElementTypeState:51:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(226, './img/state/stateDown.png', 'ElementTypeState:51:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(226, './img/state/stateAlarm.png', 'ElementTypeState:51:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(234, './img/state/stateUnknown.png', 'ElementTypeState:54:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(234, './img/state/stateUp.png', 'ElementTypeState:54:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(234, './img/state/stateDown.png', 'ElementTypeState:54:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(234, './img/state/stateAlarm.png', 'ElementTypeState:54:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(242, './img/state/stateUnknown.png', 'ElementTypeState:64:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(242, './img/state/stateUp.png', 'ElementTypeState:64:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(242, './img/state/stateDown.png', 'ElementTypeState:64:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(242, './img/state/stateAlarm.png', 'ElementTypeState:64:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(253, './img/state/stateUnknown.png', 'ElementTypeState:68:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(253, './img/state/stateUp.png', 'ElementTypeState:68:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(253, './img/state/stateDown.png', 'ElementTypeState:68:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(253, './img/state/stateAlarm.png', 'ElementTypeState:68:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),    

(263, './img/state/stateUnknown.png', 'ElementTypeState:71:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(263, './img/state/stateUp.png', 'ElementTypeState:71:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(263, './img/state/stateDown.png', 'ElementTypeState:71:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(263, './img/state/stateAlarm.png', 'ElementTypeState:71:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),

(283, './img/state/stateUnknown.png', 'ElementTypeState:89:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(283, './img/state/stateUp.png', 'ElementTypeState:89:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(283, './img/state/stateDown.png', 'ElementTypeState:89:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(283, './img/state/stateAlarm.png', 'ElementTypeState:89:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),

(274, './img/state/stateUnknown.png', 'ElementTypeState:97:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(274, './img/state/stateUp.png', 'ElementTypeState:97:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),          
(274, './img/state/stateDown.png', 'ElementTypeState:97:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),      
(274, './img/state/stateAlarm.png', 'ElementTypeState:97:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS');    


