1=ESTACION METEOROLOGICA
2=CAMARA
3=DETECTOR
4=SECCION
5=SERVIDOR DE MEGAFONIA
7=ZONE
8=BARRERA
9=VENTILADOR
11=POSTE SOS
12=LUXOMETRO
13=SEMAFORO DE 3 GRUPOS 
14=LUMINANCIMETRO
15=ZONA DE INCENDIOS
16=ZONA DE MEGAFONIA 
17=GALIBO
18=ANEMOMETRO INTERIOR
19=CO
20=NO
21=OPAC
22=VALVULAS
23=BATERIA
24=BIE
25=EC
26=SWITCH
27=PLC
28=NAS
29=CENTRAL FIBROLASER
30=SISTEMA RADIO
31=FOTOCELULA
32=PRESURIZACION
33=TRAFO
34=EC_SCN
36=BALIZA
37=IPL
38=BUS-VAO
41=EC_ATC
42=EC_NRL
43=EC_NRS
44=EC_TFA_3D
45=EC_TFA_LOOPS
46=EC_TOLL
47=EC_TU
50=VIAS
51=ETD
52=SERVIDOR DAI
53=SEMAFORO 2 GRUPOS
54=ATC
55=LOCAL TECNICO
56=UNIFILAR
57=INTERRUPTOR
58=PULSADOR
59=DETECTOR DE HUMO
60=SIRENA
61=CENTRAL PUNTUAL DE INCENDIOS
65=SAI
66=VELETA
68=TFA_3D
70=ANALIZADOR DE RED
71=PANEL DE MENSAJE VARIABLE
74=ERU
75=GRUPO ELECTROGENO
81=VISIBILIMETRO
82=ACELEROMETRO
83=RADAR
84=CIRCUITO ELECTRICO
85=DALI
86=BOMBA
87=DEPOSITO
88=SENSOR PERDIDA DE AGUA
89=PUERTA
93=GRUPO DE TRASIEGO
94=SISTEMA DE LLAMADA
96=GRUPO DE MEGAFONIA
1000=CC
2000=TUBO
2001=VENTILACION
2002=ILUMINACION
