address_to.level0=
address_to.level1=rlsantiago@ausol.es,jandrades@ausol.es
address_to.level2=mtamayo@ausol.es,caguilar@ausol.es,rlsantiago@ausol.es,jandrades@ausol.es,jalopez@ausol.es,dalende@ausol.es,aalonso@ausol.es
address_to.level3=
address_to.level4=mtamayo@ausol.es,caguilar@ausol.es,jalopez@ausol.es,dalende@ausol.es,aalonso@ausol.es
address_to.level5=mtamayo@ausol.es,caguilar@ausol.es,jalopez@ausol.es,dalende@ausol.es,aalonso@ausol.es

address_cc.level0=
address_cc.level1=
address_cc.level2=
address_cc.level3=
address_cc.level4=
address_cc.level5=

address_bcc.level0=
address_bcc.level1=
address_bcc.level2=
address_bcc.level3=
address_bcc.level4=
address_bcc.level5=