RV=TÚNEL DE RIO VERDE
MM=TÚNEL DE MONTEMAYOR
STMI=TÚNEL DE STA. MARIA I
STM2=TÚNEL DE STA. MARIA II
CH=TÚNEL DE CALAHONDA
COR=TÚNEL DE COROMINAS
LQ=TÚNEL DE LA QUINTA
EST=TÚNEL DE ESTEPONA
CAS=TÚNEL DE CASARES
NG=TÚNEL DE NAGÜELES
