INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(1, 26, 31, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 32, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 33, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 34, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 35, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 36, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 37, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 38, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 39, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 40, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 41, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 42, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 99, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
