-- 
-- Table: master.element_types
--
INSERT INTO master.element_types
(element_type_id, alias, description, label_alias, label_description,  initial_element_type_state_id, connected_element_type_state_id, disconnected_element_type_state_id, enabled, visible, created_at, updated_at)VALUES
(1, 'WEATHER_STATION', 'Weather station','LBL_ELEMENT_TYPE_WEATHER_STATION', 'LBL_ELEMENT_TYPE_WEATHER_STATION_DESC', 0, 1, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--
-- Table: master.element_type_params
--
INSERT INTO master.element_type_params
(element_type_id, param_type_id, element_type_param_id, element_type_param_unit_id, data_type_id, default_value, alias, description, label_alias, label_description, enabled, visible, editable, created_at, updated_at) VALUES
--CONFIG
(1,1,1, NULL,2, NULL, 'brand', 'brand', 'LBL_ELEMENT_TYPE_PARAM_BRAND' , 'LBL_ELEMENT_TYPE_PARAM_BRAND_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,1,2, NULL,2, NULL, 'model', 'model', 'LBL_ELEMENT_TYPE_PARAM_MODEL' , 'LBL_ELEMENT_TYPE_PARAM_MODEL_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,1,1003, NULL,2, NULL, 'MANGO SESSION_UID', 'MANGO SESSION_UID', 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID' , 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--MEASURE
(1,2,1,8,3, NULL, 'Surface_Temperature', 'surface temperature', 'LBL_ELEMENT_TYPE_PARAM_SURFACE_TEMPERATURE', 'LBL_ELEMENT_TYPE_PARAM_SURFACE_TEMPERATURE_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,2,8,3, NULL, 'Sub_Surface_Temperature', 'sub surface temperature', 'LBL_ELEMENT_TYPE_PARAM_SUB_SURFACE_TEMPERATURE', 'LBL_ELEMENT_TYPE_PARAM_SUB_SURFACE_TEMPERATURE_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,3,8,3, NULL, 'Freeze_Point', 'freeze point', 'LBL_ELEMENT_TYPE_PARAM_FREEZE_POINT', 'LBL_ELEMENT_TYPE_PARAM_FREEZE_POINT_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,4,2,3, NULL, 'Air_Pressure', 'air pressure', 'LBL_ELEMENT_TYPE_PARAM_AIR_PRESSURE', 'LBL_ELEMENT_TYPE_PARAM_AIR_PRESSURE_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,5,23,1, NULL, 'Water_Depth', 'water depth', 'LBL_ELEMENT_TYPE_PARAM_WATER_DEPTH', 'LBL_ELEMENT_TYPE_PARAM_WATER_DEPTH_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,6,3,1, NULL, 'Concentration_NaCl', 'concentration nacl', 'LBL_ELEMENT_TYPE_PARAM_CONCENTRATION_NACL', 'LBL_ELEMENT_TYPE_PARAM_CONCENTRATION_NACL_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,7,3,1, NULL, 'Concentration_MgCl2', 'concentration mgcl2', 'LBL_ELEMENT_TYPE_PARAM_CONCENTRATION_MGCL2', 'LBL_ELEMENT_TYPE_PARAM_CONCENTRATION_MGCL2_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,8,3,1, NULL, 'Concentration_CaCl', 'concentration cacl', 'LBL_ELEMENT_TYPE_PARAM_CONCENTRATION_CACL', 'LBL_ELEMENT_TYPE_PARAM_CONCENTRATION_CACL_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,9, NULL,1, NULL, 'Road_Condition', 'road condition mapped', 'LBL_ELEMENT_TYPE_PARAM_ROAD_CONDITION', 'LBL_ELEMENT_TYPE_PARAM_ROAD_CONDITION_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,10,3,1, NULL, 'Relative_Humidity', 'relative humidity', 'LBL_ELEMENT_TYPE_PARAM_RELATIVE_HUMIDITY', 'LBL_ELEMENT_TYPE_PARAM_RELATIVE_HUMIDITY_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,11,5,3, NULL, 'Precipitation_Intensity', 'precipitation intensity', 'LBL_ELEMENT_TYPE_PARAM_PRECIPITATION_INTENSITY', 'LBL_ELEMENT_TYPE_PARAM_PRECIPITATION_INTENSITY_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,12,5,3, NULL, 'Snow_Fall_Intensity', 'snow fall intensity', 'LBL_ELEMENT_TYPE_PARAM_SNOW_FALL_INTENSITY', 'LBL_ELEMENT_TYPE_PARAM_SNOW_FALL_INTENSITY_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,13,6,3, NULL, 'Average_Wind_Speed', 'average wind speed', 'LBL_ELEMENT_TYPE_PARAM_AVERAGE_WIND_SPEED', 'LBL_ELEMENT_TYPE_PARAM_AVERAGE_WIND_SPEED_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,14,7,1, NULL, 'Average_Wind_Direction', 'average wind direction', 'LBL_ELEMENT_TYPE_PARAM_AVERAGE_WIND_DIRECTION', 'LBL_ELEMENT_TYPE_PARAM_AVERAGE_WIND_DIRECTION_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,15,6,3, NULL, 'Gust_Wind_Speed', 'gust wind speed', 'LBL_ELEMENT_TYPE_PARAM_GUST_WIND_SPEED', 'LBL_ELEMENT_TYPE_PARAM_GUST_WIND_SPEED_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,16,7,1, NULL, 'Gust_Wind_Direction', 'gust wind direction', 'LBL_ELEMENT_TYPE_PARAM_GUST_WIND_DIRECTION', 'LBL_ELEMENT_TYPE_PARAM_GUST_WIND_DIRECTION_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,17,8,3, NULL, 'Air_Temperature', 'air temperature', 'LBL_ELEMENT_TYPE_PARAM_AIR_TEMPERATURE', 'LBL_ELEMENT_TYPE_PARAM_AIR_TEMPERATURE_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,18,8,3, NULL, 'Dew_Point_Temperature', 'dew point temperature', 'LBL_ELEMENT_TYPE_PARAM_DEW_POINT_TEMPERATURE', 'LBL_ELEMENT_TYPE_PARAM_DEW_POINT_TEMPERATURE_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,19, NULL,1, NULL, 'Precipitation_Type', 'precipitation type', 'LBL_ELEMENT_TYPE_PARAM_PRECIPITATION_TYPE', 'LBL_ELEMENT_TYPE_PARAM_PRECIPITATION_TYPE_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,20,1,3, NULL, 'Visibility', 'visibility', 'LBL_ELEMENT_TYPE_PARAM_VISIBILITY', 'LBL_ELEMENT_TYPE_PARAM_VISIBILITY_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,21, NULL,1, NULL, 'Black_Ice_Signal', 'black ice signal', 'LBL_ELEMENT_TYPE_PARAM_BLACK_ICE_SIGNAL', 'LBL_ELEMENT_TYPE_PARAM_BLACK_ICE_SIGNAL_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,22, NULL,1, NULL, 'Prediction_Alarm_Code', 'prediction alarm code', 'LBL_ELEMENT_TYPE_PARAM_PREDICTION_ALARM_CODE', 'LBL_ELEMENT_TYPE_PARAM_PREDICTION_ALARM_CODE_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,23, NULL,3, NULL, 'Precipitation_Quantity', 'precipitation quantity', 'LBL_ELEMENT_TYPE_PARAM_PRECIPITATION_QUANTITY', 'LBL_ELEMENT_TYPE_PARAM_PRECIPITATION_QUANTITY_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,24, NULL,3, NULL, 'Ice_Percent', 'ice percent', 'LBL_ELEMENT_TYPE_PARAM_ICE_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_ICE_PERCENT_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1,2,25, NULL,3, NULL, 'Friction', 'friccion', 'LBL_ELEMENT_TYPE_PARAM_FRICTION', 'LBL_ELEMENT_TYPE_PARAM_FRICTION_DESC', true, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_type_states
--
INSERT INTO master.element_type_states
(element_type_id, element_type_state_id, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(1, 0, 'UNKNOWN', 'Unknown state', 'LBL_ELEMENT_TYPE_STATE_UNKNOWN', 'LBL_ELEMENT_TYPE_STATE_UNKNOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 'UP', 'The state of the equipment is: comunicates', 'LBL_ELEMENT_TYPE_STATE_UP', 'LBL_ELEMENT_TYPE_STATE_UP_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 'DOWN', 'The state of the equipment is: out of communication', 'LBL_ELEMENT_TYPE_STATE_DOWN', 'LBL_ELEMENT_TYPE_STATE_DOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 'ALARMS', 'The state of the equipment is: with alarms', 'LBL_ELEMENT_TYPE_STATE_ALARMS', 'LBL_ELEMENT_TYPE_STATE_ALARMS_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, 'MAINTENANCE', 'The state of the equipment is: on Maintenance', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_type_state_transitions
--
INSERT INTO master.element_type_state_transitions 
(element_type_id, current_element_type_state_id, next_element_type_state_id, enabled, visible, editable, created_at, updated_at) VALUES
(1, 0, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 0, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 1, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_hierarchies_allowed
--
INSERT INTO master.element_hierarchies_allowed
(parent_element_type_id, child_element_type_id, enabled, visible, created_at, updated_at) VALUES
(1, 31, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 54, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 71, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.io_controller_module_type_element_types
--
INSERT INTO master.io_controller_module_type_element_types
(module_type_id, element_type_id, enabled, visible, created_at, updated_at) VALUES
(1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: conf.alarm_configs
--
INSERT INTO conf.alarm_configs
(alarm_config_id, alarm_type_id, alarm_level_id, element_type_id, element_id, element_type_state_id, mine, treatment, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
--Común a todos los subtipos
(010001, 2, 6, 1, NULL, NULL, true, true, 'ALARM WS NO CONNECTION', 'ALARM WS NO CONNECTION', 'LBL_ALARM_CONFIGS_ALARM_WS_NO_CONNECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Subtipos NTCIP P1 y P2
(020001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS DOOR OPEN', 'ALARM WS DOOR OPEN', 'LBL_ALARM_CONFIGS_ALARM_WS_DOOR_OPEN', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(030001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS POWER SUPPLY FAIL', 'ALARM WS POWER SUPPLY FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_POWER_SUPPLY_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(040001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS BATTERY LOW', 'ALARM WS BATTERY LOW', 'LBL_ALARM_CONFIGS_ALARM_WS_BATTERY_LOW', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(050001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS OVERLOAD UPS', 'ALARM WS OVERLOAD UPS', 'LBL_ALARM_CONFIGS_ALARM_WS_OVERLOAD_UPS', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(060001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS PLC STATUS', 'ALARM WS PLC STATUS', 'LBL_ALARM_CONFIGS_ALARM_WS_PLC_STATUS', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Subtipo Modbus P2
(070001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS VISIBILIMETER FAIL', 'ALARM WS VISIBILIMETER FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_VISIBILIMETER_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(080001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS AIR TEMPERATURE FAIL', 'ALARM WS AIR TEMPERATURE FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_AIR_TEMPERATURE_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS RELATIVE HUMIDITY FAIL', 'ALARM WS RELATIVE HUMIDITY FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_RELATIVE_HUMIDITY_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS AIR PRESSURE FAIL', 'ALARM WS AIR PRESSURE FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_AIR_PRESSURE_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS WIND SPEED FAIL', 'ALARM WS WIND SPEED FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_WIND_SPEED_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS WIND DIRECTION FAIL', 'ALARM WS WIND DIRECTION FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_WIND_DIRECTION_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(130001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS PRECIPITATION TYPE FAIL', 'ALARM WS PRECIPITATION TYPE FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_TYPE_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(140001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS PRECIPITATION INTENSITY FAIL', 'ALARM WS PRECIPITATION INTENSITY FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_INTENSITY_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(150001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS PRECIPITATION DIFFERENTIAL FAIL', 'ALARM WS PRECIPITATION DIFFERENTIAL FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_DIFFERENTIAL_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(160001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS SURFACE TEMPERATURE FAIL', 'ALARM WS SURFACE TEMPERATURE FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_SURFACE_TEMPERATURE_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(170001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS FREEZE SURFACE FAIL', 'ALARM WS FREEZE SURFACE FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_FREEZE_SURFACE_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(180001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS WATER DEPTH FAIL', 'ALARM WS WATER DEPTH FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_WATER_DEPTH_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(190001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS ICE PERCENT FAIL', 'ALARM WS ICE PERCENT FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_ICE_PERCENT_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(200001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS FRICTION FAIL', 'ALARM WS FRICTION FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_FRICTION_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(210001, 2, 5, 1, NULL, 3, true, true, 'ALARM WS ROAD CONDITION FAIL', 'ALARM WS ROAD CONDITION FAIL', 'LBL_ALARM_CONFIGS_ALARM_WS_ROAD_CONDITION_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: conf.element_state_alarms
--
INSERT INTO conf.element_state_alarms
(element_type_id, element_type_state_id, alarm_config_id, created_at, updated_at) VALUES
(1, 2, 010001, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
