/*INSERT INTO ui.vms_libraries(id, name, description, label, enabled, visible) VALUES
(01, 'Librería mensajes', null, 'LBL_LIB_VMS', true, true);

INSERT INTO ui.vms_library_nodes(id, vms_library_id, name, description, label, signaling, enabled, visible) VALUES
(01, 01, 'Libreria', null, 'Libreria', null, true, true),

(0101, 01, 'Alternantes', null, 'Alternantes', null, true, true),
(0102, 01, 'Fijos', null, 'Fijos', null, true, true),
(0103, 01, 'Campaña DGT OPE', null, 'Campaña DGT OPE', null, true, true),
(0104, 01, '01 SECUENCA NAGÜELES', null, '01 SECUENCA NAGÜELES', null, true, true),
(0105, 01, 'CAMPAÑA SEGURIDAD VIAL', null, 'CAMPAÑA SEGURIDAD VIAL', null, true, true),
(0106, 01, 'CSV DIC', null, 'CSV DIC', null, true, true),
(0107, 01, 'CSV FEB', null, 'CSV FEB', null, true, true),
(0108, 01, 'CSV MAR', null, 'CSV MAR', null, true, true),
(0109, 01, 'CSV ABR', null, 'CSV ABR', null, true, true),
(0110, 01, 'CSV MAY', null, 'CSV MAY', null, true, true),
(0111, 01, 'CSV JUN', null, 'CSV JUN', null, true, true),

--Alternantes
(010101, 01, 'PLAN DESCUENTOS 2 QUINCENA PMV 22', null, 'PLAN DESCUENTOS 2 QUINCENA PMV 22', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":551,"alternance":551}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CON VIAT-TARJETA","alternance":"VISITE"},{"id":2,"value":"DESCUENTOS","alternance":"NUESTRA WEB"},{"id":3,"value":"HASTA 50%","alternance":""}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010102, 01, 'PLAN DESCUENTOS 1 QUINCENA PMV 9,10,18,19', null, 'PLAN DESCUENTOS 1 QUINCENA PMV 9,10,18,19', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":551,"alternance":null}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"AUTOPISTA","alternance":""},{"id":2,"value":"POR SU","alternance":""},{"id":3,"value":"SEGURIDAD","alternance":""}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010103, 01, 'S04A LLUVIA (PMV 1 PICTOGRAMA)', null, 'S04A LLUVIA (PMV 1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":67,"alternance":564}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CON LLUVIA","alternance":"CON LLUVIA"},{"id":2,"value":"MODERE","alternance":"MODERE"},{"id":3,"value":"VELOCIDAD","alternance":"VELOCIDAD"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010104, 01, 'SEÑALIZACIÓN S06 ARCEN OCUPADO', null, 'SEÑALIZACIÓN S06 ARCEN OCUPADO', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":317,"alternance":85}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCION"},{"id":2,"value":"EN TUNEL","alternance":"EN TUNEL"},{"id":3,"value":"","alternance":""}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010105, 01, 'S04C VIENTO (PMV 1 PICTOGRAMA)', null, 'S04C VIENTO (PMV 1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":564,"alternance":77}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CON VIENTO","alternance":"CON VIENTO"},{"id":2,"value":"MODERE SU","alternance":"MODERE SU"},{"id":3,"value":"VELOCIDAD","alternance":"VELOCIDAD"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010106, 01, 'CARRIL IZQUIERDO S05 (PMV 1 PICTOGRAMA)', null, 'CARRIL IZQUIERDO S05 (PMV 1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":723,"alternance":317}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CARRIL IZQDO","alternance":"CARRIL IZQDO"},{"id":2,"value":"CORTADO","alternance":"CORTADO"},{"id":3,"value":"EN TUNEL","alternance":"EN TUNEL"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010107, 01, 'S 11 RETENCIÓN EN TÚNEL ( 1 PICTOGRAMA)', null, 'S 11 RETENCIÓN EN TÚNEL ( 1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":80,"alternance":82}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"RETENCIONES","alternance":"EN RETENCION"},{"id":2,"value":"EN EL TUNEL","alternance":"PARE MOTOR"},{"id":3,"value":"","alternance":""}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010108, 01, 'S 11 RETENCIÓN EN TÚNEL ( 2 PICTOGRAMAS)', null, 'S 11 RETENCIÓN EN TÚNEL ( 2 PICTOGRAMAS)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":80,"alternance":80}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"RETENCIONES","alternance":"EN RETENCION"},{"id":2,"value":"EN EL TUNEL","alternance":"PARE MOTOR"},{"id":3,"value":"","alternance":""}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010109, 01, 'S05 CARRIL DERECHO (PMV 1 PICTOGRAMA)', null, 'S05 CARRIL DERECHO (PMV 1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":722,"alternance":317}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CARRIL DRCHO","alternance":"CARRIL DRCHO"},{"id":2,"value":"CORTADO","alternance":"CORTADO"},{"id":3,"value":"EN TUNEL","alternance":"EN TUNEL"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010110, 01, 'S05 CARRIL IZQUIERDO (PMV 1 PICTOGRAMA)', null, 'S05 CARRIL IZQUIERDO (PMV 1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":723,"alternance":317}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CARRIL IZQDO","alternance":"CARRIL IZQDO"},{"id":2,"value":"CORTADO","alternance":"CORTADO"},{"id":3,"value":"EN TUNEL","alternance":"EN TUNEL"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010111, 01, 'PLAN PAGO RÁPIDO PMV 11 Y 13', null, 'PLAN PAGO RÁPIDO PMV 11 Y 13', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":555,"alternance":555}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PREPARE","alternance":"POR RAPIDEZ"},{"id":2,"value":"PEAJE","alternance":"PAGUE CON"},{"id":3,"value":"2.05 EUROS","alternance":"TARJETA"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010112, 01, 'S 25 OBRA CARRIL DERECHO (1 PICTOGRAMA)', null, 'S 25 OBRA CARRIL DERECHO (1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":744,"alternance":66}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CARRIL DRCHO","alternance":""},{"id":2,"value":"CORTADO","alternance":"MODERE SU"},{"id":3,"value":"EN TUNEL","alternance":"VELOCIDAD"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010113, 01, 'S 25 OBRA CARRIL IZQUIERDO (1 PICTOGRAMA)', null, 'S 25 OBRA CARRIL IZQUIERDO (1 PICTOGRAMA)', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":743,"alternance":66}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CARRIL IZQDO","alternance":""},{"id":2,"value":"CORTADO","alternance":"MODERE SU"},{"id":3,"value":"EN TUNEL","alternance":"VELOCIDAD"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010114, 01, 'CORONAVIRUS', null, 'CORONAVIRUS', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":819,"alternance":819}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"OMS ACONSEJA","alternance":"OMS ACONSEJA"},{"id":2,"value":"PAGO CON","alternance":"PAGO CON"},{"id":3,"value":"TARJETA","alternance":"CONTACT-LESS"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010115, 01, 'NUEVA 60 1 PICTOGRAMA', null, 'NUEVA 60 1 PICTOGRAMA', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":66,"alternance":317}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"RESPETE LA","alternance":"PRECAUCION"},{"id":2,"value":"SEÑALIZACION","alternance":"EN"},{"id":3,"value":"","alternance":"TUNEL"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010116, 01, 'NUEVA 80 1 PICTOGRAMA', null, 'NUEVA 80 1 PICTOGRAMA', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":66,"alternance":319}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"RESPETE LA","alternance":"PRECAUCION"},{"id":2,"value":"SEÑALIZACION","alternance":"EN"},{"id":3,"value":"","alternance":"TUNEL"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010117, 01, 'NUEVA 80 2 PICTOGRAMAS', null, 'NUEVA 80 2 PICTOGRAMAS', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":319,"alternance":319}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"RESPETE LA","alternance":""PRECAUCION},{"id":2,"value":"SEÑALIZACION","alternance":"EN"},{"id":3,"value":"","alternance":"TUNEL"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),
(010118, 01, 'NUEVA 60 2 PICTOGRAMAS', null, 'NUEVA 60 2 PICTOGRAMAS', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":317,"alternance":317}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"RESPETE LA","alternance":"PRECAUCION"},{"id":2,"value":"SEÑALIZACION","alternance":"EN"},{"id":3,"value":"","alternance":"TUNEL"}]},{"zone":3,"alternance_ms":3000,"graphics":[{"id":1,"value":null,"alternance":null}]}]', true, true),


--Fijos
(010201, 01, 'Arcén derecho a', null, 'Arcén derecho a', '[{"zone":1,"graphics":[{"id":1,"value":64}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"A X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010202, 01, 'Arcén derecho en', null, 'Arcén derecho en', '[{"zone":1,"graphics":[{"id":1,"value":64}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010203, 01, 'Arcén derecho en túnel', null, 'Arcén derecho en túnel', '[{"zone":1,"graphics":[{"id":1,"value":64}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN TUNEL"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010204, 01, 'Arcén derecho ocupado', null, 'Arcén derecho ocupado', '[{"zone":1,"graphics":[{"id":1,"value":64}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"PRECAUCION"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010205, 01, 'Arcén izquierdo a', null, 'Arcén izquierdo a', '[{"zone":1,"graphics":[{"id":1,"value":65}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"A X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010206, 01, 'Arcén izquierdo en', null, 'Arcén izquierdo en', '[{"zone":1,"graphics":[{"id":1,"value":65}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010207, 01, 'Arcén izquierdo en túnel', null, 'Arcén izquierdo en túnel', '[{"zone":1,"graphics":[{"id":1,"value":65}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN TUNEL"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010208, 01, 'Arcén izquierdo ocupado', null, 'Arcén izquierdo ocupado', '[{"zone":1,"graphics":[{"id":1,"value":65}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"PRECAUCION"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010209, 01, 'S04_SEÑALIZACION_POR_LLUVIA', null, 'S04_SEÑALIZACION_POR_LLUVIA', '[{"zone":1,"graphics":[{"id":1,"value":67}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CON LLUVIA"},{"id":2,"value":"MODERE SU"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010210, 01, 'S04_SEÑALIZACION_POR_VIENTO', null, 'S04_SEÑALIZACION_POR_VIENTO', '[{"zone":1,"graphics":[{"id":1,"value":77}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CON VIENTO"},{"id":2,"value":"MODERE SU"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010211, 01, 'Viento', null, 'Viento', '[{"zone":1,"graphics":[{"id":1,"value":77}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"MODERE"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010212, 01, 'Precaución_accidente_a', null, 'Precaución_accidente_a', '[{"zone":1,"graphics":[{"id":1,"value":80}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"ACCIDENTE"},{"id":3,"value":"A X KM"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010213, 01, 'Retenciones_a', null, 'Retenciones_a', '[{"zone":1,"graphics":[{"id":1,"value":80}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"A X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010214, 01, 'Retenciones_en', null, 'Retenciones_en', '[{"zone":1,"graphics":[{"id":1,"value":80}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010215, 01, 'Vehículo_lento_en_túnel', null, 'Vehículo_lento_en_túnel', '[{"zone":1,"graphics":[{"id":1,"value":80}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"VEHICULO"},{"id":2,"value":"LENTO"},{"id":3,"value":"EN TUNEL"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010216, 01, 'S02_CIERRE_ACCESO_TUNEL_FASE_2', null, 'S02_CIERRE_ACCESO_TUNEL_FASE_2', '[{"zone":1,"graphics":[{"id":1,"value":80}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"TUNEL"},{"id":2,"value":"CERRADO"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010217, 01, 'Visibilidad_reducida_en_Túnel', null, 'Visibilidad_reducida_en_Túnel', '[{"zone":1,"graphics":[{"id":1,"value":82}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN TUNEL"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010218, 01, 'Niebla', null, 'Niebla', '[{"zone":1,"graphics":[{"id":1,"value":82}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CON NIEBLA"},{"id":2,"value":"MODERE"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010219, 01, 'Nieve-Hielo', null, 'Nieve-Hielo', '[{"zone":1,"graphics":[{"id":1,"value":84}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"MODERE"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010220, 01, 'Plan_desvíos_01-A', null, 'Plan_desvíos_01-A', '[{"zone":1,"graphics":[{"id":1,"value":85}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"AP-7"},{"id":2,"value":"CORTADA"},{"id":3,"value":"EN PK X"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010221, 01, 'Plan_desvíos_02-A', null, 'Plan_desvíos_02-A', '[{"zone":1,"graphics":[{"id":1,"value":85}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"AP-7"},{"id":2,"value":"CORTADA"},{"id":3,"value":"A X M"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010222, 01, 'Plan_desvíos_03-A', null, 'Plan_desvíos_03-A', '[{"zone":1,"graphics":[{"id":1,"value":85}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"AP-7"},{"id":2,"value":"CORTADA"},{"id":3,"value":"A X M"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010223, 01, 'Precaución_vehículo_lento', null, 'Precaución_vehículo_lento', '[{"zone":1,"graphics":[{"id":1,"value":85}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"PRECAUCION"},{"id":2,"value":"VEHICULO"},{"id":3,"value":"LENTO"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010224, 01, 'S04_SEÑALIZACION_POR_NIEBLA', null, 'S04_SEÑALIZACION_POR_NIEBLA', '[{"zone":1,"graphics":[{"id":1,"value":85}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CON NIEBLA"},{"id":2,"value":"MODERE SU"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010225, 01, 'Túnel_cerrado', null, 'Túnel_cerrado', '[{"zone":1,"graphics":[{"id":1,"value":202}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"TUNEL"},{"id":3,"value":"CERRADO"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010226, 01, 'Lluvia', null, 'Lluvia', '[{"zone":1,"graphics":[{"id":1,"value":301}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CON LLUVIA"},{"id":2,"value":"MODERE"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010227, 01, 'Precaución_en_túnel', null, 'Precaución_en_túnel', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"PRECAUCION"},{"id":3,"value":"EN TUNEL"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010228, 01, 'S02_CIERRE_ACCESO_TUNEL_FASE_1', null, 'S02_CIERRE_ACCESO_TUNEL_FASE_1', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"ATENCION"},{"id":2,"value":"RESPETE"},{"id":3,"value":"SEMAFOROS"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010229, 01, 'S03_SEÑALIZACION_TUNEL_POR_LLUVIA_INTENSA', null, 'S03_SEÑALIZACION_TUNEL_POR_LLUVIA_INTENSA', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CON LLUVIA"},{"id":2,"value":"MODERE SU"},{"id":3,"value":"VELOCIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010230, 01, 'S05_CORTE_CARRIL_DERECHO_EN_TUNEL', null, 'S05_CORTE_CARRIL_DERECHO_EN_TUNEL', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CARRIL DCHO"},{"id":2,"value":"CORTADO"},{"id":3,"value":"EN TUNEL"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010231, 01, 'S05_CORTE_CARRIL_IZQUIERDO_EN_TUNEL', null, 'S05_CORTE_CARRIL_IZQUIERDO_EN_TUNEL', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CARRIL IZQDO"},{"id":2,"value":"CORTADO"},{"id":3,"value":"EN TUNEL"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010232, 01, 'S06_PRECAUCION_EN_INTERIOR_TUNEL', null, 'S06_PRECAUCION_EN_INTERIOR_TUNEL', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"PRECAUCION"},{"id":2,"value":"EN TUNEL"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010233, 01, 'S07_VISIBILIDAD_REDUCIDA_EN_TUNEL', null, 'S07_VISIBILIDAD_REDUCIDA_EN_TUNEL', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"VISIBILIDAD"},{"id":2,"value":"REDUCIDA"},{"id":3,"value":"EN TUNEL"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010234, 01, 'S10_VEHICULO_LENTO_EN_TUNEL', null, 'S10_VEHICULO_LENTO_EN_TUNEL', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"VEHICULO"},{"id":2,"value":"LENTO"},{"id":3,"value":"EN TUNEL"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010235, 01, 'S10_VEHÍCULO_LENTO_EN_TÚNEL', null, 'S10_VEHÍCULO_LENTO_EN_TÚNEL', '[{"zone":1,"graphics":[{"id":1,"value":317}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"VEHICULO"},{"id":2,"value":"LENTO"},{"id":3,"value":"EN TUNEL"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010236, 01, 'MEJORAS_EN_TUNELES_1_Y_2_PICTOGRAMAS', null, 'MEJORAS_EN_TUNELES_1_Y_2_PICTOGRAMAS', '[{"zone":1,"graphics":[{"id":1,"value":319}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"MEJORAS EN"},{"id":2,"value":"TUNELES POR"},{"id":3,"value":"SU SEGURIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010237, 01, '02_Prueba_Panel', null, '02_Prueba_Panel', '[{"zone":1,"graphics":[{"id":1,"value":322}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"888888888888"},{"id":2,"value":"888888888888"},{"id":3,"value":"888888888888"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010238, 01, 'Radar', null, 'Radar', '[{"zone":1,"graphics":[{"id":1,"value":716}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"VELOCIDAD"},{"id":2,"value":"CONTROLADA"},{"id":3,"value":"POR RADAR"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010239, 01, 'Carril_derecho_a', null, 'Carril_derecho_a', '[{"zone":1,"graphics":[{"id":1,"value":722}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"A X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010240, 01, 'Carril_derecho_cortado', null, 'Carril_derecho_cortado', '[{"zone":1,"graphics":[{"id":1,"value":722}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"PRECAUCION"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010241, 01, 'Carril_derecho_en', null, 'Carril_derecho_en', '[{"zone":1,"graphics":[{"id":1,"value":722}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010242, 01, 'Carril_derecho_en_túnel', null, 'Carril_derecho_en_túnel', '[{"zone":1,"graphics":[{"id":1,"value":722}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN TUNEL"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010243, 01, 'Carril_izquierdo_a', null, 'Carril_izquierdo_a', '[{"zone":1,"graphics":[{"id":1,"value":723}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"A X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010244, 01, 'Carril_izquierdo_cortado', null, 'Carril_izquierdo_cortado', '[{"zone":1,"graphics":[{"id":1,"value":723}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"PRECAUCION"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010245, 01, 'Carril_izquierdo_en', null, 'Carril_izquierdo_en', '[{"zone":1,"graphics":[{"id":1,"value":723}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN X KM"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010246, 01, 'Carril_izquierdo_en_túnel', null, 'Carril_izquierdo_en_túnel', '[{"zone":1,"graphics":[{"id":1,"value":723}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"EN TUNEL"},{"id":3,"value":""}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010247, 01, 'OMS_Coronavirus_1', null, 'OMS_Coronavirus_1', '[{"zone":1,"graphics":[{"id":1,"value":819}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"OMS ACONSEJA"},{"id":2,"value":"PAGO CON"},{"id":3,"value":"CONTACT-LESS"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010248, 01, 'OMS_Coronavirus_2', null, 'OMS_Coronavirus_2', '[{"zone":1,"graphics":[{"id":1,"value":819}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"OMS ACONSEJA"},{"id":2,"value":"PAGO CON"},{"id":3,"value":"TARJETA"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010249, 01, 'Plan_desvíos_01-B', null, 'Plan_desvíos_01-B', '[{"zone":1,"graphics":[{"id":1,"value":819}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"ALTERNATIVA"},{"id":2,"value":"POR A-7"},{"id":3,"value":"SALIDA X"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010250, 01, 'Plan_desvíos_02-B', null, 'Plan_desvíos_02-B', '[{"zone":1,"graphics":[{"id":1,"value":819}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"ALTERNATIVA"},{"id":2,"value":"POR A-7"},{"id":3,"value":"SALIDA X"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010251, 01, 'Plan_desvíos_03-B', null, 'Plan_desvíos_03-B', '[{"zone":1,"graphics":[{"id":1,"value":819}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"DESVIO"},{"id":2,"value":"PROVISIONAL"},{"id":3,"value":"SALIDA X"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010252, 01, 'Plan_desvíos_04', null, 'Plan_desvíos_04', '[{"zone":1,"graphics":[{"id":1,"value":819}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"ACCESO A"},{"id":2,"value":"AUTOPISTA"},{"id":3,"value":"AP-7"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010253, 01, '01_Prueba_Panel', null, '01_Prueba_Panel', '[{"zone":1,"graphics":[{"id":1,"value":819}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"888888888888"},{"id":2,"value":"888888888888"},{"id":3,"value":"888888888888"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),
(010254, 01, '100 MEJORAS EN TUNELES POR SU SEGURIDAD', null, '100 MEJORAS EN TUNELES POR SU SEGURIDAD', '[{"zone":1,"graphics":[{"id":1,"value":321}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"MEJORAS EN"},{"id":2,"value":"TUNELES POR"},{"id":3,"value":"SU SEGURIDAD"}]},{"zone":3,"graphics":[{"id":1,"value":null}]}]', true, true),

--Campaña DGT OPE
(010301, 01, 'USO OBLIGATORIO DEL CINTURON', null, 'USO OBLIGATORIO DEL CINTURON', '[{"zone":1,"graphics":[{"id":1,"value":"438"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"OBLIGATORIO","alternance":"CEINTURE","color":"#FFFFFF"},{"id":2,"value":"USO DEL","alternance":"EST","color":"#FFFFFF"},{"id":3,"value":"CINTURON","alternance":"OBLIGATOIRE","color":"#FFFFFF"}]},{"zone":3,"graphics":[{"id":1,"value":"438"}]}]', true, true),
(010302, 01, 'ADELANTE CON PRECAUCION', NULL, 'ADELANTE CON PRECAUCION', '[{"zone":1,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":3,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"ADELANTE","alternance":"DOUBLEZ","color":"#FFFFFF"},{"id":2,"value":"CON","alternance":"AVEC","color":"#FFFFFF"},{"id":3,"value":"PRECAUCION","alternance":"PRECAUTION","color":"#FFFFFF"}]}]', true, true),
(010303, 01, 'RESPETE LIMITACION VELOCIDAD', NULL, 'RESPETE LIMITACION VELOCIDAD', '[{"zone":1,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":3,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"RESPETE","alternance":"RESPECTEZ LA","color":"#FFFFFF"},{"id":2,"value":"LIMITACION","alternance":"LIMITATION","color":"#FFFFFF"},{"id":3,"value":"VELOCIDAD","alternance":"DE VITESSE","color":"#FFFFFF"}]}]', true, true),
(010304, 01, 'RESPETE LA DISTANCIA DE SEGURIDAD', NULL, 'RESPETE LA DISTANCIA DE SEGURIDAD', '[{"zone":1,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":3,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"RESPETE","alternance":"RESPECTEZ","color":"#FFFFFF"},{"id":2,"value":"LA DISTANCIA","alternance":"DISTANCES DE","color":"#FFFFFF"},{"id":3,"value":"DE SEGURIDAD","alternance":"SECURITE","color":"#FFFFFF"}]}]', true, true),
(010305, 01, 'NO VIAJE FATIGADO NI CON SUEÑO', NULL, 'NO VIAJE FATIGADO NI CON SUEÑO', '[{"zone":1,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":3,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"NO VIAJE","alternance":"NE VOYAGEZ","color":"#FFFFFF"},{"id":2,"value":"FATIGADO NI","alternance":"NI FATIGUE","color":"#FFFFFF"},{"id":3,"value":"CON SUEÑO","alternance":"NI SOMNOLENT","color":"#FFFFFF"}]}]', true, true),
(010306, 01, 'HAGA UNA PAUSA CADA 2 O 3 HORAS', NULL, 'HAGA UNA PAUSA CADA 2 O 3 HORAS', '[{"zone":1,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":3,"alternance_ms":5000,"graphics":[{"id":1,"value":"3000","alternance":"8001"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"HAGA UNA","alternance":"FAITES UNE","color":"#FFFFFF"},{"id":2,"value":"PAUSA CADA","alternance":"PAUSE CHAQUE","color":"#FFFFFF"},{"id":3,"value":"2 O 3 HORAS","alternance":"2 OU 3 HEURE","color":"#FFFFFF"}]}]', true, true),
(010307, 01, 'RECOMENDADO COMPRA ANTICIPADA', NULL, 'RECOMENDADO COMPRA ANTICIPADA', '[{"zone":1,"graphics":[{"id":1,"value":"8001"}]},{"zone":3,"graphics":[{"id":1,"value":"8001"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"RECOMENDADO","alternance":"AVIS","color":"#FFFFFF"},{"id":2,"value":"COMPRA","alternance":"ANTICIPER","color":"#FFFFFF"},{"id":3,"value":"ANTICIPADA","alternance":"ACHAT","color":"#FFFFFF"}]}]', true, true),
(010308, 01, 'TICKET PUERTOS EMBARQUE', NULL, 'TICKET PUERTOS EMBARQUE', '[{"zone":1,"graphics":[{"id":1,"value":"8001"}]},{"zone":3,"graphics":[{"id":1,"value":"8001"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"TICKET","alternance":"TICKET","color":"#FFFFFF"},{"id":2,"value":"PUERTOS","alternance":"PORTS","color":"#FFFFFF"},{"id":3,"value":"EMBARQUE","alternance":"EMBARQUEMENT","color":"#FFFFFF"}]}]', true, true),
(010309, 01, 'REVISA LAS LUCES DE TU VEHICULO', null, 'REVISA LAS LUCES DE TU VEHICULO','[{"zone":1,"alternance_ms":3000,"flashing_on_ms":0,"flashing_off_ms":0,"texts":[],"graphics":[],"align":"center"},{"zone":2,"alternance_ms":3000,"flashing_on_ms":0,"flashing_off_ms":0,"texts":[{"id":1,"value":"REVISA LAS","color":"#FFFFFF"},{"id":2,"value":"LUCES DE","color":"#FFFFFF"},{"id":3,"value":"TU VEHICULO","color":"#FFFFFF"}],"graphics":[],"align":"center"},{"zone":3,"alternance_ms":3000,"flashing_on_ms":0,"flashing_off_ms":0,"texts":[],"graphics":[],"align":"center"}]', true, true),
(010310, 01, 'LUCES PERFECTAS 0 INCIDENCIAS', null, 'LUCES PERFECTAS 0 INCIDENCIAS','[{"zone":1,"alternance_ms":3000,"flashing_on_ms":0,"flashing_off_ms":0,"texts":[],"graphics":[],"align":"center"},{"zone":2,"alternance_ms":3000,"flashing_on_ms":0,"flashing_off_ms":0,"texts":[{"id":1,"value":"LUCES","color":"#FFFFFF"},{"id":2,"value":"PERFECTAS 0","color":"#FFFFFF"},{"id":3,"value":"INCIDENCIAS","color":"#FFFFFF"}],"graphics":[],"align":"center"},{"zone":3,"alternance_ms":3000,"flashing_on_ms":0,"flashing_off_ms":0,"texts":[],"graphics":[],"align":"center"}]', true, true),

--01 SECUENCA NAGÜELES
(010401, 01, 'Secuencia Nagüeles', null, 'Secuencia Nagüeles', '[{"zone":3,"alternance_ms":5000,"graphics":[{"id":1,"value":"319","alternance":"319"}]},{"zone":1,"alternance_ms":5000,"graphics":[{"id":1,"value":"434","alternance":"301"}]},{"zone":2,"alternance_ms":5000,"align":"center","texts":[{"id":1,"value":"T. NAGUELES","alternance":"MANTENGA","color":"#FFFFFF"},{"id":2,"value":"CIRCULE CON","alternance":"DISTANCIA","color":"#FFFFFF"},{"id":3,"value":"PRECAUCION","alternance":"DE SEGURIDAD","color":"#FFFFFF"}]}]', true, true),


--01 CAMPAÑA SEGURIDAD VIAL - CSV OCT
(010601, 01, 'NO TE DISTRAIGAS', NULL, 'NO TE DISTRAIGAS', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":"NO  USES  EL","color":"#FFFFFF"},{"id":2,"value":" MOVIL  AL","color":"#FFFFFF"},{"id":3,"value":"   VOLANTE","color":"#FFFFFF"}]}]', true, true),
(010602, 01, 'UN SEGUNDO CAMBIA LA VIDA', NULL, 'UN SEGUNDO CAMBIA LA VIDA', '[{"zone":1,"graphics":[]},{"zone":3,"graphics":[]},{"zone":2,"align":"center","texts":[{"id":1,"value":"UN  SEGUNDO","color":"#FFFFFF"},{"id":2,"value":"   CAMBIA","color":"#FFFFFF"},{"id":3,"value":"  LA  VIDA","color":"#FFFFFF"}]}]', true, true),

--01 CAMPAÑA SEGURIDAD VIAL - CSV FEB
(010701, 01, 'NO USES EL MOVIL', NULL, 'NO USES EL MOVIL', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":"NO  USES  EL","color":"#FFFFFF"},{"id":2,"value":" MOVIL  AL  ","color":"#FFFFFF"},{"id":3,"value":"   VOLANTE","color":"#FFFFFF"}]}]', true, true),
(010702, 01, 'USAR EL MOVIL SUPONE', NULL, 'USAR EL MOVIL SUPONE', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":"  USAR EL","color":"#FFFFFF"},{"id":2,"value":"MOVIL SUPONE","color":"#FFFFFF"},{"id":3,"value":"  4 PUNTOS","color":"#FFFFFF"}]}]', true, true),

--01 CAMPAÑA SEGURIDAD VIAL - CSV MAR
(010801, 01, 'NEUMÁTICOS PERFECTOS', NULL, 'NEUMÁTICOS PERFECTOS', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":" NEUMATICOS","color":"#FFFFFF"},{"id":2,"value":"PERFECTOS TU","color":"#FFFFFF"},{"id":3,"value":"MEJOR SEGURO","color":"#FFFFFF"}]}]', true, true),
(010802, 01, 'REVISA TUS NEUMÁTICOS', NULL, 'REVISA TUS NEUMÁTICOS', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":"REVISA TUS","color":"#FFFFFF"},{"id":2,"value":"NEUMATICOS","color":"#FFFFFF"},{"id":3,"value":"CADA 15 DIAS","color":"#FFFFFF"}]}]', true, true),

--01 CAMPAÑA SEGURIDAD VIAL - CSV ABR
(010901, 01, 'MANTEN LA DISTANCIA', NULL, 'MANTEN LA DISTANCIA', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":" MANTEN LA","color":"#FFFFFF"},{"id":2,"value":" DISTANCIA","color":"#FFFFFF"},{"id":3,"value":"DE SEGURIDAD","color":"#FFFFFF"}]}]', true, true),
(010902, 01, 'SEGURIDAD', NULL, 'SEGURIDAD', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":" SEGURIDAD","color":"#FFFFFF"},{"id":2,"value":" ES MANTENER","color":"#FFFFFF"},{"id":3,"value":"LA DISTANCIA","color":"#FFFFFF"}]}]', true, true),

--01 CAMPAÑA SEGURIDAD VIAL - CSV MAY
(011001, 01, 'ANTES DEL VIAJE', NULL, 'ANTES DEL VIAJE', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":" ANTES DEL","color":"#FFFFFF"},{"id":2,"value":"VIAJE REVISA","color":"#FFFFFF"},{"id":3,"value":"TU VEHICULO","color":"#FFFFFF"}]}]', true, true),
(011002, 01, 'EVITA RIESGOS', NULL, 'EVITA RIESGOS', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":"  EVITA","color":"#FFFFFF"},{"id":2,"value":"RIESGOS HAZ","color":"#FFFFFF"},{"id":3,"value":"LA REVISION","color":"#FFFFFF"}]}]', true, true),

--01 CAMPAÑA SEGURIDAD VIAL - CSV JUN
(011101, 01, 'CERO ALCOHOL', NULL, 'CERO ALCOHOL', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":"CERO ALCOHOL","color":"#FFFFFF"},{"id":2,"value":" AL VOLANTE","color":"#FFFFFF"},{"id":3,"value":"","color":"#FFFFFF"}]}]', true, true),
(011102, 01, 'SI BEBES', NULL, 'SI BEBES', '[{"zone":1,"graphics":[{"id":1,"value":"3000"}]},{"zone":3,"graphics":[{"id":1,"value":"3000"}]},{"zone":2,"align":"center","texts":[{"id":1,"value":"  SI  BEBES","color":"#FFFFFF"},{"id":2,"value":"    NO","color":"#FFFFFF"},{"id":3,"value":" CONDUZCAS","color":"#FFFFFF"}]}]', true, true);

INSERT INTO ui.vms_library_hierarchies(vms_library_id, node_parent_id, node_child_id, enabled, visible) VALUES
(01, 01, 0101, true, true),
	(01, 0101, 010101, true, true),
	(01, 0101, 010102, true, true),
	(01, 0101, 010103, true, true),
	(01, 0101, 010104, true, true),
	(01, 0101, 010105, true, true),
	(01, 0101, 010106, true, true),
	(01, 0101, 010107, true, true),
	(01, 0101, 010108, true, true),
	(01, 0101, 010109, true, true),
	(01, 0101, 010110, true, true),
	(01, 0101, 010111, true, true),
	(01, 0101, 010112, true, true),
	(01, 0101, 010113, true, true),
	(01, 0101, 010114, true, true),
	(01, 0101, 010115, true, true),
	(01, 0101, 010116, true, true),
	(01, 0101, 010117, true, true),
	(01, 0101, 010118, true, true),
	
(01, 01, 0102, true, true),
	(01, 0102, 010201, true, true),
	(01, 0102, 010202, true, true),
	(01, 0102, 010203, true, true),
	(01, 0102, 010204, true, true),
	(01, 0102, 010205, true, true),
	(01, 0102, 010206, true, true),
	(01, 0102, 010207, true, true),
	(01, 0102, 010208, true, true),
	(01, 0102, 010209, true, true),
	(01, 0102, 010210, true, true),
	(01, 0102, 010211, true, true),
	(01, 0102, 010212, true, true),
	(01, 0102, 010213, true, true),
	(01, 0102, 010214, true, true),
	(01, 0102, 010215, true, true),
	(01, 0102, 010216, true, true),
	(01, 0102, 010217, true, true),
	(01, 0102, 010218, true, true),
	(01, 0102, 010219, true, true),
	(01, 0102, 010220, true, true),
	(01, 0102, 010221, true, true),
	(01, 0102, 010222, true, true),
	(01, 0102, 010223, true, true),
	(01, 0102, 010224, true, true),
	(01, 0102, 010225, true, true),
	(01, 0102, 010226, true, true),
	(01, 0102, 010227, true, true),
	(01, 0102, 010228, true, true),
	(01, 0102, 010229, true, true),
	(01, 0102, 010230, true, true),
	(01, 0102, 010231, true, true),
	(01, 0102, 010232, true, true),
	(01, 0102, 010233, true, true),
	(01, 0102, 010234, true, true),
	(01, 0102, 010235, true, true),
	(01, 0102, 010236, true, true),
	(01, 0102, 010237, true, true),
	(01, 0102, 010238, true, true),
	(01, 0102, 010239, true, true),
	(01, 0102, 010240, true, true),
	(01, 0102, 010241, true, true),
	(01, 0102, 010242, true, true),
	(01, 0102, 010243, true, true),
	(01, 0102, 010244, true, true),
	(01, 0102, 010245, true, true),
	(01, 0102, 010246, true, true),
	(01, 0102, 010247, true, true),
	(01, 0102, 010248, true, true),
	(01, 0102, 010249, true, true),
	(01, 0102, 010250, true, true),
	(01, 0102, 010251, true, true),
	(01, 0102, 010252, true, true),
	(01, 0102, 010253, true, true),
	(01, 0102, 010254, true, true),
	
(01, 0101, 0103, true, true),
	(01, 0103, 010301, true, true),
	(01, 0103, 010302, true, true),
	(01, 0103, 010303, true, true),
	(01, 0103, 010304, true, true),
	(01, 0103, 010305, true, true),
	(01, 0103, 010306, true, true),
	(01, 0103, 010307, true, true),
	(01, 0103, 010308, true, true),
	(01, 0103, 010309, true, true),
	(01, 0103, 010310, true, true),
	
(01, 0101, 0104, true, true),
	(01, 0104, 010401, true, true),
	
(01, 01, 0105, true, true),
	(01, 0105, 0106, true, true),	
		(01, 0106, 010601, true, true),	
		(01, 0106, 010602, true, true),	
	(01, 0105, 0107, true, true),	
		(01, 0107, 010701, true, true),	
		(01, 0107, 010702, true, true),	
	(01, 0105, 0108, true, true),	
		(01, 0108, 010801, true, true),	
		(01, 0108, 010802, true, true),	
	(01, 0105, 0109, true, true),	
		(01, 0109, 010901, true, true),	
		(01, 0109, 010902, true, true),	
	(01, 0105, 0110, true, true),	
		(01, 0110, 011001, true, true),	
		(01, 0110, 011002, true, true),	
	(01, 0105, 0111, true, true),	
		(01, 0111, 011101, true, true),	
		(01, 0111, 011102, true, true);



INSERT INTO ui.vms_library_element_subtypes(element_subtype_id, vms_library_id, enabled, visible) VALUES
('ElementSubtype:22:71', 01, true, true);*/
