INSERT INTO conf.element_hierarchies
(parent_element_type_id, parent_element_id, child_element_type_id, child_element_id, enabled, visible, created_at, updated_at) VALUES 
--SENTIDO NORTE-SUR
(6, 1, 4, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 4, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 4, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 2, 4, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 2, 4, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 2, 4, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 2, 4, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 3, 4, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 3, 4, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 3, 4, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 3, 4, 14, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 3, 4, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 3, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 3, 4, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 4, 4, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 14, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 4, 4, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 5, 4, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(6, 5, 4, 12, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 14, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 5, 4, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 6, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 6, 4, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 6, 4, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 6, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 7, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 7, 4, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(6, 7, 4, 12, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 7, 4, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 7, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 8, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 8, 4, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 8, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 9, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 9, 4, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(6, 9, 4, 12, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 9, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--SENTIDO SUR-NORTE
(6, 10, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 10, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 10, 4, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 11, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 11, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 11, 4, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 11, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 12, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 12, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 12, 4, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 12, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 12, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 13, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 13, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 13, 4, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 13, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 13, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 13, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 13, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 14, 4, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 14, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 15, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 15, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 15, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 16, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 16, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 16, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 16, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 17, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 17, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 17, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 17, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 17, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 17, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 18, 4, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 18, 4, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 18, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 18, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 18, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 18, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 18, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 18, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 19, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 19, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 19, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 19, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 20, 4, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 20, 4, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 20, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 20, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 20, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 20, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 21, 4, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 21, 4, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 21, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 21, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 22, 4, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 22, 4, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 22, 4, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 23, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 23, 4, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 23, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 24, 4, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 24, 4, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 24, 4, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 25, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 25, 4, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 25, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 26, 4, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 26, 4, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 26, 4, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 27, 4, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 27, 4, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 27, 4, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 28, 4, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 28, 4, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 28, 4, 21, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
