DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'incidents') THEN
		
		INSERT INTO incidents.municipalities (alias) VALUES('Abáigar');
		INSERT INTO incidents.municipalities (alias) VALUES('Abárzuza / Abartzuza');
		INSERT INTO incidents.municipalities (alias) VALUES('Abaurregaina / Abaurrea Alta');
		INSERT INTO incidents.municipalities (alias) VALUES('Abaurrepea / Abaurrea Baja');
		INSERT INTO incidents.municipalities (alias) VALUES('Aberin');
		INSERT INTO incidents.municipalities (alias) VALUES('Ablitas');
		INSERT INTO incidents.municipalities (alias) VALUES('Adiós');
		INSERT INTO incidents.municipalities (alias) VALUES('Aguilar de Codés');
		INSERT INTO incidents.municipalities (alias) VALUES('Aibar / Oibar');
		INSERT INTO incidents.municipalities (alias) VALUES('Altsasu / Alsasua');
		INSERT INTO incidents.municipalities (alias) VALUES('Allín / Allin');
		INSERT INTO incidents.municipalities (alias) VALUES('Allo');
		INSERT INTO incidents.municipalities (alias) VALUES('Améscoa Baja');
		INSERT INTO incidents.municipalities (alias) VALUES('Ancín / Antzin');
		INSERT INTO incidents.municipalities (alias) VALUES('Andosilla');
		INSERT INTO incidents.municipalities (alias) VALUES('Ansoáin / Antsoain');
		INSERT INTO incidents.municipalities (alias) VALUES('Anue');
		INSERT INTO incidents.municipalities (alias) VALUES('Añorbe');
		INSERT INTO incidents.municipalities (alias) VALUES('Aoiz / Agoitz');
		INSERT INTO incidents.municipalities (alias) VALUES('Araitz');
		INSERT INTO incidents.municipalities (alias) VALUES('Aranarache / Aranaratxe');
		INSERT INTO incidents.municipalities (alias) VALUES('Arantza');
		INSERT INTO incidents.municipalities (alias) VALUES('Aranguren');
		INSERT INTO incidents.municipalities (alias) VALUES('Arano');
		INSERT INTO incidents.municipalities (alias) VALUES('Arakil');
		INSERT INTO incidents.municipalities (alias) VALUES('Aras');
		INSERT INTO incidents.municipalities (alias) VALUES('Arbizu');
		INSERT INTO incidents.municipalities (alias) VALUES('Arce / Artzi');
		INSERT INTO incidents.municipalities (alias) VALUES('Los Arcos');
		INSERT INTO incidents.municipalities (alias) VALUES('Arellano');
		INSERT INTO incidents.municipalities (alias) VALUES('Areso');
		INSERT INTO incidents.municipalities (alias) VALUES('Arguedas');
		INSERT INTO incidents.municipalities (alias) VALUES('Aria');
		INSERT INTO incidents.municipalities (alias) VALUES('Aribe');
		INSERT INTO incidents.municipalities (alias) VALUES('Armañanzas');
		INSERT INTO incidents.municipalities (alias) VALUES('Arróniz');
		INSERT INTO incidents.municipalities (alias) VALUES('Arruazu');
		INSERT INTO incidents.municipalities (alias) VALUES('Artajona');
		INSERT INTO incidents.municipalities (alias) VALUES('Artazu');
		INSERT INTO incidents.municipalities (alias) VALUES('Atetz');
		INSERT INTO incidents.municipalities (alias) VALUES('Ayegui / Aiegi');
		INSERT INTO incidents.municipalities (alias) VALUES('Azagra');
		INSERT INTO incidents.municipalities (alias) VALUES('Azuelo');
		INSERT INTO incidents.municipalities (alias) VALUES('Bakaiku');
		INSERT INTO incidents.municipalities (alias) VALUES('Barásoain');
		INSERT INTO incidents.municipalities (alias) VALUES('Barbarin');
		INSERT INTO incidents.municipalities (alias) VALUES('Bargota');
		INSERT INTO incidents.municipalities (alias) VALUES('Barillas');
		INSERT INTO incidents.municipalities (alias) VALUES('Basaburua');
		INSERT INTO incidents.municipalities (alias) VALUES('Baztan');
		INSERT INTO incidents.municipalities (alias) VALUES('Beire');
		INSERT INTO incidents.municipalities (alias) VALUES('Belascoáin');
		INSERT INTO incidents.municipalities (alias) VALUES('Berbinzana');
		INSERT INTO incidents.municipalities (alias) VALUES('Bertizarana');
		INSERT INTO incidents.municipalities (alias) VALUES('Betelu');
		INSERT INTO incidents.municipalities (alias) VALUES('Biurrun-Olcoz');
		INSERT INTO incidents.municipalities (alias) VALUES('Buñuel');
		INSERT INTO incidents.municipalities (alias) VALUES('Auritz / Burguete');
		INSERT INTO incidents.municipalities (alias) VALUES('Burgui / Burgi');
		INSERT INTO incidents.municipalities (alias) VALUES('Burlada / Burlata');
		INSERT INTO incidents.municipalities (alias) VALUES('El Busto');
		INSERT INTO incidents.municipalities (alias) VALUES('Cabanillas');
		INSERT INTO incidents.municipalities (alias) VALUES('Cabredo');
		INSERT INTO incidents.municipalities (alias) VALUES('Cadreita');
		INSERT INTO incidents.municipalities (alias) VALUES('Caparroso');
		INSERT INTO incidents.municipalities (alias) VALUES('Cárcar');
		INSERT INTO incidents.municipalities (alias) VALUES('Carcastillo');
		INSERT INTO incidents.municipalities (alias) VALUES('Cascante');
		INSERT INTO incidents.municipalities (alias) VALUES('Cáseda');
		INSERT INTO incidents.municipalities (alias) VALUES('Castejón');
		INSERT INTO incidents.municipalities (alias) VALUES('Castillonuevo / Gazteluberri');
		INSERT INTO incidents.municipalities (alias) VALUES('Cintruénigo');
		INSERT INTO incidents.municipalities (alias) VALUES('Ziordia');
		INSERT INTO incidents.municipalities (alias) VALUES('Cirauqui / Zirauki');
		INSERT INTO incidents.municipalities (alias) VALUES('Ciriza / Ziritza');
		INSERT INTO incidents.municipalities (alias) VALUES('Cizur');
		INSERT INTO incidents.municipalities (alias) VALUES('Corella');
		INSERT INTO incidents.municipalities (alias) VALUES('Cortes');
		INSERT INTO incidents.municipalities (alias) VALUES('Desojo');
		INSERT INTO incidents.municipalities (alias) VALUES('Dicastillo');
		INSERT INTO incidents.municipalities (alias) VALUES('Donamaria');
		INSERT INTO incidents.municipalities (alias) VALUES('Etxalar');
		INSERT INTO incidents.municipalities (alias) VALUES('Echarri / Etxarri');
		INSERT INTO incidents.municipalities (alias) VALUES('Etxarri Aranatz');
		INSERT INTO incidents.municipalities (alias) VALUES('Etxauri');
		INSERT INTO incidents.municipalities (alias) VALUES('Valle de Egüés / Eguesibar');
		INSERT INTO incidents.municipalities (alias) VALUES('Elgorriaga');
		INSERT INTO incidents.municipalities (alias) VALUES('Valle de Elorz / Elortzibar');
		INSERT INTO incidents.municipalities (alias) VALUES('Enériz / Eneritz');
		INSERT INTO incidents.municipalities (alias) VALUES('Eratsun');
		INSERT INTO incidents.municipalities (alias) VALUES('Ergoiena');
		INSERT INTO incidents.municipalities (alias) VALUES('Erro');
		INSERT INTO incidents.municipalities (alias) VALUES('Ezcároz / Ezkaroze');
		INSERT INTO incidents.municipalities (alias) VALUES('Eslava');
		INSERT INTO incidents.municipalities (alias) VALUES('Esparza de Salazar / Espartza Zaraitzu');
		INSERT INTO incidents.municipalities (alias) VALUES('Espronceda');
		INSERT INTO incidents.municipalities (alias) VALUES('Estella-Lizarra');
		INSERT INTO incidents.municipalities (alias) VALUES('Esteribar');
		INSERT INTO incidents.municipalities (alias) VALUES('Etayo');
		INSERT INTO incidents.municipalities (alias) VALUES('Eulate');
		INSERT INTO incidents.municipalities (alias) VALUES('Ezcabarte');
		INSERT INTO incidents.municipalities (alias) VALUES('Ezkurra');
		INSERT INTO incidents.municipalities (alias) VALUES('Ezprogui');
		INSERT INTO incidents.municipalities (alias) VALUES('Falces');
		INSERT INTO incidents.municipalities (alias) VALUES('Fitero');
		INSERT INTO incidents.municipalities (alias) VALUES('Fontellas');
		INSERT INTO incidents.municipalities (alias) VALUES('Funes');
		INSERT INTO incidents.municipalities (alias) VALUES('Fustiñana');
		INSERT INTO incidents.municipalities (alias) VALUES('Galar');
		INSERT INTO incidents.municipalities (alias) VALUES('Gallipienzo / Galipentzu');
		INSERT INTO incidents.municipalities (alias) VALUES('Gallués / Galoze');
		INSERT INTO incidents.municipalities (alias) VALUES('Garaioa');
		INSERT INTO incidents.municipalities (alias) VALUES('Garde');
		INSERT INTO incidents.municipalities (alias) VALUES('Garínoain');
		INSERT INTO incidents.municipalities (alias) VALUES('Garralda');
		INSERT INTO incidents.municipalities (alias) VALUES('Genevilla');
		INSERT INTO incidents.municipalities (alias) VALUES('Goizueta');
		INSERT INTO incidents.municipalities (alias) VALUES('Goñi');
		INSERT INTO incidents.municipalities (alias) VALUES('Güesa / Gorza');
		INSERT INTO incidents.municipalities (alias) VALUES('Guesálaz / Gesalatz');
		INSERT INTO incidents.municipalities (alias) VALUES('Guirguillano');
		INSERT INTO incidents.municipalities (alias) VALUES('Huarte / Uharte');
		INSERT INTO incidents.municipalities (alias) VALUES('Uharte Arakil');
		INSERT INTO incidents.municipalities (alias) VALUES('Ibargoiti');
		INSERT INTO incidents.municipalities (alias) VALUES('Igúzquiza');
		INSERT INTO incidents.municipalities (alias) VALUES('Imotz');
		INSERT INTO incidents.municipalities (alias) VALUES('Irañeta');
		INSERT INTO incidents.municipalities (alias) VALUES('Isaba / Izaba');
		INSERT INTO incidents.municipalities (alias) VALUES('Ituren');
		INSERT INTO incidents.municipalities (alias) VALUES('Iturmendi');
		INSERT INTO incidents.municipalities (alias) VALUES('Iza / Itza');
		INSERT INTO incidents.municipalities (alias) VALUES('Izagaondoa');
		INSERT INTO incidents.municipalities (alias) VALUES('Izalzu / Itzaltzu');
		INSERT INTO incidents.municipalities (alias) VALUES('Jaurrieta');
		INSERT INTO incidents.municipalities (alias) VALUES('Javier');
		INSERT INTO incidents.municipalities (alias) VALUES('Juslapeña / Txulapain');
		INSERT INTO incidents.municipalities (alias) VALUES('Beintza-Labaien');
		INSERT INTO incidents.municipalities (alias) VALUES('Lakuntza');
		INSERT INTO incidents.municipalities (alias) VALUES('Lana');
		INSERT INTO incidents.municipalities (alias) VALUES('Lantz');
		INSERT INTO incidents.municipalities (alias) VALUES('Lapoblación');
		INSERT INTO incidents.municipalities (alias) VALUES('Larraga');
		INSERT INTO incidents.municipalities (alias) VALUES('Larraona');
		INSERT INTO incidents.municipalities (alias) VALUES('Larraun');
		INSERT INTO incidents.municipalities (alias) VALUES('Lazagurría');
		INSERT INTO incidents.municipalities (alias) VALUES('Leache / Leatxe');
		INSERT INTO incidents.municipalities (alias) VALUES('Legarda');
		INSERT INTO incidents.municipalities (alias) VALUES('Legaria');
		INSERT INTO incidents.municipalities (alias) VALUES('Leitza');
		INSERT INTO incidents.municipalities (alias) VALUES('Leoz / Leotz');
		INSERT INTO incidents.municipalities (alias) VALUES('Lerga');
		INSERT INTO incidents.municipalities (alias) VALUES('Lerín');
		INSERT INTO incidents.municipalities (alias) VALUES('Lesaka');
		INSERT INTO incidents.municipalities (alias) VALUES('Lezaun');
		INSERT INTO incidents.municipalities (alias) VALUES('Liédena');
		INSERT INTO incidents.municipalities (alias) VALUES('Lizoain-Arriasgoiti / Lizoainibar-Arriasgoiti');
		INSERT INTO incidents.municipalities (alias) VALUES('Lodosa');
		INSERT INTO incidents.municipalities (alias) VALUES('Lónguida / Longida');
		INSERT INTO incidents.municipalities (alias) VALUES('Lumbier');
		INSERT INTO incidents.municipalities (alias) VALUES('Luquin');
		INSERT INTO incidents.municipalities (alias) VALUES('Mañeru');
		INSERT INTO incidents.municipalities (alias) VALUES('Marañón');
		INSERT INTO incidents.municipalities (alias) VALUES('Marcilla');
		INSERT INTO incidents.municipalities (alias) VALUES('Mélida');
		INSERT INTO incidents.municipalities (alias) VALUES('Mendavia');
		INSERT INTO incidents.municipalities (alias) VALUES('Mendaza');
		INSERT INTO incidents.municipalities (alias) VALUES('Mendigorria');
		INSERT INTO incidents.municipalities (alias) VALUES('Metauten');
		INSERT INTO incidents.municipalities (alias) VALUES('Milagro');
		INSERT INTO incidents.municipalities (alias) VALUES('Mirafuentes');
		INSERT INTO incidents.municipalities (alias) VALUES('Miranda de Arga');
		INSERT INTO incidents.municipalities (alias) VALUES('Monreal / Elo');
		INSERT INTO incidents.municipalities (alias) VALUES('Monteagudo');
		INSERT INTO incidents.municipalities (alias) VALUES('Morentin');
		INSERT INTO incidents.municipalities (alias) VALUES('Mues');
		INSERT INTO incidents.municipalities (alias) VALUES('Murchante');
		INSERT INTO incidents.municipalities (alias) VALUES('Murieta');
		INSERT INTO incidents.municipalities (alias) VALUES('Murillo el Cuende');
		INSERT INTO incidents.municipalities (alias) VALUES('Murillo el Fruto');
		INSERT INTO incidents.municipalities (alias) VALUES('Muruzábal');
		INSERT INTO incidents.municipalities (alias) VALUES('Navascués / Nabaskoze');
		INSERT INTO incidents.municipalities (alias) VALUES('Nazar');
		INSERT INTO incidents.municipalities (alias) VALUES('Obanos');
		INSERT INTO incidents.municipalities (alias) VALUES('Oco');
		INSERT INTO incidents.municipalities (alias) VALUES('Ochagavía / Otsagabia');
		INSERT INTO incidents.municipalities (alias) VALUES('Odieta');
		INSERT INTO incidents.municipalities (alias) VALUES('Oiz');
		INSERT INTO incidents.municipalities (alias) VALUES('Oláibar');
		INSERT INTO incidents.municipalities (alias) VALUES('Olazti / Olazagutía');
		INSERT INTO incidents.municipalities (alias) VALUES('Olejua');
		INSERT INTO incidents.municipalities (alias) VALUES('Olite / Erriberri');
		INSERT INTO incidents.municipalities (alias) VALUES('Olóriz / Oloritz');
		INSERT INTO incidents.municipalities (alias) VALUES('Cendea de Olza / Oltza Zendea');
		INSERT INTO incidents.municipalities (alias) VALUES('Valle de Ollo / Ollaran');
		INSERT INTO incidents.municipalities (alias) VALUES('Orbaizeta');
		INSERT INTO incidents.municipalities (alias) VALUES('Orbara');
		INSERT INTO incidents.municipalities (alias) VALUES('Orísoain');
		INSERT INTO incidents.municipalities (alias) VALUES('Oronz / Orontze');
		INSERT INTO incidents.municipalities (alias) VALUES('Oroz-Betelu / Orotz-Betelu');
		INSERT INTO incidents.municipalities (alias) VALUES('Oteiza');
		INSERT INTO incidents.municipalities (alias) VALUES('Pamplona / Iruña');
		INSERT INTO incidents.municipalities (alias) VALUES('Peralta / Azkoien');
		INSERT INTO incidents.municipalities (alias) VALUES('Petilla de Aragón');
		INSERT INTO incidents.municipalities (alias) VALUES('Piedramillera');
		INSERT INTO incidents.municipalities (alias) VALUES('Pitillas');
		INSERT INTO incidents.municipalities (alias) VALUES('Puente la Reina / Gares');
		INSERT INTO incidents.municipalities (alias) VALUES('Pueyo / Puiu');
		INSERT INTO incidents.municipalities (alias) VALUES('Ribaforada');
		INSERT INTO incidents.municipalities (alias) VALUES('Romanzado / Erromantzatua');
		INSERT INTO incidents.municipalities (alias) VALUES('Roncal / Erronkari');
		INSERT INTO incidents.municipalities (alias) VALUES('Orreaga / Roncesvalles');
		INSERT INTO incidents.municipalities (alias) VALUES('Sada');
		INSERT INTO incidents.municipalities (alias) VALUES('Saldias');
		INSERT INTO incidents.municipalities (alias) VALUES('Salinas de Oro / Jaitz');
		INSERT INTO incidents.municipalities (alias) VALUES('San Adrián');
		INSERT INTO incidents.municipalities (alias) VALUES('Sangüesa / Zangoza');
		INSERT INTO incidents.municipalities (alias) VALUES('San Martín de Unx');
		INSERT INTO incidents.municipalities (alias) VALUES('Sansol');
		INSERT INTO incidents.municipalities (alias) VALUES('Santacara');
		INSERT INTO incidents.municipalities (alias) VALUES('Doneztebe / Santesteban');
		INSERT INTO incidents.municipalities (alias) VALUES('Sarriés / Sartze');
		INSERT INTO incidents.municipalities (alias) VALUES('Sartaguda');
		INSERT INTO incidents.municipalities (alias) VALUES('Sesma');
		INSERT INTO incidents.municipalities (alias) VALUES('Sorlada');
		INSERT INTO incidents.municipalities (alias) VALUES('Sunbilla');
		INSERT INTO incidents.municipalities (alias) VALUES('Tafalla');
		INSERT INTO incidents.municipalities (alias) VALUES('Tiebas-Muruarte de Reta');
		INSERT INTO incidents.municipalities (alias) VALUES('Tirapu');
		INSERT INTO incidents.municipalities (alias) VALUES('Torralba del Río');
		INSERT INTO incidents.municipalities (alias) VALUES('Torres del Río');
		INSERT INTO incidents.municipalities (alias) VALUES('Tudela');
		INSERT INTO incidents.municipalities (alias) VALUES('Tulebras');
		INSERT INTO incidents.municipalities (alias) VALUES('Úcar');
		INSERT INTO incidents.municipalities (alias) VALUES('Ujué / Uxue');
		INSERT INTO incidents.municipalities (alias) VALUES('Ultzama');
		INSERT INTO incidents.municipalities (alias) VALUES('Unciti');
		INSERT INTO incidents.municipalities (alias) VALUES('Unzué / Untzue');
		INSERT INTO incidents.municipalities (alias) VALUES('Urdazubi / Urdax');
		INSERT INTO incidents.municipalities (alias) VALUES('Urdiain');
		INSERT INTO incidents.municipalities (alias) VALUES('Urraúl Alto');
		INSERT INTO incidents.municipalities (alias) VALUES('Urraúl Bajo');
		INSERT INTO incidents.municipalities (alias) VALUES('Urroz-Villa');
		INSERT INTO incidents.municipalities (alias) VALUES('Urroz');
		INSERT INTO incidents.municipalities (alias) VALUES('Urzainqui / Urzainki');
		INSERT INTO incidents.municipalities (alias) VALUES('Uterga');
		INSERT INTO incidents.municipalities (alias) VALUES('Uztárroz / Uztarroze');
		INSERT INTO incidents.municipalities (alias) VALUES('Luzaide / Valcarlos');
		INSERT INTO incidents.municipalities (alias) VALUES('Valtierra');
		INSERT INTO incidents.municipalities (alias) VALUES('Bera');
		INSERT INTO incidents.municipalities (alias) VALUES('Viana');
		INSERT INTO incidents.municipalities (alias) VALUES('Vidángoz / Bidankoze');
		INSERT INTO incidents.municipalities (alias) VALUES('Bidaurreta');
		INSERT INTO incidents.municipalities (alias) VALUES('Villafranca');
		INSERT INTO incidents.municipalities (alias) VALUES('Villamayor de Monjardín');
		INSERT INTO incidents.municipalities (alias) VALUES('Hiriberri / Villanueva de Aezkoa');
		INSERT INTO incidents.municipalities (alias) VALUES('Villatuerta');
		INSERT INTO incidents.municipalities (alias) VALUES('Villava / Atarrabia');
		INSERT INTO incidents.municipalities (alias) VALUES('Igantzi');
		INSERT INTO incidents.municipalities (alias) VALUES('Valle de Yerri / Deierri');
		INSERT INTO incidents.municipalities (alias) VALUES('Yesa');
		INSERT INTO incidents.municipalities (alias) VALUES('Zabalza / Zabaltza');
		INSERT INTO incidents.municipalities (alias) VALUES('Zubieta');
		INSERT INTO incidents.municipalities (alias) VALUES('Zugarramurdi');
		INSERT INTO incidents.municipalities (alias) VALUES('Zúñiga');
		INSERT INTO incidents.municipalities (alias) VALUES('Barañáin / Barañain');
		INSERT INTO incidents.municipalities (alias) VALUES('Berrioplano / Berriobeiti');
		INSERT INTO incidents.municipalities (alias) VALUES('Berriozar');
		INSERT INTO incidents.municipalities (alias) VALUES('Irurtzun');
		INSERT INTO incidents.municipalities (alias) VALUES('Beriáin');
		INSERT INTO incidents.municipalities (alias) VALUES('Orkoien');
		INSERT INTO incidents.municipalities (alias) VALUES('Zizur Mayor / Zizur Nagusia');
		INSERT INTO incidents.municipalities (alias) VALUES('Lekunberri');

  END IF;
END $$;