INSERT INTO ui.vo_entities(id, vo_entity_type_id, enabled, visible) VALUES
('ElementTypeParam:1:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:11', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:15', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:16', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:19', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:23', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:1:3', 'ElementTypeParamUI', true, true),

('ElementTypeParam:2:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:3:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:40', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:41', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:42', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:43', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:20', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:21', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:22', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:60', 'ElementTypeParamUI', true, true),

('ElementTypeParam:4:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:18', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:80', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:81', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:82', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:83', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:60', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:61', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:62', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:100', 'ElementTypeParamUI', true, true),

('ElementTypeParam:5:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:5:2:1001','ElementTypeParamUI', true, true),
('ElementTypeParam:5:2:1002', 'ElementTypeParamUI', true, true),

('ElementTypeParam:8:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:9:2:1', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:2', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:3', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:4', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:7', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:8', 'ElementTypeParamUI', true,  true),

('ElementTypeParam:11:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:12:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:12:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:13:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:14:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:14:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:14:2:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:15:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:15:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:15:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:15:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:15:1:6', 'ElementTypeParamUI', true, true),

('ElementTypeParam:16:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:16:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:16:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:16:2:1001', 'ElementTypeParamUI', true, true),
('ElementTypeParam:16:2:1002', 'ElementTypeParamUI', true, true),
('ElementTypeParam:16:2:1003', 'ElementTypeParamUI', true, true),
('ElementTypeParam:16:2:1004', 'ElementTypeParamUI', true, true),

('ElementTypeParam:18:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:18:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:19:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:19:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:20:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:20:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:21:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:21:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:22:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:22:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:30:1:3', 'ElementTypeParamUI', true, true),

('ElementTypeParam:31:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:31:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:32:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:32:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:32:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:32:2:3', 'ElementTypeParamUI', true, true),

('ElementTypeParam:33:1:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:51:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:51:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:51:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:51:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:51:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:51:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:53:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:55:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:57:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:58:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:59:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:60:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:65:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:65:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:65:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:65:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:65:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:65:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:65:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:65:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:66:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:66:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:66:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:66:2:4', 'ElementTypeParamUI', true, true),

('ElementTypeParam:70:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:11', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:12', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:14', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:15', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:16', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:17', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:18', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:19', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:20', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:21', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:22', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:23', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:24', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:25', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:26', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:27', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:28', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:29', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:30', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:31', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:32', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:33', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:34', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:35', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:36', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:37', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:38', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:39', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:40', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:41', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:42', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:43', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:44', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:45', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:46', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:2:47', 'ElementTypeParamUI', true, true),
('ElementTypeParam:70:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:71:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:1003', 'ElementTypeParamUI', true, true),

('ElementTypeParam:74:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:74:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:74:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:74:1:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:74:1:7', 'ElementTypeParamUI', true, true),

('ElementTypeParam:75:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:11', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:12', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:14', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:15', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:16', 'ElementTypeParamUI', true, true),
('ElementTypeParam:75:2:17', 'ElementTypeParamUI', true, true),

('ElementTypeParam:84:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:84:1:5', 'ElementTypeParamUI', true, true),

('ElementTypeParam:85:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:86:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:87:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:87:2:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:93:2:1', 'ElementTypeParamUI', true, true),

('Location:1', 'LocationUI', true, true),
('Location:2', 'LocationUI', true, true),
('Location:3', 'LocationUI', true, true),
('Location:4', 'LocationUI', true, true);