INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(1, 26, 43, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 44, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 45, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 46, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 47, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 48, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 49, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 50, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 51, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 98, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
