DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'historical_data') THEN
  
    INSERT INTO historical_data.sg_i18n_labels (locale_code, "label", "translation", created_at, updated_at) VALUES

	-- 
  	-- historical_data.sg_metadata_columns
  	--
    --es_ES
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ID', 'Id', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_DATE', 'Fecha', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_USER', 'Usuario', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_COMMAND', 'Comando', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT', 'Equipo', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_DATA', 'Datos', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_COMMENT', 'Origen', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_TEXT', 'Mensajes', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_ES','LBL_BACKOFFICE_SG_METADATA_COLUMNS_GRAPHIC', 'Gráficos', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

    --en_GB
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ID', 'Id', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_DATE', 'Date', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_USER', 'User', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_COMMAND', 'Command', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT', 'Element', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('en_GB','LBL_BACKOFFICE_SG_METADATA_COLUMNS_DATA', 'Data', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
         
    --es_CL
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ID', 'Id', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_DATE', 'Fecha', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_USER', 'Usuario', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_COMMAND', 'Comando', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_ELEMENT', 'Equipo', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
        ('es_CL','LBL_BACKOFFICE_SG_METADATA_COLUMNS_DATA', 'Datos', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
       
	END IF;
END $$;