INSERT INTO conf.command_elements (command_element_type_id, element_type_id, command_element_id, element_id, enabled, visible, created_at, updated_at) VALUES
(2, 71, 1, 3, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 2, 12, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 3, 13, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 4, 14, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 5, 4, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 6, 5, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 7, 6, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 8, 7, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 9, 8, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10, 9, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 11, 10, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 12, 11, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

