INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(1, 26, 1,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 2,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 3,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 4,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 5,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 6,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 7,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 8,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 9,  true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 11, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 12, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 26, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);