INSERT INTO conf.element_hierarchies
(parent_element_type_id, parent_element_id, child_element_type_id, child_element_id, enabled, visible, created_at, updated_at) VALUES 

(52, 1, 2, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 11, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 15, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 21, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 23, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 25, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 27, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 29, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 31, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 33, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 1, 2, 35, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


(52, 2, 2, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 12, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 14, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 16, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 22, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 24, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 26, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 28, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 30, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 32, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 2, 2, 34, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);





