[Modbus]
ip = 192.168.88.201
puerto = 5130

[AspaFlechas]
measuresOffset = 0
commandsOffset = 512
numEquipments = 3
numCommands = 2

[CLV]
measuresOffset = 6
commandsOffset = 518
numEquipments = 3
numCommands = 4