INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(1, 85, 21, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 22, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 23, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 24, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 25, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 26, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 27, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 28, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 29, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 30, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 31, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 85, 32, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
