TITLE ELECTRICAL_CABINET_NRS
@echo off
START /b /MIN unslave ELECTRICAL_CABINET_NRS/PLCRNRKD02L.json
START /b /MIN unslave ELECTRICAL_CABINET_NRS/PLCRNRKD04L.json
START /b /MIN unslave ELECTRICAL_CABINET_NRS/PLCRNRSPS405JSPP.json
START /b /MIN unslave ELECTRICAL_CABINET_NRS/PLCRNRJS20P.json
EXIT