INSERT INTO ui.modules(id, module_type_id, "name", description, default_view_type_id, default_system_permission_id, js_file, js_method_draw, js_method_callbacks, data_query, wss_topic, enabled, visible, autoload) VALUES
(200, 3, 'MAP', 'MAP', 1,null, 'modules/mapModule.js', 'getView', 'loadData', NULL, NULL, true, true, true),

(401, 5, 'ExternalMap', 'ExternalMap', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),
(402, 5, 'ExternalMap', 'ExternalMap', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),

(1920, 8, 'Selector Tree Module', 'Selector Tree Module', 1, null, 'modules/selectorModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6000, 9, 'INCIDENTS GIP - actions', 'Incidents GIP - actions', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6001, 9, 'INCIDENTS GIP - agents', 'Incidents GIP - agents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6002, 9, 'INCIDENTS GIP - assigned_pdas', 'Incidents GIP - assigned_pdas', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6003, 9, 'INCIDENTS GIP - assigned_resources', 'Incidents GIP - assigned_resources', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6004, 9, 'INCIDENTS GIP - assistance_types', 'Incidents GIP - assistance_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6005, 9, 'INCIDENTS GIP - atmospheric_states', 'Incidents GIP - atmospheric_states', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6006, 9, 'INCIDENTS GIP - attendeds', 'Incidents GIP - attendeds', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6007, 9, 'INCIDENTS GIP - causes', 'Incidents GIP - causes', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6008, 9, 'INCIDENTS GIP - conditions', 'Incidents GIP - conditions', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6009, 9, 'INCIDENTS GIP - elements', 'Incidents GIP - elements', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6010, 9, 'INCIDENTS GIP - genders', 'Incidents GIP - genders', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6011, 9, 'INCIDENTS GIP - incidents', 'Incidents GIP - incidents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6012, 9, 'INCIDENTS GIP - infrastructure_damages', 'Incidents GIP - infrastructure_damages', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6013, 9, 'INCIDENTS GIP - injury_levels', 'Incidents GIP - injury_levels', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6014, 9, 'INCIDENTS GIP - injury_types', 'Incidents GIP - injury_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6015, 9, 'INCIDENTS GIP - interrupt_agents', 'Incidents GIP - interrupt_agents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6016, 9, 'INCIDENTS GIP - lanes', 'Incidents GIP - lanes', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6017, 9, 'INCIDENTS GIP - lanes_actions', 'Incidents GIP - lanes_actions', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6018, 9, 'INCIDENTS GIP - lanes_states', 'Incidents GIP - lanes_states', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6019, 9, 'INCIDENTS GIP - luminosities', 'Incidents GIP - luminosities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6020, 9, 'INCIDENTS GIP - maneuvers', 'Incidents GIP - maneuvers', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6021, 9, 'INCIDENTS GIP - participant_assistance_types', 'Incidents GIP - participant_assistance_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6022, 9, 'INCIDENTS GIP - participant_transfer_places', 'Incidents GIP - participant_transfer_places', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6023, 9, 'INCIDENTS GIP - participant_types', 'Incidents GIP - participant_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6024, 9, 'INCIDENTS GIP - participants', 'Incidents GIP - participants', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6025, 9, 'INCIDENTS GIP - pdas', 'Incidents GIP - pdas', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6026, 9, 'INCIDENTS GIP - resources', 'Incidents GIP - resources', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6027, 9, 'INCIDENTS GIP - road_impacts', 'Incidents GIP - road_impacts', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6028, 9, 'INCIDENTS GIP - sources', 'Incidents GIP - sources', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6029, 9, 'INCIDENTS GIP - stages', 'Incidents GIP - stages', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6030, 9, 'INCIDENTS GIP - transfer_places', 'Incidents GIP - transfer_places', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6031, 9, 'INCIDENTS GIP - typologies', 'Incidents GIP - typologies', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6032, 9, 'INCIDENTS GIP - unavailable_lanes', 'Incidents GIP - unavailable_lanes', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6033, 9, 'INCIDENTS GIP - user_types', 'Incidents GIP - user_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6034, 9, 'INCIDENTS GIP - vehicle_brands', 'Incidents GIP - vehicle_brands', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6035, 9, 'INCIDENTS GIP - vehicle_damages', 'Incidents GIP - vehicle_damages', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6036, 9, 'INCIDENTS GIP - vehicle_models', 'Incidents GIP - vehicle_models', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6037, 9, 'INCIDENTS GIP - vehicle_types', 'Incidents GIP - vehicle_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6038, 9, 'INCIDENTS GIP - vehicles', 'Incidents GIP - vehicles', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

(1950, 9, 'c4_ext_entities_with_values', 'c4_ext_entities_with_values', 1, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(1951, 9, 'e112_ext_entities_with_values', 'e112_ext_entities_with_values', 1, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(7001, 9, '112 - Resources', '112 - Resources', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(7002, 9, '112 - Vehicles', '112 - Vehicles', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

(8000, 9, 'waze_traffic_alert_ext_entities_with_values', 'waze_traffic_alert_ext_entities_with_values', 1, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(8001, 9, 'waze_traffic_jam_ext_entities_with_values', 'waze_traffic_jam_ext_entities_with_values', 1, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

(2020, 8, 'Selector Tree Module', 'Selector Tree Module', 1, null, 'modules/selectorModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL);


