pipeline {
    agent any
    
    environment {
        RUTA_BASE_BACK = 'rits/ritsback/resources/db'
        RUTA_BASE_FRONT = 'rits/ritsfront/resources/db'
    }

    stages {
        stage('Verificar repositorios') {
            steps {
                script {
                    def repos = ['rits', 'ritsback', 'ritsfront']
        
                    for (repo in repos) {
                        dir(repo) {
                            git(
                                url: "ssh://git@192.168.88.194:3004/~/${repo}.git",
                                branch: 'master',
                                changelog: true,
                                poll: true
                            )
                        }
                    }
                }
            }
        }
        stage('Ejecutar scripts back') {
            steps {
                script {
                    def carpetas = ['maqueta_fullequip', 'maqueta_ruta_mina', 'maqueta_ruta_mina', 'maqueta_dev', 'maqueta_dgt_jaen', 'maqueta_nogales']

                    parallel carpetas.collectEntries { carpeta ->
                        ["Ejecutando en $carpeta": {
                            echo "Ejecutando script en la carpeta: $carpeta"

                            // Cambia el directorio de trabajo a la carpeta actual
                            dir("${RUTA_BASE_BACK}") {
                                sh "./make_param_jenkins.sh $carpeta localhost 5430"
                            }
                        }]
                    }
                }
            }
        }
        stage('Ejecutar scripts front') {
            steps {
                script {
                    def carpetas = ['maqueta_fullequip', 'maqueta_ruta_mina', 'maqueta_ruta_mina', 'maqueta_dev', 'maqueta_dgt_jaen', 'maqueta_nogales']

                    parallel carpetas.collectEntries { carpeta ->
                        ["Ejecutando en $carpeta": {
                            echo "Ejecutando script en la carpeta: $carpeta"

                            // Cambia el directorio de trabajo a la carpeta actual
                            dir("${RUTA_BASE_FRONT}") {
                                sh "./make_param_jenkins.sh $carpeta localhost 5430"
                            }
                        }]
                    }
                }
            }
        }
    }
    
    post {
        success {
            emailext (
                body: """$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
    
                Revisar la salida de la consola en: $BUILD_URL para más detalles.""",
                subject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!",
                to: "jenkins.openits@gmail.com"
            )
        }
        failure {
            emailext (
                body: """$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:
    
                Error en scripts para el commit $GIT_COMMIT --> Autor = $GIT_AUTHOR_NAME
    
                Revisar la salida de la consola en: $BUILD_URL para más detalles.""",
                subject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!",
                to: "jenkins.openits@gmail.com"
            )
        }
    }
}