-- 
-- Table: master.element_types
--
INSERT INTO master.element_types(element_type_id, element_group_id, alias, description,label_alias, label_description, initial_element_type_state_id, connected_element_type_state_id, disconnected_element_type_state_id, enabled, visible, created_at, updated_at) VALUES
(29, 2, 'FIBROLASER_CT', 'FIBROLASER_CT', 'LBL_ELEMENT_TYPE_FIBROLASER_CT', 'LBL_ELEMENT_TYPE_FIBROLASER_CT_DESC', 0, 1, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--
-- Table: master.element_type_params
--
INSERT INTO master.element_type_params (element_type_id, param_type_id, element_type_param_id, element_type_param_unit_id, data_type_id, default_value, alias, description, label_alias, label_description, enabled, visible, editable, created_at, updated_at) VALUES
--CONFIG
(29,1,1, NULL,2, ' ', 'brand', 'brand', 'LBL_ELEMENT_TYPE_PARAM_BRAND' , 'LBL_ELEMENT_TYPE_PARAM_BRAND_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29,1,2, NULL,2, ' ', 'model', 'model', 'LBL_ELEMENT_TYPE_PARAM_MODEL' , 'LBL_ELEMENT_TYPE_PARAM_MODEL_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29,1,1003, NULL,2, ' ', 'MANGO SESSION_UID', 'MANGO SESSION_UID', 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID' , 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--MEASURE
(29,2,1, NULL,5, NULL, 'ack_state', 'ack_state', 'LBL_ELEMENT_TYPE_PARAM_ACK_STATE' , 'LBL_ELEMENT_TYPE_PARAM_ACK_STATE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29,2,2, NULL,5, NULL, 'reset_state', 'reset_state', 'LBL_ELEMENT_TYPE_PARAM_RESET_STATE' , 'LBL_ELEMENT_TYPE_PARAM_RESET_STATE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29,2,3, NULL,5, NULL, 'test_mode_activated', 'test_mode_activated', 'LBL_ELEMENT_TYPE_PARAM_TEST_MODE_ACTIVATED' , 'LBL_ELEMENT_TYPE_PARAM_TEST_MODE_ACTIVATED_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_type_states
--
INSERT INTO master.element_type_states(element_type_id, element_type_state_id, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(29, 0, 'UNKNOWN', 'Unknown state', 'LBL_ELEMENT_TYPE_STATE_UNKNOWN', 'LBL_ELEMENT_TYPE_STATE_UNKNOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 1, 'UP', 'The state of the equipment is: comunicates', 'LBL_ELEMENT_TYPE_STATE_UP', 'LBL_ELEMENT_TYPE_STATE_UP_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 2, 'DOWN', 'The state of the equipment is: out of communication', 'LBL_ELEMENT_TYPE_STATE_DOWN', 'LBL_ELEMENT_TYPE_STATE_DOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 3, 'ALARMS', 'The state of the equipment is: with alarms', 'LBL_ELEMENT_TYPE_STATE_ALARMS', 'LBL_ELEMENT_TYPE_STATE_ALARMS_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 4, 'MAINTENANCE', 'The state of the equipment is: on Maintenance', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 
-- Table: master.element_type_state_transitions
--
INSERT INTO master.element_type_state_transitions 
(element_type_id, current_element_type_state_id, next_element_type_state_id, enabled, visible, editable, created_at, updated_at) VALUES
(29, 0, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 0, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 1, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 1, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 2, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 2, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 3, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 3, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.command_element_types
--
INSERT INTO master.command_element_types
(command_element_type_id, element_type_id, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(1, 29, 'FIBROLASER CT RESET ALARMS', 'FIBROLASER CT RESET ALARMS', 'LBL_COMMAND_ELEMENT_TYPE_FIBROLASER_CT_RESET_ALARMS', null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 29, 'FIBROLASER CT ACKNOWLEDGE', 'FIBROLASER CT ACKNOWLEDGE', 'LBL_COMMAND_ELEMENT_TYPE_FIBROLASER_CT_ACKNOWLEDGE', null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 
-- Table: master.io_controller_module_type_element_types
--
INSERT INTO master.io_controller_module_type_element_types
(module_type_id, element_type_id, enabled, visible, created_at, updated_at) VALUES
(1, 29, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: conf.alarm_configs
--
INSERT INTO conf.alarm_configs
(alarm_config_id, alarm_type_id, alarm_level_id, element_type_id, element_id, element_type_state_id, mine, treatment, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(010029, 2, 3, 29, NULL, NULL, true, true, 'ALARM FIBROLASER CT NO CONNECTION', 'ALARM FIBROLASER CT NO CONNECTION', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_NO_CONNECTION', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_NO_CONNECTION_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(020029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER FAIL COMMS', 'ALARM FIBROLASER FAIL COMMS', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_FAILS_COMMS', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_FAILS_COMMS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(030029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER SYSTEM FAULT', 'ALARM FIBROLASER SYSTEM FAULT', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_SYSTEM_FAULT', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_SYSTEM_FAULT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(040029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER FIBRE BREAK', 'ALARM FIBROLASER FIBRE BREAK', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_FIBRE_BREAK', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_FIBRE_BREAK', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(050029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER DEVICE ERROR', 'ALARM FIBROLASER DEVICE ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_DEVICE_ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_DEVICE_ERROR', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(060029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER MEASUREMENT STOPPED', 'ALARM FIBROLASER MEASUREMENT STOPPED', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_MEASUREMENT_STOPPED', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_MEASUREMENT_STOPPED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(070029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER MEASUREMENT INACTIVE', 'ALARM FIBROLASER MEASUREMENT INACTIVE', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_MEASUREMENT_INACTIVE', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_MEASUREMENT_INACTIVE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(080029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER CT CONFIGURATION ERROR', 'ALARM FIBROLASER CT CONFIGURATION ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_CONFIGURATION_ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_CONFIGURATION_ERROR_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER CT MEASUREMENT ERROR', 'ALARM FIBROLASER CT MEASUREMENT ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_MEASUREMENT_ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_MEASUREMENT_ERROR_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER CT DEVICE ERROR SUPPORT', 'ALARM FIBROLASER CT DEVICE ERROR SUPPORT', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_DEVICE_ERROR_SUPPORT', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_DEVICE_ERROR_SUPPORT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER CT ENVIRONMENT CONDITIONS ERROR', 'ALARM FIBROLASER CT ENVIRONMENT CONDITIONS ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_CONDITIONS_ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_CONDITIONS_ERROR_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120029, 2, 3, 29, NULL, 3, true, true, 'ALARM FIBROLASER CT HANDLING ERROR', 'ALARM FIBROLASER CT HANDLING ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_HANDLING_ERROR', 'LBL_ALARM_CONFIGS_ALARM_FIBROLASER_CT_HANDLING_ERROR_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: conf.element_state_alarms
--
INSERT INTO conf.element_state_alarms
(element_type_id, element_type_state_id, alarm_config_id, created_at, updated_at) VALUES
(29, 2, 010029, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
