--Active params
UPDATE master.element_subtype_active_params SET enabled = true WHERE element_type_id = 2 and param_type_id = 2 and element_type_param_id IN (1,3,4,5);

INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(2, 3, 1, 0010002, NULL, NULL, 'NO-S1S1-CCTV-01', 'NO-S1S1-CCTV-01', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 2, 0020002, NULL, NULL, 'NO-S1S1-CCTV-02', 'NO-S1S1-CCTV-02', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 3, 0030002, NULL, NULL, 'NO-S1S1-CCTV-03', 'NO-S1S1-CCTV-03', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 4, 0040002, NULL, NULL, 'NO-S1S1-CCTV-04', 'NO-S1S1-CCTV-04', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 5, 0050002, NULL, NULL, 'NO-S1S1-CCTV-05', 'NO-S1S1-CCTV-05', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 6, 0060002, NULL, NULL, 'NO-S1S1-CCTV-06', 'NO-S1S1-CCTV-06', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 7, 0070002, NULL, NULL, 'NO-S1S2-CCTV-01', 'NO-S1S2-CCTV-01', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 8, 0080002, NULL, NULL, 'NO-S1S2-CCTV-02', 'NO-S1S2-CCTV-02', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 9, 0090002, NULL, NULL, 'NO-S1S2-CCTV-03', 'NO-S1S2-CCTV-03', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 10, 0100002, NULL, NULL, 'NO-S1S2-CCTV-04', 'NO-S1S2-CCTV-04', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 11, 0110002, NULL, NULL, 'NO-S1S2-CCTV-05', 'NO-S1S2-CCTV-05', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 12, 0120002, NULL, NULL, 'NO-S1S2-CCTV-06', 'NO-S1S2-CCTV-06', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 13, 0130002, NULL, NULL, 'NO-S1S2-CCTV-07', 'NO-S1S2-CCTV-07', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 14, 0140002, NULL, NULL, 'NO-S1S3-CCTV-01', 'NO-S1S3-CCTV-01', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 15, 0150002, NULL, NULL, 'NO-S1S3-CCTV-02', 'NO-S1S3-CCTV-02', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 16, 0160002, NULL, NULL, 'NO-S1S3-CCTV-03', 'NO-S1S3-CCTV-03', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 17, 0170002, NULL, NULL, 'NO-S2-CCTV-01', 'NO-S2-CCTV-01', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 18, 0180002, NULL, NULL, 'NO-S2-CCTV-02', 'NO-S2-CCTV-02', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 19, 0190002, NULL, NULL, 'NO-S2-CCTV-03', 'NO-S2-CCTV-03', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 20, 0200002, NULL, NULL, 'NO-S2-CCTV-04', 'NO-S2-CCTV-04', 'sendDAIAlarm.groovy', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(2, 1, 1, 1, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 1, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 1, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 1, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 1, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 1, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 1, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 1, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 1, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 1, NULL, 'NO-S1S1-CCTV-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 2, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 2, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 2, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 2, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 2, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 2, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 2, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 2, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 2, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 2, NULL, 'NO-S1S1-CCTV-02', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 3, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 3, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 3, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 3, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 3, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 3, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 3, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 3, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 3, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 3, NULL, 'NO-S1S1-CCTV-03', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 4, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 4, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 4, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 4, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 4, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 4, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 4, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 4, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 4, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 4, NULL, 'NO-S1S1-CCTV-04', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 5, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 5, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 5, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 5, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 5, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 5, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 5, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 5, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 5, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 5, NULL, 'NO-S1S1-CCTV-05', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 6, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 6, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 6, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 6, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 6, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 6, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 6, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 6, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 6, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 6, NULL, 'NO-S1S1-CCTV-06', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 7, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 7, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 7, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 7, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 7, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 7, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 7, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 7, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 7, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 7, NULL, 'NO-S1S2-CCTV-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 8, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 8, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 8, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 8, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 8, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 8, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 8, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 8, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 8, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 8, NULL, 'NO-S1S2-CCTV-02', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 9, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 9, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 9, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 9, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 9, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 9, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 9, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 9, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 9, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 9, NULL, 'NO-S1S2-CCTV-03', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 10, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 10, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 10, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 10, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 10, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 10, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 10, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 10, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 10, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 10, NULL, 'NO-S1S2-CCTV-04', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 11, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 11, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 11, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 11, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 11, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 11, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 11, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 11, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 11, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 11, NULL, 'NO-S1S2-CCTV-05', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 12, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 12, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 12, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 12, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 12, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 12, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 12, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 12, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 12, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 12, NULL, 'NO-S1S2-CCTV-06', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 13, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 13, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 13, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 13, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 13, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 13, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 13, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 13, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 13, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 13, NULL, 'NO-S1S2-CCTV-07', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 14, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 14, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 14, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 14, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 14, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 14, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 14, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 14, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 14, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 14, NULL, 'NO-S1S3-CCTV-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 15, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 15, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 15, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 15, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 15, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 15, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 15, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 15, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 15, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 15, NULL, 'NO-S1S3-CCTV-02', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 16, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 16, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 16, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.12.10/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 16, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 16, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 16, NULL, '10.50.12.10', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 16, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 16, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 16, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 16, NULL, 'NO-S1S3-CCTV-03', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 17, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 17, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 17, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 17, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 17, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 17, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 17, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 17, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 17, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 17, NULL, 'NO-S2-CCTV-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 18, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 18, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 18, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 18, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 18, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 18, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 18, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 18, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 18, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 18, NULL, 'NO-S2-CCTV-02', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 19, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 19, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 19, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 19, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 19, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 19, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 19, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 19, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 19, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 19, NULL, 'NO-S2-CCTV-03', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 20, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 20, NULL, 'DS-2DF8242IX-AELW_SNAP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 20, NULL, 'http://ITS_Admin:VO1-cam22.@10.50.17.6/ISAPI/Streaming/channels/1/picture', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 20, NULL, '[{"id": 1,"alias": "Preset 1","description": "Panorámica hacia el Sur","default": true},{"id": 2,"alias": "Preset 2","description": "Panorámica hacia el Norte","default": false},{"id": 3,"alias": "Preset 3","description": "Boca de túnel sin zoom","default": false},{"id": 4,"alias": "Preset 4","description": "SOS exterior","default": false},{"id": 5,"alias": "Preset 5","description": "Puerta SE","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 20, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 20, NULL, '10.50.17.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 20, NULL, 'ITS_Admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 20, NULL, 'VO1-cam22.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 20, NULL, '{"up":0.02,"down":-0.02,"right":0.02,"left":-0.02,"zoom_in":0.02,"zoom_out":-0.02}', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 20, NULL, 'NO-S2-CCTV-04', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(2, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
