-- 
-- Table: conf.alarm_configs
--
INSERT INTO conf.alarm_configs
(alarm_config_id, alarm_type_id, alarm_level_id, element_type_id, element_id, element_type_state_id, mine, treatment, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
--ALARMAS DAI
--Vehículo lento
(1070002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 1', 'ALARM DAI SLOW VEH LANE 1', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1080002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 2', 'ALARM DAI SLOW VEH LANE 2', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1090002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 3', 'ALARM DAI SLOW VEH LANE 3', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_3', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1100002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 4', 'ALARM DAI SLOW VEH LANE 4', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1110002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 5', 'ALARM DAI SLOW VEH LANE 5', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_5', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1120002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 6', 'ALARM DAI SLOW VEH LANE 6', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_6', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1130002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 7', 'ALARM DAI SLOW VEH LANE 7', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_7', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1140002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 8', 'ALARM DAI SLOW VEH LANE 8', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_8', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1150002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 9', 'ALARM DAI SLOW VEH LANE 9', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_9', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1160002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 10', 'ALARM DAI SLOW VEH LANE 10', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1170002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 11', 'ALARM DAI SLOW VEH LANE 11', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_11', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1180002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI SLOW VEH LANE 12', 'ALARM DAI SLOW VEH LANE 12', 'LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_12', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--Vehículo parado
(1190002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 1', 'ALARM DAI STOP VEH LANE 1', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1200002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 2', 'ALARM DAI STOP VEH LANE 2', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1210002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 3', 'ALARM DAI STOP VEH LANE 3', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_3', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1220002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 4', 'ALARM DAI STOP VEH LANE 4', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1230002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 5', 'ALARM DAI STOP VEH LANE 5', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_5', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1240002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 6', 'ALARM DAI STOP VEH LANE 6', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_6', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1250002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 7', 'ALARM DAI STOP VEH LANE 7', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_7', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1260002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 8', 'ALARM DAI STOP VEH LANE 8', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_8', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1270002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 9', 'ALARM DAI STOP VEH LANE 9', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_9', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1280002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 10', 'ALARM DAI STOP VEH LANE 10', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1290002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 11', 'ALARM DAI STOP VEH LANE 11', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_11', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1300002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI STOP VEH LANE 12', 'ALARM DAI STOP VEH LANE 12', 'LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_12', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--Objeto en la vía
(1310002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 1', 'ALARM DAI DEBRIS LANE 1', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1320002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 2', 'ALARM DAI DEBRIS LANE 2', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1330002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 3', 'ALARM DAI DEBRIS LANE 3', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_3', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1340002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 4', 'ALARM DAI DEBRIS LANE 4', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1350002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 5', 'ALARM DAI DEBRIS LANE 5', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_5', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1360002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 6', 'ALARM DAI DEBRIS LANE 6', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_6', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1370002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 7', 'ALARM DAI DEBRIS LANE 7', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_7', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1380002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 8', 'ALARM DAI DEBRIS LANE 8', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_8', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1390002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 9', 'ALARM DAI DEBRIS LANE 9', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_9', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1400002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 10', 'ALARM DAI DEBRIS LANE 10', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1410002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 11', 'ALARM DAI DEBRIS LANE 11', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_11', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1420002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI DEBRIS LANE 12', 'ALARM DAI DEBRIS LANE 12', 'LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_12', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--Peaton
(1430002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 1', 'ALARM DAI PEDESTRIAN LANE 1', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1440002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 2', 'ALARM DAI PEDESTRIAN LANE 2', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1450002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 3', 'ALARM DAI PEDESTRIAN LANE 3', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_3', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1460002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 4', 'ALARM DAI PEDESTRIAN LANE 4', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1470002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 5', 'ALARM DAI PEDESTRIAN LANE 5', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_5', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1480002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 6', 'ALARM DAI PEDESTRIAN LANE 6', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_6', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1490002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 7', 'ALARM DAI PEDESTRIAN LANE 7', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_7', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1500002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 8', 'ALARM DAI PEDESTRIAN LANE 8', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_8', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1510002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 9', 'ALARM DAI PEDESTRIAN LANE 9', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_9', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1520002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 10', 'ALARM DAI PEDESTRIAN LANE 10', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1530002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 11', 'ALARM DAI PEDESTRIAN LANE 11', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_11', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1540002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI PEDESTRIAN LANE 12', 'ALARM DAI PEDESTRIAN LANE 12', 'LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_12', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--Visibilidad reducida
(1550002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 1', 'ALARM DAI VISIBILITY LANE 1', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1560002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 2', 'ALARM DAI VISIBILITY LANE 2', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1570002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 3', 'ALARM DAI VISIBILITY LANE 3', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_3', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1580002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 4', 'ALARM DAI VISIBILITY LANE 4', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1590002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 5', 'ALARM DAI VISIBILITY LANE 5', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_5', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1600002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 6', 'ALARM DAI VISIBILITY LANE 6', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_6', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1610002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 7', 'ALARM DAI VISIBILITY LANE 7', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_7', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1620002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 8', 'ALARM DAI VISIBILITY LANE 8', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_8', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1630002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 9', 'ALARM DAI VISIBILITY LANE 9', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_9', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1640002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 10', 'ALARM DAI VISIBILITY LANE 10', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1650002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 11', 'ALARM DAI VISIBILITY LANE 11', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_11', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1660002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI VISIBILITY LANE 12', 'ALARM DAI VISIBILITY LANE 12', 'LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_12', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--Congestion
(1670002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 1', 'ALARM DAI CONGESTION LANE 1', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1680002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 2', 'ALARM DAI CONGESTION LANE 2', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1690002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 3', 'ALARM DAI CONGESTION LANE 3', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_3', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1700002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 4', 'ALARM DAI CONGESTION LANE 4', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1710002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 5', 'ALARM DAI CONGESTION LANE 5', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_5', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1720002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 6', 'ALARM DAI CONGESTION LANE 6', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_6', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1730002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 7', 'ALARM DAI CONGESTION LANE 7', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_7', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1740002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 8', 'ALARM DAI CONGESTION LANE 8', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_8', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1750002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 9', 'ALARM DAI CONGESTION LANE 9', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_9', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1760002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 10', 'ALARM DAI CONGESTION LANE 10', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1770002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 11', 'ALARM DAI CONGESTION LANE 11', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_11', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1780002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI CONGESTION LANE 12', 'ALARM DAI CONGESTION LANE 12', 'LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_12', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--Kamikaze
(1790002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 1', 'ALARM DAI KAMIKAZE LANE 1', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1800002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 2', 'ALARM DAI KAMIKAZE LANE 2', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1810002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 3', 'ALARM DAI KAMIKAZE LANE 3', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_3', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1820002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 4', 'ALARM DAI KAMIKAZE LANE 4', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1830002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 5', 'ALARM DAI KAMIKAZE LANE 5', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_5', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1840002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 6', 'ALARM DAI KAMIKAZE LANE 6', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_6', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1850002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 7', 'ALARM DAI KAMIKAZE LANE 7', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_7', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1860002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 8', 'ALARM DAI KAMIKAZE LANE 8', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_8', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1870002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 9', 'ALARM DAI KAMIKAZE LANE 9', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_9', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1880002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 10', 'ALARM DAI KAMIKAZE LANE 10', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1890002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 11', 'ALARM DAI KAMIKAZE LANE 11', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_11', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1900002, 3, 5, 2, NULL, 3, true, true, 'ALARM DAI KAMIKAZE LANE 12', 'ALARM DAI KAMIKAZE LANE 12', 'LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_12', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
