TITLE ELECTRICAL_CABINET_P2
@echo off
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRKD.2.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRKD.3.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRDH.0.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRDH.1.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRDH.2.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRJS.3.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRJS.4.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRJS.5.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRJS.6.json
START /b /MIN unslave ELECTRICAL_CABINET_P2/PLCRISRJS.7.json
EXIT