INSERT INTO conf.plan_nodes (node_id, alias, description, plan_id, management_area_id, enabled, visible) VALUES
(1, 'Apertura', 'Apertura', NULL, NULL, True, True),
(2, 'Cierre', 'Cierre', NULL, NULL, True, True),
(3, 'Precaución', 'Precaución', NULL, NULL, True, True),
(4, 'ABRIR TÚNELES SENTIDO -> NORTE', 'ABRIR TÚNELES SENTIDO -> NORTE', 1, NULL, True, True),
(5, 'ABRIR TÚNELES SENTIDO -> SUR', 'ABRIR TÚNELES SENTIDO -> SUR', 2, NULL, True, True),
(8, 'Despeñaperros', 'Despeñaperros', NULL, NULL, True, True),
(9, 'PRECAUCIÓN 60KM/H -> SENTIDO NORTE', 'PRECAUCIÓN 60KM/H -> SENTIDO NORTE', 5, NULL, True, True),
(10, 'PRECAUCIÓN 40KM/H -> SENTIDO NORTE', 'PRECAUCIÓN 40KM/H -> SENTIDO NORTE', 6, NULL, True, True),
(11, 'restitución', 'restitución', NULL, NULL, True, True),
(15, 'PRECAUCIÓN 60KM/H -> SENTIDO SUR', 'PRECAUCIÓN 60KM/H -> SENTIDO SUR', 8, NULL, True, True),
(16, 'PRECAUCION 40KM/H -> SENTIDO SUR', 'PRECAUCION 40KM/H -> SENTIDO SUR', 9, NULL, True, True),
(17, 'Despeñaperros', 'Despeñaperros', NULL, NULL, True, True),
(18, 'Túnel con normalidad sentido norte', 'Túnel con normalidad sentido norte', 10, NULL, True, True),
(19, 'Túnel con normalidad sentido sur', 'Túnel con normalidad sentido sur', 11, NULL, True, True),
(20, 'Visibilidad reducida', 'Visibilidad reducida', NULL, NULL, True, True),
(21, 'Despeñaperros', 'Despeñaperros', NULL, NULL, True, True),
(22, 'VISIBILIDAD REDUCIDA -> SENTIDO NORTE', 'VISIBILIDAD REDUCIDA -> SENTIDO NORTE', 12, NULL, True, True),
(23, 'VISIBILIDAD REDUCIDA -> SENTIDO SUR', 'VISIBILIDAD REDUCIDA -> SENTIDO SUR', 13, NULL, True, True),
(24, 'El Corzo', 'El Corzo', NULL, NULL, True, True),
(25, 'PRECAUCIÓN 40KM/H -> SENTIDO NORTE', 'PRECAUCIÓN 40KM/H -> SENTIDO NORTE', 14, NULL, True, True),
(26, 'CZ ->PRECAUCIÓN 60KM/H-> SENTIDO NORTE', 'CZ ->PRECAUCIÓN 60KM/H-> SENTIDO NORTE', 15, NULL, True, True),
(27, 'CZ -> PRECAUCIÓN 40KM/H -> SENTIDO SUR', 'CZ -> PRECAUCIÓN 40KM/H -> SENTIDO SUR', 16, NULL, True, True),
(28, 'CZ -> PRECAUCION 60KM/H -> SENTIDO SUR', 'CZ -> PRECAUCION 60KM/H -> SENTIDO SUR', 17, NULL, True, True),
(29, 'El Corzo', 'El Corzo', NULL, NULL, True, True),
(30, 'CZ -> TÚNEL CON NORMALIDAD -> SENTIDO NORTE', 'CZ -> TÚNEL CON NORMALIDAD -> SENTIDO NORTE', 18, NULL, True, True),
(31, 'CZ -> TÚNEL CON NORMALIDAD -> SENTIDO SUR', 'CZ -> TÚNEL CON NORMALIDAD -> SENTIDO SUR', 19, NULL, True, True),
(32, 'El Corzo', 'El Corzo', NULL, NULL, True, True),
(33, 'CZ -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE', 'CZ -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE', 20, NULL, True, True),
(34, 'CZ -> VISIBILIDAD REDUCIDA -> SENTIDO SUR', 'CZ -> VISIBILIDAD REDUCIDA -> SENTIDO SUR', 21, NULL, True, True),
(35, 'La Cantera', 'La Cantera', NULL, NULL, True, True),
(36, 'CA -> PRECAUCIÓN 40KM/H -> SENTIDO SUR', 'CA -> PRECAUCIÓN 40KM/H -> SENTIDO SUR', 22, NULL, True, True),
(37, 'CA -> PRECAUCIÓN 60KM/H -> SENTIDO NORTE', 'CA -> PRECAUCIÓN 60KM/H -> SENTIDO NORTE', 23, NULL, True, True),
(38, 'CA -> PRECAUCIÓN 40KM/H -> SENTIDO SUR', 'CA -> PRECAUCIÓN 40KM/H -> SENTIDO SUR', 24, NULL, True, True),
(39, 'CA -> PRECAUCIÓN 60KM/H -> SENTIDO SUR', 'CA -> PRECAUCIÓN 60KM/H -> SENTIDO SUR', 25, NULL, True, True),
(40, 'La Cantera', 'La Cantera', NULL, NULL, True, True),
(41, 'CA -> TÚNEL CON NORMALIDAD -> SENTIDO NORTE', 'CA -> TÚNEL CON NORMALIDAD -> SENTIDO NORTE', 26, NULL, True, True),
(42, 'CA -> TÚNEL CON NORMALIDAD -> SENTIDO SUR', 'CA -> TÚNEL CON NORMALIDAD -> SENTIDO SUR', 27, NULL, True, True),
(43, 'La Cantera', 'La Cantera', NULL, NULL, True, True),
(44, 'CA -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE', 'CA -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE', 28, NULL, True, True),
(45, 'CA -> VISIBILIDAD REDUCIDA -> SENTIDO SUR', 'CA -> VISIBILIDAD REDUCIDA -> SENTIDO SUR', 29, NULL, True, True),
(46, 'Despeñaperros', 'Despeñaperros', NULL, NULL, True, True),
(47, 'DP -> BAJAR BARRERAS -> SENTIDO NORTE', 'DP -> BAJAR BARRERAS -> SENTIDO NORTE', 30, NULL, True, True),
(48, 'DP -> BAJAR BARRERAS -> SENTIDO SUR', 'DP -> BAJAR BARRERAS -> SENTIDO SUR', 31, NULL, True, True),
(49, 'Incendio', 'Incendio', NULL, NULL, True, True),
(50, 'DP -> CIERRE DE TUNEL -> SENTIDO NORTE', 'DP -> CIERRE DE TUNEL -> SENTIDO NORTE', 32, NULL, True, True),
(51, 'DP -> CIERRE TUNEL -> SENTIDO SUR', 'DP -> CIERRE TUNEL -> SENTIDO SUR', 33, NULL, True, True),
(52, 'DP -> INCENDIO EN TUNEL -> SENTIDO NORTE', 'DP -> INCENDIO EN TUNEL -> SENTIDO NORTE', 34, NULL, True, True),
(53, 'DP -> INCENDIO EN TÚNEL -> SENTIDO SUR', 'DP -> INCENDIO EN TÚNEL -> SENTIDO SUR', 35, NULL, True, True),
(54, 'ABRIR TÚNELES SENTIDO -> NORTE', 'ABRIR TÚNELES SENTIDO -> NORTE', 36, NULL, True, True),
(55, 'ABRIR TÚNELES SENTIDO -> SUR', 'ABRIR TÚNELES SENTIDO -> SUR', 37, NULL, True, True),
(56, 'CERRAR TÚNELES SENTIDO -> NORTE', 'CERRAR TÚNELES SENTIDO -> NORTE', 38, NULL, True, True),
(57, 'CERRAR TÚNELES SENTIDO -> SUR', 'CERRAR TÚNELES SENTIDO -> SUR', 39, NULL, True, True),
(58, 'PRECAUCIÓN TÚNELES SENTIDO -> NORTE', 'PRECAUCIÓN TÚNELES SENTIDO -> NORTE', 40, NULL, True, True),
(59, 'PRECAUCIÓN TÚNELES SENTIDO -> SUR', 'PRECAUCIÓN TÚNELES SENTIDO -> SUR', 41, NULL, True, True),
(60, 'CORTE CARRIL DERECHO', 'CORTE CARRIL DERECHO', 42, NULL, True, True),
(61, 'CORTE CARRIL SENTIDO -> SUR', 'CORTE CARRIL SENTIDO -> SUR', 43, NULL, True, True),
(62, 'Corte carril', 'Corte carril', NULL, NULL, True, True);

