INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(25, NULL, 1, 0010025, NULL, NULL, 'ICEO-AIM-001_AE', 'ICEO-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 2, 0020025, NULL, NULL, 'ICEP-AIM-001_AE', 'ICEP-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 3, 0030025, NULL, NULL, 'IVEN-AIM-001_AE', 'IVEN-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 4, 0040025, NULL, NULL, 'IVEN-AIM-002_AE', 'IVEN-AIM-002_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 5, 0050025, NULL, NULL, 'S1TN-AIM-001_AE', 'S1TN-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 6, 0060025, NULL, NULL, 'S1TN-AIM-002_AE', 'S1TN-AIM-002_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 7, 0070025, NULL, NULL, 'S1TN-AIM-003_AE', 'S1TN-AIM-003_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 8, 0080025, NULL, NULL, 'S1TN-AIM-004_AE', 'S1TN-AIM-004_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 9, 0090025, NULL, NULL, 'S1TN-AIM-005_AE', 'S1TN-AIM-005_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 10, 0100025, NULL, NULL, 'S1TS-AIM-001_AE', 'S1TS-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 11, 0110025, NULL, NULL, 'INKP-AIM-001_AE', 'INKP-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 12, 0120025, NULL, NULL, 'IVIP-AIM-001_AE', 'IVIP-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 13, 0130025, NULL, NULL, 'IPRO-AIM-001_AE', 'IPRO-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 14, 0140025, NULL, NULL, 'ICCO-AIM-001_AE', 'ICCO-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 15, 0150025, NULL, NULL, 'ICCP-AIM-001_AE', 'ICCP-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, NULL, 16, 0160025, NULL, NULL, 'IBTO-AIM-001_AE', 'IBTO-AIM-001_AE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(25, 1003, 1, 1, NULL, 'ICEO-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 2, NULL, 'ICEP-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 3, NULL, 'IVEN-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 4, NULL, 'IVEN-AIM-002_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 5, NULL, 'S1TN-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 6, NULL, 'S1TN-AIM-002_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 7, NULL, 'S1TN-AIM-003_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 8, NULL, 'S1TN-AIM-004_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 9, NULL, 'S1TN-AIM-005_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 10, NULL, 'S1TS-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 11, NULL, 'INKP-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 12, NULL, 'IVIP-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 13, NULL, 'IPRO-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 14, NULL, 'ICCO-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 15, NULL, 'ICCP-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(25, 1003, 1, 16, NULL, 'IBTO-AIM-001_AE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(25, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(25, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
