INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(88, NULL, 1, 0010088, NULL, NULL, 'ALJ1-DETFLJ-PCI-1', 'ALJ1-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 2, 0020088, NULL, NULL, 'ALJ1-DETFLJ-PCI-2', 'ALJ1-DETFLJ-PCI-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 3, 0030088, NULL, NULL, 'ALJ1-DETPR-PCI-1', 'ALJ1-DETPR-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 4, 0040088, NULL, NULL, 'ALJ2-DETFLJ-PCI-1', 'ALJ2-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 5, 0050088, NULL, NULL, 'ALJ2-DETFLJ-PCI-2', 'ALJ2-DETFLJ-PCI-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 6, 0060088, NULL, NULL, 'ALJ2-DETPR-PCI-1', 'ALJ2-DETPR-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 7, 0070088, NULL, NULL, 'ALJ3-DETFLJ-PCI-1', 'ALJ3-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 8, 0080088, NULL, NULL, 'ALJ3-DETFLJ-PCI-2', 'ALJ3-DETFLJ-PCI-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 9, 0090088, NULL, NULL, 'ALJ3-DETPR-PCI-1', 'ALJ3-DETPR-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 10, 0100088, NULL, NULL, 'ALJ4-DETFLJ-PCI-1', 'ALJ4-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 11, 0110088, NULL, NULL, 'ALJ4-DETFLJ-PCI-2', 'ALJ4-DETFLJ-PCI-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 12, 0120088, NULL, NULL, 'ALJ4-DETPR-PCI-1', 'ALJ4-DETPR-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 13, 0130088, NULL, NULL, 'ALJ1-DETROOM-PCI-1', 'ALJ1-DETROOM-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 14, 0140088, NULL, NULL, 'ALJ2-DETROOM-PCI-1', 'ALJ2-DETROOM-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 15, 0150088, NULL, NULL, 'ALJ3-DETROOM-PCI-1', 'ALJ3-DETROOM-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 16, 0160088, NULL, NULL, 'ALJ4-DETROOM-PCI-1', 'ALJ4-DETROOM-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(88, 1003, 1, 1, NULL, 'ALJ1-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 2, NULL, 'ALJ1-DETFLJ-PCI-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 3, NULL, 'ALJ1-DETPR-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 4, NULL, 'ALJ2-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 5, NULL, 'ALJ2-DETFLJ-PCI-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 6, NULL, 'ALJ2-DETPR-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 7, NULL, 'ALJ3-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 8, NULL, 'ALJ3-DETFLJ-PCI-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 9, NULL, 'ALJ3-DETPR-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 10, NULL, 'ALJ4-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 11, NULL, 'ALJ4-DETFLJ-PCI-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 12, NULL, 'ALJ4-DETPR-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 13, NULL, 'ALJ1-DETROOM-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 14, NULL, 'ALJ2-DETROOM-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 15, NULL, 'ALJ3-DETROOM-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 16, NULL, 'ALJ4-DETROOM-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(88, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
