INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(26, NULL, 1, 0010026, NULL, NULL, 'RV-SWL', 'RV-SWL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 2, 0020026, NULL, NULL, 'RV-SWS-1CA', 'RV-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 3, 0030026, NULL, NULL, 'RV-SWS-1MA', 'RV-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 4, 0040026, NULL, NULL, 'RV-SWE-CA', 'RV-SWE-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 5, 0050026, NULL, NULL, 'MM-SWL', 'MM-SWL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 6, 0060026, NULL, NULL, 'MM-SWS-1CA', 'MM-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 7, 0070026, NULL, NULL, 'MM-SWS-2CA', 'MM-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 8, 0080026, NULL, NULL, 'MM-SWS-3CA', 'MM-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 9, 0090026, NULL, NULL, 'MM-SWG-CA', 'MM-SWG-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 10, 0100026, NULL, NULL, 'MM-SWE-CA', 'MM-SWE-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 11, 0110026, NULL, NULL, 'MM-SWS-1MA', 'MM-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 12, 0120026, NULL, NULL, 'MM-SWS-2MA', 'MM-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 13, 0130026, NULL, NULL, 'MM-SWS-3MA', 'MM-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 14, 0140026, NULL, NULL, 'STMI-SWL', 'STMI-SWL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 15, 0150026, NULL, NULL, 'STMI-SWS-1CA', 'STMI-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 16, 0160026, NULL, NULL, 'STMI-SWS-1MA', 'STMI-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 17, 0170026, NULL, NULL, 'STMI-SWE-CA', 'STMI-SWE-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 18, 0180026, NULL, NULL, 'COR-SWL-BC', 'COR-SWL-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 19, 0190026, NULL, NULL, 'COR-SWL-BM', 'COR-SWL-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 20, 0200026, NULL, NULL, 'COR-SWS-1CA', 'COR-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 21, 0210026, NULL, NULL, 'COR-SWS-2CA', 'COR-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 22, 0220026, NULL, NULL, 'COR-SWS-3CA', 'COR-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 23, 0230026, NULL, NULL, 'COR-SWS-4CA', 'COR-SWS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 24, 0240026, NULL, NULL, 'COR-SWG1-CA', 'COR-SWG1-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 25, 0250026, NULL, NULL, 'COR-SWG2-MA', 'COR-SWG2-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 26, 0260026, NULL, NULL, 'COR-SWG3-CA', 'COR-SWG3-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 27, 0270026, NULL, NULL, 'COR-SWS-1MA', 'COR-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 28, 0280026, NULL, NULL, 'COR-SWS-2MA', 'COR-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 29, 0290026, NULL, NULL, 'COR-SWS-3MA', 'COR-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 30, 0300026, NULL, NULL, 'COR-SWS-4MA', 'COR-SWS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 31, 0310026, NULL, NULL, 'LQ-SWS-1CA', 'LQ-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 32, 0320026, NULL, NULL, 'LQ-SWS-2CA', 'LQ-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 33, 0330026, NULL, NULL, 'LQ-SWS-3CA', 'LQ-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 34, 0340026, NULL, NULL, 'LQ-SWS-4CA', 'LQ-SWS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 35, 0350026, NULL, NULL, 'LQ-SWS-5CA', 'LQ-SWS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 36, 0360026, NULL, NULL, 'LQ-SWS-1MA', 'LQ-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 37, 0370026, NULL, NULL, 'LQ-SWS-2MA', 'LQ-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 38, 0380026, NULL, NULL, 'LQ-SWS-3MA', 'LQ-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 39, 0390026, NULL, NULL, 'LQ-SWS-4MA', 'LQ-SWS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 40, 0400026, NULL, NULL, 'LQ-SWG-CA', 'LQ-SWG-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 41, 0410026, NULL, NULL, 'LQ-SWE-CA', 'LQ-SWE-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 42, 0420026, NULL, NULL, 'LQ-SWL', 'LQ-SWL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 43, 0430026, NULL, NULL, 'CH-SWS-1CA', 'CH-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 44, 0440026, NULL, NULL, 'CH-SWS-2CA', 'CH-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 45, 0450026, NULL, NULL, 'CH-SWS-3CA', 'CH-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 46, 0460026, NULL, NULL, 'CH-SWS-1MA', 'CH-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 47, 0470026, NULL, NULL, 'CH-SWS-2MA', 'CH-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 48, 0480026, NULL, NULL, 'CH-SWS-3MA', 'CH-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 49, 0490026, NULL, NULL, 'CH-SWG-CA', 'CH-SWG-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 50, 0500026, NULL, NULL, 'CH-SWE-BC', 'CH-SWE-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 51, 0510026, NULL, NULL, 'CH-SWL', 'CH-SWL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 52, 0520026, NULL, NULL, 'STM2-SWS-1CA', 'STM2-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 53, 0530026, NULL, NULL, 'STM2-SWS-2CA', 'STM2-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 54, 0540026, NULL, NULL, 'STM2-SWS-3CA', 'STM2-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 55, 0550026, NULL, NULL, 'STM2-SWS-1MA', 'STM2-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 56, 0560026, NULL, NULL, 'STM2-SWS-2MA', 'STM2-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 57, 0570026, NULL, NULL, 'STM2-SWS-3MA', 'STM2-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 58, 0580026, NULL, NULL, 'STM2-SWG-CA', 'STM2-SWG-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 59, 0590026, NULL, NULL, 'STM2-SWL-BM', 'STM2-SWL-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 60, 0600026, NULL, NULL, 'STM2-SWL-BC', 'STM2-SWL-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 61, 0610026, NULL, NULL, 'CAS-SWS-1CA', 'CAS-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 62, 0620026, NULL, NULL, 'CAS-SWS-2CA', 'CAS-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 63, 0630026, NULL, NULL, 'CAS-SWS-3CA', 'CAS-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 64, 0640026, NULL, NULL, 'CAS-SWS-4CA', 'CAS-SWS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 65, 0650026, NULL, NULL, 'CAS-SWS-5CA', 'CAS-SWS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 66, 0660026, NULL, NULL, 'CAS-SWS-1MA', 'CAS-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 67, 0670026, NULL, NULL, 'CAS-SWS-2MA', 'CAS-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 68, 0680026, NULL, NULL, 'CAS-SWS-3MA', 'CAS-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 69, 0690026, NULL, NULL, 'CAS-SWS-4MA', 'CAS-SWS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 70, 0700026, NULL, NULL, 'CAS-SWS-5MA', 'CAS-SWS-5MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 71, 0710026, NULL, NULL, 'CAS-SWL-BC', 'CAS-SWL-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 72, 0720026, NULL, NULL, 'CAS-SWL-BM', 'CAS-SWL-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 73, 0730026, NULL, NULL, 'CAS-SWG1-CA', 'CAS-SWG1-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 74, 0740026, NULL, NULL, 'CAS-SWG2-MA', 'CAS-SWG2-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 75, 0750026, NULL, NULL, 'EST-SWS-1CA', 'EST-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 76, 0760026, NULL, NULL, 'EST-SWS-1MA', 'EST-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 77, 0770026, NULL, NULL, 'EST-SWE-BC', 'EST-SWE-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 78, 0780026, NULL, NULL, 'EST-SWL', 'EST-SWL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 79, 0790026, NULL, NULL, 'NG-SWL-BC', 'NG-SWL-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 80, 0800026, NULL, NULL, 'NG-SWS-1CA', 'NG-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 81, 0810026, NULL, NULL, 'NG-SWS-2CA', 'NG-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 82, 0820026, NULL, NULL, 'NG-SWS-3CA', 'NG-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 83, 0830026, NULL, NULL, 'NG-SWS-4CA', 'NG-SWS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 84, 0840026, NULL, NULL, 'NG-SWS-5CA', 'NG-SWS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 85, 0850026, NULL, NULL, 'NG-SWS-6CA', 'NG-SWS-6CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 86, 0860026, NULL, NULL, 'NG-SWS-7CA', 'NG-SWS-7CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 87, 0870026, NULL, NULL, 'NG-SWS-8CA', 'NG-SWS-8CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 88, 0880026, NULL, NULL, 'NG-SWG-CA', 'NG-SWG-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 89, 0890026, NULL, NULL, 'NG-SWL-BM', 'NG-SWL-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 90, 0900026, NULL, NULL, 'NG-SWS-1MA', 'NG-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 91, 0910026, NULL, NULL, 'NG-SWS-2MA', 'NG-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 92, 0920026, NULL, NULL, 'NG-SWS-3MA', 'NG-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 93, 0930026, NULL, NULL, 'NG-SWS-4MA', 'NG-SWS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 94, 0940026, NULL, NULL, 'NG-SWS-5MA', 'NG-SWS-5MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 95, 0950026, NULL, NULL, 'NG-SWS-6MA', 'NG-SWS-6MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 96, 0960026, NULL, NULL, 'NG-SWS-7MA', 'NG-SWS-7MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 97, 0970026, NULL, NULL, 'NG-SWS-8MA', 'NG-SWS-8MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 98, 0980026, NULL, NULL, 'CH-SWE-BM', 'CH-SWE-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 99, 0990026, NULL, NULL, 'LQ-SWE-MA', 'LQ-SWE-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(26, 1003, 1, 1, NULL, 'RV-SWL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 2, NULL, 'RV-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 3, NULL, 'RV-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 4, NULL, 'RV-SWE-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 5, NULL, 'MM-SWL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 6, NULL, 'MM-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 7, NULL, 'MM-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 8, NULL, 'MM-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 9, NULL, 'MM-SWG-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 10, NULL, 'MM-SWE-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 11, NULL, 'MM-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 12, NULL, 'MM-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 13, NULL, 'MM-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 14, NULL, 'STMI-SWL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 15, NULL, 'STMI-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 16, NULL, 'STMI-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 17, NULL, 'STMI-SWE-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 18, NULL, 'COR-SWL-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 19, NULL, 'COR-SWL-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 20, NULL, 'COR-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 21, NULL, 'COR-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 22, NULL, 'COR-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 23, NULL, 'COR-SWS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 24, NULL, 'COR-SWG1-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 25, NULL, 'COR-SWG2-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 26, NULL, 'COR-SWG3-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 27, NULL, 'COR-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 28, NULL, 'COR-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 29, NULL, 'COR-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 30, NULL, 'COR-SWS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 31, NULL, 'LQ-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 32, NULL, 'LQ-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 33, NULL, 'LQ-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 34, NULL, 'LQ-SWS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 35, NULL, 'LQ-SWS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 36, NULL, 'LQ-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 37, NULL, 'LQ-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 38, NULL, 'LQ-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 39, NULL, 'LQ-SWS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 40, NULL, 'LQ-SWG-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 41, NULL, 'LQ-SWE-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 42, NULL, 'LQ-SWL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 43, NULL, 'CH-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 44, NULL, 'CH-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 45, NULL, 'CH-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 46, NULL, 'CH-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 47, NULL, 'CH-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 48, NULL, 'CH-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 49, NULL, 'CH-SWG-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 50, NULL, 'CH-SWE-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 51, NULL, 'CH-SWL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 52, NULL, 'STM2-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 53, NULL, 'STM2-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 54, NULL, 'STM2-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 55, NULL, 'STM2-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 56, NULL, 'STM2-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 57, NULL, 'STM2-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 58, NULL, 'STM2-SWG-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 59, NULL, 'STM2-SWL-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 60, NULL, 'STM2-SWL-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 61, NULL, 'CAS-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 62, NULL, 'CAS-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 63, NULL, 'CAS-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 64, NULL, 'CAS-SWS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 65, NULL, 'CAS-SWS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 66, NULL, 'CAS-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 67, NULL, 'CAS-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 68, NULL, 'CAS-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 69, NULL, 'CAS-SWS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 70, NULL, 'CAS-SWS-5MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 71, NULL, 'CAS-SWL-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 72, NULL, 'CAS-SWL-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 73, NULL, 'CAS-SWG1-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 74, NULL, 'CAS-SWG2-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 75, NULL, 'EST-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 76, NULL, 'EST-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 77, NULL, 'EST-SWE-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 78, NULL, 'EST-SWL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 79, NULL, 'NG-SWL-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 80, NULL, 'NG-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 81, NULL, 'NG-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 82, NULL, 'NG-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 83, NULL, 'NG-SWS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 84, NULL, 'NG-SWS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 85, NULL, 'NG-SWS-6CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 86, NULL, 'NG-SWS-7CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 87, NULL, 'NG-SWS-8CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 88, NULL, 'NG-SWG-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 89, NULL, 'NG-SWL-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 90, NULL, 'NG-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 91, NULL, 'NG-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 92, NULL, 'NG-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 93, NULL, 'NG-SWS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 94, NULL, 'NG-SWS-5MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 95, NULL, 'NG-SWS-6MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 96, NULL, 'NG-SWS-7MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 97, NULL, 'NG-SWS-8MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 98, NULL, 'CH-SWE-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 99, NULL, 'LQ-SWE-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(26, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 41, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 42, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 43, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 44, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 45, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 46, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 47, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 48, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 49, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 50, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 51, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 52, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 53, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 54, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 55, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 56, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 57, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 58, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 59, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 60, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 61, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 62, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 63, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 64, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 65, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 66, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 67, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 68, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 69, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 70, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 71, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 72, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 73, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 74, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 75, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 76, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 77, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 78, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 79, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 80, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 81, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 82, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 83, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 84, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 85, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 86, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 87, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 88, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 89, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 90, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 91, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 92, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 93, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 94, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 95, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 96, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 97, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 98, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 99, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
