INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(59, NULL, 1, 0010059, NULL, NULL, 'RV-CT-ITS-HUM-1', 'RV-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 2, 0020059, NULL, NULL, 'RV-CT-ITS-HUM-2', 'RV-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 3, 0030059, NULL, NULL, 'RV-CT-CGBT-HUM-1', 'RV-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 4, 0040059, NULL, NULL, 'RV-CT-CGBT-HUM-2', 'RV-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 5, 0050059, NULL, NULL, 'RV-CT-PCI-HUM-1', 'RV-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 6, 0060059, NULL, NULL, 'RV-CT-PCI-HUM-2', 'RV-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 7, 0070059, NULL, NULL, 'MM-CT-ITS-HUM-1', 'MM-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 8, 0080059, NULL, NULL, 'MM-CT-ITS-HUM-2', 'MM-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 9, 0090059, NULL, NULL, 'MM-CT-CGBT-HUM-1', 'MM-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 10, 0100059, NULL, NULL, 'MM-CT-CGBT-HUM-2', 'MM-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 11, 0110059, NULL, NULL, 'STMI-CT-ITS-HUM-1', 'STMI-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 12, 0120059, NULL, NULL, 'STMI-CT-ITS-HUM-2', 'STMI-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 13, 0130059, NULL, NULL, 'MM-CT-PCI-HUM-1', 'MM-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 14, 0140059, NULL, NULL, 'MM-CT-PCI-HUM-2', 'MM-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 15, 0150059, NULL, NULL, 'STMI-CT-CGBT-HUM-1', 'STMI-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 16, 0160059, NULL, NULL, 'STMI-CT-CGBT-HUM-2', 'STMI-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 17, 0170059, NULL, NULL, 'CAS-CT-PCI-HUM-1', 'CAS-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 18, 0180059, NULL, NULL, 'CAS-CT-PCI-HUM-2', 'CAS-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 19, 0190059, NULL, NULL, 'CAS-CT-CGBT-BC-HUM-1', 'CAS-CT-CGBT-BC-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 20, 0200059, NULL, NULL, 'CAS-CT-CGBT-BC-HUM-2', 'CAS-CT-CGBT-BC-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 21, 0210059, NULL, NULL, 'CAS-CT-ITS-BC-HUM-1', 'CAS-CT-ITS-BC-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 22, 0220059, NULL, NULL, 'CAS-CT-ITS-BC-HUM-2', 'CAS-CT-ITS-BC-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 23, 0230059, NULL, NULL, 'CAS-CT-CGBT-BM-HUM-1', 'CAS-CT-CGBT-BM-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 24, 0240059, NULL, NULL, 'CAS-CT-CGBT-BM-HUM-2', 'CAS-CT-CGBT-BM-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 25, 0250059, NULL, NULL, 'CAS-CT-ITS-BM-HUM-1', 'CAS-CT-ITS-BM-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 26, 0260059, NULL, NULL, 'CAS-CT-ITS-BM-HUM-2', 'CAS-CT-ITS-BM-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 27, 0270059, NULL, NULL, 'CH-CT-CGBT-HUM-1', 'CH-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 28, 0280059, NULL, NULL, 'CH-CT-CGBT-HUM-2', 'CH-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 29, 0290059, NULL, NULL, 'CH-CT-ITS-HUM-1', 'CH-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 30, 0300059, NULL, NULL, 'CH-CT-ITS-HUM-2', 'CH-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 31, 0310059, NULL, NULL, 'CH-CT-PCI-HUM-1', 'CH-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 32, 0320059, NULL, NULL, 'CH-CT-PCI-HUM-2', 'CH-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 33, 0330059, NULL, NULL, 'EST-CT-CGBT-HUM-1', 'EST-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 34, 0340059, NULL, NULL, 'EST-CT-CGBT-HUM-2', 'EST-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 35, 0350059, NULL, NULL, 'EST-CT-ITS-HUM-1', 'EST-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 36, 0360059, NULL, NULL, 'EST-CT-ITS-HUM-2', 'EST-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 37, 0370059, NULL, NULL, 'STM2-CT-CGBT-HUM-1', 'STM2-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 38, 0380059, NULL, NULL, 'STM2-CT-CGBT-HUM-2', 'STM2-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 39, 0390059, NULL, NULL, 'STM2-CT-ITS-HUM-1', 'STM2-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 40, 0400059, NULL, NULL, 'STM2-CT-ITS-HUM-2', 'STM2-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 42, 0420059, NULL, NULL, 'LQ-CT-CGBT-HUM-1', 'LQ-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 43, 0430059, NULL, NULL, 'LQ-CT-CGBT-HUM-2', 'LQ-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 44, 0440059, NULL, NULL, 'LQ-CT-ITS-HUM-1', 'LQ-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 45, 0450059, NULL, NULL, 'LQ-CT-ITS-HUM-2', 'LQ-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 46, 0460059, NULL, NULL, 'LQ-CT-PCI-HUM-1', 'LQ-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 47, 0470059, NULL, NULL, 'LQ-CT-PCI-HUM-2', 'LQ-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 48, 0480059, NULL, NULL, 'NG-CT-CGBT-HUM-1', 'NG-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 49, 0490059, NULL, NULL, 'NG-CT-CGBT-HUM-2', 'NG-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 50, 0500059, NULL, NULL, 'NG-CT-ITS-HUM-1', 'NG-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 51, 0510059, NULL, NULL, 'NG-CT-ITS-HUM-2', 'NG-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 52, 0520059, NULL, NULL, 'NG-CT-PCI-HUM-1', 'NG-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 53, 0530059, NULL, NULL, 'NG-CT-PCI-HUM-2', 'NG-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 54, 0540059, NULL, NULL, 'COR-CT-CGBT-BC-HUM-1', 'COR-CT-CGBT-BC-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 55, 0550059, NULL, NULL, 'COR-CT-CGBT-BC-HUM-2', 'COR-CT-CGBT-BC-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 56, 0560059, NULL, NULL, 'COR-CT-CGBT-BM-HUM-1', 'COR-CT-CGBT-BM-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 57, 0570059, NULL, NULL, 'COR-CT-CGBT-BM-HUM-2', 'COR-CT-CGBT-BM-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 58, 0580059, NULL, NULL, 'COR-CT-IT-BC-HUM-1', 'COR-CT-IT-BC-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 59, 0590059, NULL, NULL, 'COR-CT-IT-BC-HUM-2', 'COR-CT-IT-BC-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 60, 0600059, NULL, NULL, 'COR-CT-IT-BM-HUM-1', 'COR-CT-IT-BM-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 61, 0610059, NULL, NULL, 'COR-CT-IT-BM-HUM-2', 'COR-CT-IT-BM-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 62, 0620059, NULL, NULL, 'COR-CT-PCI-HUM-1', 'COR-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 63, 0630059, NULL, NULL, 'COR-CT-PCI-HUM-2', 'COR-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(59, 1003, 1, 1, NULL, 'RV-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 2, NULL, 'RV-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 3, NULL, 'RV-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 4, NULL, 'RV-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 5, NULL, 'RV-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 6, NULL, 'RV-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 7, NULL, 'MM-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 8, NULL, 'MM-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 9, NULL, 'MM-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 10, NULL, 'MM-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 11, NULL, 'STMI-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 12, NULL, 'STMI-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 13, NULL, 'MM-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 14, NULL, 'MM-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 15, NULL, 'STMI-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 16, NULL, 'STMI-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 17, NULL, 'CAS-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 18, NULL, 'CAS-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 19, NULL, 'CAS-CT-CGBT-BC-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 20, NULL, 'CAS-CT-CGBT-BC-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 21, NULL, 'CAS-CT-ITS-BC-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 22, NULL, 'CAS-CT-ITS-BC-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 23, NULL, 'CAS-CT-CGBT-BM-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 24, NULL, 'CAS-CT-CGBT-BM-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 25, NULL, 'CAS-CT-ITS-BM-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 26, NULL, 'CAS-CT-ITS-BM-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 27, NULL, 'CH-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 28, NULL, 'CH-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 29, NULL, 'CH-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 30, NULL, 'CH-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 31, NULL, 'CH-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 32, NULL, 'CH-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 33, NULL, 'EST-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 34, NULL, 'EST-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 35, NULL, 'EST-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 36, NULL, 'EST-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 37, NULL, 'STM2-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 38, NULL, 'STM2-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 39, NULL, 'STM2-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 40, NULL, 'STM2-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 42, NULL, 'LQ-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 43, NULL, 'LQ-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 44, NULL, 'LQ-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 45, NULL, 'LQ-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 46, NULL, 'LQ-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 47, NULL, 'LQ-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 48, NULL, 'NG-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 49, NULL, 'NG-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 50, NULL, 'NG-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 51, NULL, 'NG-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 52, NULL, 'NG-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 53, NULL, 'NG-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 54, NULL, 'COR-CT-CGBT-BC-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 55, NULL, 'COR-CT-CGBT-BC-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 56, NULL, 'COR-CT-CGBT-BM-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 57, NULL, 'COR-CT-CGBT-BM-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 58, NULL, 'COR-CT-IT-BC-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 59, NULL, 'COR-CT-IT-BC-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 60, NULL, 'COR-CT-IT-BM-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 61, NULL, 'COR-CT-IT-BM-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 62, NULL, 'COR-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 63, NULL, 'COR-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(59, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 42, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 43, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 44, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 45, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 46, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 47, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 48, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 49, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 50, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 51, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 52, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 53, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 54, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 55, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 56, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 57, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 58, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 59, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 60, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 61, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 62, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 63, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
