INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(88, NULL, 1, 0010088, NULL, NULL, 'RV-DETFLJ-PCI-1', 'RV-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 2, 0020088, NULL, NULL, 'MM-DETFLJ-PCI-SC', 'MM-DETFLJ-PCI-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 3, 0030088, NULL, NULL, 'LQ-DETFLJ-PCI-1', 'LQ-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 4, 0040088, NULL, NULL, 'LQ-DETFLJ-PCI-2', 'LQ-DETFLJ-PCI-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 5, 0050088, NULL, NULL, 'CAS-DETFLJ-PCI-1', 'CAS-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 6, 0060088, NULL, NULL, 'CAS-DETFLJ-PCI-2', 'CAS-DETFLJ-PCI-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 7, 0070088, NULL, NULL, 'CH-DETFLJ-PCI-1', 'CH-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 8, 0080088, NULL, NULL, 'COR-DETFLJ-PCI-1', 'COR-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, NULL, 9, 0090088, NULL, NULL, 'NG-DETFLJ-PCI-1', 'NG-DETFLJ-PCI-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(88, NULL, 10, 0100088, NULL, NULL, 'MM-DETFLJ-PCI-SM', 'MM-DETFLJ-PCI-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(88, 1003, 1, 1, NULL, 'RV-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 2, NULL, 'MM-DETFLJ-PCI-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 3, NULL, 'LQ-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 4, NULL, 'LQ-DETFLJ-PCI-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 5, NULL, 'CAS-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 6, NULL, 'CAS-DETFLJ-PCI-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 7, NULL, 'CH-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 8, NULL, 'COR-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 9, NULL, 'NG-DETFLJ-PCI-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(88, 1003, 1, 10, NULL, 'MM-DETFLJ-PCI-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(88, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(88, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
