INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(89, NULL, 1, 0010089, NULL, NULL, 'MM-PTA1-GAL', 'MM-PTA1-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 2, 0020089, NULL, NULL, 'MM-PTA2-GAL', 'MM-PTA2-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 3, 0030089, NULL, NULL, 'CH-PTA1-GAL', 'CH-PTA1-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 4, 0040089, NULL, NULL, 'CH-PTA2-GAL', 'CH-PTA2-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 5, 0050089, NULL, NULL, 'LQ-PTA1-GAL', 'LQ-PTA1-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 6, 0060089, NULL, NULL, 'LQ-PTA2-GAL', 'LQ-PTA2-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 7, 0070089, NULL, NULL, 'COR-PTA1-GAL', 'COR-PTA1-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 8, 0080089, NULL, NULL, 'COR-PTA2-GAL', 'COR-PTA2-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 9, 0090089, NULL, NULL, 'COR-PTA3-GAL', 'COR-PTA3-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 10, 0100089, NULL, NULL, 'COR-PTA4-GAL', 'COR-PTA4-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 11, 0110089, NULL, NULL, 'COR-PTA5-GAL', 'COR-PTA5-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 12, 0120089, NULL, NULL, 'COR-PTA6-GAL', 'COR-PTA6-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 13, 0130089, NULL, NULL, 'STM2-PTA1-GAL', 'STM2-PTA1-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 14, 0140089, NULL, NULL, 'STM2-PTA2-GAL', 'STM2-PTA2-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 15, 0150089, NULL, NULL, 'NG-PTA1-GAL', 'NG-PTA1-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 16, 0160089, NULL, NULL, 'NG-PTA2-GAL', 'NG-PTA2-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 17, 0170089, NULL, NULL, 'CAS-PTA1-GAL', 'CAS-PTA1-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 18, 0180089, NULL, NULL, 'CAS-PTA2-GAL', 'CAS-PTA2-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 19, 0190089, NULL, NULL, 'CAS-PTA3-GAL', 'CAS-PTA3-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, NULL, 20, 0200089, NULL, NULL, 'CAS-PTA4-GAL', 'CAS-PTA4-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(89, 1003, 1, 1, NULL, 'MM-PTA1-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 2, NULL, 'MM-PTA2-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 3, NULL, 'CH-PTA1-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 4, NULL, 'CH-PTA2-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 5, NULL, 'LQ-PTA1-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 6, NULL, 'LQ-PTA2-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 7, NULL, 'COR-PTA1-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 8, NULL, 'COR-PTA2-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 9, NULL, 'COR-PTA3-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 10, NULL, 'COR-PTA4-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 11, NULL, 'COR-PTA5-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 12, NULL, 'COR-PTA6-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 13, NULL, 'STM2-PTA1-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 14, NULL, 'STM2-PTA2-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 15, NULL, 'NG-PTA1-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 16, NULL, 'NG-PTA2-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 17, NULL, 'CAS-PTA1-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 18, NULL, 'CAS-PTA2-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 19, NULL, 'CAS-PTA3-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(89, 1003, 1, 20, NULL, 'CAS-PTA4-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(89, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(89, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
