INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(96, NULL, 1, 1000, NULL, NULL, 'RV-MEG-GR-TUNEL', 'RV-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 2, 1002, NULL, NULL, 'RV-MEG-GR-TSC', 'RV-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 3, 1001, NULL, NULL, 'RV-MEG-GR-TSM', 'RV-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 4, 1007, NULL, NULL, 'MM-MEG-GR-TUNEL', 'MM-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 5, 1009, NULL, NULL, 'MM-MEG-GR-TSC', 'MM-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 6, 1008, NULL, NULL, 'MM-MEG-GR-TSM', 'MM-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 7, 1021, NULL, NULL, 'LQ-MEG-GR-TUNEL', 'LQ-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 8, 1023, NULL, NULL, 'LQ-MEG-GR-TSC', 'LQ-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 9, 1022, NULL, NULL, 'LQ-MEG-GR-TSM', 'LQ-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 10, 1078, NULL, NULL, 'NG-MEG-GR-TUNEL', 'NG-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 11, 1080, NULL, NULL, 'NG-MEG-GR-TSC', 'NG-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 12, 1079, NULL, NULL, 'NG-MEG-GR-TSM', 'NG-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 13, 1018, NULL, NULL, 'STMI-MEG-GR-TUNEL', 'STMI-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 14, 1020, NULL, NULL, 'STMI-MEG-GR-TSC', 'STMI-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 15, 1019, NULL, NULL, 'STMI-MEG-GR-TSM', 'STMI-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 16, 1031, NULL, NULL, 'CH-MEG-GR-TUNEL', 'CH-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 17, 1033, NULL, NULL, 'CH-MEG-GR-TSC', 'CH-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 18, 1032, NULL, NULL, 'CH-MEG-GR-TSM', 'CH-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 19, 1064, NULL, NULL, 'STM2-MEG-GR-TUNEL', 'STM2-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 20, 1066, NULL, NULL, 'STM2-MEG-GR-TSC', 'STM2-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 21, 1065, NULL, NULL, 'STM2-MEG-GR-TSM', 'STM2-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 22, 1053, NULL, NULL, 'COR-MEG-GR-TUNEL', 'COR-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 23, 1055, NULL, NULL, 'COR-MEG-GR-TSC', 'COR-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 24, 1054, NULL, NULL, 'COR-MEG-GR-TSM', 'COR-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 25, 1075, NULL, NULL, 'EST-MEG-GR-TUNEL', 'EST-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 26, 1077, NULL, NULL, 'EST-MEG-GR-TSC', 'EST-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 27, 1076, NULL, NULL, 'EST-MEG-GR-TSM', 'EST-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(96, NULL, 28, 1042, NULL, NULL, 'CAS-MEG-GR-TUNEL', 'CAS-MEG-GR-TUNEL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 29, 1044, NULL, NULL, 'CAS-MEG-GR-TSC', 'CAS-MEG-GR-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, NULL, 30, 1043, NULL, NULL, 'CAS-MEG-GR-TSM', 'CAS-MEG-GR-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(96, 5, 1, 1, NULL, '3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 1, NULL, 'RV-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 2, NULL, '31', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 2, NULL, 'RV-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 3, NULL, '32', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 3, NULL, 'RV-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 4, NULL, '1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 4, NULL, 'MM-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 5, NULL, '11', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 5, NULL, 'MM-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 6, NULL, '12', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 6, NULL, 'MM-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 7, NULL, '2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 7, NULL, 'LQ-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 8, NULL, '21', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 8, NULL, 'LQ-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 9, NULL, '22', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 9, NULL, 'LQ-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 10, NULL, '4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 10, NULL, 'NG-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 11, NULL, '41', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 11, NULL, 'NG-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 12, NULL, '42', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 12, NULL, 'NG-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 13, NULL, '5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 13, NULL, 'STMI-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 14, NULL, '51', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 14, NULL, 'STMI-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 15, NULL, '52', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 15, NULL, 'STMI-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 16, NULL, '6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 16, NULL, 'CH-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 17, NULL, '61', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 17, NULL, 'CH-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 18, NULL, '62', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 18, NULL, 'CH-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 19, NULL, '7', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 19, NULL, 'STM2-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 20, NULL, '71', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 20, NULL, 'STM2-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 21, NULL, '72', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 21, NULL, 'STM2-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 22, NULL, '8', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 22, NULL, 'COR-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 23, NULL, '81', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 23, NULL, 'COR-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 24, NULL, '82', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 24, NULL, 'COR-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 25, NULL, '9', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 25, NULL, 'EST-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 26, NULL, '91', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 26, NULL, 'EST-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 27, NULL, '92', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 27, NULL, 'EST-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 28, NULL, '100', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 28, NULL, 'CAS-MEG-GR-TUNEL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 29, NULL, '101', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 29, NULL, 'CAS-MEG-GR-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(96, 5, 1, 30, NULL, '102', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 1003, 1, 30, NULL, 'CAS-MEG-GR-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(96, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(96, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
