INSERT INTO ui.grids(id, adapter_id, "label", enabled, visible) VALUES
(70, 2, 'LBL_ELEMENT_TYPE_ANALIZADOR_RED', true, true);

INSERT INTO ui.grid_fields(id, grid_id, grid_field_data_type_id, "position", required, parameterized, extended, filtered, "label", label_tooltip, source_field, is_pk, is_epoch_milli, align, needs_translation, grouping_summary, width_px, grid_field_group_operation_id, enabled, visible, adjust, header_vertical, fixed_column, replacement_function, precision_filter) VALUES
--el id lo definimos como: <tipo><numero de fila 4 numeros>
(700001, 70, 1, 1, true, false, false, false, 'LBL_GRID_FIELD_ID', 'LBL_GRID_FIELD_ID', 'id', true, false, null, false, false, 500, NULL, true, false, NULL, NULL, NULL, NULL, NULL),
(700002, 70, 1, 2, true, false, false, true, 'LBL_GRID_FIELD_NAME', 'LBL_GRID_FIELD_NAME', 'alias', false, false, NULL, false, false, 180, NULL, true, true, NULL, NULL, true, NULL, NULL),
(700003, 70, 1, 3, true, false, false, false, 'LBL_GRID_FIELD_DESCRIPTION', 'LBL_GRID_FIELD_DESCRIPTION', 'description', false, false, NULL, false, false, 180, NULL, true, true, NULL, NULL, NULL, NULL, NULL),
(700004, 70, 1, 4, true, true, false, false, NULL, NULL, 'state', false, false, NULL, false, false, 30, NULL, true, true, NULL, NULL, NULL, NULL, NULL),
(700005, 70, 1, 5, true, true, false, true, 'LBL_GRID_FIELD_STATE_LABEL', 'LBL_GRID_FIELD_STATE_LABEL', 'stateLabel', false, false, NULL, true, false, 120, NULL, true, true, NULL, NULL, NULL, NULL, NULL),
(700006, 70, 2, 6, true, false, false, false, 'LBL_CORRIENTE_FASE_A', 'LBL_CORRIENTE_FASE_A', 'ElementTypeParam:70:2:1', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700007, 70, 2, 7, true, false, false, false, 'LBL_CORRIENTE_FASE_B', 'LBL_CORRIENTE_FASE_B', 'ElementTypeParam:70:2:2', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700008, 70, 2, 8, true, false, false, false, 'LBL_CORRIENTE_FASE_C', 'LBL_CORRIENTE_FASE_C', 'ElementTypeParam:70:2:3', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700009, 70, 2, 9, true, false, false, false, 'LBL_CORRIENTE_FASE_NEUTRO', 'LBL_CORRIENTE_FASE_NEUTRO', 'ElementTypeParam:70:2:4', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700010, 70, 2, 10, true, false, false, false, 'LBL_CORRIENTE_FASE_TRIFASICA', 'LBL_CORRIENTE_FASE_TRIFASICA', 'ElementTypeParam:70:2:5', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700011, 70, 2, 11, true, false, false, false, 'LBL_TENSION_FASE_A', 'LBL_TENSION_FASE_A', 'ElementTypeParam:70:2:6', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700012, 70, 2, 12, true, false, false, false, 'LBL_TENSION_FASE_C', 'LBL_TENSION_FASE_C', 'ElementTypeParam:70:2:7', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700013, 70, 2, 13, true, false, false, false, 'LBL_TENSION_FASE_B', 'LBL_TENSION_FASE_B', 'ElementTypeParam:70:2:8', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700014, 70, 2, 14, true, false, false, false, 'LBL_TENSION_FASE_TRIFASICA', 'LBL_TENSION_FASE_TRIFASICA', 'ElementTypeParam:70:2:9', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700015, 70, 2, 15, true, false, false, false, 'LBL_TENSION_FASE_A_B', 'LBL_TENSION_FASE_A_B', 'ElementTypeParam:70:2:10', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700016, 70, 2, 16, true, false, false, false, 'LBL_TENSION_FASE_B_C', 'LBL_TENSION_FASE_B_C', 'ElementTypeParam:70:2:11', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700017, 70, 2, 17, true, false, false, false, 'LBL_TENSION_FASE_C_A', 'LBL_TENSION_FASE_C_A', 'ElementTypeParam:70:2:12', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700018, 70, 2, 18, true, false, false, false, 'LBL_TENSION_PROMEDIO_FASE_NEUTRO', 'LBL_TENSION_PROMEDIO_FASE_NEUTRO', 'ElementTypeParam:70:2:13', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700019, 70, 2, 19, true, false, false, false, 'LBL_POTENCIA_ACTIVA_FASE_A', 'LBL_POTENCIA_ACTIVA_FASE_A', 'ElementTypeParam:70:2:14', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700020, 70, 2, 20, true, false, false, false, 'LBL_POTENCIA_ACTIVA_FASE_B', 'LBL_POTENCIA_ACTIVA_FASE_B', 'ElementTypeParam:70:2:15', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700021, 70, 2, 21, true, false, false, false, 'LBL_POTENCIA_ACTIVA_FASE_C', 'LBL_POTENCIA_ACTIVA_FASE_C', 'ElementTypeParam:70:2:16', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700022, 70, 2, 22, true, false, false, false, 'LBL_POTENCIA_ACTIVA_TOTAL', 'LBL_POTENCIA_ACTIVA_TOTAL', 'ElementTypeParam:70:2:17', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700023, 70, 2, 23, true, false, false, false, 'LBL_POTENCIA_REACTIVA_FASE_A', 'LBL_POTENCIA_REACTIVA_FASE_A', 'ElementTypeParam:70:2:18', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700024, 70, 2, 24, true, false, false, false, 'LBL_POTENCIA_REACTIVA_FASE_B', 'LBL_POTENCIA_REACTIVA_FASE_B', 'ElementTypeParam:70:2:19', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700025, 70, 2, 25, true, false, false, false, 'LBL_POTENCIA_REACTIVA_FASE_C', 'LBL_POTENCIA_REACTIVA_FASE_C', 'ElementTypeParam:70:2:20', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700026, 70, 2, 26, true, false, false, false, 'LBL_POTENCIA_REACTIVA_TOTAL', 'LBL_POTENCIA_REACTIVA_TOTAL', 'ElementTypeParam:70:2:21', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700027, 70, 2, 27, true, false, false, false, 'LBL_POTENCIA_APARENTE_FASE_A', 'LBL_POTENCIA_APARENTE_FASE_A', 'ElementTypeParam:70:2:22', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700028, 70, 2, 28, true, false, false, false, 'LBL_POTENCIA_APARENTE_FASE_B', 'LBL_POTENCIA_APARENTE_FASE_B', 'ElementTypeParam:70:2:23', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700029, 70, 2, 29, true, false, false, false, 'LBL_POTENCIA_APARENTE_FASE_C', 'LBL_POTENCIA_APARENTE_FASE_C', 'ElementTypeParam:70:2:24', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700030, 70, 2, 30, true, false, false, false, 'LBL_POTENCIA_APARENTE_TOTAL', 'LBL_POTENCIA_APARENTE_TOTAL', 'ElementTypeParam:70:2:25', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700031, 70, 3, 31, true, false, false, false, 'LBL_FACTOR_DE_POTENCIA_FASE_A', 'LBL_FACTOR_DE_POTENCIA_FASE_A', 'ElementTypeParam:70:2:26', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700032, 70, 3, 32, true, false, false, false, 'LBL_FACTOR_DE_POTENCIA_FASE_B', 'LBL_FACTOR_DE_POTENCIA_FASE_B', 'ElementTypeParam:70:2:27', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700033, 70, 3, 33, true, false, false, false, 'LBL_FACTOR_DE_POTENCIA_FASE_C', 'LBL_FACTOR_DE_POTENCIA_FASE_C', 'ElementTypeParam:70:2:28', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700034, 70, 3, 34, true, false, false, false, 'LBL_FACTOR_DE_POTENCIA_TRIFASICO', 'LBL_FACTOR_DE_POTENCIA_TRIFASICO', 'ElementTypeParam:70:2:29', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700035, 70, 2, 35, true, false, false, false, 'LBL_FRECUENCIA', 'LBL_FRECUENCIA', 'ElementTypeParam:70:2:30', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700037, 70, 2, 37, true, false, false, false, 'LBL_ENERGIA_ACTIVA_ENTREGADA', 'LBL_ENERGIA_ACTIVA_ENTREGADA', 'ElementTypeParam:70:2:32', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700038, 70, 2, 38, true, false, false, false, 'LBL_ENERGIA_ACTIVA_RECIBIDA', 'LBL_ENERGIA_ACTIVA_RECIBIDA', 'ElementTypeParam:70:2:33', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700039, 70, 2, 39, true, false, false, false, 'LBL_ENERGIA_ACTIVA_ENTREGADA+RECIBIDA', 'LBL_ENERGIA_ACTIVA_ENTREGADA+RECIBIDA', 'ElementTypeParam:70:2:34', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700040, 70, 2, 40, true, false, false, false, 'LBL_ENERGIA_ACTIVA_ENTREGADA-RECIBIDA', 'LBL_ENERGIA_ACTIVA_ENTREGADA-RECIBIDA', 'ElementTypeParam:70:2:35', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700041, 70, 2, 41, true, false, false, false, 'LBL_ENERGIA_REACTIVA_ENTREGADA', 'LBL_ENERGIA_REACTIVA_ENTREGADA', 'ElementTypeParam:70:2:36', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700042, 70, 2, 42, true, false, false, false, 'LBL_ENERGIA_REACTIVA_RECIBIDA', 'LBL_ENERGIA_REACTIVA_RECIBIDA', 'ElementTypeParam:70:2:37', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700043, 70, 2, 43, true, false, false, false, 'LBL_ENERGIA_REACTIVA_ENTREGADA+RECIBIDA', 'LBL_ENERGIA_REACTIVA_ENTREGADA+RECIBIDA', 'ElementTypeParam:70:2:38', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700044, 70, 2, 44, true, false, false, false, 'LBL_ENERGIA_REACTIVA_ENTREGADA-RECIBIDA', 'LBL_ENERGIA_REACTIVA_ENTREGADA-RECIBIDA', 'ElementTypeParam:70:2:39', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700045, 70, 2, 45, true, false, false, false, 'LBL_ENERGIA_APARENTE_ENTREGADA', 'LBL_ENERGIA_APARENTE_ENTREGADA', 'ElementTypeParam:70:2:40', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700046, 70, 2, 46, true, false, false, false, 'LBL_ENERGIA_APARENTE_RECIBIDA', 'LBL_ENERGIA_APARENTE_RECIBIDA', 'ElementTypeParam:70:2:41', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700047, 70, 2, 47, true, false, false, false, 'LBL_ENERGIA_APARENTE_ENTREGADA+RECIBIDA', 'LBL_ENERGIA_APARENTE_ENTREGADA+RECIBIDA', 'ElementTypeParam:70:2:42', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700048, 70, 2, 48, true, false, false, false, 'LBL_ENERGIA_APARENTE_ENTREGADA-RECIBIDA', 'LBL_ENERGIA_APARENTE_ENTREGADA-RECIBIDA', 'ElementTypeParam:70:2:43', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700049, 70, 2, 49, true, false, false, false, 'LBL_ULTIMA_DEMANDA', 'LBL_ULTIMA_DEMANDA', 'ElementTypeParam:70:2:44', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700050, 70, 2, 50, true, false, false, false, 'LBL_DEMANDA_ACTUAL', 'LBL_DEMANDA_ACTUAL', 'ElementTypeParam:70:2:45', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700051, 70, 2, 51, true, false, false, false, 'LBL_DEMANDA_PREVISTA', 'LBL_DEMANDA_PREVISTA', 'ElementTypeParam:70:2:46', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL),
(700052, 70, 2, 52, true, false, false, false, 'LBL_DEMANDA_MAXIMA', 'LBL_DEMANDA_MAXIMA', 'ElementTypeParam:70:2:47', false, false, 'left', false, false, 60, NULL, true, true, NULL, true, NULL, NULL, NULL);

INSERT INTO ui.grid_option_values(grid_id, grid_option_id, value) VALUES
(70, 1, 'true'),
(70, 2, 'true'),
(70, 7, 'true'),
(70, 8, 'true'),
(70, 9, 'false'),
(70, 10, 'true'),
(70, 11, 'true'),
(70, 12, 'true'),
(70, 13, 'true'),
(70, 14, 'false'),
(70, 15, 'false'),
(70, 16, 'img/grid/element_type_70.png'),
(70, 17, 'true'),
(70, 22, '150'),
(70, 25, 'true'),
(70, 26, 'true');

INSERT INTO ui.grid_commands(grid_id, "position", "label", icon, "default", module_action_id, args, view_type_id, multiselect, show_text, item_required) VALUES
(70, 1, 'LBL_CMD_VIEW', 'mdi mdi-eye', true, 101401, null, null, false, false, true),
(70, 2, 'LBL_CMD_SHOW_ALARMS', 'mdi mdi-bell', false, 100501, null, 2, true, true, true),
(70, 3, 'LBL_CMD_SHOW_IN_MAP', 'mdi mdi-map-search', false, 200004, null, null, false, false, true);

INSERT INTO ui.grid_field_icons(grid_field_id, icon, value, show_value, badge_color, avatar, enabled, label_value) VALUES(600004, './img/state/stateUnknown.png', 'ElementTypeState:60:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(700004, './img/state/stateUnknown.png', 'ElementTypeState:70:0', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UNKNOWN'),
(700004, './img/state/stateUp.png', 'ElementTypeState:70:1', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_UP'),
(700004, './img/state/stateDown.png', 'ElementTypeState:70:2', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_DOWN'),
(700004, './img/state/stateAlarm.png', 'ElementTypeState:70:3', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_ALARMS'),
(700004, './img/state/stateMaintenance.png', 'ElementTypeState:70:4', false, false, false, true, 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE');

