[Modbus]
ip = 192.168.88.201
puerto = 5060

[Pressurization_N]
measuresOffset1 = 1
measuresOffset2 = 3
measuresOffset3 = 7
commandsOffset1 = 512
commandsOffset2 = 4
commandsOffset3 = 519
numEquipments = 1
numCommands = 3

[Pressurization_S]
measuresOffset1 = 0
measuresOffset2 = 2
measuresOffset3 = 6
commandsOffset1 = 514
commandsOffset2 = 5
commandsOffset3 = 518
numEquipments = 1
numCommands = 3