
INSERT INTO conf.plan_schedules (plan_schedule_id, plan_id, cron_expression, alias, description, enabled, visible, created_at, updated_at) VALUES

(1, 10001, '0 0 14,20 ? * MON,TUE,WED,THU *', 'CSV - APAGADO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 10001, '0 0 16,22 ? * FRI,SAT,SUN *', 'CSV - APAGADO', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 10002, '0 0 12,18 ? JAN MON,TUE,WED,THU *', 'CSV ENE - ENCENDIDO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 10002, '0 0 12,18 ? JAN FRI,SAT,SUN *', 'CSV ENE - ENCENDIDO ', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 10003, '0 0 12,18 ? FEB MON,TUE,WED,THU *', 'CSV FEB - ENCENDIDO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 10003, '0 0 12,18 ? FEB FRI,SAT,SUN *', 'CSV FEB - ENCENDIDO ', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 10004, '0 0 12,18 ? MAR MON,TUE,WED,THU *', 'CSV MAR - ENCENDIDO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 10004, '0 0 12,18 ? MAR FRI,SAT,SUN *', 'CSV MAR - ENCENDIDO ', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 10005, '0 0 12,18 ? APR MON,TUE,WED,THU *', 'CSV ABR - ENCENDIDO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 10005, '0 0 12,18 ? APR FRI,SAT,SUN *', 'CSV ABR - ENCENDIDO ', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 10006, '0 0 12,18 ? APR MON,TUE,WED,THU *', 'CSV MAY - ENCENDIDO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 10006, '0 0 12,18 ? APR FRI,SAT,SUN *', 'CSV MAY - ENCENDIDO ', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 10007, '0 0 12,18 ? JUN MON,TUE,WED,THU *', 'CSV JUN - ENCENDIDO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 10007, '0 0 12,18 ? JUN FRI,SAT,SUN *', 'CSV JUN - ENCENDIDO ', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100, 10101, '0 0 7 ? * * *', 'Alarmas', 'Envio diario de alarmas', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(101, 10114, '0 0 12,18 ? JUL MON,TUE,WED,THU *', 'CSV JUL - ENCENDIDO', 'L, M, X Y J', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 10114, '0 0 12,18 ? JUL FRI,SAT,SUN *', 'CSV JUL - ENCENDIDO', 'V, S Y D', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
