INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(69, NULL, 1, 0010069, NULL, NULL, 'RM-RFID-001', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 2, 0020069, NULL, NULL, 'RM-RFID-002', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 3, 0030069, NULL, NULL, 'RM-RFID-003', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 4, 0040069, NULL, NULL, 'RM-RFID-004', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 5, 0050069, NULL, NULL, 'RM-RFID-005', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 6, 0060069, NULL, NULL, 'RM-RFID-006', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 7, 0070069, NULL, NULL, 'RM-RFID-007', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 8, 0080069, NULL, NULL, 'RM-RFID-008', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 9, 0090069, NULL, NULL, 'RM-RFID-009', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 10, 0100069, NULL, NULL, 'RM-RFID-010', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 11, 0110069, NULL, NULL, 'RM-RFID-011', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 12, 0120069, NULL, NULL, 'RM-RFID-012', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 13, 0130069, NULL, NULL, 'RM-RFID-013', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 14, 0140069, NULL, NULL, 'RM-RFID-014', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 15, 0150069, NULL, NULL, 'RM-RFID-015', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 16, 0160069, NULL, NULL, 'RM-RFID-016', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 17, 0170069, NULL, NULL, 'RM-RFID-017', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 18, 0180069, NULL, NULL, 'RM-RFID-018', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 19, 0190069, NULL, NULL, 'RM-RFID-019', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 20, 0200069, NULL, NULL, 'RM-RFID-020', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 21, 0210069, NULL, NULL, 'RM-RFID-021', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, NULL, 22, 0220069, NULL, NULL, 'RM-RFID-022', 'Sistema de lectura RFID', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(69, 1003, 1, 1, NULL, 'RM-RFID-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 2, NULL, 'RM-RFID-002', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 3, NULL, 'RM-RFID-003', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 4, NULL, 'RM-RFID-004', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 5, NULL, 'RM-RFID-005', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 6, NULL, 'RM-RFID-006', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 7, NULL, 'RM-RFID-007', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 8, NULL, 'RM-RFID-008', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 9, NULL, 'RM-RFID-009', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 10, NULL, 'RM-RFID-010', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 11, NULL, 'RM-RFID-011', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 12, NULL, 'RM-RFID-012', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 13, NULL, 'RM-RFID-013', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 14, NULL, 'RM-RFID-014', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 15, NULL, 'RM-RFID-015', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 16, NULL, 'RM-RFID-016', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 17, NULL, 'RM-RFID-017', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 18, NULL, 'RM-RFID-018', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 19, NULL, 'RM-RFID-019', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 20, NULL, 'RM-RFID-020', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 21, NULL, 'RM-RFID-021', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(69, 1003, 1, 22, NULL, 'RM-RFID-022', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(69, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(69, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);