INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(11, 1, 1, 0010011, NULL, NULL, 'DESP-SOS-1-SEV', 'DESP-SOS-1-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 2, 0020011, NULL, NULL, 'DESP-SOS-2-SEV', 'DESP-SOS-2-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 3, 0030011, NULL, NULL, 'DESP-SOS-3-SEV', 'DESP-SOS-3-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 4, 0040011, NULL, NULL, 'DESP-SOS-4-SEV', 'DESP-SOS-4-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 5, 0050011, NULL, NULL, 'DESP-SOS-5-SEV', 'DESP-SOS-5-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 6, 0060011, NULL, NULL, 'DESP-SOS-6-SEV', 'DESP-SOS-6-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 7, 0070011, NULL, NULL, 'DESP-SOS-7-SEV', 'DESP-SOS-7-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 8, 0080011, NULL, NULL, 'DESP-SOS-8-SEV', 'DESP-SOS-8-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 9, 0090011, NULL, NULL, 'DESP-SOS-9-SEV', 'DESP-SOS-9-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 10, 0100011, NULL, NULL, 'DESP-SOS-10-SEV', 'DESP-SOS-10-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 11, 0110011, NULL, NULL, 'DESP-SOS-11-SEV', 'DESP-SOS-11-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 12, 0120011, NULL, NULL, 'DESP-SOS-12-SEV', 'DESP-SOS-12-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 13, 0130011, NULL, NULL, 'DESP-SOS-13-SEV', 'DESP-SOS-13-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 14, 0140011, NULL, NULL, 'DESP-SOS-14-SEV', 'DESP-SOS-14-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 15, 0150011, NULL, NULL, 'DESP-SOS-15-SEV', 'DESP-SOS-15-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 16, 0160011, NULL, NULL, 'DESP-SOS-16-SEV', 'DESP-SOS-16-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 17, 0170011, NULL, NULL, 'DESP-SOS-17-SEV', 'DESP-SOS-17-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 18, 0180011, NULL, NULL, 'DESP-SOS-18-SEV', 'DESP-SOS-18-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 19, 0190011, NULL, NULL, 'DESP-SOS-19-SEV', 'DESP-SOS-19-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 20, 0200011, NULL, NULL, 'DESP-SOS-20-SEV', 'DESP-SOS-20-SEV', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 21, 0210011, NULL, NULL, 'DESP-SOS-1-MAD', 'DESP-SOS-1-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 22, 0220011, NULL, NULL, 'DESP-SOS-2-MAD', 'DESP-SOS-2-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 23, 0230011, NULL, NULL, 'DESP-SOS-3-MAD', 'DESP-SOS-3-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 24, 0240011, NULL, NULL, 'DESP-SOS-4-MAD', 'DESP-SOS-4-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 25, 0250011, NULL, NULL, 'DESP-SOS-5-MAD', 'DESP-SOS-5-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 26, 0260011, NULL, NULL, 'DESP-SOS-6-MAD', 'DESP-SOS-6-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 27, 0270011, NULL, NULL, 'DESP-SOS-7-MAD', 'DESP-SOS-7-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 28, 0280011, NULL, NULL, 'DESP-SOS-8-MAD', 'DESP-SOS-8-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 29, 0290011, NULL, NULL, 'DESP-SOS-9-MAD', 'DESP-SOS-9-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 30, 0300011, NULL, NULL, 'DESP-SOS-10-MAD', 'DESP-SOS-10-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 31, 0310011, NULL, NULL, 'DESP-SOS-11-MAD', 'DESP-SOS-11-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 32, 0320011, NULL, NULL, 'DESP-SOS-12-MAD', 'DESP-SOS-12-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 33, 0330011, NULL, NULL, 'DESP-SOS-13-MAD', 'DESP-SOS-13-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 34, 0340011, NULL, NULL, 'DESP-SOS-14-MAD', 'DESP-SOS-14-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 35, 0350011, NULL, NULL, 'DESP-SOS-15-MAD', 'DESP-SOS-15-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 36, 0360011, NULL, NULL, 'DESP-SOS-16-MAD', 'DESP-SOS-16-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 37, 0370011, NULL, NULL, 'DESP-SOS-17-MAD', 'DESP-SOS-17-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 38, 0380011, NULL, NULL, 'DESP-SOS-18-MAD', 'DESP-SOS-18-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 39, 0390011, NULL, NULL, 'DESP-SOS-19-MAD', 'DESP-SOS-19-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 40, 0400011, NULL, NULL, 'DESP-SOS-20-MAD', 'DESP-SOS-20-MAD', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(11, 1003, 1, 1, NULL, 'DESP-SOS-1-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 2, NULL, 'DESP-SOS-2-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 3, NULL, 'DESP-SOS-3-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 4, NULL, 'DESP-SOS-4-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 5, NULL, 'DESP-SOS-5-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 6, NULL, 'DESP-SOS-6-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 7, NULL, 'DESP-SOS-7-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 8, NULL, 'DESP-SOS-8-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 9, NULL, 'DESP-SOS-9-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 10, NULL, 'DESP-SOS-10-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 11, NULL, 'DESP-SOS-11-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 12, NULL, 'DESP-SOS-12-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 13, NULL, 'DESP-SOS-13-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 14, NULL, 'DESP-SOS-14-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 15, NULL, 'DESP-SOS-15-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 16, NULL, 'DESP-SOS-16-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 17, NULL, 'DESP-SOS-17-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 18, NULL, 'DESP-SOS-18-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 19, NULL, 'DESP-SOS-19-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 20, NULL, 'DESP-SOS-20-SEV', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 21, NULL, 'DESP-SOS-1-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 22, NULL, 'DESP-SOS-2-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 23, NULL, 'DESP-SOS-3-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 24, NULL, 'DESP-SOS-4-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 25, NULL, 'DESP-SOS-5-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 26, NULL, 'DESP-SOS-6-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 27, NULL, 'DESP-SOS-7-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 28, NULL, 'DESP-SOS-8-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 29, NULL, 'DESP-SOS-9-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 30, NULL, 'DESP-SOS-10-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 31, NULL, 'DESP-SOS-11-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 32, NULL, 'DESP-SOS-12-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 33, NULL, 'DESP-SOS-13-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 34, NULL, 'DESP-SOS-14-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 35, NULL, 'DESP-SOS-15-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 36, NULL, 'DESP-SOS-16-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 37, NULL, 'DESP-SOS-17-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 38, NULL, 'DESP-SOS-18-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 39, NULL, 'DESP-SOS-19-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 40, NULL, 'DESP-SOS-20-MAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(11, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);