
INSERT INTO ui.vo_entities(id, vo_entity_type_id, enabled, visible) VALUES
('ElementType:1', 'ElementTypeUI', true, true),
('ElementTypeParam:1:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:26', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:27', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:28', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:29', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:30', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:31', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:32', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:33', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:34', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:35', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:36', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:37', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:38', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:39', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:40', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:41', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:42', 'ElementTypeParamUI', true, true),
('ElementTypeParam:1:2:43', 'ElementTypeParamUI', true, true),

('ElementType:2', 'ElementTypeUI', true, true),
('ElementTypeParam:2:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:14', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:16', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:17', 'ElementTypeParamUI', true, true),

('ElementType:10', 'ElementTypeUI', true, true),
('ElementTypeParam:10:1:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:10:1:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:10:1:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:10:1:9', 'ElementTypeParamUI', true, true),

('ElementType:38', 'ElementTypeUI', true, true),
('ElementTypeParam:38:1:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:38:1:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:38:1:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:38:1:9', 'ElementTypeParamUI', true, true),

('ElementType:71', 'ElementTypeUI', true, true),
('ElementTypeParam:71:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:1003', 'ElementTypeParamUI', true, true),

('ElementType:81', 'ElementTypeUI', true, true),
('ElementTypeParam:81:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:1:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:81:2:7', 'ElementTypeParamUI', true, true),

('ElementType:82', 'ElementTypeUI', true, true),
('ElementTypeParam:82:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:82:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:82:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:82:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:82:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:82:1:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:82:2:1', 'ElementTypeParamUI', true, true),

('ElementType:83', 'ElementTypeUI', true, true),
('ElementTypeParam:83:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:83:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:83:1:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:83:1:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:83:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:83:2:1', 'ElementTypeParamUI', true, true),

('ElementSubtype:16:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:19:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:20:71', 'ElementSubtypeUI', true, true),
('ElementSubtype:21:71', 'ElementSubtypeUI', true, true),

('Location:1', 'LocationUI', true, true),
('Location:2', 'LocationUI', true, true),
('Location:3', 'LocationUI', true, true),
('Location:4', 'LocationUI', true, true),

('ElementTypeState:1:0', 'ElementTypeStateUI', true, true),
('ElementTypeState:1:1', 'ElementTypeStateUI', true, true),
('ElementTypeState:1:2', 'ElementTypeStateUI', true, true),
('ElementTypeState:1:3', 'ElementTypeStateUI', true, true),

('ElementTypeState:2:0', 'ElementTypeStateUI', true, true),
('ElementTypeState:2:1', 'ElementTypeStateUI', true, true),
('ElementTypeState:2:2', 'ElementTypeStateUI', true, true),
('ElementTypeState:2:3', 'ElementTypeStateUI', true, true),

('ElementTypeState:10:0', 'ElementTypeStateUI', true, true),
('ElementTypeState:10:1', 'ElementTypeStateUI', true, true),
('ElementTypeState:10:2', 'ElementTypeStateUI', true, true),
('ElementTypeState:10:3', 'ElementTypeStateUI', true, true),

('ElementTypeState:38:0', 'ElementTypeStateUI', true, true),
('ElementTypeState:38:1', 'ElementTypeStateUI', true, true),
('ElementTypeState:38:2', 'ElementTypeStateUI', true, true),
('ElementTypeState:38:3', 'ElementTypeStateUI', true, true),

('ElementTypeState:81:0', 'ElementTypeStateUI', true, true),
('ElementTypeState:81:1', 'ElementTypeStateUI', true, true),
('ElementTypeState:81:2', 'ElementTypeStateUI', true, true),
('ElementTypeState:81:3', 'ElementTypeStateUI', true, true),

('ElementTypeState:82:0', 'ElementTypeStateUI', true, true),
('ElementTypeState:82:1', 'ElementTypeStateUI', true, true),
('ElementTypeState:82:2', 'ElementTypeStateUI', true, true),
('ElementTypeState:82:3', 'ElementTypeStateUI', true, true),

('ElementTypeState:83:0', 'ElementTypeStateUI', true, true),
('ElementTypeState:83:1', 'ElementTypeStateUI', true, true),
('ElementTypeState:83:2', 'ElementTypeStateUI', true, true),
('ElementTypeState:83:3', 'ElementTypeStateUI', true, true),

('CommandElementType:2:71', 'CommandElementTypeUI', true, true),
('CommandElementType:3:71', 'CommandElementTypeUI', true, true);


INSERT INTO ui.vo_entity_values(vo_entity_id, vo_entity_field_id, value) VALUES
('ElementType:1', 1, '1'),
('ElementType:1', 2, 'element_type_1.svg'),
('ElementType:1', 14, 'grid/element_type_01.png'),
('ElementType:1', 23, '101901'),

('ElementType:2', 1, '2'),
('ElementType:2', 2, 'element_type_2.svg'),
('ElementType:2', 14, 'grid/element_type_02.png'),
('ElementType:2', 23, '101901'),

('ElementType:10', 1, '10'),
('ElementType:10', 2, 'element_type_10.svg'),
('ElementType:10', 14, 'grid/element_type_10.png'),

('ElementType:38', 1, '38'),
('ElementType:38', 2, 'element_type_38.svg'),
('ElementType:38', 14, 'grid/element_type_38.png'),

('ElementType:71', 1, '71'),
('ElementType:71', 2, 'graphic_icon/71_vms_dgt.svg'),
('ElementType:71', 14, 'grid/element_type_71.png'),
('ElementType:71', 23, '102601'),
('ElementType:71', 30, '102602'),

('ElementType:81', 1, '81'),
('ElementType:81', 2, 'element_type_81.svg'),
('ElementType:81', 14, 'grid/element_type_81.png'),

('ElementType:82', 1, '82'),
('ElementType:82', 2, 'element_type_82.svg'),
('ElementType:82', 14, 'grid/element_type_82.png'),

('ElementType:83', 1, '83'),
('ElementType:83', 2, 'element_type_83.svg'),
('ElementType:83', 14, 'grid/element_type_83.png'),

('ElementType:10', 23, '102601'),
('ElementType:38', 23, '102601'),
--('ElementType:71', 23, '102601'),

('Location:1', 5, '40.50192872888957'),
('Location:1', 6, '-3.5075150487690823'),
('Location:2', 5, '40.50601573088965'),
('Location:2', 6, '-3.5115705015736878'),
('Location:3', 5, '40.49601573088965'),
('Location:3', 6, '-3.5015705015736878'),

('AlarmLevel:1', 8, 'false'),
('AlarmLevel:1', 9, null),
('AlarmLevel:2', 8, 'false'),
('AlarmLevel:2', 9, null),
('AlarmLevel:3', 8, 'false'),
('AlarmLevel:3', 9, null),
('AlarmLevel:4', 8, 'false'),
('AlarmLevel:4', 9, null),
('AlarmLevel:5', 8, 'false'),
('AlarmLevel:5', 9, null),
('AlarmLevel:6', 8, 'true'),
('AlarmLevel:6', 9, 'alarm.mp3'),

('CommandElementType:2:71', 38, 'DEBUG'),
('CommandElementType:3:71', 38, 'DEBUG');

INSERT INTO ui.vo_entity_hierarchies(parent_id, child_id, "position") VALUES
('Location:4', 'Location:2', 1),
('Location:4', 'Location:3', 2);
