-- 
-- Table: master.element_types
--
INSERT INTO master.element_types(element_type_id, alias, description,label_alias, label_description, initial_element_type_state_id, connected_element_type_state_id, disconnected_element_type_state_id, enabled, visible, created_at, updated_at)
VALUES(9, 'FAN', 'FAN','LBL_ELEMENT_TYPE_FAN', 'LBL_ELEMENT_TYPE_FAN_DESC', 0, 1, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_type_states.FAN
--
INSERT INTO master.element_type_params (element_type_id, param_type_id, element_type_param_id, element_type_param_unit_id, data_type_id, threshold_1, threshold_2, default_value, alias, description, label_alias, label_description, enabled, visible, editable, created_at, updated_at) VALUES
--CONFIG
(9,1,1, NULL,2, NULL, NULL, ' ', 'brand', 'brand', 'LBL_ELEMENT_TYPE_PARAM_BRAND' , 'LBL_ELEMENT_TYPE_PARAM_BRAND_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,1,2, NULL,2, NULL, NULL, ' ', 'model', 'model', 'LBL_ELEMENT_TYPE_PARAM_MODEL' , 'LBL_ELEMENT_TYPE_PARAM_MODEL_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,1,5, 22,1, NULL, NULL, NULL, 'delay_before_start', 'delay before start in seconds', 'LBL_ELEMENT_TYPE_PARAM_DELAY_BEFORE_START_SEC' , 'LBL_ELEMENT_TYPE_PARAM_DELAY_BEFORE_START_SEC_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,1,6, NULL,5, NULL, NULL, NULL, 'flip', 'flip', 'LBL_ELEMENT_TYPE_PARAM_FAN_FLIP' , 'LBL_ELEMENT_TYPE_PARAM_FAN_FLIP_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,1,1003, NULL,2, NULL, NULL, ' ', 'MANGO SESSION_UID', 'MANGO SESSION_UID', 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID' , 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--MEASURE
(9,2,1, NULL,1, NULL, NULL, NULL, 'fan_state', 'state for fan', 'LBL_ELEMENT_TYPE_PARAM_FAN_STATE' , 'LBL_ELEMENT_TYPE_PARAM_FAN_STATE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,2,27,3, NULL, NULL, '', 'fan_vibration', 'fan vibration level', 'LBL_ELEMENT_TYPE_PARAM_FAN_VIBRATION' , 'LBL_ELEMENT_TYPE_PARAM_FAN_VIBRATION_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,3,8,1, NULL, NULL, '', 'front_bearing_temperature', 'front motor bearing temperature', 'LBL_ELEMENT_TYPE_PARAM_FRONT_BEARING_TEMP' , 'LBL_ELEMENT_TYPE_PARAM_FRONT_BEARING_TEMP_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,4,8,1, NULL, NULL, '', 'back_bearing_temperature', 'back motor bearing temperature', 'LBL_ELEMENT_TYPE_PARAM_BACK_BEARING_TEMP' , 'LBL_ELEMENT_TYPE_PARAM_BACK_BEARING_TEMP_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,5, NULL,5, NULL, NULL, '', 'fan_available', 'fan available', 'LBL_ELEMENT_TYPE_PARAM_FAN_AVAILABLE' , 'LBL_ELEMENT_TYPE_PARAM_FAN_AVAILABLE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,6, NULL,5, NULL, NULL, '', 'fan_running', 'fan running', 'LBL_ELEMENT_TYPE_PARAM_FAN_RUNNING' , 'LBL_ELEMENT_TYPE_PARAM_FAN_RUNNING_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,7, NULL,5, NULL, NULL, '', 'local_remote', 'local remote', 'LBL_ELEMENT_TYPE_PARAM_FAN_LOCAL_REMOTE' , 'LBL_ELEMENT_TYPE_PARAM_FAN_LOCAL_REMOTE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,8, 34,1, NULL, NULL, '', 'flow', 'flow', 'LBL_ELEMENT_TYPE_PARAM_FLOW' , 'LBL_ELEMENT_TYPE_PARAM_FLOW_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,9, 3,1, NULL, NULL, '', 'electrical_consumption', 'electrical consumption', 'LBL_ELEMENT_TYPE_PARAM_ELECTRICAL_CONSUMPTION' , 'LBL_ELEMENT_TYPE_PARAM_ELECTRICAL_CONSUMPTION_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,10, NULL,5, NULL, NULL, '', 'turning_direction', 'turning direction', 'LBL_ELEMENT_TYPE_PARAM_TURNING_DIRECTION' , 'LBL_ELEMENT_TYPE_PARAM_TURNING_DIRECTION_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,14, 31,1, NULL, NULL, NULL, 'parcial_operating_hours', 'parcial_operating_hours', 'LBL_ELEMENT_TYPE_PARAM_FAN_PARCIAL_OPERATING_HOURS' , 'LBL_ELEMENT_TYPE_PARAM_FAN_PARCIAL_OPERATING_HOURS_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,15, 31,1, NULL, NULL, NULL, 'total_operating_hours', 'total_operating_hours', 'LBL_ELEMENT_TYPE_PARAM_FAN_TOTAL_OPERATING_HOURS' , 'LBL_ELEMENT_TYPE_PARAM_FAN_TOTAL_OPERATING_HOURS_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--
--AXIAL PARAMS
---
(9,2,16, 15,1, NULL, NULL, NULL, 'power', 'power', 'LBL_ELEMENT_TYPE_PARAM_POWER' , 'LBL_ELEMENT_TYPE_PARAM_POWER_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,17, 3,1, NULL, NULL, NULL, 'engine_reference', 'engine_reference', 'LBL_ELEMENT_TYPE_PARAM_ENGINE_REFERENCE' , 'LBL_ELEMENT_TYPE_PARAM_ENGINE_REFERENCE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,18, 3,1, NULL, NULL, NULL, 'engine_speed', 'engine_speed', 'LBL_ELEMENT_TYPE_PARAM_ENGINE_SPEED' , 'LBL_ELEMENT_TYPE_PARAM_ENGINE_SPEED_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,19, 32,1, NULL, NULL, NULL, 'engine_speed_rpm', 'engine_speed_rpm', 'LBL_ELEMENT_TYPE_PARAM_ENGINE_SPEED_RPM' , 'LBL_ELEMENT_TYPE_PARAM_ENGINE_SPEED_RPM_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,20, NULL,5, NULL, NULL, '', 'axial_direct_order', 'axial_direct_order', 'LBL_ELEMENT_TYPE_PARAM_AXIAL_DIRECT_ORDER' , 'LBL_ELEMENT_TYPE_PARAM_AXIAL_DIRECT_ORDER_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,21, NULL,5, NULL, NULL, '', 'axial_reverse_order', 'axial_reverse_order', 'LBL_ELEMENT_TYPE_PARAM_AXIAL_REVERSE_ORDER' , 'LBL_ELEMENT_TYPE_PARAM_AXIAL_REVERSE_ORDER_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,22, NULL,5, NULL, NULL, '', 'axial_local_mode', 'axial_local', 'LBL_ELEMENT_TYPE_PARAM_AXIAL_LOCAL', 'LBL_ELEMENT_TYPE_PARAM_AXIAL_LOCAL_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,23, NULL,5, NULL, NULL, '', 'axial_remote_mode', 'axial_remote', 'LBL_ELEMENT_TYPE_PARAM_AXIAL_REMOTE' , 'LBL_ELEMENT_TYPE_PARAM_AXIAL_REMOTE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,24, NULL,5, NULL, NULL, '', 'emergency_mode', 'emergency_mode', 'LBL_ELEMENT_TYPE_PARAM_EMERGENCY_MODE' , 'LBL_ELEMENT_TYPE_PARAM_EMERGENCY_MODE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,25, NULL,5, NULL, NULL, '', 'open_damper', 'open_damper', 'LBL_ELEMENT_TYPE_PARAM_OPEN_DAMPER' , 'LBL_ELEMENT_TYPE_PARAM_OPEN_DAMPER_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,26, NULL,5, NULL, NULL, '', 'close_damper', 'close_damper', 'LBL_ELEMENT_TYPE_PARAM_CLOSE_DAMPER' , 'LBL_ELEMENT_TYPE_PARAM_CLOSE_DAMPER_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9,2,27, NULL,1, NULL, NULL, '', 'n_starts', 'n_starts', 'LBL_ELEMENT_TYPE_PARAM_N_STARTS' , 'LBL_ELEMENT_TYPE_PARAM_N_STARTS_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);





--
-- Table: master.element_type_params
--
INSERT INTO master.element_type_states(element_type_id, element_type_state_id, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(9, 0, 'UNKNOWN', 'Unknown state', 'LBL_ELEMENT_TYPE_STATE_UNKNOWN', 'LBL_ELEMENT_TYPE_STATE_UNKNOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 1, 'UP', 'The state of the equipment is: comunicates', 'LBL_ELEMENT_TYPE_STATE_UP', 'LBL_ELEMENT_TYPE_STATE_UP_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 'DOWN', 'The state of the equipment is: out of communication', 'LBL_ELEMENT_TYPE_STATE_DOWN', 'LBL_ELEMENT_TYPE_STATE_DOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 3, 'ALARMS', 'The state of the equipment is: with alarms', 'LBL_ELEMENT_TYPE_STATE_ALARMS', 'LBL_ELEMENT_TYPE_STATE_ALARMS_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 4, 'MAINTENANCE', 'The state of the equipment is: on Maintenance', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_type_state_transitions
--
INSERT INTO master.element_type_state_transitions
(element_type_id, current_element_type_state_id, next_element_type_state_id, enabled, visible, editable, created_at, updated_at) VALUES
(9, 0, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 0, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 1, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 1, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 3, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 3, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.command_element_types
--

INSERT INTO master.command_element_types
(command_element_type_id, element_type_id, alias, description, label_alias, label_description, on_change, enabled, visible, created_at, updated_at) VALUES
--(1, 9, 'FAN STOP', 'FAN STOP', 'LBL_COMMAND_ELEMENT_TYPE_FAN_STOP', null, 'TunnelVentilationSystem/StopFan', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(2, 9, 'FAN START', 'FAN START', 'LBL_COMMAND_ELEMENT_TYPE_FAN_START', null, 'TunnelVentilationSystem/StartFan', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 9, 'FAN START REVERSE', 'FAN START REVERSE', 'LBL_COMMAND_ELEMENT_TYPE_FAN_START_REVERSE', null, 'TunnelVentilationSystem/StartReverseFan', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 9, 'FAN STOP', 'FAN STOP', 'LBL_COMMAND_ELEMENT_TYPE_FAN_STOP', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 'FAN START', 'FAN START', 'LBL_COMMAND_ELEMENT_TYPE_FAN_START', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 9, 'FAN START REVERSE', 'FAN START REVERSE', 'LBL_COMMAND_ELEMENT_TYPE_FAN_START_REVERSE', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(4, 9, 'FAN RESET PARTIAL HOURS', 'FAN RESET PARTIAL HOURS', 'LBL_COMMAND_ELEMENT_TYPE_FAN_RESET_PARTIAL_HOURS', null, 'TunnelVentilationSystem/ResetPartialHoursFan', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(5, 9, 'FAN RESET TOTAL HOURS', 'FAN RESET TOTAL HOURS', 'LBL_COMMAND_ELEMENT_TYPE_FAN_RESET_TOTAL_HOURS', null, 'TunnelVentilationSystem/ResetTotalHoursFan', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(6, 9, 'FAN RESET ALARMS', 'FAN RESET ALARMS', 'LBL_COMMAND_ELEMENT_TYPE_FAN_RESET_ALARMS', null, 'TunnelVentilationSystem/ResetAlarmFan', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
(4, 9, 'FAN RESET PARTIAL HOURS', 'FAN RESET PARTIAL HOURS', 'LBL_COMMAND_ELEMENT_TYPE_FAN_RESET_PARTIAL_HOURS', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 9, 'FAN RESET TOTAL HOURS', 'FAN RESET TOTAL HOURS', 'LBL_COMMAND_ELEMENT_TYPE_FAN_RESET_TOTAL_HOURS', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 9, 'FAN RESET ALARMS', 'FAN RESET ALARMS', 'LBL_COMMAND_ELEMENT_TYPE_FAN_RESET_ALARMS', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 9, 'FAN SPEED REFERENCE', 'FAN SPEED REFERENCE', 'LBL_COMMAND_ELEMENT_TYPE_FAN_SPEED_REFERENCE', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 9, 'FAN RESET STARTS', 'FAN RESET STARTS', 'LBL_COMMAND_ELEMENT_TYPE_FAN_RESET_STARTS', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 9, 'FAN START PERCENT', 'FAN START PERCENT', 'LBL_COMMAND_ELEMENT_TYPE_FAN_START_PERCENT', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 9, 'FAN START REVERSE PERCENT', 'FAN START REVERSE PERCENT', 'LBL_COMMAND_ELEMENT_TYPE_FAN_START_REVERSE_PERCENT', null, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO master.command_element_type_params
(command_element_type_id, element_type_id, command_element_type_param_id, data_type_id, threshold_1, threshold_2, command_element_type_param_unit_id, alias, description, Label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(9, 9, 1, 1, '0', '100', 3, 'FAN_PERCENT', 'Percent', 'LBL_COMMAND_ELEMENT_TYPE_PARAM_FAN_PERCENT', null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 9, 1, 1, '0', '100', 3,  'FAN_PERCENT', 'Percent', 'LBL_COMMAND_ELEMENT_TYPE_PARAM_FAN_REVERSE_PERCENT', null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 
-- Table: master.io_controller_module_type_element_types
--
INSERT INTO master.io_controller_module_type_element_types
(module_type_id, element_type_id, enabled, visible, created_at, updated_at) VALUES
(1, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: conf.alarm_configs
--
INSERT INTO conf.alarm_configs
(alarm_config_id, alarm_type_id, alarm_level_id, element_type_id, element_id, element_type_state_id, mine, treatment, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(010009, 4, 3, 9, NULL, 3, true, true, 'ALARM SENSOR TEMPERATURE', 'ALARM SENSOR TEMPERATURE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_SENSOR_TEMPERATURE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_SENSOR_TEMPERATURE_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(020009, 4, 3, 9, NULL, 3, true, true, 'ALARM TEMPERATURE MOTOR WINDING', 'ALARM TEMPERATURE MOTOR WINDING', 'LBL_ALARM_CONFIGS_ALARM_TEMPERATURE_MOTOR_WINDING', 'LBL_ALARM_CONFIGS_ALARM_TEMPERATURE_MOTOR_WINDING_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(030009, 4, 3, 9, NULL, NULL, true, true, 'ALARM JETFAN DISCONNECTED', 'ALARM JETFAN DISCONNECTED', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DISCONNECTED', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DISCONNECTED_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(040009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN FAIL', 'ALARM JETFAN FAIL', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_FAIL', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_FAIL_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(050009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN DROP', 'ALARM JETFAN DROP', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DROP', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DROP_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(060009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN SWITCH', 'ALARM JETFAN SWITCH', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_SWITCH', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_SWITCH', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(070009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN GEAR', 'ALARM JETFAN GEAR', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_GEAR', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_GEAR', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(080009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN NO START', 'ALARM JETFAN NO START', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NO_START', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NO_START', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN NO STOP', 'ALARM JETFAN NO STOP', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NO_STOP', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NO_STOP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN DE OUT RANGE', 'ALARM JETFAN DE OUT RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_OUT_RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_OUT_RANGE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN DE BROKEN STRAND', 'ALARM JETFAN DE BROKEN STRAND', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_BROKEN_STRAND', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_BROKEN_STRAND', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN DE ALARM', 'ALARM JETFAN DE ALARM', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_ALARM', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_ALARM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(130009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN DE DETENTION', 'ALARM JETFAN DE DETENTION', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_DETENTION', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_DE_DETENTION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(140009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN NDE OUT RANGE', 'ALARM JETFAN NDE OUT RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_OUT_RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_OUT_RANGE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(150009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN NDE BROKEN STRAND', 'ALARM JETFAN NDE BROKEN STRAND', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_BROKEN_STRAND', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_BROKEN_STRAND', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(160009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN NDE ALARM', 'ALARM JETFAN NDE ALARM', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_ALARM', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_ALARM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(170009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN NDE DETENTION', 'ALARM JETFAN NDE DETENTION', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_DETENTION', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_NDE_DETENTION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(180009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN VIBRATION OUT RANGE', 'ALARM JETFAN VIBRATION OUT RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_OUT_RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_OUT_RANGE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(190009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN VIBRATION BROKEN STRAND', 'ALARM JETFAN VIBRATION BROKEN STRAND', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_BROKEN_STRAND', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_BROKEN_STRAND', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(200009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN VIBRATION ALARM', 'ALARM JETFAN VIBRATION ALARM', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_ALARM', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_ALARM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(210009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN VIBRATION DETENTION', 'ALARM JETFAN VIBRATION DETENTION', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_DETENTION', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_DETENTION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(260009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN LOCAL REMOTE', 'ALARM JETFAN LOCAL REMOTE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_LOCAL_REMOTE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_LOCAL_REMOTE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(270009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN AVAILABLE', 'ALARM JETFAN AVAILABLE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_AVAILABLE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_AVAILABLE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(280009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN VIBRATION SENSOR OUT OF RANGE', 'ALARM JETFAN VIBRATION SENSOR OUT OF RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_SENSOR_OUT_OF_RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_SENSOR_OUT_OF_RANGE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(290009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN FRONT MOTOR BEARING SENSOR OUT OF RANGE', 'ALARM JETFAN FRONT MOTOR BEARING SENSOR OUT OF RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_FRONT_MOTOR_BEARING_OUT_OF_RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_FRONT_MOTOR_BEARING_OUT_OF_RANGE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(300009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN BACK MOTOR BEARING SENSOR OUT OF RANGE', 'ALARM JETFAN BACK MOTOR BEARING SENSOR OUT OF RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_BACK_MOTOR_BEARING_OUT_OF_RANGE', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_BACK_MOTOR_BEARING_OUT_OF_RANGE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10310009, 4, 3, 9, NULL, 3, true, true, 'ALARM JETFAN PTC WINDINGS', 'ALARM JETFAN PTC WINDINGS', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_PTC_WINDINGS', 'LBL_ALARM_CONFIGS_ALARM_JETFAN_PTC_WINDINGS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


(090010, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN PRESENT TRIP', 'ALARM AXIALFAN PRESENT TRIP', 'LBL_ALARM_CONFIGS_ALARM_PRESENT_TRIP', 'LBL_ALARM_CONFIGS_ALARM_PRESENT_TRIP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090011, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN PUSH BUTTON', 'ALARM AXIALFAN PUSH BUTTON', 'LBL_ALARM_CONFIGS_ALARM_PUSH_BUTTON', 'LBL_ALARM_CONFIGS_ALARM_PUSH_BUTTON', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090012, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN VARIATOR FAIL', 'ALARM AXIALFAN VARIATOR FAIL', 'LBL_ALARM_CONFIGS_ALARM_VARIATOR_FAIL', 'LBL_ALARM_CONFIGS_ALARM_VARIATOR_FAIL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090013, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN RUNNING TIMEOUT EXCEEDED', 'ALARM AXIALFAN RUNNING TIMEOUT EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_RUNNING_TIMEOUT_EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_RUNNING_TIMEOUT_EXCEEDED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090014, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN PT100 FRONT BEARING TEMP', 'ALARM AXIALFAN PT100 FRONT BEARING TEMP', 'LBL_ALARM_CONFIGS_ALARM_PT100_FRONT_BEARING_TEMP', 'LBL_ALARM_CONFIGS_ALARM_PT100_FRONT_BEARING_TEMP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090015, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN PT100 REAR BEARING TEMP', 'ALARM AXIALFAN PT100 REAR BEARING TEMP', 'LBL_ALARM_CONFIGS_ALARM_PT100_REAR_BEARING_TEMP', 'LBL_ALARM_CONFIGS_ALARM_PT100_REAR_BEARING_TEMP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090016, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN PTC WINDINGS TEMPERATURE', 'ALARM AXIALFAN PTC WINDINGS TEMPERATURE', 'LBL_ALARM_CONFIGS_ALARM_PTC_WINDINGS_TEMPERATURE', 'LBL_ALARM_CONFIGS_ALARM_PTC_WINDINGS_TEMPERATURE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090017, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ENGINE VIBRATIONS', 'ALARM AXIALFAN ENGINE VIBRATIONS', 'LBL_ALARM_CONFIGS_ALARM_ENGINE_VIBRATIONS', 'LBL_ALARM_CONFIGS_ALARM_ENGINE_VIBRATIONS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090018, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN WARNING ENGINE VIBRATIONS', 'ALARM AXIALFAN WARNING ENGINE VIBRATIONS', 'LBL_ALARM_CONFIGS_ALARM_WARNING_ENGINE_VIBRATIONS', 'LBL_ALARM_CONFIGS_ALARM_WARNING_ENGINE_VIBRATIONS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090019, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ENGINE VIBRATIONS SIGNAL FAIL', 'ALARM AXIALFAN ENGINE VIBRATIONS SIGNAL FAIL', 'LBL_ALARM_CONFIGS_ALARM_ENGINE_VIBRATIONS_SIGNAL_FAIL', 'LBL_ALARM_CONFIGS_ALARM_ENGINE_VIBRATIONS_SIGNAL_FAIL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090020, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN PTC WINDINGS TEMPERATURE TRIP', 'ALARM AXIALFAN PTC WINDINGS TEMPERATURE TRIP', 'LBL_ALARM_CONFIGS_ALARM_PTC_WINDINGS_TEMPERATURE_TRIP', 'LBL_ALARM_CONFIGS_ALARM_PTC_WINDINGS_TEMPERATURE_TRIP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090021, 4, 5, 9, NULL, 3, true, true, 'ALARM AXIALFAN RELAY PHASES DAMPER', 'ALARM AXIALFAN RELAY PHASES DAMPER', 'LBL_ALARM_CONFIGS_ALARM_RELAY_PHASES_DAMPER', 'LBL_ALARM_CONFIGS_ALARM_RELAY_PHASES_DAMPER', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090022, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ACT_1 OPENING TIME EXCEEDED', 'ALARM AXIALFAN ACT_1 OPENING TIME EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_ACT_1_OPENING_TIME_EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_ACT_1_OPENING_TIME_EXCEEDED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090023, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ACT_1 CLOSING TIME EXCEEDED', 'ALARM AXIALFAN ACT_1 CLOSING TIME EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_ACT_1_CLOSING_TIME_EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_ACT_1_CLOSING_TIME_EXCEEDED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090024, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ACT_1 ELECTRIC PROTECTION', 'ALARM AXIALFAN ACT_1 ELECTRIC PROTECTION', 'LBL_ALARM_CONFIGS_ALARM_ACT_1_ELECTRIC_PROTECTION', 'LBL_ALARM_CONFIGS_ALARM_ACT_1_ELECTRIC_PROTECTION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090025, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ACT_2 OPENING TIME EXCEEDED', 'ALARM AXIALFAN RUNNING TIMEOUT EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_ACT_2_OPENING_TIME_EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_ACT_2_OPENING_TIME_EXCEEDED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090026, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ACT_2 CLOSING TIME EXCEEDED', 'ALARM AXIALFAN PT100 FRONT BEARING TEMP', 'LBL_ALARM_CONFIGS_ALARM_ACT_2_CLOSING_TIME_EXCEEDED', 'LBL_ALARM_CONFIGS_ALARM_ACT_2_CLOSING_TIME_EXCEEDED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090027, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN ACT_2 ELECTRIC PROTECTION', 'ALARM AXIALFAN PT100 REAR BEARING TEMP', 'LBL_ALARM_CONFIGS_ALARM_ACT_2_ELECTRIC_PROTECTION', 'LBL_ALARM_CONFIGS_ALARM_ACT_2_ELECTRIC_PROTECTION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090030, 4, 5, 9, NULL, 3, true, true, 'ALARM AXIALFAN WARNING PLC STATE', 'ALARM AXIALFAN WARNING PLC STATE', 'LBL_ALARM_CONFIGS_ALARM_WARNING_PLC_STATE', 'LBL_ALARM_CONFIGS_ALARM_WARNING_PLC_STATE_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090031, 4, 3, 9, NULL, 3, true, true, 'ALARM DAMPER PRESENT TRIP', 'ALARM DAMPER PRESENT TRIP', 'LBL_ALARM_CONFIGS_ALARM_DAMPER_PRESENT_TRIP', 'LBL_ALARM_CONFIGS_ALARM_DAMPER_PRESENT_TRIP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090033, 4, 3, 9, NULL, 3, true, true, 'ALARM GENERAL WARNING PRESENT', 'ALARM GENERAL WARNING PRESENT', 'LBL_ALARM_CONFIGS_ALARM_GENERAL_WARNING_PRESENT', 'LBL_ALARM_CONFIGS_ALARM_GENERAL_WARNING_PRESENT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090034, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN RELAY PHASES', 'ALARM AXIALFAN RELAY PHASES', 'LBL_ALARM_CONFIGS_ALARM_AXIALFAN_RELAY_PHASES', 'LBL_ALARM_CONFIGS_ALARM_AXIALFAN_RELAY_PHASES', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090036, 4, 3, 9, NULL, 3, true, true, 'ALARM WARNING OVERVOLTAGE', 'ALARM WARNING OVERVOLTAGE', 'LBL_ALARM_CONFIGS_ALARM_WARNING_OVERVOLTAGE', 'LBL_ALARM_CONFIGS_ALARM_WARNING_OVERVOLTAGE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(090037, 4, 3, 9, NULL, 3, true, true, 'ALARM AXIALFAN COMUNICATION FAIL', 'ALARM AXIALFAN COMUNICATION FAIL', 'LBL_ALARM_CONFIGS_ALARM_AXIALFAN_COMUNICATION_FAIL', 'LBL_ALARM_CONFIGS_ALARM_AXIALFAN_COMUNICATION_FAIL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

----- Hablar con Antonio si se modifica
(092000, 2, 3, 9, NULL, 3, true, false, 'ALARM SIGNALLING NOT ARRIVED', 'ALARM SIGNALLING NOT ARRIVED', 'LBL_ALARM_CONFIGS_SIGNALLING_NOT_ARRIVED', 'LBL_ALARM_CONFIGS_SIGNALLING_NOT_ARRIVED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);





-- 
-- Table: conf.element_state_alarms
--
INSERT INTO conf.element_state_alarms
(element_type_id, element_type_state_id, alarm_config_id, created_at, updated_at) VALUES
(9, 2, 030009, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

