INSERT INTO conf.plan_nodes (node_id,alias,description,plan_id,management_area_id,enabled,visible) VALUES
	 (1,'Apertura','Apertura',NULL,NULL,true,true),
	 (2,'Cierre','Cierre',NULL,NULL,true,true),
	 (3,'Precaución','Precaución',NULL,NULL,true,true),
	 (8,'Despeñaperros','Despeñaperros',NULL,NULL,true,true),
	 (20,'Visibilidad reducida','Visibilidad reducida',NULL,NULL,true,true),
	 (21,'Despeñaperros','Despeñaperros',NULL,NULL,true,true),
	 (22,'VISIBILIDAD REDUCIDA -> SENTIDO NORTE','VISIBILIDAD REDUCIDA -> SENTIDO NORTE',12,NULL,true,true),
	 (23,'VISIBILIDAD REDUCIDA -> SENTIDO SUR','VISIBILIDAD REDUCIDA -> SENTIDO SUR',13,NULL,true,true),
	 (24,'El Corzo','El Corzo',NULL,NULL,true,true),
	 (32,'El Corzo','El Corzo',NULL,NULL,true,true),
	 (33,'CZ -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE','CZ -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE',20,NULL,true,true),
	 (34,'CZ -> VISIBILIDAD REDUCIDA -> SENTIDO SUR','CZ -> VISIBILIDAD REDUCIDA -> SENTIDO SUR',21,NULL,true,true),
	 (35,'La Cantera','La Cantera',NULL,NULL,true,true),
	 (43,'La Cantera','La Cantera',NULL,NULL,true,true),
	 (44,'CA -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE','CA -> VISIBILIDAD REDUCIDA -> SENTIDO NORTE',28,NULL,true,true),
	 (45,'CA -> VISIBILIDAD REDUCIDA -> SENTIDO SUR','CA -> VISIBILIDAD REDUCIDA -> SENTIDO SUR',29,NULL,true,true),
	 (62,'Corte carril','Corte carril',NULL,NULL,true,true),
	 (63,'General','General',NULL,NULL,true,true),
	 (64,'Precaución 80 Sentido Norte','Precaución 80 Sentido Norte',44,NULL,true,true),
	 (65,'Precaución 60 Sentido Norte','Precaución 60 Sentido Norte',45,NULL,true,true),
	 (66,'General','General',NULL,NULL,true,true),
	 (67,'Cierre Túneles Sentido Norte','Cierre Túneles Sentido Norte',46,NULL,true,true),
	 (68,'General','General',NULL,NULL,true,true),
	 (69,'Apertura Túneles Sentido Norte','Apertura Túneles Sentido Norte',47,NULL,true,true),
	 (70,'General','General',NULL,NULL,true,true),
	 (71,'Corte Carril Derecho Sentido Norte','Corte Carril Derecho Sentido Norte',48,NULL,true,true),
	 (72,'Corte Carriles Derecho + Central Sentido Norte','Corte Carriles Derecho + Central Sentido Norte',49,NULL,true,true),
	 (73,'Corte Carril Izquierdo Sentido Norte','Corte Carril Izquierdo Sentido Norte',50,NULL,true,true),
	 (74,'Corte Carriles Izquierdo + Central Sentido Norte','Corte Carriles Izquierdo + Central Sentido Norte',51,NULL,true,true),
	 (75,'Precaución 80 Sentido Sur','Precaución 80 Sentido Sur',52,NULL,true,true),
	 (76,'Precaución 60 Sentido Sur','Precaución 60 Sentido Sur',53,NULL,true,true),
	 (77,'Cierre Túneles Sentido Sur','Cierre Túneles Sentido Sur',54,NULL,true,true),
	 (78,'Apertura Túneles Sentido Sur','Apertura Túneles Sentido Sur',55,NULL,true,true),
	 (79,'Corte Carril Derecho Sentido Sur','Corte Carril Derecho Sentido Sur',56,NULL,true,true),
	 (80,'Corte Carriles Derecho + Central Sentido Sur','Corte Carriles Derecho + Central Sentido Sur',57,NULL,true,true),
	 (81,'Corte Carril Izquierdo Sentido Sur','Corte Carril Izquierdo Sentido Sur',58,NULL,true,true),
	 (82,'Corte Carriles Izquierdo + Central Sentido Sur','Corte Carriles Izquierdo + Central Sentido Sur',59,NULL,true,true),
	 (83,'Restitución ','Restitución ',NULL,NULL,true,true),
	 (84,'Despeñaperros','Despeñaperros',NULL,NULL,true,true),
	 (85,'DP -> Túnel con normalidad sentido norte','DP -> Túnel con normalidad sentido norte',60,NULL,true,true),
	 (86,'DP -> Túnel con normalidad sentido sur','DP -> Túnel con normalidad sentido sur',61,NULL,true,true),
	 (87,'El Corzo','El Corzo',NULL,NULL,true,true),
	 (88,'CZ -> Túnel con normalidad sentido norte','CZ -> Túnel con normalidad sentido norte',62,NULL,true,true),
	 (89,'CZ -> Túnel con normalidad sentido sur','CZ -> Túnel con normalidad sentido sur',63,NULL,true,true),
	 (90,'La Cantera','La Cantera',NULL,NULL,true,true),
	 (91,'CA -> Túnel con normalidad sentido norte','CA -> Túnel con normalidad sentido norte',64,NULL,true,true),
	 (92,'CA -> Túnel con normalidad sentido sur','CA -> Túnel con normalidad sentido sur',65,NULL,true,true),
	 (10,'DP -> PRECAUCIÓN 80KM/H -> SENTIDO NORTE','DP -> PRECAUCIÓN 80KM/H -> SENTIDO NORTE',6,NULL,true,true),
	 (16,'DP -> PRECAUCION 80KM/H -> SENTIDO SUR','DP -> PRECAUCION 80KM/H -> SENTIDO SUR',9,NULL,true,true),
	 (26,'CZ -> PRECAUCIÓN 80KM/H-> SENTIDO NORTE','CZ -> PRECAUCIÓN 80KM/H-> SENTIDO NORTE',15,NULL,true,true),
	 (28,'CZ -> PRECAUCION 80KM/H -> SENTIDO SUR','CZ -> PRECAUCION 80KM/H -> SENTIDO SUR',17,NULL,true,true),
	 (37,'CA -> PRECAUCIÓN 80KM/H -> SENTIDO NORTE','CA -> PRECAUCIÓN 80KM/H -> SENTIDO NORTE',23,NULL,true,true),
	 (39,'CA -> PRECAUCIÓN 80KM/H -> SENTIDO SUR','CA -> PRECAUCIÓN 80KM/H -> SENTIDO SUR',25,NULL,true,true);
