INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(1, 11, 36, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 37, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 38, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 39, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 40, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 41, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 42, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 43, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 44, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, 45, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
