INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(1, 22, 55, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 56, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 57, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 58, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 59, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 60, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 61, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 62, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 63, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 64, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 65, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 66, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 22, 67, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
