INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(9, 4, 1, 0010009, NULL, NULL, 'VEN-2-01-DP-1', 'VEN-2-01-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 2, 0020009, NULL, NULL, 'VEN-2-02-DP-1', 'VEN-2-02-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 3, 0030009, NULL, NULL, 'VEN-2-03-DP-1', 'VEN-2-03-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 4, 0040009, NULL, NULL, 'VEN-2-04-DP-1', 'VEN-2-04-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 5, 0050009, NULL, NULL, 'VEN-2-05-DP-1', 'VEN-2-05-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 6, 0060009, NULL, NULL, 'VEN-2-06-DP-2', 'VEN-2-06-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 7, 0070009, NULL, NULL, 'VEN-2-07-DP-2', 'VEN-2-07-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 8, 0080009, NULL, NULL, 'VEN-2-08-DP-2', 'VEN-2-08-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 9, 0090009, NULL, NULL, 'VEN-2-09-DP-2', 'VEN-2-09-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 10, 0100009, NULL, NULL, 'VEN-2-10-DP-2', 'VEN-2-10-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 11, 0110009, NULL, NULL, 'VEN-3-01-DP-1', 'VEN-3-01-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 12, 0120009, NULL, NULL, 'VEN-3-02-DP-1', 'VEN-3-02-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 13, 0130009, NULL, NULL, 'VEN-3-03-DP-1', 'VEN-3-03-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 14, 0140009, NULL, NULL, 'VEN-3-04-DP-1', 'VEN-3-04-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 15, 0150009, NULL, NULL, 'VEN-3-05-DP-1', 'VEN-3-05-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 16, 0160009, NULL, NULL, 'VEN-3-06-DP-1', 'VEN-3-06-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 17, 0170009, NULL, NULL, 'VEN-3-07-DP-1', 'VEN-3-07-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 18, 0180009, NULL, NULL, 'VEN-3-08-DP-1', 'VEN-3-08-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 19, 0190009, NULL, NULL, 'VEN-3-09-DP-1', 'VEN-3-09-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 20, 0200009, NULL, NULL, 'VEN-3-10-DP-1', 'VEN-3-10-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 21, 0210009, NULL, NULL, 'VEN-3-11-DP-1', 'VEN-3-11-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 22, 0220009, NULL, NULL, 'VEN-3-12-DP-1', 'VEN-3-12-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 23, 0230009, NULL, NULL, 'VEN-3-13-DP-1', 'VEN-3-13-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 24, 0240009, NULL, NULL, 'VEN-3-14-DP-1', 'VEN-3-14-DP-1', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 25, 0250009, NULL, NULL, 'VEN-3-15-DP-2', 'VEN-3-15-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 26, 0260009, NULL, NULL, 'VEN-3-16-DP-2', 'VEN-3-16-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 27, 0270009, NULL, NULL, 'VEN-3-17-DP-2', 'VEN-3-17-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 28, 0280009, NULL, NULL, 'VEN-3-18-DP-2', 'VEN-3-18-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 29, 0290009, NULL, NULL, 'VEN-3-19-DP-2', 'VEN-3-19-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 30, 0300009, NULL, NULL, 'VEN-3-20-DP-2', 'VEN-3-20-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 31, 0310009, NULL, NULL, 'VEN-3-21-DP-2', 'VEN-3-21-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 32, 0320009, NULL, NULL, 'VEN-3-22-DP-2', 'VEN-3-22-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 33, 0330009, NULL, NULL, 'VEN-3-23-DP-2', 'VEN-3-23-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 34, 0340009, NULL, NULL, 'VEN-3-24-DP-2', 'VEN-3-24-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 35, 0350009, NULL, NULL, 'VEN-3-25-DP-2', 'VEN-3-25-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 36, 0360009, NULL, NULL, 'VEN-3-26-DP-2', 'VEN-3-26-DP-2', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 37, 0370009, NULL, NULL, 'VEN-1-01-CZ', 'VEN-1-01-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 38, 0380009, NULL, NULL, 'VEN-1-02-CZ', 'VEN-1-02-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 39, 0390009, NULL, NULL, 'VEN-1-03-CZ', 'VEN-1-03-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 40, 0400009, NULL, NULL, 'VEN-1-04-CZ', 'VEN-1-04-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 41, 0410009, NULL, NULL, 'VEN-1-05-CZ', 'VEN-1-05-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 42, 0420009, NULL, NULL, 'VEN-1-06-CZ', 'VEN-1-06-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 43, 0430009, NULL, NULL, 'VEN-1-07-CZ', 'VEN-1-07-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 44, 0440009, NULL, NULL, 'VEN-1-08-CZ', 'VEN-1-08-CZ', 'SendAlarmsToVentilation.groovy', 'SendFanStateToVentilation.groovy', 'SendValuesToVentilation.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(9, 1, 1, 1, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 1, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 1, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 1, NULL, 'VEN-2-01-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 2, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 2, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 2, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 2, NULL, 'VEN-2-02-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 3, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 3, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 3, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 3, NULL, 'VEN-2-03-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 4, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 4, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 4, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 4, NULL, 'VEN-2-04-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 5, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 5, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 5, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 5, NULL, 'VEN-2-05-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 6, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 6, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 6, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 6, NULL, 'VEN-2-06-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 7, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 7, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 7, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 7, NULL, 'VEN-2-07-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 8, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 8, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 8, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 8, NULL, 'VEN-2-08-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 9, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 9, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 9, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 9, NULL, 'VEN-2-09-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 10, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 10, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 10, NULL, 'false', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 10, NULL, 'VEN-2-10-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 11, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 11, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 11, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 11, NULL, 'VEN-3-01-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 12, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 12, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 12, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 12, NULL, 'VEN-3-02-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 13, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 13, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 13, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 13, NULL, 'VEN-3-03-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 14, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 14, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 14, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 14, NULL, 'VEN-3-04-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 15, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 15, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 15, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 15, NULL, 'VEN-3-05-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 16, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 16, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 16, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 16, NULL, 'VEN-3-06-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 17, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 17, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 17, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 17, NULL, 'VEN-3-07-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 18, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 18, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 18, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 18, NULL, 'VEN-3-08-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 19, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 19, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 19, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 19, NULL, 'VEN-3-09-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 20, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 20, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 20, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 20, NULL, 'VEN-3-10-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 21, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 21, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 21, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 21, NULL, 'VEN-3-11-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 22, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 22, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 22, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 22, NULL, 'VEN-3-12-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 23, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 23, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 23, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 23, NULL, 'VEN-3-13-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 24, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 24, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 24, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 24, NULL, 'VEN-3-14-DP-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 25, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 25, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 25, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 25, NULL, 'VEN-3-15-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 26, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 26, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 26, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 26, NULL, 'VEN-3-16-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 27, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 27, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 27, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 27, NULL, 'VEN-3-17-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 28, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 28, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 28, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 28, NULL, 'VEN-3-18-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 29, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 29, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 29, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 29, NULL, 'VEN-3-19-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 30, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 30, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 30, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 30, NULL, 'VEN-3-20-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 31, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 31, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 31, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 31, NULL, 'VEN-3-21-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 32, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 32, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 32, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 32, NULL, 'VEN-3-22-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 33, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 33, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 33, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 33, NULL, 'VEN-3-23-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 34, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 34, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 34, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 34, NULL, 'VEN-3-24-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 35, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 35, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 35, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 35, NULL, 'VEN-3-25-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 36, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 36, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 36, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 36, NULL, 'VEN-3-26-DP-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 37, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 37, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 37, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 37, NULL, 'VEN-1-01-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 38, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 38, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 38, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 38, NULL, 'VEN-1-02-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 39, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 39, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 39, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 39, NULL, 'VEN-1-03-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 40, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 40, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 40, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 40, NULL, 'VEN-1-04-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 41, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 41, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 41, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 41, NULL, 'VEN-1-05-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 42, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 42, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 42, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 42, NULL, 'VEN-1-06-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 43, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 43, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 43, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 43, NULL, 'VEN-1-07-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(9, 1, 1, 44, NULL, 'Zitrón', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 44, NULL, 'JZR 16-55/4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 44, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 1003, 1, 44, NULL, 'VEN-1-08-CZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(9, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 41, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 42, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 43, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(9, 44, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
