[Modbus]
ip = 192.168.88.73
puerto = 502

[EstacionMeteorologica]
initRegister = 0
numEquipments = 8
surfaceTemperature:
	min = 50
	max = 350
relativeHumidity:
	min = 0
	max = 100
airPressure:
	min = 9000
	max = 12000
gustWindDirection:
	min = 0
	max = 360
gustWindSpeed:
	min = 0
	max = 100
precipitationIntensity:
	min = 0
	max = 250
precipitationQuantity:
	min = 0
	max = 250
precipitationType:
	mod = 0,60,70
	
[Ventiladores]
initRegister = 2371
numEquipments = 128
fan_vibration:
	min = 0
	max = 7
front_bearing_temperature:
	min = 20
	max = 50
back_bearing_temperature:
	min = 20
	max = 50
	
[Luxometros]
initRegister = 2769
numEquipments = 64
luminosity:
	min = 50
	max = 120
	
[Luminancimetros]
initRegister = 2882
numEquipments = 64
luminosity:
	min = 300
	max = 10000
luminosity_real:
	min = 300
	max = 10000
multiplier:
	min = 1
	max = 1
	
[ZonasIncendio]
initRegister = 2937
numEquipments = 157
tempMedia:
	min = 150
	max = 300
tempMaxima:
	min = 280
	max = 300
tempMinima:
	min = 150
	max = 170		
	
[AnemInt]
initRegister = 3417
numEquipments = 36
windSpeed:
	min = 0
	max = 300
trafficDirection:
	min = 0
	max = 360
	
[CO]
initRegister = 3497
numEquipments = 71
coConcentration:
	min = 0
	max = 300
	
[NO]
initRegister = 3572
numEquipments = 53
noConcentration:
	min = 0
	max = 39
	
[OPAC]
initRegister = 3632
numEquipments = 53
opacConcentration:
	min = 0
	max = 11
	
[Fotocelulas]
initRegister = 3809
numEquipments = 12
luminosity:
	min = 300
	max = 1000
	
[LocalesTecnicos]
initRegister = 3924
numEquipments = 42
luminosity:
	min = 200
	max = 349
	
[SAI]
initRegister = 5184
numEquipments = 12
bypass:
	min = 0
	max = 1
powerFail:
	min = 0
	max = 1
temperature:
	min = 20
	max = 40
L1:
	min = 220
	max = 230
L2:
	min = 220
	max = 230
L3:
	min = 220
	max = 230
autonomy:
	min = 51
	max = 100

[Veleta]
initRegister = 5273
numEquipments = 8
windSpeed:
	min = 0
	max = 20
windSpeedKmh:
	min = 0
	max = 120
windDirection:
	min = 0
	max = 360

[AnalizadorRed]
initRegister = 5301
numEquipments = 12
corrienteFaseA:
	min = 50
	max = 150
corrienteFaseB:
	min = 50
	max = 150
corrienteFaseC:
	min = 50
	max = 150
corrienteFaseNeutro:
	min = 5
	max = 40
corrienteFaseTrifasica:
	min = 30
	max = 150
tensionFaseA:
	min = 230
	max = 240
tensionFaseB:
	min = 230
	max = 240
tensionFaseC:
	min = 230
	max = 240
tensionFaseTrifasica:
	min = 0
	max = 0
tensionFaseAB:
	min = 410
	max = 430
tensionFaseBC:
	min = 410
	max = 430
tensionFaseCA:
	min = 410
	max = 430
tensionPromedioFaseNeutro:
	min = 230
	max = 250
potenciaActivaFaseA:
	min = 0
	max = 40
potenciaActivaFaseB:
	min = 0
	max = 40
potenciaActivaFaseC:
	min = 0
	max = 40
potenciaActivaTotal:
	min = 5
	max = 100
potenciaReactivaFaseA:
	min = 1
	max = 15
potenciaReactivaFaseB:
	min = 1
	max = 15
potenciaReactivaFaseC:
	min = 1
	max = 15
potenciaReactivaTotal:
	min = 1
	max = 40
potenciaAparenteFaseA:
	min = 1
	max = 40
potenciaAparenteFaseB:
	min = 1
	max = 40
potenciaAparenteFaseC:
	min = 1
	max = 40
potenciaAparenteTotal:
	min = 1
	max = 100
factorDePotenciaFaseA:
	min = 100
	max = 105
factorDePotenciaFaseB:
	min = 100
	max = 105
factorDePotenciaFaseC:
	min = 100
	max = 105
factorDePotenciaTrifasico:
	min = 100
	max = 105
frecuencia:
	min = 50
	max = 50
energiaActivaEntregada:
	min = 32278
	max = 65535
energiaActivaRecibida:
	min = 32278
	max = 65535
energiaActivaEntregadaRecibidaPos:
	min = 32278
	max = 65535
energiaActivaEntregadaRecibidaNeg:
	min = 32278
	max = 65535
energiaReactivaEntregada:
	min = 32278
	max = 65535
energiaReactivaRecibida:
	min = 32278
	max = 65535
energiaReactivaEntregadaRecibidaPos:
	min = 32278
	max = 65535
energiaReactivaEntregadaRecibidaNeg:
	min = 32278
	max = 65535
energiaAparenteEntregada:
	min = 32278
	max = 65535
energiaAparenteRecibida:
	min = 32278
	max = 65535
energiaAparenteEntregadaRecibidaPos:
	min = 32278
	max = 65535
energiaAparenteEntregadaRecibidaNeg:
	min = 32278
	max = 65535
ultimaDemanda:
	min = 1
	max = 100
demandaActual:
	min = 1
	max = 75
demandaPrevista:
	min = 1
	max = 75
demandaMaxima:
	min = 20
	max = 350

[GrupoElectrogeno]
initRegister = 5954
numEquipments = 12
grpCorrienteFase1:
	min = 20
	max = 100
grpCorrienteFase2:
	min = 20
	max = 100
grpCorrienteFase3:
	min = 20
	max = 100
grpFrecuenciaSalida:
	min = 50
	max = 50
grpHorasTotMarcha:
	min = 1
	max = 1000
grpRPMGenerador:
	min = 3200
	max = 3600
grpTensionBateria:
	min = 50
	max = 75
grpTensionSalidaGen:
	min = 210
	max = 240
grpModoOperacionOff:
	min = 0
	max = 0
grpModoOperacionMan:
	min = 0
	max = 0
grpModoOperacionAut:
	min = 1
	max = 1
grpVolGenL1N:
	min = 210
	max = 240
grpVolGenL2N:
	min = 210
	max = 240
grpVolGenL3N:
	min = 210
	max = 240
grpGasLevel:
	min = 20
	max = 350
grpTempRad:
	min = 40
	max = 50
grpKWH:
	min = 250
	max = 350

[Depósito]
initRegister = 6426
numEquipments = 24
tankCapacity:
	min = 80
	max = 100