[Modbus]
ip = 192.168.88.73
puerto = 502

[Barreras]
measuresOffset = 2200
commandsOffset = 8001
numEquipments = 40
numCommands = 1
	
[Ventiladores]
measuresOffset = 2244
commandsOffset = 8050
numEquipments = 128
numCommands = 1

[Semaforos3Grupos]
measuresOffset = 2842
commandsOffset = 8180
numEquipments = 38
numCommands = 1

[Semaforos2Grupos]
measuresOffset = 3895
commandsOffset = 8220
numEquipments = 25
numCommands = 1

[CircuitosIluminacion]
measuresOffset = 6190
commandsOffset = 8250
numEquipments = 220
numCommands = 1