-- 
-- Table: master.element_types
--
INSERT INTO master.element_types(element_type_id, alias, description,label_alias, label_description, initial_element_type_state_id, connected_element_type_state_id, disconnected_element_type_state_id, enabled, visible, created_at, updated_at)
VALUES(3, 'DETECTOR', 'Detector type of equipment','LBL_ELEMENT_TYPE_DETECTOR', 'LBL_ELEMENT_TYPE_DETECTOR_DESC', 0, 1, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--
-- Table: master.element_type_params
--
INSERT INTO master.element_type_params
(element_type_id, param_type_id, element_type_param_id, element_type_param_unit_id, data_type_id, default_value, alias, description, label_alias, label_description, enabled, visible, editable, created_at, updated_at) VALUES
--CONFIG
(3,1,1, NULL,5, null, 'direction', 'direction', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DIRECTION', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DIRECTION_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,1,2, NULL,1, null, 'order', 'number of lane. Current directon from left to right', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_ORDER', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_ORDER_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,1,3, NULL,1, null, 'mask_validation', 'Active traffic data validation rules', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_CLASSIF_SPEED', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_CLASSIF_SPEED_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,1,4, NULL,1, null, 'delay', 'Number of delayed periods', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DELAY', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DELAY_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,1,1003, NULL,2, '', 'MANGO SESSION_UID', 'MANGO SESSION_UID', 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID', 'LBL_ELEMENT_TYPE_PARAM_MANGO_SESSION_UID_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,1,1004, NULL,2, '', 'RTMS ZONE ID', 'RTMS ZONE ID', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_RTMS_ZONE_ID', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_RTMS_ZONE_ID_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--MEASURE
(3,2,1, null,4, null, 'date', 'date', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DATE', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DATE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,2,9,1, null, 'period', 'period of detection', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_PERIOD', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_PERIOD_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,3, NULL,5, null, 'current_direction', 'current_direction', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_CURRENT_DIRECTION', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_CURRENT_DIRECTION_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,4, NULL,1, null, 'n_vehicles', 'total number of vehicles', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_N_VEHICLES', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_N_VEHICLES_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,5,24,1, null, 'intensity', 'vehicles per hour', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_INTENSITY', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_INTENSITY_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,6,3,1, null, 'occupancy', 'occupancy (percent of occupancy),', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_OCCUPANCY', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_OCCUPANCY_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,7, NULL,5, null, 'congestion', 'congestion detection', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_CONGESTION', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_CONGESTION_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,8, NULL,5, null, 'kamikaze', 'kamikaze detection', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_KAMIKAZE', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_KAMIKAZE_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,9,10,1, null, 'speed', 'Average speed', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_AVG_SPEED', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_AVG_SPEED_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,10,1,1, null, 'gap', 'Average distante between bumps', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_GAP', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_GAP_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,11,11,1, null, 'headway', 'Average distante between front bumps', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_HEADWAY', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_HEADWAY_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,12,28,1, null, 'weight', 'Average weight (WIMS),', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_WEIGHT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_WEIGHT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,13, NULL,5, null, 'fail_data', 'fail_data', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_FAIL_DATA', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_FAIL_DATA_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,14, NULL,1, null, 'flow', 'traffic flow', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_FLOW', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_FLOW_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,15, NULL,1, null, 'density', 'density', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DENSITY', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_DENSITY_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,16, NULL,1, null, 'invalid_mask', 'invalid_mask (mask of bits with error codes),', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_INVALID_MASK', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_INVALID_MASK_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,17,1,1, null, 'length', 'Average length', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_LENGTH', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_LENGTH_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3,2,20,11,1, null, 'veh_length_1', 'veh_length_1', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_1', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_1_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,21,11,1, null, 'veh_length_2', 'veh_length_2', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_2', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_2_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,22,11,1, null, 'veh_length_3', 'veh_length_3', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_3', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_3_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,23,11,1, null, 'veh_length_4', 'veh_length_4', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_4', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_4_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,24,11,1, null, 'veh_length_5', 'veh_length_5', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_5', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_5_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,25,11,1, null, 'veh_length_6', 'veh_length_6', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_6', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_6_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,26,11,1, null, 'veh_length_7', 'veh_length_7', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_7', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_7_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,27,11,1, null, 'veh_length_8', 'veh_length_8', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_8', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_8_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,28,11,1, null, 'veh_length_9', 'veh_length_9', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_9', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_9_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,29,11,1, null, 'veh_length_10', 'veh_length_10', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_10', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_10_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,30,11,1, null, 'veh_length_11', 'veh_length_11', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_11', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_11_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,31,11,1, null, 'veh_length_12', 'veh_length_12', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_12', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_12_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,32,11,1, null, 'veh_length_13', 'veh_length_13', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_13', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_13_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,33,11,1, null, 'veh_length_14', 'veh_length_14', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_14', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_14_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,34,11,1, null, 'veh_length_15', 'veh_length_15', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_15', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_15_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,35,11,1, null, 'veh_length_16', 'veh_length_16', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_16', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_16_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3,2,40,37,1, null, 'veh_speed_1', 'veh_speed_1', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_1', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_1_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,41,37,1, null, 'veh_speed_2', 'veh_speed_2', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_2', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_2_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,42,37,1, null, 'veh_speed_3', 'veh_speed_3', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_3', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_3_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,43,37,1, null, 'veh_speed_4', 'veh_speed_4', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_4', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_4_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,44,37,1, null, 'veh_speed_5', 'veh_speed_5', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_5', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_5_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,45,37,1, null, 'veh_speed_6', 'veh_speed_6', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_6', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_6_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,46,37,1, null, 'veh_speed_7', 'veh_speed_7', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_7', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_7_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,47,37,1, null, 'veh_speed_8', 'veh_speed_8', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_8', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_8_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,48,37,1, null, 'veh_speed_9', 'veh_speed_9', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_9', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_9_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,49,37,1, null, 'veh_speed_10', 'veh_speed_10', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_10', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_10_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,50,37,1, null, 'veh_speed_11', 'veh_speed_11', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_11', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_11_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,51,37,1, null, 'veh_speed_12', 'veh_speed_12', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_12', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_12_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,52,37,1, null, 'veh_speed_13', 'veh_speed_13', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_13', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_13_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,53,37,1, null, 'veh_speed_14', 'veh_speed_14', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_14', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_14_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,54,37,1, null, 'veh_speed_15', 'veh_speed_15', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_15', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_15_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,55,37,1, null, 'veh_speed_16', 'veh_speed_16', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_16', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_16_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3,2,60,3,1, null, 'veh_length_1_percent', 'veh_length_1_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_1_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_1_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,61,3,1, null, 'veh_length_2_percent', 'veh_length_2_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_2_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_2_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,62,3,1, null, 'veh_length_3_percent', 'veh_length_3_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_3_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_3_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,63,3,1, null, 'veh_length_4_percent', 'veh_length_4_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_4_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_4_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,64,3,1, null, 'veh_length_5_percent', 'veh_length_5_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_5_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_5_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,65,3,1, null, 'veh_length_6_percent', 'veh_length_6_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_6_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_6_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,66,3,1, null, 'veh_length_7_percent', 'veh_length_7_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_7_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_7_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,67,3,1, null, 'veh_length_8_percent', 'veh_length_8_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_8_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_8_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,68,3,1, null, 'veh_length_9_percent', 'veh_length_9_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_9_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_9_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,69,3,1, null, 'veh_length_10_percent', 'veh_length_10_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_10_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_10_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,70,3,1, null, 'veh_length_11_percent', 'veh_length_11_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_11_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_11_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,71,3,1, null, 'veh_length_12_percent', 'veh_length_12_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_12_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_12_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,72,3,1, null, 'veh_length_13_percent', 'veh_length_13_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_13_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_13_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,73,3,1, null, 'veh_length_14_percent', 'veh_length_14_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_14_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_14_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,74,3,1, null, 'veh_length_15_percent', 'veh_length_15_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_15_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_15_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,75,3,1, null, 'veh_length_16_percent', 'veh_length_16_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_16_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_LENGTH_16_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3,2,80,3,1, null, 'veh_speed_1_percent', 'veh_speed_1_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_1_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_1_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,81,3,1, null, 'veh_speed_2_percent', 'veh_speed_2_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_2_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_2_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,82,3,1, null, 'veh_speed_3_percent', 'veh_speed_3_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_3_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_3_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,83,3,1, null, 'veh_speed_4_percent', 'veh_speed_4_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_4_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_4_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,84,3,1, null, 'veh_speed_5_percent', 'veh_speed_5_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_5_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_5_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,85,3,1, null, 'veh_speed_6_percent', 'veh_speed_6_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_6_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_6_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,86,3,1, null, 'veh_speed_7_percent', 'veh_speed_7_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_7_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_7_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,87,3,1, null, 'veh_speed_8_percent', 'veh_speed_8_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_8_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_8_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,88,3,1, null, 'veh_speed_9_percent', 'veh_speed_9_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_9_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_9_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,89,3,1, null, 'veh_speed_10_percent', 'veh_speed_10_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_10_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_10_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,90,3,1, null, 'veh_speed_11_percent', 'veh_speed_11_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_11_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_11_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,91,3,1, null, 'veh_speed_12_percent', 'veh_speed_12_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_12_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_12_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,92,3,1, null, 'veh_speed_13_percent', 'veh_speed_13_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_13_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_13_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,93,3,1, null, 'veh_speed_14_percent', 'veh_speed_14_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_14_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_14_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,94,3,1, null, 'veh_speed_15_percent', 'veh_speed_15_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_15_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_15_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,95,3,1, null, 'veh_speed_16_percent', 'veh_speed_16_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_16_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_SPEED_16_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3,2,100, NULL,1, null, 'veh_pa_1', 'veh_pa_1', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_1', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_1_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,101, NULL,1, null, 'veh_pa_2', 'veh_pa_2', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_2', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_2_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,102, NULL,1, null, 'veh_pa_3', 'veh_pa_3', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_3', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_3_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,103, NULL,1, null, 'veh_pa_4', 'veh_pa_4', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_4', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_4_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,104, NULL,1, null, 'veh_pa_5', 'veh_pa_5', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_5', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_5_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,105, NULL,1, null, 'veh_pa_6', 'veh_pa_6', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_6', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_6_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,106, NULL,1, null, 'veh_pa_7', 'veh_pa_7', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_7', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_7_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,107, NULL,1, null, 'veh_pa_8', 'veh_pa_8', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_8', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_8_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,108, NULL,1, null, 'veh_pa_9', 'veh_pa_9', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_9', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_9_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,109, NULL,1, null, 'veh_pa_10', 'veh_pa_10', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_10', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_10_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,110, NULL,1, null, 'veh_pa_11', 'veh_pa_11', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_11', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_11_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,111, NULL,1, null, 'veh_pa_12', 'veh_pa_12', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_12', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_12_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,112, NULL,1, null, 'veh_pa_13', 'veh_pa_13', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_13', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_13_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3,2,120,3,1, null, 'veh_pa_1_percent', 'veh_pa_1_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_1_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_1_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,121,3,1, null, 'veh_pa_2_percent', 'veh_pa_2_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_2_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_2_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,122,3,1, null, 'veh_pa_3_percent', 'veh_pa_3_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_3_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_3_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,123,3,1, null, 'veh_pa_4_percent', 'veh_pa_4_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_4_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_4_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,124,3,1, null, 'veh_pa_5_percent', 'veh_pa_5_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_5_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_5_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,125,3,1, null, 'veh_pa_6_percent', 'veh_pa_6_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_6_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_6_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,126,3,1, null, 'veh_pa_7_percent', 'veh_pa_7_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_7_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_7_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,127,3,1, null, 'veh_pa_8_percent', 'veh_pa_8_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_8_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_8_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,128,3,1, null, 'veh_pa_9_percent', 'veh_pa_9_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_9_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_9_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,129,3,1, null, 'veh_pa_10_percent', 'veh_pa_10_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_10_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_10_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,130,3,1, null, 'veh_pa_11_percent', 'veh_pa_11_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_11_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_11_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,131,3,1, null, 'veh_pa_12_percent', 'veh_pa_12_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_12_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_12_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3,2,132,3,1, null, 'veh_pa_13_percent', 'veh_pa_13_percent', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_13_PERCENT', 'LBL_ELEMENT_TYPE_PARAM_DETECTOR_VEH_PA_13_PERCENT_DESC', true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_subtypes
--
INSERT INTO master.element_subtypes(element_subtype_id, element_type_id, alias, description,label_alias, label_description, enabled, visible, created_at, updated_at)
VALUES
(1, 3, 'Det KINEO', 'Detector Kineo', 'LBL_ELEMENT_SUBTYPE_DETECTOR_KINEO', 'LBL_ELEMENT_SUBTYPE_DETECTOR_KINEO_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 'Det REVENGA', 'Detector Revenga', 'LBL_ELEMENT_SUBTYPE_DETECTOR_REVENGA', 'LBL_ELEMENT_SUBTYPE_DETECTOR_REVENGA_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 'Det TFA3D', 'Detector TFA3D', 'LBL_ELEMENT_SUBTYPE_DETECTOR_TFA3D', 'LBL_ELEMENT_SUBTYPE_DETECTOR_TFA3D_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 'Det RTMS', 'Detector RTMS', 'LBL_ELEMENT_SUBTYPE_DETECTOR_RTMS', 'LBL_ELEMENT_SUBTYPE_DETECTOR_RTMS_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_subtype_active_params 
--
INSERT INTO master.element_subtype_active_params
(element_subtype_id, element_type_id, param_type_id, element_type_param_id, enabled, visible, created_at, updated_at)VALUES
--KINEO
(1, 3, 2, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(1, 3, 2, 100, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 101, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 102, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 103, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 104, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 105, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 106, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 107, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 108, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 109, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 110, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 111, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, 2, 112, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--REVENGA
(2, 3, 2, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, 3, 2, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 21, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, 3, 2, 40, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 41, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 42, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, 3, 2, 60, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 61, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, 3, 2, 80, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 81, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, 2, 82, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


--TFA3D
(3, 3, 2, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 7, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 8, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 17, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 100, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 101, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 102, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 103, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 104, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 105, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 106, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 107, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 2, 108, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--rtms
(4, 3, 2, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 2, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 4, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 6, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 9, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 10, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 11, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 13, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 21, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 22, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 40, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 41, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, 2, 42, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_type_states
--
INSERT INTO master.element_type_states(element_type_id, element_type_state_id, alias, description,label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(3, 0, 'UNKNOWN', 'Unknown state','LBL_ELEMENT_TYPE_STATE_UNKNOWN', 'LBL_ELEMENT_TYPE_STATE_UNKNOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 'UP', 'The state of the equipment is: comunicates','LBL_ELEMENT_TYPE_STATE_UP', 'LBL_ELEMENT_TYPE_STATE_UP_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 'DOWN', 'The state of the equipment is: out of communication', 'LBL_ELEMENT_TYPE_STATE_DOWN', 'LBL_ELEMENT_TYPE_STATE_DOWN_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 'ALARMS', 'The state of the equipment is: with alarms','LBL_ELEMENT_TYPE_STATE_ALARMS', 'LBL_ELEMENT_TYPE_STATE_ALARMS_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, 'MAINTENANCE', 'The state of the equipment is: on Maintenance', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE', 'LBL_ELEMENT_TYPE_STATE_MAINTENANCE_DESC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_hierarchies_allowed
--
INSERT INTO master.element_hierarchies_allowed
(parent_element_type_id, child_element_type_id, enabled, visible, created_at, updated_at) VALUES
(97, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.element_type_state_transitions
--
INSERT INTO master.element_type_state_transitions
(element_type_id, current_element_type_state_id, next_element_type_state_id, enabled, visible, editable, created_at, updated_at) VALUES
(3, 3, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 0, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 0, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 2, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 3, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: master.io_controller_module_type_element_types
--
INSERT INTO master.io_controller_module_type_element_types
(module_type_id, element_type_id, enabled, visible, created_at, updated_at) VALUES
(1, 3, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 
-- Table: conf.alarm_configs
--
INSERT INTO conf.alarm_configs
(alarm_config_id, alarm_type_id, alarm_level_id, element_type_id, element_id, element_type_state_id, mine, treatment, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(010004, 2, 4, 3, NULL, NULL, true, true, 'ALARM DETECTOR NO CONNECTION', 'ALARM DETECTOR NO CONNECTION', 'LBL_ALARM_CONFIGS_ALARM_DETECTOR_NO_CONNECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(020004, 2, 4, 3, NULL, 3, true, true, 'ALARM DETECTOR FAIL', 'ALARM DETECTOR FAIL', 'LBL_ALARM_CONFIGS_ALARM_DETECTOR_FAIL', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(030004, 2, 5, 3, NULL, 3, true, true, 'ALARM DETECTOR CONGESTION', 'ALARM DETECTOR CONGESTION', 'LBL_ALARM_CONFIGS_ALARM_DETECTOR_CONGESTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(040004, 2, 5, 3, NULL, 3, true, true, 'ALARM FALLA PIEZO ELECTRICO', 'ALARM FALLA PIEZO ELECTRICO', 'LBL_ALARM_CONFIGS_ALARM_FALLA_PIEZO_ELECTRICO', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(050004, 2, 5, 3, NULL, 3, true, true, 'ALARM FALLA ESPIRA 1', 'ALARM FALLA ESPIRA 1', 'LBL_ALARM_CONFIGS_ALARM_FALLA_ESPIRA_1', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(060004, 2, 5, 3, NULL, 3, true, true, 'ALARM FALLA ESPIRA 2', 'ALARM FALLA ESPIRA 2', 'LBL_ALARM_CONFIGS_ALARM_FALLA_ESPIRA_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- 
-- Table: conf.element_state_alarms
--
INSERT INTO conf.element_state_alarms
(element_type_id, element_type_state_id, alarm_config_id, created_at, updated_at) VALUES
(3, 2, 010004, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
