INSERT INTO ui.modules(id, module_type_id, "name", description, default_view_type_id, default_system_permission_id, js_file, js_method_draw, js_method_callbacks, data_query, wss_topic, enabled, visible, autoload) VALUES
(200, 3, 'MAP', 'MAP', 1,null, 'modules/mapModule.js', 'getView', 'loadData', NULL, NULL, true, true, true),
(1921, 8, 'Selector Tree Incidencias', 'Selector Tree Incidencias', 1, null, 'modules/selectorModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(1922, 8, 'Selector Tree Reportes', 'Selector Tree Reportes', 1, null, 'modules/selectorModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

(6000, 9, 'INCIDENTS - incidents', 'Incidents - incidents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6001, 9, 'INCIDENTS - vehicles', 'Incidents - vehicles', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6002, 9, 'INCIDENTS - participants', 'Incidents - participants', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6003, 9, 'INCIDENTS - closures', 'Incidents - closures', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6004, 9, 'INCIDENTS - event', 'Incidents - event', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6005, 9, 'INCIDENTS - side', 'Incidents - side', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6006, 9, 'INCIDENTS - stretch', 'Incidents - stretch', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6007, 9, 'INCIDENTS - event_type', 'Incidents - event_type', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6008, 9, 'INCIDENTS - collision', 'Incidents - collision', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6009, 9, 'INCIDENTS - object_crash', 'Incidents - object_crash', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6010, 9, 'INCIDENTS - vehicle_crash', 'Incidents - vehicle_crash', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6011, 9, 'INCIDENTS - relative_location', 'Incidents - relative_location', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6012, 9, 'INCIDENTS - vehicle_types', 'Incidents - vehicle_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6013, 9, 'INCIDENTS - vehicle_services', 'Incidents - vehicle_services', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6014, 9, 'INCIDENTS - vehicle_consecuences', 'Incidents - vehicle_consecuences', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6015, 9, 'INCIDENTS - vehicle_manoeuvres', 'Incidents - vehicle_manoeuvres', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6016, 9, 'INCIDENTS - vehicle_brands', 'Incidents - vehicle_brands', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6017, 9, 'INCIDENTS - participant_types', 'Incidents - participant_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6018, 9, 'INCIDENTS - participant_injuries', 'Incidents - participant_injuries', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6019, 9, 'INCIDENTS - participant_nacionalities', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6020, 9, 'INCIDENTS - support_services', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6021, 9, 'INCIDENTS - damages_responsabilities', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6022, 9, 'INCIDENTS - damages_evaluations', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6023, 9, 'INCIDENTS - owner_types', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6024, 9, 'INCIDENTS - support_service_types', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6025, 9, 'INCIDENTS - support_service_subtypes', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6026, 9, 'INCIDENTS - road_conditions', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6027, 9, 'INCIDENTS - road_types', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6028, 9, 'INCIDENTS - road_states', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6029, 9, 'INCIDENTS - weather_states', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6030, 9, 'INCIDENTS - luminosity', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6031, 9, 'INCIDENTS - ligth', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6032, 9, 'INCIDENTS - causes', 'Incidents - participant_nacionalities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

(6050, 9, 'SUMMARY - annual', 'SUMMARY - annual', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6051, 9, 'SUMMARY - month', 'SUMMARY - month', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6052, 9, 'SUMMARY - incidents', 'SUMMARY - incidents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

(6100, 9, 'REPORTS - alarms', 'REPORTS - alarms', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6101, 9, 'REPORTS - states', 'REPORTS - states', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6110, 9, 'REPORTS - PMVs send commands', 'REPORTS - PMVs send commands', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL);

