INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(3, NULL, 33, 0330003, NULL, NULL, 'LQ-SEC-1-DET-1CA-IN', 'LQ-SEC-1-DET-1CA-IN', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, NULL, 34, 0340003, NULL, NULL, 'LQ-SEC-1-DET-2CA-IN', 'LQ-SEC-1-DET-2CA-IN', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, NULL, 35, 0350003, NULL, NULL, 'LQ-SEC-2-DET-3MA-OUT', 'LQ-SEC-2-DET-3MA-OUT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, NULL, 36, 0360003, NULL, NULL, 'LQ-SEC-2-DET-4MA-OUT', 'LQ-SEC-2-DET-4MA-OUT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, NULL, 37, 0370003, NULL, NULL, 'LQ-SEC-1-DET-1MA-IN', 'LQ-SEC-1-DET-1MA-IN', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, NULL, 38, 0380003, NULL, NULL, 'LQ-SEC-1-DET-2MA-IN', 'LQ-SEC-1-DET-2MA-IN', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, NULL, 39, 0390003, NULL, NULL, 'LQ-SEC-2-DET-3CA-OUT', 'LQ-SEC-2-DET-3CA-OUT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, NULL, 40, 0400003, NULL, NULL, 'LQ-SEC-2-DET-4CA-OUT', 'LQ-SEC-2-DET-4CA-OUT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(3, 1, 1, 33, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 33, NULL, '3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 33, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 33, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 33, NULL, 'LQ-SEC-1-DET-1CA-IN', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(3, 1, 1, 34, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 34, NULL, '4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 34, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 34, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 34, NULL, 'LQ-SEC-1-DET-2CA-IN', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(3, 1, 1, 35, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 35, NULL, '1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 35, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 35, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 35, NULL, 'LQ-SEC-2-DET-3MA-OUT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(3, 1, 1, 36, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 36, NULL, '2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 36, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 36, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 36, NULL, 'LQ-SEC-2-DET-4MA-OUT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(3, 1, 1, 37, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 37, NULL, '1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 37, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 37, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 37, NULL, 'LQ-SEC-1-DET-1MA-IN', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(3, 1, 1, 38, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 38, NULL, '2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 38, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 38, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 38, NULL, 'LQ-SEC-1-DET-2MA-IN', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(3, 1, 1, 39, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 39, NULL, '3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 39, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 39, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 39, NULL, 'LQ-SEC-2-DET-3CA-OUT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(3, 1, 1, 40, NULL, 'true', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 2, 1, 40, NULL, '4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 3, 1, 40, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 4, 1, 40, NULL, '0', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 1003, 1, 40, NULL, 'LQ-SEC-2-DET-4CA-OUT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(3, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(3, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);