INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(11, 1, 1, 0010011, NULL, NULL, 'TUN-SOS-1CA', 'TUN-SOS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 2, 0020011, NULL, NULL, 'TUN-SOS-2CA', 'TUN-SOS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 3, 0030011, NULL, NULL, 'TUN-SOS-3CA', 'TUN-SOS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 4, 0040011, NULL, NULL, 'TUN-SOS-4CA', 'TUN-SOS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 5, 0050011, NULL, NULL, 'TUN-SOS-5CA', 'TUN-SOS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 6, 0060011, NULL, NULL, 'TUN-SOSE-1CA', 'TUN-SOSE-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 7, 0070011, NULL, NULL, 'TUN-SOSE-2CA', 'TUN-SOSE-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 8, 0080011, NULL, NULL, 'TUN-SOS-1MA', 'TUN-SOS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 9, 0090011, NULL, NULL, 'TUN-SOS-2MA', 'TUN-SOS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 10, 0100011, NULL, NULL, 'TUN-SOS-3MA', 'TUN-SOS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 11, 0110011, NULL, NULL, 'TUN-SOS-4MA', 'TUN-SOS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 12, 0120011, NULL, NULL, 'TUN-SOSE-1MA', 'TUN-SOSE-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 1, 13, 0130011, NULL, NULL, 'TUN-SOSE-2MA', 'TUN-SOSE-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(11, 1003, 1, 1, NULL, 'TUN-SOS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 2, NULL, 'TUN-SOS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 3, NULL, 'TUN-SOS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 4, NULL, 'TUN-SOS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 5, NULL, 'TUN-SOS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 6, NULL, 'TUN-SOSE-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 7, NULL, 'TUN-SOSE-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 8, NULL, 'TUN-SOS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 9, NULL, 'TUN-SOS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 10, NULL, 'TUN-SOS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 11, NULL, 'TUN-SOS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 12, NULL, 'TUN-SOSE-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(11, 1003, 1, 13, NULL, 'TUN-SOSE-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(11, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(11, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);