INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(15, NULL, 1, 0010015, NULL, NULL, 'LQ-ZI-1CA', 'Boca Cadiz - Zona Incendios 1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 2, 0020015, NULL, NULL, 'LQ-ZI-2CA', 'Boca Cadiz - Zona Incendios 2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 3, 0030015, NULL, NULL, 'LQ-ZI-3CA', 'Boca Cadiz - Zona Incendios 3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 4, 0040015, NULL, NULL, 'LQ-ZI-4CA', 'Boca Cadiz - Zona Incendios 4', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 5, 0050015, NULL, NULL, 'LQ-ZI-5CA', 'Boca Cadiz - Zona Incendios 5', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 6, 0060015, NULL, NULL, 'LQ-ZI-6CA', 'Boca Cadiz - Zona Incendios 6', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 7, 0070015, NULL, NULL, 'LQ-ZI-7CA', 'Boca Cadiz - Zona Incendios 7', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 8, 0080015, NULL, NULL, 'LQ-ZI-8CA', 'Boca Cadiz - Zona Incendios 8', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 9, 0090015, NULL, NULL, 'LQ-ZI-9CA', 'Boca Cadiz - Zona Incendios 9', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 10, 0100015, NULL, NULL, 'LQ-ZI-10CA', 'Boca Cadiz - Zona Incendios 10', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 11, 0110015, NULL, NULL, 'LQ-ZI-11CA', 'Boca Cadiz - Zona Incendios 11', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 12, 0120015, NULL, NULL, 'LQ-ZI-1MA', 'Boca Malaga - Zona Incendios 1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 13, 0130015, NULL, NULL, 'LQ-ZI-2MA', 'Boca Malaga - Zona Incendios 2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 14, 0140015, NULL, NULL, 'LQ-ZI-3MA', 'Boca Malaga - Zona Incendios 3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 15, 0150015, NULL, NULL, 'LQ-ZI-4MA', 'Boca Malaga - Zona Incendios 4', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 16, 0160015, NULL, NULL, 'LQ-ZI-5MA', 'Boca Malaga - Zona Incendios 5', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 17, 0170015, NULL, NULL, 'LQ-ZI-6MA', 'Boca Malaga - Zona Incendios 6', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 18, 0180015, NULL, NULL, 'LQ-ZI-7MA', 'Boca Malaga - Zona Incendios 7', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 19, 0190015, NULL, NULL, 'LQ-ZI-8MA', 'Boca Malaga - Zona Incendios 8', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, NULL, 20, 0200015, NULL, NULL, 'LQ-ZI-9MA', 'Boca Malaga - Zona Incendios 9', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(15, 5, 1, 1, NULL, '147+535', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 1, NULL, '147+535', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 1, NULL, 'LQ-ZI-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 2, NULL, '147+381', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 2, NULL, '147+535', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 2, NULL, 'LQ-ZI-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 3, NULL, '147+226', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 3, NULL, '147+381', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 3, NULL, 'LQ-ZI-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 4, NULL, '147+070', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 4, NULL, '147+226', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 4, NULL, 'LQ-ZI-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 5, NULL, '146+917', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 5, NULL, '147+070', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 5, NULL, 'LQ-ZI-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 6, NULL, '146+763', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 6, NULL, '146+917', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 6, NULL, 'LQ-ZI-6CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 7, NULL, '146+608', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 7, NULL, '146+763', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 7, NULL, 'LQ-ZI-7CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 8, NULL, '147+070', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 8, NULL, '147+226', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 8, NULL, 'LQ-ZI-8CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 9, NULL, '146+917', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 9, NULL, '147+070', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 9, NULL, 'LQ-ZI-9CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 10, NULL, '146+763', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 10, NULL, '146+917', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 10, NULL, 'LQ-ZI-10CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 11, NULL, '146+608', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 11, NULL, '146+763', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 11, NULL, 'LQ-ZI-11CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 12, NULL, '147+561', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 12, NULL, '147+561', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 12, NULL, 'LQ-ZI-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 13, NULL, '146+655', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 13, NULL, '146+506', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 13, NULL, 'LQ-ZI-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 14, NULL, '146+808', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 14, NULL, '146+655', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 14, NULL, 'LQ-ZI-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 15, NULL, '146+961', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 15, NULL, '146+808', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 15, NULL, 'LQ-ZI-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 16, NULL, '147+114', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 16, NULL, '146+961', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 16, NULL, 'LQ-ZI-5MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 17, NULL, '147+267', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 17, NULL, '147+114', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 17, NULL, 'LQ-ZI-6MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 18, NULL, '147+420', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 18, NULL, '147+267', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 18, NULL, 'LQ-ZI-7MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 19, NULL, '147+267', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 19, NULL, '147+114', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 19, NULL, 'LQ-ZI-8MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(15, 5, 1, 20, NULL, '147+420', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 20, NULL, '147+267', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 1003, 1, 20, NULL, 'LQ-ZI-9MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(15, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(15, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);