INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(22, NULL, 1, 0010022, NULL, NULL, 'LQ-VM-1MA', 'LQ-VM-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 2, 0020022, NULL, NULL, 'LQ-VM-2MA', 'LQ-VM-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 3, 0030022, NULL, NULL, 'LQ-VM-3MA', 'LQ-VM-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 4, 0040022, NULL, NULL, 'LQ-VM-5MA', 'LQ-VM-5MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 5, 0050022, NULL, NULL, 'LQ-VC-1MA', 'LQ-VC-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 6, 0060022, NULL, NULL, 'LQ-VM-1CA', 'LQ-VM-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 7, 0070022, NULL, NULL, 'LQ-VM-2CA', 'LQ-VM-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 8, 0080022, NULL, NULL, 'LQ-VM-3CA', 'LQ-VM-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 9, 0090022, NULL, NULL, 'LQ-VM-4CA', 'LQ-VM-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 10, 0100022, NULL, NULL, 'LQ-VM-5CA', 'LQ-VM-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 11, 0110022, NULL, NULL, 'LQ-VM-6CA', 'LQ-VM-6CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 12, 0120022, NULL, NULL, 'LQ-VC-1CA', 'LQ-VC-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 13, 0130022, NULL, NULL, 'LQ-VM-7CA', 'LQ-VM-7CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 14, 0140022, NULL, NULL, 'LQ-VM-6MA', 'LQ-VM-6MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 15, 0150022, NULL, NULL, 'LQ-VM-4MA', 'LQ-VM-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 16, 0160022, NULL, NULL, 'LQ-VC-2MA', 'LQ-VC-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 17, 0170022, NULL, NULL, 'LQ-VC-3MA', 'LQ-VC-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, NULL, 18, 0180022, NULL, NULL, 'LQ-VC-DALJ', 'LQ-VC-DALJ', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(22, 1003, 1, 1, NULL, 'LQ-VM-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 2, NULL, 'LQ-VM-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 3, NULL, 'LQ-VM-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 4, NULL, 'LQ-VM-5MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 5, NULL, 'LQ-VC-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 6, NULL, 'LQ-VM-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 7, NULL, 'LQ-VM-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 8, NULL, 'LQ-VM-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 9, NULL, 'LQ-VM-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 10, NULL, 'LQ-VM-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 11, NULL, 'LQ-VM-6CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 12, NULL, 'LQ-VC-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 13, NULL, 'LQ-VM-7CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 14, NULL, 'LQ-VM-6MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 15, NULL, 'LQ-VM-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 16, NULL, 'LQ-VC-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 17, NULL, 'LQ-VC-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(22, 1003, 1, 18, NULL, 'LQ-VC-DALJ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(22, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(22, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);