INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(26, NULL, 1, 0010026, NULL, NULL, 'LQ-SWS-1CA', 'LQ-SWS-1CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 2, 0020026, NULL, NULL, 'LQ-SWS-2CA', 'LQ-SWS-2CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 3, 0030026, NULL, NULL, 'LQ-SWS-3CA', 'LQ-SWS-3CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 4, 0040026, NULL, NULL, 'LQ-SWS-4CA', 'LQ-SWS-4CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 5, 0050026, NULL, NULL, 'LQ-SWS-5CA', 'LQ-SWS-5CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 6, 0060026, NULL, NULL, 'LQ-SWS-1MA', 'LQ-SWS-1MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 7, 0070026, NULL, NULL, 'LQ-SWS-2MA', 'LQ-SWS-2MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 8, 0080026, NULL, NULL, 'LQ-SWS-3MA', 'LQ-SWS-3MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 9, 0090026, NULL, NULL, 'LQ-SWS-4MA', 'LQ-SWS-4MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 10, 0100026, NULL, NULL, 'LQ-SWG-CA', 'LQ-SWG-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 11, 0110026, NULL, NULL, 'LQ-SWE-CA', 'LQ-SWE-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 12, 0120026, NULL, NULL, 'LQ-SWL', 'LQ-SWL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, NULL, 13, 0130026, NULL, NULL, 'LQ-SWE-MA', 'LQ-SWE-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(26, 1003, 1, 1, NULL, 'LQ-SWS-1CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 2, NULL, 'LQ-SWS-2CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 3, NULL, 'LQ-SWS-3CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 4, NULL, 'LQ-SWS-4CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 5, NULL, 'LQ-SWS-5CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 6, NULL, 'LQ-SWS-1MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 7, NULL, 'LQ-SWS-2MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 8, NULL, 'LQ-SWS-3MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 9, NULL, 'LQ-SWS-4MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 10, NULL, 'LQ-SWG-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 11, NULL, 'LQ-SWE-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 12, NULL, 'LQ-SWL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(26, 1003, 1, 13, NULL, 'LQ-SWE-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(26, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(26, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);