INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(57, NULL, 1, 0010057, NULL, NULL, 'TUN-MAG-CSA-SAI', 'TUN-MAG-CSA-SAI', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 2, 0020057, NULL, NULL, 'TUN-INT-CSA-SAI', 'TUN-INT-CSA-SAI', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 3, 0030057, NULL, NULL, 'TUN-MAGDIF-AA1-SC', 'TUN-MAGDIF-AA1-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 4, 0040057, NULL, NULL, 'TUN-MAGDIF-AA15-SC', 'TUN-MAGDIF-AA15-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 5, 0050057, NULL, NULL, 'TUN-MAGDIF-AA2-SC', 'TUN-MAGDIF-AA2-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 6, 0060057, NULL, NULL, 'TUN-MAGDIF-AA16-SC', 'TUN-MAGDIF-AA16-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 7, 0070057, NULL, NULL, 'TUN-MAGDIF-AA11-SM', 'TUN-MAGDIF-AA11-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 8, 0080057, NULL, NULL, 'TUN-MAGDIF-AA21-SM', 'TUN-MAGDIF-AA21-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 9, 0090057, NULL, NULL, 'TUN-MAGDIF-AA10-SM', 'TUN-MAGDIF-AA10-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 10, 0100057, NULL, NULL, 'TUN-MAGDIF-AA20-SM', 'TUN-MAGDIF-AA20-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 11, 0110057, NULL, NULL, 'TUN-MAGDIF-AE14-SM', 'TUN-MAGDIF-AE14-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 12, 0120057, NULL, NULL, 'TUN-MAGDIF-AE9-SC', 'TUN-MAGDIF-AE9-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 13, 0130057, NULL, NULL, 'TUN-MAGDIF-A29-SC', 'TUN-MAGDIF-A29-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 14, 0140057, NULL, NULL, 'TUN-MAGDIF-A30-SC', 'TUN-MAGDIF-A30-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 15, 0150057, NULL, NULL, 'TUN-MAGDIF-A31-SM', 'TUN-MAGDIF-A31-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 16, 0160057, NULL, NULL, 'TUN-MAGDIF-A32-SM', 'TUN-MAGDIF-A32-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 17, 0170057, NULL, NULL, 'TUN-MAG-CSA-RED', 'TUN-MAG-CSA-RED', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 18, 0180057, NULL, NULL, 'TUN-INT-CSA-RED', 'TUN-INT-CSA-RED', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 19, 0190057, NULL, NULL, 'TUN-MAGDIF-A3-SC', 'TUN-MAGDIF-A3-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 20, 0200057, NULL, NULL, 'TUN-MAGDIF-A5-SC', 'TUN-MAGDIF-A5-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 21, 0210057, NULL, NULL, 'TUN-MAGDIF-A4-SC', 'TUN-MAGDIF-A4-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 22, 0220057, NULL, NULL, 'TUN-MAGDIF-A6-SC', 'TUN-MAGDIF-A6-SC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 23, 0230057, NULL, NULL, 'TUN-MAGDIF-A13-SM', 'TUN-MAGDIF-A13-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 24, 0240057, NULL, NULL, 'TUN-MAGDIF-A23-SM', 'TUN-MAGDIF-A23-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 25, 0250057, NULL, NULL, 'TUN-MAGDIF-A12-SM', 'TUN-MAGDIF-A12-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 26, 0260057, NULL, NULL, 'TUN-MAGDIF-A22-SM', 'TUN-MAGDIF-A22-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 27, 0270057, NULL, NULL, 'TUN-MAGDIF-A33-SM', 'TUN-MAGDIF-A33-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 28, 0280057, NULL, NULL, 'TUN-MAGDIF-A34-SM', 'TUN-MAGDIF-A34-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 29, 0290057, NULL, NULL, 'TUN-MAGDIF-A35-SM', 'TUN-MAGDIF-A35-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 30, 0300057, NULL, NULL, 'TUN-MAGDIF-A36-SM', 'TUN-MAGDIF-A36-SM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 31, 0310057, NULL, NULL, 'TUN-MAG-CGBT', 'TUN-MAG-CGBT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 32, 0320057, NULL, NULL, 'TUN-INT-CGBT-CSA-RED', 'TUN-INT-CGBT-CSA-RED', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 33, 0330057, NULL, NULL, 'TUN-MAG-CGBT-SERV-AUX-GE', 'TUN-MAG-CGBT-SERV-AUX-GE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 34, 0340057, NULL, NULL, 'TUN-INT-CGBT-COM-RED', 'TUN-INT-CGBT-COM-RED', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 35, 0350057, NULL, NULL, 'TUN-INT-CGBT-COM-GRUPO', 'TUN-INT-CGBT-COM-GRUPO', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 36, 0360057, NULL, NULL, 'TUN-INT-CGBT-BAT-COND', 'TUN-INT-CGBT-BAT-COND', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 37, 0370057, NULL, NULL, 'TUN-INT-CGBT-CSV-TSM', 'TUN-INT-CGBT-CSV-TSM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 38, 0380057, NULL, NULL, 'TUN-MAG-GEN-CSSAI', 'TUN-MAG-GEN-CSSAI', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 39, 0390057, NULL, NULL, 'TUN-INT-CS-EDIF-PCI', 'TUN-INT-CS-EDIF-PCI', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 40, 0400057, NULL, NULL, 'TUN-INT-CGBT-CSV-TSC', 'TUN-INT-CGBT-CSV-TSC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 41, 0410057, NULL, NULL, 'TUN-MAG-CGBT-CSEDBT', 'TUN-MAG-CGBT-CSEDBT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 42, 0420057, NULL, NULL, 'TUN-VENT-INT-VF1-CA', 'TUN-VENT-INT-VF1-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 43, 0430057, NULL, NULL, 'TUN-VENT-INT-VF2-CA', 'TUN-VENT-INT-VF2-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 44, 0440057, NULL, NULL, 'TUN-VENT-INT-VF3-CA', 'TUN-VENT-INT-VF3-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 45, 0450057, NULL, NULL, 'TUN-VENT-INT-VF4-CA', 'TUN-VENT-INT-VF4-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 46, 0460057, NULL, NULL, 'TUN-VENT-INT-VF5-CA', 'TUN-VENT-INT-VF5-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 47, 0470057, NULL, NULL, 'TUN-VENT-INT-VF6-CA', 'TUN-VENT-INT-VF6-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 48, 0480057, NULL, NULL, 'TUN-VENT-INT-VF7-CA', 'TUN-VENT-INT-VF7-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 49, 0490057, NULL, NULL, 'TUN-VENT-INT-VF8-CA', 'TUN-VENT-INT-VF8-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 50, 0500057, NULL, NULL, 'TUN-VENT-INT-VF9-CA', 'TUN-VENT-INT-VF9-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 51, 0510057, NULL, NULL, 'TUN-VENT-INT-VF10-CA', 'TUN-VENT-INT-VF10-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 52, 0520057, NULL, NULL, 'TUN-VENT-INT-VF11-CA', 'TUN-VENT-INT-VF11-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 53, 0530057, NULL, NULL, 'TUN-VENT-INT-VF12-CA', 'TUN-VENT-INT-VF12-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 54, 0540057, NULL, NULL, 'TUN-VENT-INT-VF13-CA', 'TUN-VENT-INT-VF13-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 55, 0550057, NULL, NULL, 'TUN-VENT-INT-VF14-CA', 'TUN-VENT-INT-VF14-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 56, 0560057, NULL, NULL, 'TUN-VENT-INT-VF15-CA', 'TUN-VENT-INT-VF15-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 57, 0570057, NULL, NULL, 'TUN-VENT-INT-VF16-CA', 'TUN-VENT-INT-VF16-CA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 58, 0580057, NULL, NULL, 'TUN-MAG-CSV-2', 'TUN-MAG-CSV-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 59, 0590057, NULL, NULL, 'TUN-INT-CSV-2', 'TUN-INT-CSV-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 60, 0600057, NULL, NULL, 'TUN-MAGDIF-RCAL-CV2', 'TUN-MAGDIF-RCAL-CV2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 61, 0610057, NULL, NULL, 'TUN-VENT-INT-VF1-MA', 'TUN-VENT-INT-VF1-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 62, 0620057, NULL, NULL, 'TUN-VENT-INT-VF3-MA', 'TUN-VENT-INT-VF3-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 63, 0630057, NULL, NULL, 'TUN-VENT-INT-VF4-MA', 'TUN-VENT-INT-VF4-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 64, 0640057, NULL, NULL, 'TUN-VENT-INT-VF5-MA', 'TUN-VENT-INT-VF5-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 65, 0650057, NULL, NULL, 'TUN-VENT-INT-VF6-MA', 'TUN-VENT-INT-VF6-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 66, 0660057, NULL, NULL, 'TUN-VENT-INT-VF7-MA', 'TUN-VENT-INT-VF7-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 67, 0670057, NULL, NULL, 'TUN-VENT-INT-VF8-MA', 'TUN-VENT-INT-VF8-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 68, 0680057, NULL, NULL, 'TUN-VENT-INT-VF9-MA', 'TUN-VENT-INT-VF9-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 69, 0690057, NULL, NULL, 'TUN-VENT-INT-VF10-MA', 'TUN-VENT-INT-VF10-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 70, 0700057, NULL, NULL, 'TUN-MAG-CSV-1', 'TUN-MAG-CSV-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 71, 0710057, NULL, NULL, 'TUN-INT-CSV-1', 'TUN-INT-CSV-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 72, 0720057, NULL, NULL, 'TUN-MAGDIF-RCAL-CV1', 'TUN-MAGDIF-RCAL-CV1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 73, 0730057, NULL, NULL, 'TUN-MAG-CSEDBT', 'TUN-MAG-CSEDBT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 74, 0740057, NULL, NULL, 'TUN-MAG-A1-CGBT', 'TUN-MAG-A1-CGBT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 75, 0750057, NULL, NULL, 'TUN-MAG-E1-CGBT', 'TUN-MAG-E1-CGBT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 76, 0760057, NULL, NULL, 'TUN-MAG-F1-CGBT', 'TUN-MAG-F1-CGBT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 77, 0770057, NULL, NULL, 'TUN-MAG-F2-CGBT', 'TUN-MAG-F2-CGBT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 78, 0780057, NULL, NULL, 'TUN-EKOR-RPG-UCT', 'TUN-EKOR-RPG-UCT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 79, 0790057, NULL, NULL, 'TUN-MAG-CGBT-MT', 'TUN-MAG-CGBT-MT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 80, 0800057, NULL, NULL, 'TUN-MAG-CSSAI', 'I.Autom.IV, In=400 A, Ireg=272 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 81, 0810057, NULL, NULL, 'TUN-CIR-CSSAI', 'I.Autom.IV, In=400 A, Ireg=272 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 82, 0820057, NULL, NULL, 'TUN-MAG-CS-ITS1', 'I.Autom.IV, In=40 A, Ireg=272 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 83, 0830057, NULL, NULL, 'TUN-MAG-CSG-GAL', 'I.Autom.IV, In=40 A, Ireg=272 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 84, 0840057, NULL, NULL, 'TUN-MAG-CS-EDIF-ITS', 'I.MAG.II, 16A, I.DIF.II, 25A 30mA, AC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 85, 0850057, NULL, NULL, 'TUN-MAG-A1-EDIF-ITS', 'I.Autom.IV, In=100 A, Ireg=100 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 86, 0860057, NULL, NULL, 'TUN-MAG-E1-EDIF-ITS', 'I.Autom.IV, In=100 A, Ireg=100 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 87, 0870057, NULL, NULL, 'TUN-MAG-F1-EDIF-ITS', 'I.Autom.IV, In=100 A, Ireg=100 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 88, 0880057, NULL, NULL, 'TUN-MAG-F2-EDIF-ITS', 'I.Autom.IV, In=100 A, Ireg=100 A, Rele y Trans., Dif:30 mA+ AC, Curvas B+C+D', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 89, 0890057, NULL, NULL, 'TUN-INT-GEN-EDIF-PCI', 'TUN-INT-GEN-EDIF-PCI', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 90, 0900057, NULL, NULL, 'TUN-MAG-ITS1', 'TUN-MAG-ITS1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 91, 0910057, NULL, NULL, 'TUN-INT-ITS1', 'TUN-INT-ITS1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 92, 0920057, NULL, NULL, 'TUN-MAGDIF-BF10', 'TUN-MAGDIF-BF10', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 93, 0930057, NULL, NULL, 'TUN-MAGDIF-BF11', 'TUN-MAGDIF-BF11', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 94, 0940057, NULL, NULL, 'TUN-MAGDIF-BF13-2', 'TUN-MAGDIF-BF13-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 95, 0950057, NULL, NULL, 'TUN-MAGDIF-BF13-3', 'TUN-MAGDIF-BF13-3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 96, 0960057, NULL, NULL, 'TUN-MAGDIF-BF13-4', 'TUN-MAGDIF-BF13-4', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 97, 0970057, NULL, NULL, 'TUN-MAGDIF-BF13-5', 'TUN-MAGDIF-BF13-5', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 98, 0980057, NULL, NULL, 'TUN-MAGDIF-BF13-6', 'TUN-MAGDIF-BF13-6', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 99, 0990057, NULL, NULL, 'TUN-MAGDIF-BF13-7', 'TUN-MAGDIF-BF13-7', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 100, 1000057, NULL, NULL, 'TUN-MAGDIF-BF13-1', 'TUN-MAGDIF-BF13-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 101, 1010057, NULL, NULL, 'TUN-MAGDIF-BF14-2', 'TUN-MAGDIF-BF14-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 102, 1020057, NULL, NULL, 'TUN-MAGDIF-BF14-3', 'TUN-MAGDIF-BF14-3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 103, 1030057, NULL, NULL, 'TUN-MAGDIF-BF14-4', 'TUN-MAGDIF-BF14-4', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 104, 1040057, NULL, NULL, 'TUN-MAGDIF-BF14-5', 'TUN-MAGDIF-BF14-5', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 105, 1050057, NULL, NULL, 'TUN-MAGDIF-BF15', 'TUN-MAGDIF-BF15', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 106, 1060057, NULL, NULL, 'TUN-MAGDIF-BF16', 'TUN-MAGDIF-BF16', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 107, 1070057, NULL, NULL, 'TUN-MAGDIF-DET1-LAZO', 'TUN-MAGDIF-DET1-LAZO', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 108, 1080057, NULL, NULL, 'TUN-MAGDIF-METEO', 'TUN-MAGDIF-METEO', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 109, 1090057, NULL, NULL, 'TUN-MAGDIF-BF20', 'TUN-MAGDIF-BF20', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 110, 1100057, NULL, NULL, 'TUN-MAGDIF-BF21', 'TUN-MAGDIF-BF21', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 111, 1110057, NULL, NULL, 'TUN-MAGDIF-BF22', 'TUN-MAGDIF-BF22', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 112, 1120057, NULL, NULL, 'TUN-MAGDIF-BF23', 'TUN-MAGDIF-BF23', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 113, 1130057, NULL, NULL, 'TUN-MAGDIF-BF25', 'TUN-MAGDIF-BF25', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 114, 1140057, NULL, NULL, 'TUN-MAGDIF-BF26', 'TUN-MAGDIF-BF26', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 115, 1150057, NULL, NULL, 'TUN-MAGDIF-BF27', 'TUN-MAGDIF-BF27', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 116, 1160057, NULL, NULL, 'TUN-MAGDIF-BF28', 'TUN-MAGDIF-BF28', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 117, 1170057, NULL, NULL, 'TUN-MAGDIF-BF29', 'TUN-MAGDIF-BF29', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 118, 1180057, NULL, NULL, 'TUN-MAGDIF-BF30', 'TUN-MAGDIF-BF30', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 119, 1190057, NULL, NULL, 'TUN-MAGDIF-BF34', 'TUN-MAGDIF-BF34', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 120, 1200057, NULL, NULL, 'TUN-VENT-INT-VF2-MA', 'TUN-VENT-INT-VF2-MA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 121, 1210057, NULL, NULL, 'TUN-MAG-GAL', 'TUN-MAG-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 122, 1220057, NULL, NULL, 'TUN-MAGDIF-GA1-LUM', 'TUN-MAGDIF-GA1-LUM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 123, 1230057, NULL, NULL, 'TUN-MAGDIF-GA2-LUM', 'TUN-MAGDIF-GA2-LUM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 124, 1240057, NULL, NULL, 'TUN-MAGDIF-GE1-LUM', 'TUN-MAGDIF-GE1-LUM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 125, 1250057, NULL, NULL, 'TUN-MAGDIF-GF6-GAL', 'TUN-MAGDIF-GF6-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 126, 1260057, NULL, NULL, 'TUN-MAGDIF-GF9-COMM', 'TUN-MAGDIF-GF9-COMM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 127, 1270057, NULL, NULL, 'TUN-MAGDIF-PRES-GAL', 'TUN-MAGDIF-PRES-GAL', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 128, 1280057, NULL, NULL, 'TUN-INT-CS-EDIF-ITS', 'TUN-INT-CS-EDIF-ITS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 129, 1290057, NULL, NULL, 'TUN-MAGDIF-FIBRA', 'TUN-MAGDIF-FIBRA', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, NULL, 130, 1300057, NULL, NULL, 'TUN-MAGDIF-CGBT-ITS1', 'TUN-MAGDIF-CGBT-ITS1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(57, 1003, 1, 1, NULL, 'TUN-MAG-CSA-SAI', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 2, NULL, 'TUN-INT-CSA-SAI', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 3, NULL, 'TUN-MAGDIF-AA1-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 4, NULL, 'TUN-MAGDIF-AA15-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 5, NULL, 'TUN-MAGDIF-AA2-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 6, NULL, 'TUN-MAGDIF-AA16-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 7, NULL, 'TUN-MAGDIF-AA11-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 8, NULL, 'TUN-MAGDIF-AA21-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 9, NULL, 'TUN-MAGDIF-AA10-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 10, NULL, 'TUN-MAGDIF-AA20-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 11, NULL, 'TUN-MAGDIF-AE14-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 12, NULL, 'TUN-MAGDIF-AE9-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 13, NULL, 'TUN-MAGDIF-A29-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 14, NULL, 'TUN-MAGDIF-A30-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 15, NULL, 'TUN-MAGDIF-A31-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 16, NULL, 'TUN-MAGDIF-A32-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 17, NULL, 'TUN-MAG-CSA-RED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 18, NULL, 'TUN-INT-CSA-RED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 19, NULL, 'TUN-MAGDIF-A3-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 20, NULL, 'TUN-MAGDIF-A5-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 21, NULL, 'TUN-MAGDIF-A4-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 22, NULL, 'TUN-MAGDIF-A6-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 23, NULL, 'TUN-MAGDIF-A13-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 24, NULL, 'TUN-MAGDIF-A23-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 25, NULL, 'TUN-MAGDIF-A12-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 26, NULL, 'TUN-MAGDIF-A22-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 27, NULL, 'TUN-MAGDIF-A33-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 28, NULL, 'TUN-MAGDIF-A34-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 29, NULL, 'TUN-MAGDIF-A35-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 30, NULL, 'TUN-MAGDIF-A36-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 31, NULL, 'TUN-MAG-CGBT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 32, NULL, 'TUN-INT-CGBT-CSA-RED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 33, NULL, 'TUN-MAG-CGBT-SERV-AUX-GE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 34, NULL, 'TUN-INT-CGBT-COM-RED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 35, NULL, 'TUN-INT-CGBT-COM-GRUPO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 36, NULL, 'TUN-INT-CGBT-BAT-COND', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 37, NULL, 'TUN-INT-CGBT-CSV-TSM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 38, NULL, 'TUN-MAG-GEN-CSSAI', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 39, NULL, 'TUN-INT-CS-EDIF-PCI', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 40, NULL, 'TUN-INT-CGBT-CSV-TSC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 41, NULL, 'TUN-MAG-CGBT-CSEDBT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 42, NULL, 'TUN-VENT-INT-VF1-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 43, NULL, 'TUN-VENT-INT-VF2-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 44, NULL, 'TUN-VENT-INT-VF3-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 45, NULL, 'TUN-VENT-INT-VF4-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 46, NULL, 'TUN-VENT-INT-VF5-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 47, NULL, 'TUN-VENT-INT-VF6-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 48, NULL, 'TUN-VENT-INT-VF7-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 49, NULL, 'TUN-VENT-INT-VF8-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 50, NULL, 'TUN-VENT-INT-VF9-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 51, NULL, 'TUN-VENT-INT-VF10-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 52, NULL, 'TUN-VENT-INT-VF11-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 53, NULL, 'TUN-VENT-INT-VF12-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 54, NULL, 'TUN-VENT-INT-VF13-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 55, NULL, 'TUN-VENT-INT-VF14-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 56, NULL, 'TUN-VENT-INT-VF15-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 57, NULL, 'TUN-VENT-INT-VF16-CA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 58, NULL, 'TUN-MAG-CSV-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 59, NULL, 'TUN-INT-CSV-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 60, NULL, 'TUN-MAGDIF-RCA-CV2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 61, NULL, 'TUN-VENT-INT-VF1-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 62, NULL, 'TUN-VENT-INT-VF3-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 63, NULL, 'TUN-VENT-INT-VF4-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 64, NULL, 'TUN-VENT-INT-VF5-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 65, NULL, 'TUN-VENT-INT-VF6-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 66, NULL, 'TUN-VENT-INT-VF7-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 67, NULL, 'TUN-VENT-INT-VF8-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 68, NULL, 'TUN-VENT-INT-VF9-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 69, NULL, 'TUN-VENT-INT-VF10-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 70, NULL, 'TUN-MAG-CSV-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 71, NULL, 'TUN-INT-CSV-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 72, NULL, 'TUN-MAGDIF-RCAL-CV1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 73, NULL, 'TUN-MAG-CSEDBT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 74, NULL, 'TUN-MAG-A1-CGBT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 75, NULL, 'TUN-MAG-E1-CGBT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 76, NULL, 'TUN-MAG-F1-CGBT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 77, NULL, 'TUN-MAG-F2-CGBT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 78, NULL, 'TUN-EKOR-RPG-UCT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 79, NULL, 'TUN-MAG-CGBT-MT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 80, NULL, 'TUN-MAG-CSSAI', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 81, NULL, 'TUN-CIR-CSSAI', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 82, NULL, 'TUN-MAG-CS-ITS1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 83, NULL, 'TUN-MAG-CSG-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 84, NULL, 'TUN-MAG-CS-EDIF-ITS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 85, NULL, 'TUN-MAG-A1-EDIF-ITS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 86, NULL, 'TUN-MAG-E1-EDIF-ITS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 87, NULL, 'TUN-MAG-F1-EDIF-ITS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 88, NULL, 'TUN-MAG-F2-EDIF-ITS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 89, NULL, 'TUN-INT-GEN-EDIF-PCI', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 90, NULL, 'TUN-MAG-ITS1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 91, NULL, 'TUN-INT-ITS1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 92, NULL, 'TUN-MAGDIF-BF10', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 93, NULL, 'TUN-MAGDIF-BF11', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 94, NULL, 'TUN-MAGDIF-BF13-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 95, NULL, 'TUN-MAGDIF-BF13-3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 96, NULL, 'TUN-MAGDIF-BF13-4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 97, NULL, 'TUN-MAGDIF-BF13-5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 98, NULL, 'TUN-MAGDIF-BF13-6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 99, NULL, 'TUN-MAGDIF-BF13-7', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 100, NULL, 'TUN-MAGDIF-BF13-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 101, NULL, 'TUN-MAGDIF-BF14-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 102, NULL, 'TUN-MAGDIF-BF14-3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 103, NULL, 'TUN-MAGDIF-BF14-4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 104, NULL, 'TUN-MAGDIF-BF14-5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 105, NULL, 'TUN-MAGDIF-BF15', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 106, NULL, 'TUN-MAGDIF-BF16', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 107, NULL, 'TUN-MAGDIF-DET1-LAZO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 108, NULL, 'TUN-MAGDIF-METEO', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 109, NULL, 'TUN-MAGDIF-BF20', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 110, NULL, 'TUN-MAGDIF-BF21', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 111, NULL, 'TUN-MAGDIF-BF22', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 112, NULL, 'TUN-MAGDIF-BF23', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 113, NULL, 'TUN-MAGDIF-BF25', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 114, NULL, 'TUN-MAGDIF-BF26', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 115, NULL, 'TUN-MAGDIF-BF27', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 116, NULL, 'TUN-MAGDIF-BF28', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 117, NULL, 'TUN-MAGDIF-BF29', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 118, NULL, 'TUN-MAGDIF-BF30', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 119, NULL, 'TUN-MAGDIF-BF34', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 120, NULL, 'TUN-VENT-INT-VF2-MA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 121, NULL, 'TUN-MAG-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 122, NULL, 'TUN-MAGDIF-GA1-LUM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 123, NULL, 'TUN-MAGDIF-GA2-LUM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 124, NULL, 'TUN-MAGDIF-GE1-LUM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 125, NULL, 'TUN-MAGDIF-GF6-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 126, NULL, 'TUN-MAGDIF-GF9-COMM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 127, NULL, 'TUN-MAGDIF-PRES-GAL', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 128, NULL, 'TUN-INT-CS-EDIF-ITS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 129, NULL, 'TUN-MAGDIF-FIBRA', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(57, 1003, 1, 130, NULL, 'TUN-MAGDIF-CGBT-ITS1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(57, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 41, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 42, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 43, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 44, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 45, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 46, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 47, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 48, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 49, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 50, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 51, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 52, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 53, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 54, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 55, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 56, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 57, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 58, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 59, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 60, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 61, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 62, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 63, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 64, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 65, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 66, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 67, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 68, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 69, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 70, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 71, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 72, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 73, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 74, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 75, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 76, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 77, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 78, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 79, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 80, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 81, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 82, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 83, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 84, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 85, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 86, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 87, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 88, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 89, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 90, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 91, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 92, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 93, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 94, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 95, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 96, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 97, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 98, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 99, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 100, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 101, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 102, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 103, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 104, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 105, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 106, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 107, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 108, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 109, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 110, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 111, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 112, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 113, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 114, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 115, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 116, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 117, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 118, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 119, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 120, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 121, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 122, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 123, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 124, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 125, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 126, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 127, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 128, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 129, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(57, 130, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);