INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(58, NULL, 1, 0010058, NULL, NULL, 'TUN-CT-CGBT-PULS-1', 'TUN-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 2, 0020058, NULL, NULL, 'TUN-CT-ITS-PULS-1', 'TUN-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 3, 0030058, NULL, NULL, 'TUN-CT-PCI-PULS-1', 'TUN-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 4, 0040058, NULL, NULL, 'HOSP-PUL-L1-ORTH', 'HOSP-PUL-L1-ORTH', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 5, 0050058, NULL, NULL, 'HOSP-PUL-L1-REH', 'HOSP-PUL-L1-REH', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 6, 0060058, NULL, NULL, 'HOSP-PUL-L1-VAR', 'HOSP-PUL-L1-VAR', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 7, 0070058, NULL, NULL, 'HOSP-PUL-L1-ENT', 'HOSP-PUL-L1-ENT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 8, 0080058, NULL, NULL, 'HOSP-PUL-L1-SPIC', 'HOSP-PUL-L1-SPIC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 9, 0090058, NULL, NULL, 'HOSP-PUL-L1-CENT', 'HOSP-PUL-L1-CENT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 10, 0100058, NULL, NULL, 'HOSP-PUL-L1-TOW', 'HOSP-PUL-L1-TOW', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 11, 0110058, NULL, NULL, 'HOSP-PUL-L1-HEON', 'HOSP-PUL-L1-HEON', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 12, 0120058, NULL, NULL, 'HOSP-PUL-L1-RHE', 'HOSP-PUL-L1-RHE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 13, 0130058, NULL, NULL, 'HOSP-PUL-L1-END', 'HOSP-PUL-L1-END', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 14, 0140058, NULL, NULL, 'HOSP-PUL-L1-OURE', 'HOSP-PUL-L1-OURE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 15, 0150058, NULL, NULL, 'HOSP-PUL-L1-EME', 'HOSP-PUL-L1-EME', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 16, 0160058, NULL, NULL, 'HOSP-PUL-L1-OUT1', 'HOSP-PUL-L1-OUT1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 17, 0170058, NULL, NULL, 'HOSP-PUL-L1-OUT2', 'HOSP-PUL-L1-OUT2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(58, 1003, 1, 1, NULL, 'TUN-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 2, NULL, 'TUN-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 3, NULL, 'TUN-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 4, NULL, 'HOSP-PUL-L1-ORTH', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 5, NULL, 'HOSP-PUL-L1-REH', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 6, NULL, 'HOSP-PUL-L1-VAR', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 7, NULL, 'HOSP-PUL-L1-ENT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 8, NULL, 'HOSP-PUL-L1-SPIC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 9, NULL, 'HOSP-PUL-L1-CENT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 10, NULL, 'HOSP-PUL-L1-TOW', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 11, NULL, 'HOSP-PUL-L1-HEON', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 12, NULL, 'HOSP-PUL-L1-RHE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 13, NULL, 'HOSP-PUL-L1-END', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 14, NULL, 'HOSP-PUL-L1-OURE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 15, NULL, 'HOSP-PUL-L1-EME', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 16, NULL, 'HOSP-PUL-L1-OUT1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 17, NULL, 'HOSP-PUL-L1-OUT2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(58, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);