INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(59, NULL, 1, 0010059, NULL, NULL, 'TUN-CT-CGBT-HUM-1', 'TUN-CT-CGBT-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 2, 0020059, NULL, NULL, 'TUN-CT-CGBT-HUM-2', 'TUN-CT-CGBT-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 3, 0030059, NULL, NULL, 'TUN-CT-ITS-HUM-1', 'TUN-CT-ITS-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 4, 0040059, NULL, NULL, 'TUN-CT-ITS-HUM-2', 'TUN-CT-ITS-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 5, 0050059, NULL, NULL, 'TUN-CT-PCI-HUM-1', 'TUN-CT-PCI-HUM-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 6, 0060059, NULL, NULL, 'TUN-CT-PCI-HUM-2', 'TUN-CT-PCI-HUM-2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 7, 0070059, NULL, NULL, 'HOSP-HUM-L1-ORTH', 'HOSP-HUM-L1-ORTH', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 8, 0080059, NULL, NULL, 'HOSP-HUM-L1-REH', 'HOSP-HUM-L1-REH', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 9, 0090059, NULL, NULL, 'HOSP-HUM-L1-VAR', 'HOSP-HUM-L1-VAR', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 10, 0100059, NULL, NULL, 'HOSP-HUM-L1-ENT', 'HOSP-HUM-L1-ENT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 11, 0110059, NULL, NULL, 'HOSP-HUM-L1-SPIC', 'HOSP-HUM-L1-SPIC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 12, 0120059, NULL, NULL, 'HOSP-HUM-L1-CENT', 'HOSP-HUM-L1-CENT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 13, 0130059, NULL, NULL, 'HOSP-HUM-L1-TOW', 'HOSP-HUM-L1-TOW', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 14, 0140059, NULL, NULL, 'HOSP-HUM-L1-HEON', 'HOSP-HUM-L1-HEON', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 15, 0150059, NULL, NULL, 'HOSP-HUM-L1-RHE', 'HOSP-HUM-L1-RHE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 16, 0160059, NULL, NULL, 'HOSP-HUM-L1-END', 'HOSP-HUM-L1-END', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 17, 0170059, NULL, NULL, 'HOSP-HUM-L1-OURE', 'HOSP-HUM-L1-OURE', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 18, 0180059, NULL, NULL, 'HOSP-HUM-L1-EME', 'HOSP-HUM-L1-EME', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 19, 0190059, NULL, NULL, 'HOSP-HUM-L1-OUT1', 'HOSP-HUM-L1-OUT1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 20, 0200059, NULL, NULL, 'HOSP-HUM-L1-OUT2', 'HOSP-HUM-L1-OUT2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 21, 0210059, NULL, NULL, 'HOSP-HUM-L2-VAR', 'HOSP-HUM-L2-VAR', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 22, 0220059, NULL, NULL, 'HOSP-HUM-L2-MIN', 'HOSP-HUM-L2-MIN', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 23, 0230059, NULL, NULL, 'HOSP-HUM-L2-CENT1', 'HOSP-HUM-L2-CENT1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 24, 0240059, NULL, NULL, 'HOSP-HUM-L2-CENT2', 'HOSP-HUM-L2-CENT2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 25, 0250059, NULL, NULL, 'HOSP-HUM-L2-CENT3', 'HOSP-HUM-L2-CENT3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 26, 0260059, NULL, NULL, 'HOSP-HUM-L2-TOW', 'HOSP-HUM-L2-TOW', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 27, 0270059, NULL, NULL, 'HOSP-HUM-L2-GAS', 'HOSP-HUM-L2-GAS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 28, 0280059, NULL, NULL, 'HOSP-HUM-L2-PED', 'HOSP-HUM-L2-PED', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 29, 0290059, NULL, NULL, 'HOSP-HUM-L2-CAR', 'HOSP-HUM-L2-CAR', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 30, 0300059, NULL, NULL, 'HOSP-HUM-L3-CENT1', 'HOSP-HUM-L3-CENT1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 31, 0310059, NULL, NULL, 'HOSP-HUM-L3-CENT2', 'HOSP-HUM-L3-CENT2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 32, 0320059, NULL, NULL, 'HOSP-HUM-L3-CENT3', 'HOSP-HUM-L3-CENT3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 33, 0330059, NULL, NULL, 'HOSP-HUM-L3-TOW', 'HOSP-HUM-L3-TOW', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 34, 0340059, NULL, NULL, 'HOSP-HUM-L3-NEP', 'HOSP-HUM-L3-NEP', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 35, 0350059, NULL, NULL, 'HOSP-HUM-L3-NEU', 'HOSP-HUM-L3-NEU', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, NULL, 36, 0360059, NULL, NULL, 'HOSP-HUM-L3-OUT', 'HOSP-HUM-L3-OUT', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(59, 1003, 1, 1, NULL, 'TUN-CT-CGBT-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 2, NULL, 'TUN-CT-CGBT-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 3, NULL, 'TUN-CT-ITS-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 4, NULL, 'TUN-CT-ITS-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 5, NULL, 'TUN-CT-PCI-HUM-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 6, NULL, 'TUN-CT-PCI-HUM-2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 7, NULL, 'HOSP-HUM-L1-ORTH', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 8, NULL, 'HOSP-HUM-L1-REH', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 9, NULL, 'HOSP-HUM-L1-VAR', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 10, NULL, 'HOSP-HUM-L1-ENT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 11, NULL, 'HOSP-HUM-L1-SPIC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 12, NULL, 'HOSP-HUM-L1-CENT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 13, NULL, 'HOSP-HUM-L1-TOW', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 14, NULL, 'HOSP-HUM-L1-HEON', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 15, NULL, 'HOSP-HUM-L1-RHE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 16, NULL, 'HOSP-HUM-L1-END', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 17, NULL, 'HOSP-HUM-L1-OURE', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 18, NULL, 'HOSP-HUM-L1-EME', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 19, NULL, 'HOSP-HUM-L1-OUT1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 20, NULL, 'HOSP-HUM-L1-OUT2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 21, NULL, 'HOSP-HUM-L2-VAR', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 22, NULL, 'HOSP-HUM-L2-MIN', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 23, NULL, 'HOSP-HUM-L2-CENT1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 24, NULL, 'HOSP-HUM-L2-CENT2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 25, NULL, 'HOSP-HUM-L2-CENT3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 26, NULL, 'HOSP-HUM-L2-TOW', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 27, NULL, 'HOSP-HUM-L2-GAS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 28, NULL, 'HOSP-HUM-L2-PED', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 29, NULL, 'HOSP-HUM-L2-CAR', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 30, NULL, 'HOSP-HUM-L3-CENT1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 31, NULL, 'HOSP-HUM-L3-CENT2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 32, NULL, 'HOSP-HUM-L3-CENT3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 33, NULL, 'HOSP-HUM-L3-TOW', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 34, NULL, 'HOSP-HUM-L3-NEP', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 35, NULL, 'HOSP-HUM-L3-NEU', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(59, 1003, 1, 36, NULL, 'HOSP-HUM-L3-OUT', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(59, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(59, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
