INSERT INTO static.ext_entity_type_params (ext_entity_type_id, ext_entity_type_param_id, default_value, alias, description, label_alias, label_description, data_type_id, unit_id, visible, editable, created_at, updated_at) VALUES
(1, 1, null, 'id_road', 'Id road', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_CATEGORY_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 2, null, 'road', 'Road', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 3, null, 'pk', 'PK', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_PK', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_PK_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 4, null, 'hm', 'HM', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_HM', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_HM_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 5, null, 'id_road_impact', 'Id road impact', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_IMPACT', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_IMPACT_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 6, null, 'road_impact', 'Road impact', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD_IMPACT', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD_IMPACT_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 7, null, 'update_date', 'Update date', 'LBL_EXT_ENTITY_TYPE_PARAM_UPDATE_DATE', 'LBL_EXT_ENTITY_TYPE_PARAM_UPDATE_DATE_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, null, 'color', 'Color', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 9, null, 'date', 'Date', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 10, null, 'location', 'Location', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 11, null, 'categoria', 'Categoria', 'LBL_EXT_ENTITY_TYPE_PARAM_CATEGORY', 'LBL_EXT_ENTITY_TYPE_PARAM_CATEGORY_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(2, 1, null, 'id_road', 'Id road', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_CATEGORY_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 2, null, 'road', 'Road', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 3, null, 'pk', 'PK', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_PK', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_PK_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 4, null, 'hm', 'HM', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_HM', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_HM_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 5, null, 'id_road_impact', 'Id road impact', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_IMPACT', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_IMPACT_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 6, null, 'road_impact', 'Road impact', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD_IMPACT', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD_IMPACT_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 7, null, 'update_date', 'Update date', 'LBL_EXT_ENTITY_TYPE_PARAM_UPDATE_DATE', 'LBL_EXT_ENTITY_TYPE_PARAM_UPDATE_DATE_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, null, 'color', 'Color', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, null, 'date', 'Date', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 10, null, 'location', 'Location', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 11, null, 'categoria', 'Categoria', 'LBL_EXT_ENTITY_TYPE_PARAM_CATEGORY', 'LBL_EXT_ENTITY_TYPE_PARAM_CATEGORY_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3, 1, null, 'id_road', 'Id road', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_CATEGORY_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, null, 'road', 'Road', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 3, null, 'pk', 'PK', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_PK', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_PK_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 4, null, 'hm', 'HM', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_HM', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_HM_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 5, null, 'id_road_impact', 'Id road impact', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_IMPACT', 'LBL_EXT_ENTITY_TYPE_PARAM_ID_ROAD_IMPACT_DESC', 1, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 6, null, 'road_impact', 'Road impact', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD_IMPACT', 'LBL_EXT_ENTITY_TYPE_PARAM_ROAD_IMPACT_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 7, null, 'update_date', 'Update date', 'LBL_EXT_ENTITY_TYPE_PARAM_UPDATE_DATE', 'LBL_EXT_ENTITY_TYPE_PARAM_UPDATE_DATE_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 8, null, 'color', 'Color', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 9, null, 'date', 'Date', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 10, null, 'location', 'Location', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 11, null, 'categoria', 'Categoria', 'LBL_EXT_ENTITY_TYPE_PARAM_CATEGORY', 'LBL_EXT_ENTITY_TYPE_PARAM_CATEGORY_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(4, 1, null, 'location', 'Location', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION', 'LBL_EXT_ENTITY_TYPE_PARAM_LOCATION_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 2, null, 'status', 'Status', 'LBL_EXT_ENTITY_TYPE_PARAM_STATUS', 'LBL_EXT_ENTITY_TYPE_PARAM_STATUS_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 3, null, 'date', 'Date', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE', 'LBL_EXT_ENTITY_TYPE_PARAM_DATE_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(5, 1, null, 'activation_time', 'activation_time', 'LBL_EXT_ENTITY_TYPE_PARAM_ACTIVATION_TIME', 'LBL_EXT_ENTITY_TYPE_PARAM_ACTIVATION_TIME_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 2, null, 'status', 'status', 'LBL_EXT_ENTITY_TYPE_PARAM_STATUS', 'LBL_EXT_ENTITY_TYPE_PARAM_STATUS_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 3, null, 'status_time', 'status_time', 'LBL_EXT_ENTITY_TYPE_PARAM_STATUS_TIME', 'LBL_EXT_ENTITY_TYPE_PARAM_STATUS_TIME_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(6, 1, null, 'color', 'color', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR', 'LBL_EXT_ENTITY_TYPE_PARAM_COLOR_DESC', 2, null, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);




