INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(56, NULL, 1, 0010056, NULL, NULL, 'ILU-NOR-DP2', 'ILU-NOR-DP2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 2, 0020056, NULL, NULL, 'ILU-SUR-DP2', 'ILU-SUR-DP2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 3, 0030056, NULL, NULL, 'CGBT-DP2', 'CGBT-DP2', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 4, 0040056, NULL, NULL, 'ILU-NOR-DP3', 'ILU-NOR-DP3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 5, 0050056, NULL, NULL, 'ILU-SUR-DP3', 'ILU-SUR-DP3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 6, 0060056, NULL, NULL, 'CGBT-DP3', 'CGBT-DP3', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 7, 0070056, NULL, NULL, 'ILU-NOR-DP4', 'ILU-NOR-DP4', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 8, 0080056, NULL, NULL, 'ILU-SUR-DP4', 'ILU-SUR-DP4', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 9, 0090056, NULL, NULL, 'CGBT-DP4', 'CGBT-DP4', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 10, 0100056, NULL, NULL, 'ILU-SUR-DP1', 'ILU-SUR-DP1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 11, 0110056, NULL, NULL, 'ILU-NOR-DP1', 'ILU-NOR-DP1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, NULL, 12, 0120056, NULL, NULL, 'CGBT-DP1', 'CGBT-DP1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(56, 1003, 1, 1, NULL, 'ILU-NOR-DP2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 2, NULL, 'ILU-SUR-DP2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 3, NULL, 'CGBT-DP2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 4, NULL, 'ILU-NOR-DP3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 5, NULL, 'ILU-SUR-DP3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 6, NULL, 'CGBT-DP3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 7, NULL, 'ILU-NOR-DP4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 8, NULL, 'ILU-SUR-DP4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 9, NULL, 'CGBT-DP4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 10, NULL, 'ILU-SUR-DP1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 11, NULL, 'ILU-NOR-DP1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(56, 1003, 1, 12, NULL, 'CGBT-DP1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(56, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(56, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);