INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(58, NULL, 1, 0010058, NULL, NULL, 'RV-CT-ITS-PULS-1', 'RV-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 2, 0020058, NULL, NULL, 'RV-CT-CGBT-PULS-1', 'RV-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 3, 0030058, NULL, NULL, 'RV-CT-PCI-PULS-1', 'RV-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 4, 0040058, NULL, NULL, 'MM-CT-ITS-PULS-1', 'MM-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 5, 0050058, NULL, NULL, 'MM-CT-CGBT-PULS-1', 'MM-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 6, 0060058, NULL, NULL, 'MM-CT-PCI-PULS-1', 'MM-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 7, 0070058, NULL, NULL, 'STMI-CT-ITS-PULS-1', 'STMI-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 8, 0080058, NULL, NULL, 'STMI-CT-CGBT-PULS-1', 'STMI-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 9, 0090058, NULL, NULL, 'CAS-CT-PCI-PULS-1', 'CAS-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 10, 0100058, NULL, NULL, 'CAS-CT-CGBT-BC-PULS-1', 'CAS-CT-CGBT-BC-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 11, 0110058, NULL, NULL, 'CAS-CT-ITS-BC-PULS-1', 'CAS-CT-ITS-BC-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 12, 0120058, NULL, NULL, 'CAS-CT-CGBT-BM-PULS-1', 'CAS-CT-CGBT-BM-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 13, 0130058, NULL, NULL, 'CAS-CT-ITS-BM-PULS-1', 'CAS-CT-ITS-BM-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 14, 0140058, NULL, NULL, 'CH-CT-CGBT-PULS-1', 'CH-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 15, 0150058, NULL, NULL, 'CH-CT-ITS-PULS-1', 'CH-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 16, 0160058, NULL, NULL, 'CH-CT-PCI-PULS-1', 'CH-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 17, 0170058, NULL, NULL, 'EST-CT-CGBT-PULS-1', 'EST-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 18, 0180058, NULL, NULL, 'EST-CT-ITS-PULS-1', 'EST-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 19, 0190058, NULL, NULL, 'STM2-CT-CGBT-PULS-1', 'STM2-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 20, 0200058, NULL, NULL, 'STM2-CT-ITS-PULS-1', 'STM2-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 21, 0210058, NULL, NULL, 'LQ-CT-CGBT-PULS-1', 'LQ-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 22, 0220058, NULL, NULL, 'LQ-CT-ITS-PULS-1', 'LQ-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 23, 0230058, NULL, NULL, 'LQ-CT-PCI-PULS-1', 'LQ-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 24, 0240058, NULL, NULL, 'NG-CT-CGBT-PULS-1', 'NG-CT-CGBT-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 25, 0250058, NULL, NULL, 'NG-CT-ITS-PULS-1', 'NG-CT-ITS-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 26, 0260058, NULL, NULL, 'NG-CT-PCI-PULS-1', 'NG-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 27, 0270058, NULL, NULL, 'COR-CT-CGBT-BM-PULS-1', 'COR-CT-CGBT-BM-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 28, 0280058, NULL, NULL, 'COR-CT-CGBT-BC-PULS-1', 'COR-CT-CGBT-BC-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 29, 0290058, NULL, NULL, 'COR-CT-ITS-BM-PULS-1', 'COR-CT-ITS-BM-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 30, 0300058, NULL, NULL, 'COR-CT-ITS-BC-PULS-1', 'COR-CT-ITS-BC-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, NULL, 31, 0310058, NULL, NULL, 'COR-CT-PCI-PULS-1', 'COR-CT-PCI-PULS-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(58, 1003, 1, 1, NULL, 'RV-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 2, NULL, 'RV-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 3, NULL, 'RV-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 4, NULL, 'MM-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 5, NULL, 'MM-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 6, NULL, 'MM-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 7, NULL, 'STMI-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 8, NULL, 'STMI-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 9, NULL, 'CAS-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 10, NULL, 'CAS-CT-CGBT-BC-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 11, NULL, 'CAS-CT-ITS-BC-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 12, NULL, 'CAS-CT-CGBT-BM-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 13, NULL, 'CAS-CT-ITS-BM-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 14, NULL, 'CH-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 15, NULL, 'CH-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 16, NULL, 'CH-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 17, NULL, 'EST-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 18, NULL, 'EST-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 19, NULL, 'STM2-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 20, NULL, 'STM2-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 21, NULL, 'LQ-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 22, NULL, 'LQ-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 23, NULL, 'LQ-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 24, NULL, 'NG-CT-CGBT-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 25, NULL, 'NG-CT-ITS-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 26, NULL, 'NG-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 27, NULL, 'COR-CT-CGBT-BM-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 28, NULL, 'COR-CT-CGBT-BC-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 29, NULL, 'COR-CT-ITS-BM-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 30, NULL, 'COR-CT-ITS-BC-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(58, 1003, 1, 31, NULL, 'COR-CT-PCI-PULS-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(58, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(58, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);