INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(70, 1, 1, 0010070, NULL, NULL, 'RV-ARED-1', 'RV-ARED-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 2, 0020070, NULL, NULL, 'MM-ARED-1', 'MM-ARED-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 3, 0030070, NULL, NULL, 'STMI-ARED-1', 'STMI-ARED-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 4, 0040070, NULL, NULL, 'LQ-ARED-1', 'LQ-ARED-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 5, 0050070, NULL, NULL, 'CH-ARED-1', 'CH-ARED-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 6, 0060070, NULL, NULL, 'CAS-ARED-BM', 'CAS-ARED-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 7, 0070070, NULL, NULL, 'CAS-ARED-BC', 'CAS-ARED-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 8, 0080070, NULL, NULL, 'COR-ARED-BC', 'COR-ARED-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 9, 0090070, NULL, NULL, 'COR-ARED-BM', 'COR-ARED-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 10, 0100070, NULL, NULL, 'STM2-ARED-BC', 'STM2-ARED-BC', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 11, 0110070, NULL, NULL, 'EST-ARED-1', 'EST-ARED-1', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 1, 13, 0130070, NULL, NULL, 'NG-ARED-BM', 'NG-ARED-BM', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(70, 1003, 1, 1, NULL, 'RV-ARED-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 2, NULL, 'MM-ARED-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 3, NULL, 'STMI-ARED-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 4, NULL, 'LQ-ARED-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 5, NULL, 'CH-ARED-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 6, NULL, 'CAS-ARED-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 7, NULL, 'CAS-ARED-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 8, NULL, 'COR-ARED-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 9, NULL, 'COR-ARED-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 10, NULL, 'STM2-ARED-BC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 11, NULL, 'EST-ARED-1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(70, 1003, 1, 13, NULL, 'NG-ARED-BM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(70, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(70, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);