INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(2, NULL, 1, 0060002, NULL, NULL, 'CAM-001', 'CAM-001', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 2, 0060002, NULL, NULL, 'CAM-002', 'CAM-002', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 3, 0060002, NULL, NULL, 'CAM-003', 'CAM-003', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 4, 0060002, NULL, NULL, 'CAM-004', 'CAM-004', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 5, 0060002, NULL, NULL, 'CAM-005', 'CAM-005', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 12, 0060002, NULL, NULL, 'CAM-006', 'CAM-006', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 13, 0060002, NULL, NULL, 'CAM-007', 'CAM-007', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 14, 0060002, NULL, NULL, 'CAM-008', 'CAM-008', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 15, 0060002, NULL, NULL, 'CAM-009', 'CAM-009', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 16, 0060002, NULL, NULL, 'CAM-010', 'CAM-010', 'null', NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 4, 6, 1000, NULL, NULL, 'RAD-001', 'RAD-001', 'null', NULL, 'ChangeMeasureCamera.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 7, 1000, NULL, NULL, 'RAD-002', 'RAD-002', 'null', NULL, 'ChangeMeasureCamera.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 8, 1000, NULL, NULL, 'RAD-003', 'RAD-003', 'null', NULL, 'ChangeMeasureCamera.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 9, 1000, NULL, NULL, 'RAD-004', 'RAD-004', 'null', NULL, 'ChangeMeasureCamera.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 10, 1000, NULL, NULL, 'RAD-005', 'RAD-005', 'null', NULL, 'ChangeMeasureCamera.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 11, 1000, NULL, NULL, 'RAD-006', 'RAD-006', 'null', NULL, 'ChangeMeasureCamera.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(2, 1, 1, 1, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 1, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 1, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 1, NULL, 'CAM-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 2, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 2, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 2, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 2, NULL, 'CAM-002', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 3, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 3, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 3, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 3, NULL, 'CAM-003', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 4, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 4, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 4, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 4, NULL, 'CAM-004', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 5, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 5, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 5, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 5, NULL, 'CAM-005', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 12, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 12, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 12, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 12, NULL, 'CAM-006', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 13, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 13, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 13, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 13, NULL, 'CAM-007', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 14, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 14, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 14, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 14, NULL, 'CAM-008', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 15, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 15, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 15, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 15, NULL, 'CAM-009', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 16, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 16, NULL, 'DS-2CD2665FWD-IZS', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 16, NULL, 'http://109.206.96.58:8080/cam_1.cgi', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 16, NULL, 'CAM-0010', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 6, NULL, 'RAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 6, NULL, 'Local', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 6, NULL, 'RAD-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 7, NULL, 'RAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 7, NULL, 'Local', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 7, NULL, 'RAD-002', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 8, NULL, 'RAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 8, NULL, 'Local', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 8, NULL, 'RAD-003', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 9, NULL, 'RAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 9, NULL, 'Local', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 9, NULL, 'RAD-004', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 10, NULL, 'RAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 10, NULL, 'Local', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 10, NULL, 'RAD-005', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 11, NULL, 'RAD', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 11, NULL, 'Local', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 1003, 1, 11, NULL, 'RAD-006', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(2, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
