-- 
-- Table: conf.elements.DETECTOR
--
INSERT INTO conf.elements
(element_type_id,  element_subtype_id,  element_id,  location_id,  keep_values_on_disconnected,  inherit_state_id,  alias,  description,  on_change_alarm,  on_change_state,  on_change_measure,  on_schedule,  enabled,  visible,  alert,  alarm_count,  created_at,  updated_at) VALUES
--(3, 2, 1, 115, NULL,  NULL, 'DET01-ASDKD01P', 'DET01-ASDKD01P', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 2, 2, 115, NULL,  NULL, 'DET02-ASDKD01P', 'DET02-ASDKD01P', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 2, 3, 115, NULL,  NULL, 'DET03-ASDKD01L', 'DET03-ASDKD01L', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 2, 4, 115, NULL,  NULL, 'DET04-ASDKD01L', 'DET04-ASDKD01L', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--
--(3, 4, 5, NULL, NULL, NULL, 'DET01-RTMS', 'DET01-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 4, 6, NULL, NULL, NULL, 'DET02-RTMS', 'DET02-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 4, 7, NULL, NULL, NULL, 'DET03-RTMS', 'DET03-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 4, 8, NULL, NULL, NULL, 'DET04-RTMS', 'DET04-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 4, 9, NULL, NULL, NULL, 'DET05-RTMS', 'DET05-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 4, 10, NULL, NULL, NULL, 'DET06-RTMS', 'DET06-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 4, 11, NULL, NULL, NULL, 'DET07-RTMS', 'DET07-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 4, 12, NULL, NULL, NULL, 'DET08-RTMS', 'DET08-RTMS', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(3, 2, 50, NULL, NULL, NULL, 'DET01', 'DET01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 51, NULL, NULL, NULL, 'DET02', 'DET02', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 52, NULL, NULL, NULL, 'DET03', 'DET03', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 53, NULL, NULL, NULL, 'DET04', 'DET04', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 54, NULL, NULL, NULL, 'DET05', 'DET05', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 55, NULL, NULL, NULL, 'DET06', 'DET06', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 2, 56, NULL, NULL, NULL, 'DET07', 'DET07', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


INSERT INTO conf.element_values
(element_type_id, element_type_param_id, param_type_id, element_id, value, enabled, visible, created_at, updated_at) VALUES
--(3,1,1,1,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,1,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,1,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,1,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1003,1,1,'Virtual_Det_1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--
--(3,1,1,2,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,2,'2',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,2,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,2,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1003,1,2,'Virtual_Det_2',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--
--(3,1,1,3,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,3,'3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,3,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,3,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1003,1,3,'Virtual_Det_3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--
--(3,1,1,4,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,4,'4',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,4,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,4,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1003,1,4,'Virtual_Det_4',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
---- rtms
--(3,1,1,5,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,5,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,5,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,5,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,5,'100301409',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
--(3,1,1,6,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,6,'2',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,6,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,6,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,6,'807048468',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
--(3,1,1,7,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,7,'3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,7,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,7,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,7,'100301409',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
--(3,1,1,8,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,8,'3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,8,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,8,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,8,'807048468',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
--(3,1,1,9,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,9,'3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,9,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,9,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,9,'100301409',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
--(3,1,1,10,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,10,'3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,10,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,10,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,10,'807048468',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
--(3,1,1,11,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,11,'3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,11,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,11,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,11,'807048468',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
--
--(3,1,1,12,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,2,1,12,'3',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,3,1,12,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,4,1,12,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
--(3,1004,1,12,'100301409',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

(3,1,1,50,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,2,1,50,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,3,1,50,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,4,1,50,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,1003,1,50,'DET_01',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

(3,1,1,51,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,2,1,51,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,3,1,51,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,4,1,51,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,1003,1,51,'DET_02',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

(3,1,1,52,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,2,1,52,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,3,1,52,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,4,1,52,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,1003,1,52,'DET_03',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

(3,1,1,53,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,2,1,53,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,3,1,53,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,4,1,53,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,1003,1,53,'DET_04',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

(3,1,1,54,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,2,1,54,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,3,1,54,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,4,1,54,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,1003,1,54,'DET_05',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

(3,1,1,55,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,2,1,55,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,3,1,55,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,4,1,55,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,1003,1,55,'DET_06',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

(3,1,1,56,'true',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,2,1,56,'1',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,3,1,56,'0',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,4,1,56,0,true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP), 
(3,1003,1,56,'DET_07',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);