INSERT INTO ui.selector_trees (id, default_module_id, label) VALUES 
(1, 901, 'LBL_SINOPTICOS_TUNEL'), 
(2, 801, 'LBL_SINOPTICOS_HOSPITAL');

INSERT INTO ui.selector_tree_nodes 
(id, selector_tree_id, label, module_id) VALUES 
(1, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS', NULL),
	(2, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_CT', NULL),
		(3, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_CT_PLANO', 901),
	(4, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_TUNEL', NULL),
		(5, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_TUNEL_GENERAL', 902),
		(6, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_TUNEL_ILUMINACION', 903),
		(7, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_TUNEL_ENERGIA', 904),
		(8, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_TUNEL_VENTILACION', 905),
		(9, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_TUNEL_COMUNICACIONES', 906),
		(10, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_TUNEL_PCI', 907),
	(11, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_UF', NULL),
		(12, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_UF_CSG', 908),
		(13, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_UF_CGBT', 909),
		(14, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_UF_CSA', 910),
		(15, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_UF_CSB', 911),
		(16, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_UF_CSV_CA', 912),
		(17, 1, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_UF_CSV_MA', 913),

(18, 2, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_HOSPITAL', NULL),
(19, 2, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_HOSPITAL_L1', 801),
(20, 2, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_HOSPITAL_L2', 802),
(21, 2, 'LBL_SELECTOR_TREE_NODES_SINOPTICOS_HOSPITAL_L3', 803);

INSERT INTO ui.selector_tree_hierarchies 
(selector_tree_id, node_parent_id, node_child_id) VALUES 
(1, 1, 2),
	(1, 2, 3),
(1, 1, 4),
	(1, 4, 5),
	(1, 4, 6),
	(1, 4, 7),
	(1, 4, 8),
	(1, 4, 9),
	(1, 4, 10),
(1, 1, 11),
	(1, 11, 12),
	(1, 11, 13),
	(1, 11, 14),
	(1, 11, 15),
	(1, 11, 16),
	(1, 11, 17),

(2, 18, 19),
(2, 18, 20),
(2, 18, 21);

