DELETE FROM master.ims_incident_groups;

-- 
-- Table: conf.ims_incident_types
--
INSERT INTO master.ims_incident_groups (incident_group_id,alias,description,label_alias,label_description,enabled,visible,created_at,updated_at) VALUES
(1,'Stav dopravy','Stav dopravy','LBL_IMS_INCIDENT_GROUP_TYPE_TRAFFIC_STATUS', 'LBL_IMS_INCIDENT_GROUP_TYPE_TRAFFIC_STATUS_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,'typ incidentu - meteo','typ incidentu - meteo','LBL_IMS_INCIDENT_GROUP_TYPE_WEATHER_DATA', 'LBL_IMS_INCIDENT_GROUP_TYPE_WEATHER_DATA_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,'Cestná nehoda','Cestná nehoda','LBL_IMS_INCIDENT_GROUP_TYPE_ROAD_INCIDENTS', 'LBL_IMS_INCIDENT_GROUP_TYPE_ROAD_INCIDENTS_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

INSERT INTO conf.ims_incident_types (incident_type_id, incident_group_id, ini_incident_state_id, alias, description, incident_level_id, default_user_id, auto_confirm_incident, cancel_incident, valid_for_min, enabled, visible, created_at, updated_at) VALUES
(0101, 1, 1, 'T-1', 'HUSTOTA DOPRAVY VYSOKÁ',  1, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0102, 1, 1, 'T-2', 'HUSTOTA DOPRAVY KRITICKÁ',  1, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0103, 1, 1, 'T-3', 'KOLÓNA POMALY SA POHYBUJÚCA',  1, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0104, 1, 1, 'T-4', 'KOLÓNA STOJACA',  1, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0105, 1, 1, 'T-5', 'REŠTITÚCIA',  1, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0106, 1, 1, 'T-6', 'SPOMALENIE DOPRAVNÉHO PRÚDU NÁHLE',  1, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0107, 1, 1, 'T-7', 'SPOMALENIE DOPRAVNÉHO PRÚDU KOLÍZNE',  1, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(0201, 2, 1, 'W-1', 'SNEH ALEBO POL’ADOVICA. PODMIENKY TVORBY',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0202, 2, 1, 'W-2', 'SNEH ALEBO POL’ADOVICA. POZITÍVNA DETEKCIA',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0203, 2, 1, 'W-3', 'ZNÍŽENÁ ADHÉZIA NEBEZPEĈENSTVO ṤMYKU',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0204, 2, 1, 'W-4', 'ZNÍŽENÁ ADHÉZIA VYSOKÉ NEBEZPEĈENSTVO ṤMYKU',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0205, 2, 1, 'W-5', 'ZNÍŽENÁ VIDITEL’NOST’. ZNÍŽENÁ',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0206, 2, 1, 'W-6', 'ZNÍŽENÁ VIDITEL’NOST’ NÍZKA',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0207, 2, 1, 'W-7', 'ZNÍŽENÁ VIDITEL’NOST’ KRITICKÁ',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0208, 2, 1, 'W-8', 'VIETOR. SILNÝ BOĈNÝ',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0209, 2, 1, 'W-9', 'VIETOR NÁRAZOVÝ',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0210, 2, 1, 'W-10', 'DÁŽD’A, SNEH ALEBO NÁMRAZA REŠTITÚCIA',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0211, 2, 1, 'W-11', 'VIETOR REŠTITÚCIA',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0212, 2, 1, 'W-12', 'VIDITEL’NOST’ REŠTITÚCIA',  2, 6, 30, false, 5, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

(0301, 3, 1, 'R-1', 'DOPRAVNÁ NEHODA ZAISTENÁ',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0302, 3, 1, 'R-2', 'DOPRAVNÁ NEHODA NEZAISTENÁ',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0303, 3, 1, 'R-3', 'DOPRAVNÁ NEHODA VÁŽNA',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0304, 3, 1, 'R-4', 'DOPRAVNÁ NEHODA VEĽMI VÁŽNA',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0305, 3, 1, 'R-5', 'PRÁCE NA CESTE ZAISTENÉ',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0306, 3, 1, 'R-6', 'PRÁCE NA CESTE NEZAISTENÉ',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0307, 3, 1, 'R-7', 'PRÁCE NA CESTE S UZATVORENÍM ÚSEKU',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0308, 3, 1, 'R-8', 'PREKÁŽKA NA VOZOVKE MIMO JAZDNÉHO PRUHU',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0309, 3, 1, 'R-9', 'PREKÁŽKA NA VOZOVKE V JAZDNOM PRUHU',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0310, 3, 1, 'R-10', 'VOZIDLO V PROTISMERE',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(0311, 3, 1, 'R-11', 'UZATVORENÝ ÚSEK',  3, 6, 300, true, 2880, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

