INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(2, 26, 18, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 19, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 20, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 21, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 22, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 23, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 24, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 25, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 26, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 27, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 28, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 29, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 26, 30, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
