-- 
-- Table: conf.alarm_configs
--
INSERT INTO conf.alarm_configs
(alarm_config_id, alarm_type_id, alarm_level_id, element_type_id, element_id, element_type_state_id, mine, treatment, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
(3000001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS AIR PRESSURE GREATER THAN 65534', 'ALARM WS AIR PRESSURE GREATER THAN 65534', 'LBL_ALARM_CONFIGS_ALARM_WS_AIR_PRESSURE_GREATER_THAN_65534', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3010001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS AIR TEMPERATURE NOT BETWEEN -1000 AND 1000', 'ALARM WS AIR TEMPERATURE NOT BETWEEN -1000 AND 1000', 'LBL_ALARM_CONFIGS_ALARM_WS_AIR_TEMPERATURE_NOT_BETWEEN_-1000_AND_1000', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3020001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS AVERAGE WIND DIRECTION GREATER THAN 360', 'ALARM WS AVERAGE WIND DIRECTION GREATER THAN 360', 'LBL_ALARM_CONFIGS_ALARM_WS_AVERAGE_WIND_DIRECTION_GREATER_THAN_360', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3030001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS AVERAGE WIND SPEED GREATER THAN 65534', 'ALARM WS AVERAGE WIND SPEED GREATER THAN 65534', 'LBL_ALARM_CONFIGS_ALARM_WS_AVERAGE_WIND_SPEED_GREATER_THAN_65534', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3040001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS BLACK ICE SIGNAL EQUAL TO 4', 'ALARM WS BLACK ICE SIGNAL EQUAL TO 4', 'LBL_ALARM_CONFIGS_ALARM_WS_BLACK_ICE_SIGNAL_EQUAL_TO_4', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3050001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS CONCENTRATION CACL GREATER THAN 100', 'ALARM WS CONCENTRATION CACL GREATER THAN 100', 'LBL_ALARM_CONFIGS_ALARM_WS_CONCENTRATION_CACL_GREATER_THAN_100', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3060001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS CONCENTRATION MGCL2 GREATER THAN 100', 'ALARM WS CONCENTRATION MGCL2 GREATER THAN 100', 'LBL_ALARM_CONFIGS_ALARM_WS_CONCENTRATION_MGCL2_GREATER_THAN_100', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3070001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS CONCENTRATION NACL GREATER THAN 100', 'ALARM WS CONCENTRATION NACL GREATER THAN 100', 'LBL_ALARM_CONFIGS_ALARM_WS_CONCENTRATION_NACL_GREATER_THAN_100', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3080001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS DEW POINT TEMPERATURE NOT BETWEEN -1000 AND 1000', 'ALARM WS DEW POINT TEMPERATURE NOT BETWEEN -1000 AND 1000', 'LBL_ALARM_CONFIGS_ALARM_WS_DEW_POINT_TEMPERATURE_NOT_BETWEEN_-1000_AND_1000', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3090001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS FREEZE POINT NOT BETWEEN -1000 AND 1000', 'ALARM WS FREEZE POINT NOT BETWEEN -1000 AND 1000', 'LBL_ALARM_CONFIGS_ALARM_WS_FREEZE_POINT_NOT_BETWEEN_-1000_AND_1000', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3100001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS GUST WIND DIRECTION GREATER THAN 360', 'ALARM WS GUST WIND DIRECTION GREATER THAN 360', 'LBL_ALARM_CONFIGS_ALARM_WS_GUST_WIND_DIRECTION_GREATER_THAN_360', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3110001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS GUST WIND SPEED GREATER THAN 65534', 'ALARM WS GUST WIND SPEED GREATER THAN 65534', 'LBL_ALARM_CONFIGS_ALARM_WS_GUST_WIND_SPEED_GREATER_THAN_65534', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3120001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS PRECIPITATION INTENSITY GREATER THAN 65534', 'ALARM WS PRECIPITATION INTENSITY GREATER THAN 65534', 'LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_INTENSITY_GREATER_THAN_65534', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3130001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS PRECIPITATION TYPE EQUAL TO 2', 'ALARM WS PRECIPITATION TYPE EQUAL TO 2', 'LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_TYPE_EQUAL_TO_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3140001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS PREDICTION ALARM CODE EQUAL TO 255', 'ALARM WS PREDICTION ALARM CODE EQUAL TO 255', 'LBL_ALARM_CONFIGS_ALARM_WS_PREDICTION_ALARM_CODE_EQUAL_TO_255', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3150001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS RELATIVE HUMIDITY GREATER THAN 100', 'ALARM WS RELATIVE HUMIDITY GREATER THAN 100', 'LBL_ALARM_CONFIGS_ALARM_WS_RELATIVE_HUMIDITY_GREATER_THAN_100', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3160001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS ROAD CONDITION EQUAL TO 2', 'ALARM WS ROAD CONDITION EQUAL TO 2', 'LBL_ALARM_CONFIGS_ALARM_WS_ROAD_CONDITION_EQUAL_TO_2', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3170001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS SNOW FALL INTENSITY GREATER THAN 65534', 'ALARM WS SNOW FALL INTENSITY GREATER THAN 65534', 'LBL_ALARM_CONFIGS_ALARM_WS_SNOW_FALL_INTENSITY_GREATER_THAN_65534', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3180001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS SUB SURFACE TEMPERATURE GREATER THAN 1000', 'ALARM WS SUB SURFACE TEMPERATURE GREATER THAN 1000', 'LBL_ALARM_CONFIGS_ALARM_WS_SUB_SURFACE_TEMPERATURE_GREATER_THAN_1000', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3190001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS SURFACE TEMPERATURE GREATER THAN 1000', 'ALARM WS SURFACE TEMPERATURE GREATER THAN 1000', 'LBL_ALARM_CONFIGS_ALARM_WS_SURFACE_TEMPERATURE_GREATER_THAN_1000', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3200001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS VISIBILITY GREATER THAN 1000000', 'ALARM WS VISIBILITY GREATER THAN 1000000', 'LBL_ALARM_CONFIGS_ALARM_WS_VISIBILITY_GREATER_THAN_1000000', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3210001, 2, 5, 1, NULL, 3, true, false, 'ALARM WS WATER DEPTH GREATER THAN 65534', 'ALARM WS WATER DEPTH GREATER THAN 65534', 'LBL_ALARM_CONFIGS_ALARM_WS_WATER_DEPTH_GREATER_THAN_65534', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


--INCIDENT ALARMS
(3220001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS LOW VISIBILITY', 'ALARM WS LOW VISIBILITY', 'LBL_ALARM_CONFIGS_ALARM_WS_LOW_VISIBILITY', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3230001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS SNOW OR ICE COATING CREATING CONDITIONS', 'ALARM SNOW OR ICE COATING CREATING CONDITIONS', 'ALARM_WS_SNOW_OR_ICE_COATING_CREATING_CONDITIONS', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3240001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS SNOW OR ICE COATING POSITIVE DETECTION', 'ALARM SNOW OR ICE COATING POSITIVE DETECTION', 'LBL_ALARM_CONFIGS_ALARM_WS_SNOW_OR_ICE_COATING_POSITIVE_DETECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3250001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS SNOW OR ICE COATING POSITIVE DETECTION', 'ALARM WS SNOW OR ICE COATING POSITIVE DETECTION', 'LBL_ALARM_CONFIGS_ALARM_WS_SNOW_OR_ICE_COATING_POSITIVE_DETECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3260001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS DECREASED ADHESION RISK OF SKIDDING', 'ALARM WS DECREASED ADHESION RISK OF SKIDDING', 'LBL_ALARM_CONFIGS_ALARM_WS_DECREASED_ADHESION_RISK_OF_SKIDDING', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3270001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS DECREASED ADHESION HIGH RISK OF SKIDDING', 'ALARM WS DECREASED ADHESION HIGH RISK OF SKIDDING', 'LBL_ALARM_CONFIGS_ALARM_WS_DECREASED_ADHESION_HIGH_RISK_OF_SKIDDING', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3280001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS DECREASED ADHESION HIGH RISK OF SKIDDING', 'ALARM WS DECREASED ADHESION HIGH RISK OF SKIDDING', 'LBL_ALARM_CONFIGS_ALARM_WS_DECREASED_ADHESION_HIGH_RISK_OF_SKIDDING', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3290001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS SNOW OR ICE COATING CREATING CONDITIONS', 'ALARM WS SNOW OR ICE COATING CREATING CONDITIONS', 'LBL_ALARM_CONFIGS_ALARM_WS_SNOW_OR_ICE_COATING_CREATING_CONDITIONS', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3300001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS SNOW OR ICE COATING POSITIVE DETECTION', 'ALARM WS SNOW OR ICE COATING POSITIVE DETECTION', 'LBL_ALARM_CONFIGS_ALARM_WS_SNOW_OR_ICE_COATING_POSITIVE_DETECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3310001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS SNOW OR ICE COATING POSITIVE DETECTION', 'ALARM WS SNOW OR ICE COATING POSITIVE DETECTION', 'LBL_ALARM_CONFIGS_ALARM_WS_SNOW_OR_ICE_COATING_POSITIVE_DETECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3320001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS VERY LOW VISIBILITY', 'ALARM WS VERY LOW VISIBILITY', 'LBL_ALARM_CONFIGS_ALARM_WS_VERY_LOW_VISIBILITY', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3330001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS REDUCED VISIBILITY', 'ALARM WS REDUCED VISIBILITY', 'LBL_ALARM_CONFIGS_ALARM_REDUCED_VISIBILITY', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3340001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS AVERAGE WIND SPEED BETWEEN 20 THAN 30', 'ALARM WS WIND SPEED BETWEEN 20 THAN 30', 'LBL_ALARM_CONFIGS_ALARM_WIND_SPEED_BETWEEN_20_THAN_30', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3350001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS AVERAGE WIND GREATER 30', 'ALARM WS WIND SPEED GREATER 30', 'LBL_ALARM_CONFIGS_ALARM_WIND_SPEED_GREATER_30', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3360001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS RAIN SNOW OR ICING RESTITUTION', 'ALARM WS RAIN SNOW OR ICING RESTITUTION', 'LBL_ALARM_CONFIGS_ALARM_WS_RAIN_SNOW_OR_ICING_RESTITUTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3370001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS VISIBILITY GREATER THAN 130', 'ALARM WS VISIBILITY GREATER THAN 130', 'LBL_ALARM_CONFIGS_ALARM_WS_VISIBILITY_GREATER_THAN_130', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3380001, 2, 5, 1, NULL, NULL, true, false, 'ALARM WS AVERAGE WIND SPEED LESS THAN 10', 'ALARM WS AVERAGE WIND SPEED LESS THAN 10', 'LBL_ALARM_CONFIGS_ALARM_WS_AVERAGE_WIND_SPEED_LESS_THAN_10', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
-- Incident in section
(3390001, 2, 5, 1, NULL, NULL, true, false, 'ALARM INCIDENT PRECIPITATION IN SECTION', 'ALARM INCIDENT PRECIPITATION IN SECTION', 'LBL_ALARM_INCIDENT_IN_SECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- Precipitation
(3400001, 2, 5, 1, NULL, NULL, true, false, 'ALARM INCIDENT WIND IN SECTION', 'ALARM INCIDENT WIND IN SECTION', 'LBL_ALARM_INCIDENT_IN_SECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), -- Wind
(3410001, 2, 5, 1, NULL, NULL, true, false, 'ALARM INCIDENT VISIBILITY IN SECTION', 'ALARM INCIDENT VISIBILITY IN SECTION', 'LBL_ALARM_INCIDENT_IN_SECTION', '', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); -- Visibility




-- 
-- Table: conf.alarm_measures
--
INSERT INTO conf.alarm_config_measures
(alarm_config_id, element_type_id, param_type_id, element_type_param_id, alarm_threshold_operation_id, threshold_val1, threshold_val2, created_at, updated_at) VALUES
(3000001, 1, 2, 4, 4, '6553', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3010001, 1, 2, 17, 10, '-100', '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3020001, 1, 2, 14, 4, '360', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3030001, 1, 2, 13, 4, '6553', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3040001, 1, 2, 21, 2, '4', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3050001, 1, 2, 8, 4, '100', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3060001, 1, 2, 7, 4, '100', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3070001, 1, 2, 6, 4, '100', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3080001, 1, 2, 18, 10, '-100', '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3090001, 1, 2, 3, 10, '-100', '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3100001, 1, 2, 16, 4, '360', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3110001, 1, 2, 15, 4, '6553', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3120001, 1, 2, 11, 4, '23592', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3130001, 1, 2, 19, 2, '2', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3140001, 1, 2, 22, 2, '255', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3150001, 1, 2, 10, 4, '100', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3160001, 1, 2, 9, 2, '2', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3170001, 1, 2, 12, 4, '23592', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3180001, 1, 2, 2, 4, '100', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3190001, 1, 2, 1, 4, '100', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3200001, 1, 2, 20, 4, '100000', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3210001, 1, 2, 5, 4, '65534', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

--INCIDENT ALARMS
(3220001, 1, 2, 20, 1, '40', '79', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3230001, 1, 2, 19, 2, '7', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3240001, 1, 2, 19, 2, '8', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3250001, 1, 2, 19, 2, '9', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3260001, 1, 2, 19, 2, '10', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3270001, 1, 2, 19, 2, '11', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3280001, 1, 2, 19, 2, '12', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3290001, 1, 2, 19, 2, '13', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3300001, 1, 2, 19, 2, '14', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3310001, 1, 2, 19, 2, '15', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3320001, 1, 2, 20, 6, '40', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3330001, 1, 2, 20, 1, '80', '119', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3340001, 1, 2, 13, 1, '21', '30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3350001, 1, 2, 13, 4, '30', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3360001, 1, 2, 19, 2, '3', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3370001, 1, 2, 20, 4, '130', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3380001, 1, 2, 13, 6, '10', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
