-- 
-- Table: onf.ims_incident_type_state_transitions 
--

INSERT INTO conf.ims_incident_type_state_transitions (incident_type_id, ini_incident_state_id, end_incident_state_id, auto, enabled, visible, created_at, updated_at) VALUES

-- INCIDENCIA DE EXPLOTACIÓN
(3, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(3, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(4, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(5, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(6, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(47, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

 -- PREEMERGENCIA
(7, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(7, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(8, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(9, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(10, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(11, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(12, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(13, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(14, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(15, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(17, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(18, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(20, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- EMERGENCIA NIVEL 1
(21, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(21, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 1, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(22, 3, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(22, 4, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(22, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(23, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(24, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(25, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(26, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(26, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(27, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(28, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(30, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(31, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(32, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- EMERGENCIA NIVEL 2
(33, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(33, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(34, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 1, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(35, 3, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(35, 4, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (35, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 1, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(36, 3, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(36, 4, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (36, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(37, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 1, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(38, 3, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(38, 4, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (38, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(39, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(40, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 1, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(41, 3, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(41, 4, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (41, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(42, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 1, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(43, 3, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(43, 4, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (43, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 1, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(44, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 1, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(45, 3, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),(45, 4, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (45, 2, 100, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

