INSERT INTO static.ext_entity_subtypes(ext_entity_type_id, ext_entity_subtype_id, alias, description, label_alias, label_description, enabled, visible, created_at, updated_at) VALUES
--Tipo 1 = C4 - Obras
(1,1005,'Baches en la calzada','Baches en la calzada','LBL_EXT_ENTITY_SUBTYPE_5','LBL_EXT_ENTITY_SUBTYPE_5_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1006,'Piedras en la calzada','Piedras en la calzada','LBL_EXT_ENTITY_SUBTYPE_6','LBL_EXT_ENTITY_SUBTYPE_6_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1010,'Limpieza de mat. const. (gravilla, hormigón,,,)','Limpieza de mat. const. (gravilla, hormigón,,,)','LBL_EXT_ENTITY_SUBTYPE_10','LBL_EXT_ENTITY_SUBTYPE_10_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1014,'Daños a elementos de la carretera (bionda,farola)','Daños a elementos de la carretera (bionda,farola)','LBL_EXT_ENTITY_SUBTYPE_14','LBL_EXT_ENTITY_SUBTYPE_14_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1017,'Averías alumbrado y semáforos','Averías alumbrado y semáforos','LBL_EXT_ENTITY_SUBTYPE_17','LBL_EXT_ENTITY_SUBTYPE_17_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1020,'Desprendimientos (taludes,muros, o f, puentes...)','Desprendimientos (taludes,muros, o f, puentes...)','LBL_EXT_ENTITY_SUBTYPE_20','LBL_EXT_ENTITY_SUBTYPE_20_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1021,'Afecciones túneles','Afecciones túneles','LBL_EXT_ENTITY_SUBTYPE_21','LBL_EXT_ENTITY_SUBTYPE_21_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1022,'Cortes y aperturas al tráfico','Cortes y aperturas al tráfico','LBL_EXT_ENTITY_SUBTYPE_22','LBL_EXT_ENTITY_SUBTYPE_22_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1023,'Señalización','Señalización','LBL_EXT_ENTITY_SUBTYPE_23','LBL_EXT_ENTITY_SUBTYPE_23_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1024,'Afecciones a obras','Afecciones a obras','LBL_EXT_ENTITY_SUBTYPE_24','LBL_EXT_ENTITY_SUBTYPE_24_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1025,'Varios','Varios','LBL_EXT_ENTITY_SUBTYPE_25','LBL_EXT_ENTITY_SUBTYPE_25_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1034,'Afecciones por obras','Afecciones por obras','LBL_EXT_ENTITY_SUBTYPE_34','LBL_EXT_ENTITY_SUBTYPE_34_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1035,'Nieve en calzada','Nieve en calzada','LBL_EXT_ENTITY_SUBTYPE_35','LBL_EXT_ENTITY_SUBTYPE_35_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1037,'Obras','Obras','LBL_EXT_ENTITY_SUBTYPE_37','LBL_EXT_ENTITY_SUBTYPE_37_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1038,'Obras previstas','Obras previstas','LBL_EXT_ENTITY_SUBTYPE_38','LBL_EXT_ENTITY_SUBTYPE_38_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1041,'Labores de poda','Labores de poda','LBL_EXT_ENTITY_SUBTYPE_41','LBL_EXT_ENTITY_SUBTYPE_41_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1042,'Trabajos en mediana','Trabajos en mediana','LBL_EXT_ENTITY_SUBTYPE_42','LBL_EXT_ENTITY_SUBTYPE_42_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1043,'Trabajos de pintura','Trabajos de pintura','LBL_EXT_ENTITY_SUBTYPE_43','LBL_EXT_ENTITY_SUBTYPE_43_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1045,'Limpieza de cuneta','Limpieza de cuneta','LBL_EXT_ENTITY_SUBTYPE_45','LBL_EXT_ENTITY_SUBTYPE_45_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1046,'Trabajos de mantenimiento','Trabajos de mantenimiento','LBL_EXT_ENTITY_SUBTYPE_46','LBL_EXT_ENTITY_SUBTYPE_46_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1047,'Trabajos de asfaltado','Trabajos de asfaltado','LBL_EXT_ENTITY_SUBTYPE_47','LBL_EXT_ENTITY_SUBTYPE_47_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1049,'Ramales cortados','Ramales cortados','LBL_EXT_ENTITY_SUBTYPE_49','LBL_EXT_ENTITY_SUBTYPE_49_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1051,'Reposición de bionda','Reposición de bionda','LBL_EXT_ENTITY_SUBTYPE_51','LBL_EXT_ENTITY_SUBTYPE_51_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1052,'Cortes de carril','Cortes de carril','LBL_EXT_ENTITY_SUBTYPE_52','LBL_EXT_ENTITY_SUBTYPE_52_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1056,'Trabajos en el firme','Trabajos en el firme','LBL_EXT_ENTITY_SUBTYPE_56','LBL_EXT_ENTITY_SUBTYPE_56_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(1,1057,'Trabajos de jardinería','Trabajos de jardinería','LBL_EXT_ENTITY_SUBTYPE_57','LBL_EXT_ENTITY_SUBTYPE_57_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

--Tipo 2 = C4 - Meteorologicas
(2,2001,'Hielo en la calzada','Hielo en la calzada','LBL_EXT_ENTITY_SUBTYPE_1','LBL_EXT_ENTITY_SUBTYPE_1_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2002,'Árboles, ramas, setos en la calzada','Árboles, ramas, setos en la calzada','LBL_EXT_ENTITY_SUBTYPE_2','LBL_EXT_ENTITY_SUBTYPE_2_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2006,'Piedras en la calzada','Piedras en la calzada','LBL_EXT_ENTITY_SUBTYPE_6','LBL_EXT_ENTITY_SUBTYPE_6_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2008,'Limpieza de barro en la calzada','Limpieza de barro en la calzada','LBL_EXT_ENTITY_SUBTYPE_8','LBL_EXT_ENTITY_SUBTYPE_8_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2014,'Daños a elementos de la carretera (bionda,farola)','Daños a elementos de la carretera (bionda,farola)','LBL_EXT_ENTITY_SUBTYPE_14','LBL_EXT_ENTITY_SUBTYPE_14_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2017,'Averías alumbrado y semáforos','Averías alumbrado y semáforos','LBL_EXT_ENTITY_SUBTYPE_17','LBL_EXT_ENTITY_SUBTYPE_17_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2020,'Desprendimientos (taludes,muros, o f, puentes...)','Desprendimientos (taludes,muros, o f, puentes...)','LBL_EXT_ENTITY_SUBTYPE_20','LBL_EXT_ENTITY_SUBTYPE_20_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2021,'Afecciones túneles','Afecciones túneles','LBL_EXT_ENTITY_SUBTYPE_21','LBL_EXT_ENTITY_SUBTYPE_21_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2025,'Varios','Varios','LBL_EXT_ENTITY_SUBTYPE_25','LBL_EXT_ENTITY_SUBTYPE_25_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2027,'Afecciones por temporal','Afecciones por temporal','LBL_EXT_ENTITY_SUBTYPE_27','LBL_EXT_ENTITY_SUBTYPE_27_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2035,'Nieve en calzada','Nieve en calzada','LBL_EXT_ENTITY_SUBTYPE_35','LBL_EXT_ENTITY_SUBTYPE_35_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2036,'Balsas de agua en calzada','Balsas de agua en calzada','LBL_EXT_ENTITY_SUBTYPE_36','LBL_EXT_ENTITY_SUBTYPE_36_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2039,'Inundación','Inundación','LBL_EXT_ENTITY_SUBTYPE_39','LBL_EXT_ENTITY_SUBTYPE_39_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2052,'Cortes de carril','Cortes de carril','LBL_EXT_ENTITY_SUBTYPE_52','LBL_EXT_ENTITY_SUBTYPE_52_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2054,'Afecciones por temporal (incidencias)','Afecciones por temporal (incidencias)','LBL_EXT_ENTITY_SUBTYPE_54','LBL_EXT_ENTITY_SUBTYPE_54_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,2058,'Corte carretera por incendio','Corte carretera por incendio','LBL_EXT_ENTITY_SUBTYPE_58','LBL_EXT_ENTITY_SUBTYPE_58_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),

-- Tipo 3 = C4 - Red viaria
(3,3002,'Árboles, ramas, setos en la calzada','Árboles, ramas, setos en la calzada','LBL_EXT_ENTITY_SUBTYPE_2','LBL_EXT_ENTITY_SUBTYPE_2_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3003,'Animales muertos en la calzada','Animales muertos en la calzada','LBL_EXT_ENTITY_SUBTYPE_3','LBL_EXT_ENTITY_SUBTYPE_3_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3004,'Animales vivos en la calzada','Animales vivos en la calzada','LBL_EXT_ENTITY_SUBTYPE_4','LBL_EXT_ENTITY_SUBTYPE_4_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3005,'Baches en la calzada','Baches en la calzada','LBL_EXT_ENTITY_SUBTYPE_5','LBL_EXT_ENTITY_SUBTYPE_5_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3006,'Piedras en la calzada','Piedras en la calzada','LBL_EXT_ENTITY_SUBTYPE_6','LBL_EXT_ENTITY_SUBTYPE_6_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3007,'Limpieza de productos sólidos','Limpieza de productos sólidos','LBL_EXT_ENTITY_SUBTYPE_7','LBL_EXT_ENTITY_SUBTYPE_7_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3008,'Limpieza de barro en la calzada','Limpieza de barro en la calzada','LBL_EXT_ENTITY_SUBTYPE_8','LBL_EXT_ENTITY_SUBTYPE_8_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3009,'Limpieza tras accidente','Limpieza tras accidente','LBL_EXT_ENTITY_SUBTYPE_9','LBL_EXT_ENTITY_SUBTYPE_9_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3010,'Limpieza de mat. const. (gravilla, hormigón,,,)','Limpieza de mat. const. (gravilla, hormigón,,,)','LBL_EXT_ENTITY_SUBTYPE_10','LBL_EXT_ENTITY_SUBTYPE_10_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3011,'Limpieza de cargas perdidas','Limpieza de cargas perdidas','LBL_EXT_ENTITY_SUBTYPE_11','LBL_EXT_ENTITY_SUBTYPE_11_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3012,'Limpieza de basuras en calzadalzada','Limpieza de basuras en calzadalzada','LBL_EXT_ENTITY_SUBTYPE_12','LBL_EXT_ENTITY_SUBTYPE_12_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3013,'Líquidos en calzada','Líquidos en calzada','LBL_EXT_ENTITY_SUBTYPE_13','LBL_EXT_ENTITY_SUBTYPE_13_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3014,'Daños a elementos de la carretera (bionda,farola)','Daños a elementos de la carretera (bionda,farola)','LBL_EXT_ENTITY_SUBTYPE_14','LBL_EXT_ENTITY_SUBTYPE_14_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3015,'Accidente en carretera','Accidente en carretera','LBL_EXT_ENTITY_SUBTYPE_15','LBL_EXT_ENTITY_SUBTYPE_15_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3016,'Accidente en interior de túnel','Accidente en interior de túnel','LBL_EXT_ENTITY_SUBTYPE_16','LBL_EXT_ENTITY_SUBTYPE_16_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3018,'Vehículos averiados','Vehículos averiados','LBL_EXT_ENTITY_SUBTYPE_18','LBL_EXT_ENTITY_SUBTYPE_18_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3019,'Vehículos averiados en interior túnel','Vehículos averiados en interior túnel','LBL_EXT_ENTITY_SUBTYPE_19','LBL_EXT_ENTITY_SUBTYPE_19_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3020,'Desprendimientos (taludes,muros, o f, puentes...)','Desprendimientos (taludes,muros, o f, puentes...)','LBL_EXT_ENTITY_SUBTYPE_20','LBL_EXT_ENTITY_SUBTYPE_20_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3021,'Afecciones túneles','Afecciones túneles','LBL_EXT_ENTITY_SUBTYPE_21','LBL_EXT_ENTITY_SUBTYPE_21_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3022,'Cortes y aperturas al tráfico','Cortes y aperturas al tráfico','LBL_EXT_ENTITY_SUBTYPE_22','LBL_EXT_ENTITY_SUBTYPE_22_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3023,'Señalización','Señalización','LBL_EXT_ENTITY_SUBTYPE_23','LBL_EXT_ENTITY_SUBTYPE_23_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3025,'Varios','Varios','LBL_EXT_ENTITY_SUBTYPE_25','LBL_EXT_ENTITY_SUBTYPE_25_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3026,'Aviso de incendio','Aviso de incendio','LBL_EXT_ENTITY_SUBTYPE_26','LBL_EXT_ENTITY_SUBTYPE_26_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3027,'Afecciones por temporal','Afecciones por temporal','LBL_EXT_ENTITY_SUBTYPE_27','LBL_EXT_ENTITY_SUBTYPE_27_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3029,'Postes sos','Postes sos','LBL_EXT_ENTITY_SUBTYPE_29','LBL_EXT_ENTITY_SUBTYPE_29_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3030,'Limpieza de productos agrícolas','Limpieza de productos agrícolas','LBL_EXT_ENTITY_SUBTYPE_30','LBL_EXT_ENTITY_SUBTYPE_30_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3035,'Nieve en calzada','Nieve en calzada','LBL_EXT_ENTITY_SUBTYPE_35','LBL_EXT_ENTITY_SUBTYPE_35_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3036,'Balsas de agua en calzada','Balsas de agua en calzada','LBL_EXT_ENTITY_SUBTYPE_36','LBL_EXT_ENTITY_SUBTYPE_36_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3044,'Túnel cerrado','Túnel cerrado','LBL_EXT_ENTITY_SUBTYPE_44','LBL_EXT_ENTITY_SUBTYPE_44_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3048,'Restricciones al tráfico','Restricciones al tráfico','LBL_EXT_ENTITY_SUBTYPE_48','LBL_EXT_ENTITY_SUBTYPE_48_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3050,'Retenciones','Retenciones','LBL_EXT_ENTITY_SUBTYPE_50','LBL_EXT_ENTITY_SUBTYPE_50_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3052,'Cortes de carril','Cortes de carril','LBL_EXT_ENTITY_SUBTYPE_52','LBL_EXT_ENTITY_SUBTYPE_52_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3054,'Afecciones por temporal (incidencias)','Afecciones por temporal (incidencias)','LBL_EXT_ENTITY_SUBTYPE_54','LBL_EXT_ENTITY_SUBTYPE_54_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,3058,'Corte carretera por incendio','Corte carretera por incendio','LBL_EXT_ENTITY_SUBTYPE_58','LBL_EXT_ENTITY_SUBTYPE_58_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
