INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(2, 22, 68, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 69, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 70, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 71, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 72, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 73, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 74, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 75, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 76, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 77, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 78, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 22, 79, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
