services:

  haproxy:
    image: haproxy:latest
    ports:
      - "6379:6379"
      - "9000:9000"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy  
    depends_on:
      - keydb-1
      - keydb-2
    restart: unless-stopped
      
  keydb-1:
    image: eqalpha/keydb:x86_64_v6.0.18
# add: --timeout 600 to timeout client connections
    command: keydb-server --port 6371 --requirepass rits --masterauth rits --server-threads 8 --active-replica yes --replicaof keydb-2 6372 --timeout 600
    ports:
      - "6371:6371"
    restart: unless-stopped

  keydb-2:
    image: eqalpha/keydb:x86_64_v6.0.18
# add: --timeout 600 to timeout client connections
    command: keydb-server --port 6372 --requirepass rits --masterauth rits --server-threads 8 --active-replica yes --replicaof keydb-1 6371 --timeout 600
    ports:
      - "6372:6372"
    restart: unless-stopped

  activemq:
    image: ivonet/activemq
    ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
    - "61614:61614"

    environment:
    - ACTIVEMQ_MIN_MEMORY=512
    - ACTIVEMQ_MAX_MEMORY=2048
    - ACTIVEMQ_ENABLED_AUTH=false
    - ACTIVEMQ_ADMIN_LOGIN=admin
    - ACTIVEMQ_ADMIN_PASSWORD=secret
    - ACTIVEMQ_USER_LOGIN=user
    - ACTIVEMQ_USER_PASSWORD=user
    volumes:
      - ./activemq/log/activemq:/var/log/activemq
    restart: unless-stopped
        
