
INSERT INTO ui.vo_entities(id, vo_entity_type_id, enabled, visible) VALUES
('ElementType:2', 'ElementTypeUI', true, true),
('ElementSubtype:1:2', 'ElementSubtypeUI', true, true),
('ElementSubtype:2:2', 'ElementSubtypeUI', true, true),
('ElementSubtype:3:2', 'ElementSubtypeUI', true, true),
('ElementSubtype:4:2', 'ElementSubtypeUI', true, true),
('ElementTypeParam:2:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:2', 'ElementTypeParamUI', true, true),

('ElementType:25', 'ElementTypeUI', true, true),
('ElementTypeParam:25:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:25:1:2', 'ElementTypeParamUI', true, true),

('Element:25:1', 'ElementUI', true, true),
('Element:25:2', 'ElementUI', true, true),
('Element:25:3', 'ElementUI', true, true),
('Element:25:4', 'ElementUI', true, true),
('Element:25:5', 'ElementUI', true, true),
('Element:25:6', 'ElementUI', true, true),
('Element:25:7', 'ElementUI', true, true),
('Element:25:8', 'ElementUI', true, true),
('Element:25:9', 'ElementUI', true, true),
('Element:25:10', 'ElementUI', true, true),
('Element:25:11', 'ElementUI', true, true),
('Element:25:12', 'ElementUI', true, true),
('Element:25:13', 'ElementUI', true, true),
('Element:25:14', 'ElementUI', true, true),
('Element:25:15', 'ElementUI', true, true),
('Element:25:16', 'ElementUI', true, true),
('Element:25:17', 'ElementUI', true, true),
('Element:25:18', 'ElementUI', true, true),
('Element:25:19', 'ElementUI', true, true),
('Element:25:20', 'ElementUI', true, true),
('Element:25:21', 'ElementUI', true, true),
('Element:25:22', 'ElementUI', true, true),
('Element:25:23', 'ElementUI', true, true),
('Element:25:24', 'ElementUI', true, true),
('Element:25:25', 'ElementUI', true, true),
('Element:25:26', 'ElementUI', true, true),
('Element:25:27', 'ElementUI', true, true),
('Element:25:28', 'ElementUI', true, true),
('Element:25:29', 'ElementUI', true, true),
('Element:25:30', 'ElementUI', true, true),
('Element:25:31', 'ElementUI', true, true),
('Element:25:32', 'ElementUI', true, true),
('Element:25:33', 'ElementUI', true, true),
('Element:25:34', 'ElementUI', true, true),
('Element:25:35', 'ElementUI', true, true),
('Element:25:36', 'ElementUI', true, true),
('Element:25:37', 'ElementUI', true, true),
('Element:25:38', 'ElementUI', true, true),
('Element:25:39', 'ElementUI', true, true),
('Element:25:40', 'ElementUI', true, true),
('Element:25:41', 'ElementUI', true, true),
('Element:25:42', 'ElementUI', true, true),
('Element:25:43', 'ElementUI', true, true),
('Element:25:44', 'ElementUI', true, true),
('Element:25:45', 'ElementUI', true, true),
('Element:25:46', 'ElementUI', true, true),
('Element:25:47', 'ElementUI', true, true),
('Element:25:48', 'ElementUI', true, true),

('ElementType:52', 'ElementTypeUI', true, true),
('ElementTypeParam:52:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:52:1:1004', 'ElementTypeParamUI', true, true),

-- ('ElementType:52', 'ElementTypeUI', true, true),
-- ('ElementTypeParam:52:1:1', 'ElementTypeParamUI', true, true),
-- ('ElementTypeParam:52:1:2', 'ElementTypeParamUI', true, true),
-- ('ElementTypeParam:52:1:1004', 'ElementTypeParamUI', true, true),
-- 
('Element:52:1', 'ElementUI', true, true),
('Element:52:2', 'ElementUI', true, true),



('ElementType:71', 'ElementTypeUI', true, true),
('ElementSubtype:19:71', 'ElementSubtypeUI', true, true),
('ElementTypeParam:71:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:3', 'ElementTypeParamUI', true, true),

('ElementType:95', 'ElementTypeUI', true, true),
('ElementTypeParam:95:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:95:1:2', 'ElementTypeParamUI', true, true);

