UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 10001; --LBL_ALARM_CONFIGS_ALARM_WS_NO_CONNECTION
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 70001; --LBL_ALARM_CONFIGS_ALARM_WS_VISIBILIMETER_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 80001; --LBL_ALARM_CONFIGS_ALARM_WS_AIR_TEMPERATURE_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 90001; --LBL_ALARM_CONFIGS_ALARM_WS_RELATIVE_HUMIDITY_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 100001; --LBL_ALARM_CONFIGS_ALARM_WS_AIR_PRESSURE_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 110001; --LBL_ALARM_CONFIGS_ALARM_WS_WIND_SPEED_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 120001; --LBL_ALARM_CONFIGS_ALARM_WS_WIND_DIRECTION_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 130001; --LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_TYPE_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 140001; --LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_INTENSITY_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 150001; --LBL_ALARM_CONFIGS_ALARM_WS_PRECIPITATION_DIFFERENTIAL_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 160001; --LBL_ALARM_CONFIGS_ALARM_WS_SURFACE_TEMPERATURE_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 170001; --LBL_ALARM_CONFIGS_ALARM_WS_FREEZE_SURFACE_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 180001; --LBL_ALARM_CONFIGS_ALARM_WS_WATER_DEPTH_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 190001; --LBL_ALARM_CONFIGS_ALARM_WS_ICE_PERCENT_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 200001; --LBL_ALARM_CONFIGS_ALARM_WS_FRICTION_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 1 AND alarm_config_id = 210001; --LBL_ALARM_CONFIGS_ALARM_WS_ROAD_CONDITION_FAIL
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 1 AND alarm_config_id = 3010001; --LBL_ALARM_CONFIGS_ALARM_WS_NORMAL_INTENSITY
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 1 AND alarm_config_id = 3020001; --LBL_ALARM_CONFIGS_ALARM_WS_VISIBILITY
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 1 AND alarm_config_id = 3030001; --LBL_ALARM_CONFIGS_ALARM_WS_WIND_SPEED
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = False WHERE element_type_id = 1 AND alarm_config_id = 3040001; --LBL_ALARM_CONFIGS_ALARM_WS_CRITICAL_INTENSITY
