UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 29; --LBL_ALARM_CONFIGS_ALARM_CAMERA_NO_CONNECTION
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1070002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_1
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1080002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_2
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1090002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_3
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1100002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_4
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1110002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_5
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1120002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_6
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1130002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_7
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1140002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_8
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1150002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_9
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1160002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_10
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1170002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_11
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1180002; --LBL_ALARM_CONFIGS_ALARM_DAI_SLOW_VEH_LANE_12
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1190002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_1
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1200002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_2
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1210002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_3
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1220002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_4
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1230002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_5
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1240002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_6
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1250002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_7
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1260002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_8
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1270002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_9
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1280002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_10
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1290002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_11
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1300002; --LBL_ALARM_CONFIGS_ALARM_DAI_STOP_VEH_LANE_12
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1310002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_1
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1320002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_2
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1330002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_3
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1340002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_4
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1350002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_5
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1360002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_6
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1370002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_7
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1380002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_8
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1390002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_9
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1400002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_10
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1410002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_11
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1420002; --LBL_ALARM_CONFIGS_ALARM_DAI_DEBRIS_LANE_12
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1430002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_1
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1440002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_2
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1450002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_3
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1460002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_4
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1470002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_5
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1480002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_6
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1490002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_7
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1500002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_8
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1510002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_9
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1520002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_10
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1530002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_11
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1540002; --LBL_ALARM_CONFIGS_ALARM_DAI_PEDESTRIAN_LANE_12
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1550002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_1
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1560002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_2
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1570002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_3
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1580002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_4
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1590002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_5
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1600002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_6
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1610002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_7
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1620002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_8
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1630002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_9
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1640002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_10
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1650002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_11
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1660002; --LBL_ALARM_CONFIGS_ALARM_DAI_VISIBILITY_LANE_12
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1670002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_1
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1680002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_2
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1690002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_3
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1700002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_4
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1710002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_5
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1720002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_6
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1730002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_7
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1740002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_8
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1750002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_9
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1760002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_10
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1770002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_11
UPDATE conf.alarm_configs SET alarm_level_id = 4, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1780002; --LBL_ALARM_CONFIGS_ALARM_DAI_CONGESTION_LANE_12
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1790002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_1
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1800002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_2
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1810002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_3
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1820002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_4
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1830002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_5
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1840002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_6
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1850002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_7
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1860002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_8
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1870002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_9
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1880002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_10
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1890002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_11
UPDATE conf.alarm_configs SET alarm_level_id = 5, enabled = True, treatment = True WHERE element_type_id = 2 AND alarm_config_id = 1900002; --LBL_ALARM_CONFIGS_ALARM_DAI_KAMIKAZE_LANE_12
