INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(53, 2, 1, 0010053, NULL, NULL, 'IVEN-SEM-RR-BAR-001', 'IVEN-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 2, 0020053, NULL, NULL, 'ICEO-SEM-RR-BAR-001', 'ICEO-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 3, 0030053, NULL, NULL, 'ICEP-SEM-RR-BAR-001', 'ICEP-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 4, 0040053, NULL, NULL, 'S1TS-SEM-RR-BAR-001', 'S1TS-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 5, 0050053, NULL, NULL, 'S1TS-SEM-RR-BAR-002', 'S1TS-SEM-RR-BAR-002', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 6, 0060053, NULL, NULL, 'INKP-SEM-RR-BAR-001', 'INKP-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 7, 0070053, NULL, NULL, 'IVIP-SEM-RR-BAR-001', 'IVIP-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 8, 0080053, NULL, NULL, 'IPRO-SEM-RR-BAR-001', 'IPRO-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 9, 0090053, NULL, NULL, 'ICCO-SEM-RR-BAR-001', 'ICCO-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 10, 0100053, NULL, NULL, 'ICCP-SEM-RR-BAR-001', 'ICCP-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 11, 0110053, NULL, NULL, 'IBTO-SEM-RR-BAR-001', 'IBTO-SEM-RR-BAR-001', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(53, 1003, 1, 1, NULL, 'IVEN-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 2, NULL, 'ICEO-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 3, NULL, 'ICEP-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 4, NULL, 'S1TS-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 5, NULL, 'S1TS-SEM-RR-BAR-002', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 6, NULL, 'INKP-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 7, NULL, 'IVIP-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 8, NULL, 'IPRO-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 9, NULL, 'ICCO-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 10, NULL, 'ICCP-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(53, 1003, 1, 11, NULL, 'IBTO-SEM-RR-BAR-001', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(53, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(53, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
