vms.subtype_1.alternance=0
vms.subtype_1.flashing_on=0
vms.subtype_1.flashing_off=0
vms.subtype_1.num_zones=6
vms.subtype_1.typezone_1=graphic
vms.subtype_1.typezone_2=graphic
vms.subtype_1.typezone_3=graphic
vms.subtype_1.typezone_4=text
vms.subtype_1.zone_4.text.num_lines=1
vms.subtype_1.typezone_5=graphic
vms.subtype_1.typezone_6=graphic

vms.subtype_2.alternance=0
vms.subtype_2.flashing_on=0
vms.subtype_2.flashing_off=0
vms.subtype_2.num_zones=10
vms.subtype_2.typezone_1=graphic
vms.subtype_2.typezone_2=graphic
vms.subtype_2.typezone_3=graphic
vms.subtype_2.typezone_4=text
vms.subtype_2.zone_4.text.num_lines=1
vms.subtype_2.typezone_5=graphic
vms.subtype_2.typezone_6=graphic
vms.subtype_2.typezone_7=graphic
vms.subtype_2.typezone_8=text
vms.subtype_2.zone_8.text.num_lines=1
vms.subtype_2.typezone_9=graphic
vms.subtype_2.typezone_10=graphic

vms.subtype_3.alternance=0
vms.subtype_3.flashing_on=0
vms.subtype_3.flashing_off=0
vms.subtype_3.num_zones=6
vms.subtype_3.typezone_1=graphic
vms.subtype_3.typezone_2=graphic
vms.subtype_3.typezone_3=graphic
vms.subtype_3.typezone_4=text
vms.subtype_3.zone_4.text.num_lines=1

vms.subtype_4.alternance=0
vms.subtype_4.flashing_on=0
vms.subtype_4.flashing_off=0
vms.subtype_4.num_zones=3
vms.subtype_4.typezone_1=graphic
vms.subtype_4.typezone_2=text
vms.subtype_4.zone_2.text.num_lines=3
vms.subtype_4.typezone_3=text
vms.subtype_4.zone_3.text.num_lines=1

vms.subtype_5.alternance=0
vms.subtype_5.flashing_on=0
vms.subtype_5.flashing_off=0
vms.subtype_5.num_zones=1
vms.subtype_5.typezone_1=dual
vms.subtype_5.zone_1.text.num_lines=3

vms.subtype_6.alternance=0
vms.subtype_6.flashing_on=0
vms.subtype_6.flashing_off=0
vms.subtype_6.num_zones=1
vms.subtype_6.typezone_1=graphic

vms.subtype_7.alternance=0
vms.subtype_7.flashing_on=0
vms.subtype_7.flashing_off=0
vms.subtype_7.num_zones=6
vms.subtype_7.typezone_1=graphic
vms.subtype_7.typezone_2=graphic
vms.subtype_7.typezone_3=text
vms.subtype_7.zone_3.text.num_lines=1
vms.subtype_7.typezone_4=text
vms.subtype_7.zone_4.text.num_lines=1
vms.subtype_7.typezone_5=text
vms.subtype_7.zone_5.text.num_lines=1
vms.subtype_7.typezone_6=text
vms.subtype_7.zone_6.text.num_lines=1

vms.subtype_8.alternance=0
vms.subtype_8.flashing_on=0
vms.subtype_8.flashing_off=0
vms.subtype_8.num_zones=2
vms.subtype_8.typezone_1=graphic
vms.subtype_8.typezone_2=text
vms.subtype_8.zone_2.text.num_lines=1

vms.subtype_9.alternance=5000
vms.subtype_9.flashing_on=0
vms.subtype_9.flashing_off=0
vms.subtype_9.num_zones=2
vms.subtype_9.typezone_1=graphic
vms.subtype_9.typezone_2=text
vms.subtype_9.zone_2.text.num_lines=3

vms.subtype_11.flashing_on=1000
vms.subtype_11.flashing_off=1000
vms.subtype_11.num_zones=1
vms.subtype_11.typezone_1=graphic

vms.subtype_12.flashing_on=1000
vms.subtype_12.flashing_off=1000
vms.subtype_12.num_zones=1
vms.subtype_12.typezone_1=graphic

vms.subtype_13.alternance=0
vms.subtype_13.flashing_on=0
vms.subtype_13.flashing_off=0
vms.subtype_13.num_zones=1
vms.subtype_13.typezone_1=text
vms.subtype_13.zone_1.text.num_lines=1

vms.subtype_14.alternance=0
vms.subtype_14.flashing_on=0
vms.subtype_14.flashing_off=0
vms.subtype_14.num_zones=2
vms.subtype_14.typezone_1=graphic
vms.subtype_14.typezone_2=text
vms.subtype_14.zone_2.text.num_lines=2

vms.subtype_15.alternance=0
vms.subtype_15.flashing_on=0
vms.subtype_15.flashing_off=0
vms.subtype_15.num_zones=3
vms.subtype_15.typezone_1=graphic
vms.subtype_15.typezone_2=graphic
vms.subtype_15.typezone_3=text
vms.subtype_15.zone_3.text.num_lines=2

vms.subtype_16.alternance=5000
vms.subtype_16.flashing_on=0
vms.subtype_16.flashing_off=0
vms.subtype_16.num_zones=1
vms.subtype_16.typezone_1=text
vms.subtype_16.zone_1.text.num_lines=1
vms.subtype_16.color=#E2943A

vms.subtype_17.alternance=0
vms.subtype_17.flashing_on=0
vms.subtype_17.flashing_off=0
vms.subtype_17.num_zones=2
vms.subtype_17.typezone_1=graphic
vms.subtype_17.typezone_2=graphic

vms.subtype_18.alternance=5000
vms.subtype_18.flashing_on=0
vms.subtype_18.flashing_off=0
vms.subtype_18.num_zones=2
vms.subtype_18.typezone_1=graphic
vms.subtype_18.typezone_2=text
vms.subtype_18.zone_2.text.num_lines=3

vms.subtype_19.alternance=5000
vms.subtype_19.flashing_on=1000
vms.subtype_19.flashing_off=1000
vms.subtype_19.num_zones=2
vms.subtype_19.typezone_1=graphic
vms.subtype_19.typezone_2=text
vms.subtype_19.zone_2.text.num_lines=3
vms.subtype_19.color=#E2943A

vms.subtype_20.alternance=0
vms.subtype_20.flashing_on=0
vms.subtype_20.flashing_off=0
vms.subtype_20.num_zones=1
vms.subtype_20.typezone_1=text
vms.subtype_20.zone_1.text.num_lines=4

vms.subtype_21.alternance=0
vms.subtype_21.flashing_on=0
vms.subtype_21.flashing_off=0
vms.subtype_21.num_zones=1
vms.subtype_21.typezone_1=text
vms.subtype_21.zone_1.text.num_lines=2

vms.subtype_22.alternance=0
vms.subtype_22.flashing_on=0
vms.subtype_22.flashing_off=0
vms.subtype_22.num_zones=3
vms.subtype_22.typezone_1=graphic
vms.subtype_22.typezone_2=text
vms.subtype_22.typezone_3=graphic
vms.subtype_22.zone_2.text.num_lines=3
