INSERT INTO ui.vo_entities(id, vo_entity_type_id, enabled, visible) VALUES
('ElementTypeParam:2:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:2:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:3:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:11', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:12', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:14', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:15', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:16', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:17', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:20', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:21', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:22', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:23', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:24', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:25', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:26', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:27', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:28', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:29', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:30', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:31', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:32', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:33', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:34', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:35', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:40', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:41', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:42', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:43', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:44', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:45', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:46', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:47', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:48', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:49', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:50', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:51', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:52', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:53', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:54', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:55', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:60', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:61', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:62', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:63', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:64', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:65', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:66', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:67', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:68', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:69', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:70', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:71', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:72', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:73', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:74', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:75', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:80', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:81', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:82', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:83', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:84', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:85', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:86', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:87', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:88', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:89', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:90', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:91', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:92', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:93', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:94', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:95', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:100', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:101', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:102', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:103', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:104', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:105', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:106', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:107', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:108', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:109', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:110', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:111', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:112', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:120', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:121', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:122', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:123', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:124', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:125', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:126', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:127', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:128', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:129', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:130', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:131', 'ElementTypeParamUI', true, true),
('ElementTypeParam:3:2:132', 'ElementTypeParamUI', true, true),

('ElementTypeParam:4:1:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:8', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:10', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:11', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:12', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:13', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:18', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:60', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:61', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:80', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:81', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:82', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:83', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:100', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:101', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:120', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:121', 'ElementTypeParamUI', true, true),
('ElementTypeParam:4:2:122', 'ElementTypeParamUI', true, true),

('ElementTypeParam:8:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:8:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:8:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:8:2:2', 'ElementTypeParamUI', true, true),



('ElementTypeParam:9:1:5', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:1:6', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:1', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:2', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:3', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:4', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:7', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:8', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:14', 'ElementTypeParamUI', true,  true),
('ElementTypeParam:9:2:15', 'ElementTypeParamUI', true,  true),


('ElementTypeParam:11:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:11:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:19:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:19:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:19:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:20:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:20:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:20:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:21:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:21:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:21:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:49:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:49:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:49:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:51:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:51:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:58:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:58:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:59:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:59:1:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:62:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:62:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:62:2:3', 'ElementTypeParamUI', true, true),

('ElementTypeParam:63:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:63:2:2', 'ElementTypeParamUI', true, true),

('ElementTypeParam:71:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:1:9', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:4', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:6', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:7', 'ElementTypeParamUI', true, true),
('ElementTypeParam:71:2:10', 'ElementTypeParamUI', true, true),

('ElementTypeParam:84:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:84:1:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:84:1:5', 'ElementTypeParamUI', true, true),
('ElementTypeParam:84:2:1', 'ElementTypeParamUI', true, true),

('ElementTypeParam:86:2:2', 'ElementTypeParamUI', true, true),
('ElementTypeParam:86:2:3', 'ElementTypeParamUI', true, true),
('ElementTypeParam:86:2:4', 'ElementTypeParamUI', true, true),

('ElementTypeParam:89:1:1', 'ElementTypeParamUI', true, true),
('ElementTypeParam:89:1:2', 'ElementTypeParamUI', true, true);
