INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(84, NULL, 1, 0010084, NULL, NULL, 'TUN-CONT-AA1-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 2, 0020084, NULL, NULL, 'TUN-CONT-AA15-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 3, 0030084, NULL, NULL, 'TUN-CONT-AA2-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 4, 0040084, NULL, NULL, 'TUN-CONT-AA16-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 5, 0050084, NULL, NULL, 'TUN-CONT-AA11-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 6, 0060084, NULL, NULL, 'TUN-CONT-AA21-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 7, 0070084, NULL, NULL, 'TUN-CONT-AA10-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 8, 0080084, NULL, NULL, 'TUN-CONT-AA20-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 9, 0090084, NULL, NULL, 'TUN-CONT-AE14-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 10, 0100084, NULL, NULL, 'TUN-CONT-AE9-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 11, 0110084, NULL, NULL, 'TUN-CONT-A29-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 12, 0120084, NULL, NULL, 'TUN-CONT-A30-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 13, 0130084, NULL, NULL, 'TUN-CONT-A31-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 14, 0140084, NULL, NULL, 'TUN-CONT-A32-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 15, 0150084, NULL, NULL, 'TUN-CONT-A3-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 16, 0160084, NULL, NULL, 'TUN-CONT-A5-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 17, 0170084, NULL, NULL, 'TUN-CONT-A4-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 18, 0180084, NULL, NULL, 'TUN-CONT-A6-SC', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 19, 0190084, NULL, NULL, 'TUN-CONT-A13-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 20, 0200084, NULL, NULL, 'TUN-CONT-A23-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 21, 0210084, NULL, NULL, 'TUN-CONT-A12-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 22, 0220084, NULL, NULL, 'TUN-CONT-A22-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 23, 0230084, NULL, NULL, 'TUN-CONT-A33-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 24, 0240084, NULL, NULL, 'TUN-CONT-A34-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 25, 0250084, NULL, NULL, 'TUN-CONT-A35-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 26, 0260084, NULL, NULL, 'TUN-CONT-A36-SM', 'Cont. 16 A,IV', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 27, 0270084, NULL, NULL, 'TUN-CONT-BF15', 'Cont. 16 A.', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 28, 0280084, NULL, NULL, 'TUN-CONT-BF16', 'Cont. 16 A.', NULL, NULL, 'SendStateToIllumination.groovy', NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 29, 0290084, NULL, NULL, 'HOSP-ILUM-L1-P1', 'HOSP-ILUM-L1-P1', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 30, 0300084, NULL, NULL, 'HOSP-ILUM-L1-P2', 'HOSP-ILUM-L1-P2', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 31, 0310084, NULL, NULL, 'HOSP-ILUM-L1-P3', 'HOSP-ILUM-L1-P3', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 32, 0320084, NULL, NULL, 'HOSP-ILUM-L1-P4', 'HOSP-ILUM-L1-P4', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 33, 0330084, NULL, NULL, 'HOSP-ILUM-L1-P5', 'HOSP-ILUM-L1-P5', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 34, 0340084, NULL, NULL, 'HOSP-ILUM-L1-P6', 'HOSP-ILUM-L1-P6', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 35, 0350084, NULL, NULL, 'HOSP-ILUM-L1-P7', 'HOSP-ILUM-L1-P7', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 36, 0360084, NULL, NULL, 'HOSP-ILUM-L1-P8', 'HOSP-ILUM-L1-P8', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 37, 0370084, NULL, NULL, 'HOSP-ILUM-L1-P9', 'HOSP-ILUM-L1-P9', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 38, 0380084, NULL, NULL, 'HOSP-ILUM-L2-P1', 'HOSP-ILUM-L2-P1', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 39, 0390084, NULL, NULL, 'HOSP-ILUM-L2-P2', 'HOSP-ILUM-L2-P2', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 40, 0400084, NULL, NULL, 'HOSP-ILUM-L2-P3', 'HOSP-ILUM-L2-P3', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 41, 0410084, NULL, NULL, 'HOSP-ILUM-L2-P4', 'HOSP-ILUM-L2-P4', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 42, 0420084, NULL, NULL, 'HOSP-ILUM-L2-P5', 'HOSP-ILUM-L2-P5', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 43, 0430084, NULL, NULL, 'HOSP-ILUM-L2-P6', 'HOSP-ILUM-L2-P6', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 44, 0440084, NULL, NULL, 'HOSP-ILUM-L2-P7', 'HOSP-ILUM-L2-P7', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 45, 0450084, NULL, NULL, 'HOSP-ILUM-L3-P1', 'HOSP-ILUM-L3-P1', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 46, 0460084, NULL, NULL, 'HOSP-ILUM-L3-P2', 'HOSP-ILUM-L3-P2', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 47, 0470084, NULL, NULL, 'HOSP-ILUM-L3-P3', 'HOSP-ILUM-L3-P3', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 48, 0480084, NULL, NULL, 'HOSP-ILUM-L3-P4', 'HOSP-ILUM-L3-P4', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, NULL, 49, 0490084, NULL, NULL, 'HOSP-ILUM-L3-P5', 'HOSP-ILUM-L3-P5', NULL, 'SendStateToIllumination.groovy', NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(84, 5, 1, 1, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 1, NULL, 'TUN-CONT-AA1-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 2, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 2, NULL, 'TUN-CONT-AA15-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 3, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 3, NULL, 'TUN-CONT-AA2-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 4, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 4, NULL, 'TUN-CONT-AA16-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 5, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 5, NULL, 'TUN-CONT-AA11-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 6, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 6, NULL, 'TUN-CONT-AA21-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 7, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 7, NULL, 'TUN-CONT-AA10-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 8, NULL, 'Permanente', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 8, NULL, 'TUN-CONT-AA20-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 9, NULL, 'Guiado', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 9, NULL, 'TUN-CONT-AE14-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 10, NULL, 'Guiado', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 10, NULL, 'TUN-CONT-AE9-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 11, NULL, 'Aproximación', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 11, NULL, 'TUN-CONT-A29-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 12, NULL, 'Aproximación', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 12, NULL, 'TUN-CONT-A30-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 13, NULL, 'Aproximación', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 13, NULL, 'TUN-CONT-A31-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 14, NULL, 'Aproximación', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 14, NULL, 'TUN-CONT-A32-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 15, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 15, NULL, 'TUN-CONT-A3-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 16, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 16, NULL, 'TUN-CONT-A5-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 17, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 17, NULL, 'TUN-CONT-A4-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 18, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 18, NULL, 'TUN-CONT-A6-SC', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 19, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 19, NULL, 'TUN-CONT-A13-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 20, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 20, NULL, 'TUN-CONT-A23-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 21, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 21, NULL, 'TUN-CONT-A12-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 22, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 22, NULL, 'TUN-CONT-A22-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 23, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 23, NULL, 'TUN-CONT-A33-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 24, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 24, NULL, 'TUN-CONT-A34-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 25, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 25, NULL, 'TUN-CONT-A35-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 5, 1, 26, NULL, 'Refuerzo', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 1003, 1, 26, NULL, 'TUN-CONT-A36-SM', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 27, NULL, 'TUN-CONT-BF15', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 28, NULL, 'TUN-CONT-BF16', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 29, NULL, 'HOSP-ILUM-L1-P1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 30, NULL, 'HOSP-ILUM-L1-P2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 31, NULL, 'HOSP-ILUM-L1-P3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 32, NULL, 'HOSP-ILUM-L1-P4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 33, NULL, 'HOSP-ILUM-L1-P5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 34, NULL, 'HOSP-ILUM-L1-P6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 35, NULL, 'HOSP-ILUM-L1-P7', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 36, NULL, 'HOSP-ILUM-L1-P8', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 37, NULL, 'HOSP-ILUM-L1-P9', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 38, NULL, 'HOSP-ILUM-L2-P1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 39, NULL, 'HOSP-ILUM-L2-P2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 40, NULL, 'HOSP-ILUM-L2-P3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 41, NULL, 'HOSP-ILUM-L2-P4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 42, NULL, 'HOSP-ILUM-L2-P5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 43, NULL, 'HOSP-ILUM-L2-P6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 44, NULL, 'HOSP-ILUM-L2-P7', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 45, NULL, 'HOSP-ILUM-L3-P1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 46, NULL, 'HOSP-ILUM-L3-P2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 47, NULL, 'HOSP-ILUM-L3-P3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 48, NULL, 'HOSP-ILUM-L3-P4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(84, 1003, 1, 49, NULL, 'HOSP-ILUM-L3-P5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(84, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 19, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 20, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 21, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 22, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 23, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 24, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 25, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 26, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 27, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 28, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 29, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 30, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 31, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 32, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 33, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 34, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 35, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 36, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 37, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 38, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 39, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 40, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 41, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 42, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 43, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 44, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 45, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 46, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 47, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 48, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(84, 49, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
