INSERT INTO conf.elements (element_type_id, element_subtype_id, element_id, location_id, keep_values_on_disconnected, inherit_state_id, alias, description, on_change_alarm, on_change_state, on_change_measure, on_schedule, enabled, visible, alert, alarm_count, created_at, updated_at) VALUES
(2, NULL, 1, 0010002, NULL, NULL,  '00.3-ASC-DOM-01', '00.3-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 2, 0020002, NULL, NULL,  '00.8-ASC-DOM-01', '00.8-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 3, 0030002, NULL, NULL,  '01.1-ECT-DOM-01', '01.1-ECT-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 4, 0040002, NULL, NULL,  '01.2-ASC-DOM-01', '01.2-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 5, 0050002, NULL, NULL,  '01.8-MR1-DOM-01', '01.8-MR1-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 6, 0060002, NULL, NULL,  '01.8-MR1-DOM-02', '01.8-MR1-DOM-02', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 7, 0070002, NULL, NULL,  '02.3-ASC-DOM-01', '02.3-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 8, 0080002, NULL, NULL,  '02.8-ASC-DOM-01', '02.8-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 9, 0090002, NULL, NULL,  '03.3-ASC-DOM-01', '03.3-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 10, 0100002, NULL, NULL, '03.8-ASC-DOM-01', '03.8-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 11, 0110002, NULL, NULL, '04.3-MR2-DOM-01', '04.3-MR2-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 12, 0120002, NULL, NULL, '04.4-MR2-DOM-01', '04.4-MR2-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 13, 0130002, NULL, NULL, '04.6-ASC-DOM-01', '04.6-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 14, 0140002, NULL, NULL, '05.1-ASC-DOM-01', '05.1-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 15, 0150002, NULL, NULL, '05.5-ASC-DOM-01', '05.5-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 16, 0160002, NULL, NULL, '00.0-EBT-DOM-01', '00.0-EBT-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 17, 0170002, NULL, NULL, '06.0-ASC-DOM-01', '06.0-ASC-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, NULL, 18, 0180002, NULL, NULL, '00.3-AAE-DOM-01', '00.3-AAE-DOM-01', NULL, NULL, NULL, NULL, true, true, false, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_values (element_type_id, element_type_param_id, param_type_id, element_id, element_value_state_id, value, enabled, visible, created_at, updated_at) VALUES
(2, 1, 1, 1, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 1, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 1, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=00.3-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 1, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 1, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 1, NULL, '10.20.1.2', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 1, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 1, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 1, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 1, NULL, '00.3-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 2, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 2, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 2, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=00.8-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 2, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 2, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 2, NULL, '10.20.1.3', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 2, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 2, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 2, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 2, NULL, '00.8-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 3, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 3, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 3, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=01.1-ECT-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 3, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 3, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 3, NULL, '10.20.1.1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 3, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 3, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 3, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 3, NULL, '01.1-ECT-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 4, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 4, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 4, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=01.2-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 4, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 4, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 4, NULL, '10.20.1.4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 4, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 4, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 4, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 4, NULL, '01.2-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 5, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 5, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 5, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=01.8-MR1-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 5, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 5, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 5, NULL, '10.20.1.5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 5, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 5, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 5, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 5, NULL, '01.8-MR1-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 6, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 6, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 6, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=01.8-MR1-DOM-02', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 6, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 6, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 6, NULL, '10.20.1.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 6, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 6, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 6, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 6, NULL, '01.8-MR1-DOM-02', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 7, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 7, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 7, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=02.3-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 7, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 7, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 7, NULL, '10.20.1.7', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 7, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 7, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 7, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 7, NULL, '02.3-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 8, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 8, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 8, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=02.8-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 8, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 8, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 8, NULL, '10.20.1.8', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 8, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 8, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 8, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 8, NULL, '02.8-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 9, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 9, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 9, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=03.3-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 9, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 9, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 9, NULL, '10.20.1.9', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 9, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 9, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 9, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 9, NULL, '03.3-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 10, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 10, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 10, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=03.8-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 10, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 10, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 10, NULL, '10.20.1.10', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 10, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 10, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 10, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 10, NULL, '03.8-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 11, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 11, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 11, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=04.3-MR2-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 11, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 11, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 11, NULL, '10.20.2.10', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 11, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 11, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 11, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 11, NULL, '04.3-MR2-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 12, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 12, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 12, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=04.4-MR2-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 12, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 12, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 12, NULL, '10.20.2.9', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 12, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 12, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 12, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 12, NULL, '04.4-MR2-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 13, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 13, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 13, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=04.6-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 13, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 13, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 13, NULL, '10.20.2.8', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 13, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 13, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 13, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 13, NULL, '04.6-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 14, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 14, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 14, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=05.1-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 14, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 14, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 14, NULL, '10.20.2.7', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 14, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 14, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 14, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 14, NULL, '05.1-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 15, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 15, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 15, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=05.5-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 15, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 15, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 15, NULL, '10.20.2.6', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 15, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 15, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 15, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 15, NULL, '05.5-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 16, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 16, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 16, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=00.0-EBT-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 16, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 16, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 16, NULL, '10.20.2.1', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 16, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 16, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 16, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 16, NULL, '00.0-EBT-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 17, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 17, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 17, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=06.0-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 17, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 17, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 17, NULL, '10.20.2.5', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 17, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 17, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 17, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 17, NULL, '06.0-ASC-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 

(2, 1, 1, 18, NULL, 'HIKVISION', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 18, NULL, 'DS-2DE7A432IW-AEB_MJPEG', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 18, NULL, 'http://10.140.31.105:8080/rtc/api/stream.mjpeg?src=00.3-AAE-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 6, 1, 18, NULL, '[{"id": 1,"alias": "Preset 1","description": "Preset 1","default": true},{"id": 2,"alias": "Preset 2","description": "Preset 2","default": false},{"id": 3,"alias": "Preset 3","description": "Preset 3","default": false},{"id": 4,"alias": "Preset 4","description": "Preset 4","default": false},{"id": 5,"alias": "Preset 5","description": "Preset 5","default": false},{"id": 6,"alias": "Preset 6","description": "Preset 6","default": false}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 18, NULL, 'PTZ', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 18, NULL, '10.20.2.4', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 18, NULL, 'admin', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 18, NULL, 'Revenga2025.', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 18, NULL, '[{"id":1,"label":"LBL_X0","authType":"base64","commands":[{"name":"up","value":"1"},{"name":"down","value":"1"},{"name":"left","value":"1"},{"name":"right","value":"1"},{"name":"tele","value":"1"},{"name":"wide","value":"1"}]},{"id":2,"label":"LBL_X1","authType":"base64","commands":[{"name":"up","value":"2"},{"name":"down","value":"2"},{"name":"left","value":"2"},{"name":"right","value":"2"},{"name":"tele","value":"2"},{"name":"wide","value":"2"}]}]', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),  
(2, 1003, 1, 18, NULL, '00.3-AAE-DOM-01', true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.element_io_controller_modules (element_type_id, element_id, module_type_id, module_id, enabled, visible, created_at, updated_at) VALUES
(2, 1, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 2, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 3, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 4, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 5, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 6, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 7, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 8, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 9, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 10, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 11, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 12, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 13, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 14, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 15, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 16, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 17, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
(2, 18, 1, 1, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);