UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 010009; --LBL_ALARM_CONFIGS_ALARM_JETFAN_DISCONNECTED
UPDATE conf.alarm_configs SET alarm_level_id = 1, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 020009; --LBL_ALARM_CONFIGS_ALARM_JETFAN_SENSOR_TEMPERATURE
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 030009; --LBL_ALARM_CONFIGS_ALARM_TEMPERATURE_MOTOR_WINDING
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 140009; --LBL_ALARM_CONFIGS_ALARM_JETFAN_FRONT_MOTOR_BEARING_OUT_OF_RANGE
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 150009; --LBL_ALARM_CONFIGS_ALARM_JETFAN_BACK_MOTOR_BEARING_OUT_OF_RANGE
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 100009; --LBL_ALARM_CONFIGS_ALARM_HIGH_VIBRATION
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 3020009; --LBL_ALARM_CONFIGS_ALARM_MAX_VIBRATION
UPDATE conf.alarm_configs SET alarm_level_id = 2, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 3030009; --LBL_ALARM_CONFIGS_ALARM_MAX_FRONT_BEARING_TEMP
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 3040009; --LBL_ALARM_CONFIGS_ALARM_MAX_BACK_BEARING_TEMP
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 130009; --LBL_ALARM_CONFIGS_ALARM_JETFAN_VIBRATION_SENSOR_OUT_OF_RANGE
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 092000; --LBL_ALARM_CONFIGS_SIGNALLING_NOT_ARRIVED
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 060009; --LBL_ALARM_CONFIGS_ALARM_JETFAN_SWITCH
UPDATE conf.alarm_configs SET alarm_level_id = 3, enabled = True, treatment = True WHERE element_type_id = 9 AND alarm_config_id = 070009; --LBL_ALARM_CONFIGS_ALARM_JETFAN_GEAR
