TITLE ELECTRICAL_CABINET_TU
@echo off
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUKD01L.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUKD02L.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUDH01L.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUDH02L.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUDH03L.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUDH04L.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUDH05L.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUJS04P.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUJS05P.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUJS06P.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUJS07P.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUJS08P.json
START /b /MIN unslave ELECTRICAL_CABINET_TU/PLCTUJS09P.json
EXIT