INSERT INTO conf.plans (plan_id, plan_mode_type_id, alias, description, management_area_id, enabled, visible, created_at, updated_at) VALUES
(10112, 1, 'Cierre túnel Río Verde', 'Cierre túnel Río Verde', 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 1, 'Restitución túnel Río Verde', 'Restitución túnel Río Verde', 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.plan_nodes (node_id, alias, description, plan_id, management_area_id, enabled, visible) VALUES
(10113, 'Cierre/Restitución túnel Río Verde', 'Cierre/Restitución túnel Río Verde', null, 1, True, True),
(10111, 'Cierre túnel Río Verde', 'Cierre túnel Río Verde', 10112, 1, True, True),
(10112, 'Restitución túnel Río Verde', 'Restitución túnel Río Verde', 10113, 1, True, True);

INSERT INTO conf.plan_node_hierarchies (node_parent_id, node_child_id, enabled, visible) VALUES
(10113, 10111, True, True),
(10113, 10112, True, True);

INSERT INTO conf.command_elements (command_element_type_id, element_type_id, command_element_id, element_id, enabled, visible, created_at, updated_at) VALUES
(1, 8, 3808, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 3809, 3, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 3810, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 3811, 4, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 53, 3047, 3, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 53, 3048, 4, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10025, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10026, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 13, 3804, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 13, 3805, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4266, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4267, 3, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4268, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4269, 4, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4056, 3, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4057, 4, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10027, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10028, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4058, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4059, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 13, 4252, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 13, 4253, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 53, 2, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 53, 3, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.command_element_values (command_element_type_id, element_type_id, command_element_type_param_id, command_element_id, value, enabled, visible, created_at, updated_at) VALUES
(2, 71, 1, 10025, '[{"zone":1,"graphics":[{"id":1,"value":"746"}]},{"zone":2,"align":"left","texts":[{"id":1,"value":"CIERRE","color":"#FFBF00"},{"id":2,"value":"DE","color":"#FFBF00"},{"id":3,"value":"TUNEL","color":"#FFBF00"}]}]', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 1, 10026, '[{"zone":1,"graphics":[{"id":1,"value":"746"}]},{"zone":2,"align":"left","texts":[{"id":1,"value":"CIERRE","color":"#FFBF00"},{"id":2,"value":"DE","color":"#FFBF00"},{"id":3,"value":"TUNEL","color":"#FFBF00"}]}]', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 1, 10027, '[{"zone":1,"graphics":[{"id":1,"value":"320"}]},{"zone":2,"align":"left","texts":[{"id":1,"value":"CIRCULE","color":"#FFBF00"},{"id":2,"value":"CON","color":"#FFBF00"},{"id":3,"value":"PRECAUCION","color":"#FFBF00"}]}]', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 1, 10028, '[{"zone":1,"graphics":[{"id":1,"value":"320"}]},{"zone":2,"align":"left","texts":[{"id":1,"value":"CIRCULE","color":"#FFBF00"},{"id":2,"value":"CON","color":"#FFBF00"},{"id":3,"value":"PRECAUCION","color":"#FFBF00"}]}]', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.plan_orders (plan_id, plan_order_id, plan_order_type_id, plan_order_order, next_plan_order_id, next_plan_id, alias, description, enabled, visible, created_at, updated_at) VALUES
(10112, 1, 1, 1, NULL, NULL, 'SIGNALLING - RV-BAR-1CA', 'SIGNALLING - RV-BAR-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 2, 1, 2, NULL, NULL, 'SIGNALLING - RV-BAR-1MA', 'SIGNALLING - RV-BAR-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 3, 1, 3, NULL, NULL, 'SIGNALLING - RV-BAR-2CA', 'SIGNALLING - RV-BAR-2CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 4, 1, 4, NULL, NULL, 'SIGNALLING - RV-BAR-2MA', 'SIGNALLING - RV-BAR-2MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 5, 1, 5, NULL, NULL, 'SIGNALLING - RV-SMF-RR-1CA', 'SIGNALLING - RV-SMF-RR-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 6, 1, 6, NULL, NULL, 'SIGNALLING - RV-SMF-RR-1MA', 'SIGNALLING - RV-SMF-RR-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 7, 1, 7, NULL, NULL, 'SIGNALLING - RV-PMV-5MA', 'SIGNALLING - RV-PMV-5MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 8, 1, 8, NULL, NULL, 'SIGNALLING - RV-PMV-6CA', 'SIGNALLING - RV-PMV-6CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 9, 1, 9, NULL, NULL, 'SIGNALLING - RV-SMF-RAV-1CA', 'SIGNALLING - RV-SMF-RAV-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 10, 1, 10, NULL, NULL, 'SIGNALLING - RV-SMF-RAV-1MA', 'SIGNALLING - RV-SMF-RAV-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 11, 1, 11, NULL, NULL, 'SIGNALLING - RV-SMF-AA-1CA', 'SIGNALLING - RV-SMF-AA-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10112, 12, 1, 12, NULL, NULL, 'SIGNALLING - RV-SMF-AA-1MA', 'SIGNALLING - RV-SMF-AA-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 1, 1, 1, NULL, NULL, 'SIGNALLING - RV-BAR-1CA', 'SIGNALLING - RV-BAR-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 2, 1, 2, NULL, NULL, 'SIGNALLING - RV-BAR-1MA', 'SIGNALLING - RV-BAR-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 3, 1, 3, NULL, NULL, 'SIGNALLING - RV-BAR-2CA', 'SIGNALLING - RV-BAR-2CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 4, 1, 4, NULL, NULL, 'SIGNALLING - RV-BAR-2MA', 'SIGNALLING - RV-BAR-2MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 5, 1, 5, NULL, NULL, 'SIGNALLING - RV-SMF-RR-1CA', 'SIGNALLING - RV-SMF-RR-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 6, 1, 6, NULL, NULL, 'SIGNALLING - RV-SMF-RR-1MA', 'SIGNALLING - RV-SMF-RR-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 7, 1, 7, NULL, NULL, 'SIGNALLING - RV-PMV-5MA', 'SIGNALLING - RV-PMV-5MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 8, 1, 8, NULL, NULL, 'SIGNALLING - RV-PMV-6CA', 'SIGNALLING - RV-PMV-6CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 9, 1, 9, NULL, NULL, 'SIGNALLING - RV-SMF-RAV-1CA', 'SIGNALLING - RV-SMF-RAV-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 10, 1, 10, NULL, NULL, 'SIGNALLING - RV-SMF-RAV-1MA', 'SIGNALLING - RV-SMF-RAV-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 11, 1, 11, NULL, NULL, 'SIGNALLING - RV-SMF-AA-1CA', 'SIGNALLING - RV-SMF-AA-1CA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10113, 12, 1, 12, NULL, NULL, 'SIGNALLING - RV-SMF-AA-1MA', 'SIGNALLING - RV-SMF-AA-1MA', True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO conf.plan_order_command_elements (command_element_type_id, element_type_id, command_element_id, plan_id, plan_order_id, enabled, visible, created_at, updated_at) VALUES
(1, 8, 3808, 10112, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 3809, 10112, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 3810, 10112, 3, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 8, 3811, 10112, 4, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 53, 3047, 10112, 5, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 53, 3048, 10112, 6, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10025, 10112, 7, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10026, 10112, 8, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 13, 3804, 10112, 9, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 13, 3805, 10112, 10, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4058, 10112, 11, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4059, 10112, 12, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4266, 10113, 1, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4267, 10113, 2, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4268, 10113, 3, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 8, 4269, 10113, 4, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4056, 10113, 5, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 53, 4057, 10113, 6, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10027, 10113, 7, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 71, 10028, 10113, 8, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 13, 4252, 10113, 9, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(1, 13, 4253, 10113, 10, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 53, 2, 10113, 11, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 53, 3, 10113, 12, True, True, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
