/*DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'gip') THEN
		  	
		INSERT INTO gip.vehicle_types (alias) VALUES('Coche');
		INSERT INTO gip.vehicle_types (alias) VALUES('Bus');
		INSERT INTO gip.vehicle_types (alias) VALUES('Moto');
		
		
		INSERT INTO gip.vehicle_brands (alias) VALUES('Abarth');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Alfa Romeo');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Aro');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Asia');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Asia Motors');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Aston Martin');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Audi');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Austin');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Auverland');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Bentley');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Bertone');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Bmw');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Cadillac');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Chevrolet');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Chrysler');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Citroen');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Corvette');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Dacia');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Daewoo');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Daf');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Daihatsu');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Daimler');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Dodge');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Ferrari');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Fiat');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Ford');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Galloper');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Gmc');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Honda');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Hummer');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Hyundai');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Infiniti');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Innocenti');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Isuzu');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Iveco');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Iveco-pegaso');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Jaguar');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Jeep');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Kia');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Lada');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Lamborghini');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Lancia');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Land-rover');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Ldv');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Lexus');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Lotus');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Mahindra');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Maserati');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Maybach');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Mazda');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Mercedes-benz');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Mg');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Mini');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Mitsubishi');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Morgan');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Nissan');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Opel');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Peugeot');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Pontiac');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Porsche');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Renault');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Rolls-royce');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Rover');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Saab');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Santana');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Seat');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Skoda');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Smart');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Ssangyong');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Subaru');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Suzuki');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Talbot');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Tata');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Toyota');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Umm');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Vaz');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Volkswagen');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Volvo');
		INSERT INTO gip.vehicle_brands (alias) VALUES('Wartburg');

		
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(1,	'500');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(1,	'Grande Punto');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(1,	'Punto Evo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(1,	'500c');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(1,	'695');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(1,	'Punto');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'155');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'156');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'159');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'164');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'145');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'147');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'146');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Gtv');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Spider');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'166');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Gt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Crosswagon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Brera');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'90');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'75');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'33');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Giulietta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Sprint');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(2,	'Mito');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(3,	'Expander');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(3,	'10');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(3,	'24');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(3,	'Dacia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(4,	'Rocsta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(5,	'Rocsta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Db7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'V8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Db9');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Vanquish');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'V8 Vantage');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Vantage');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Dbs');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Volante');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Virage');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Vantage V8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Vantage V12');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Rapide');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(6,	'Cygnet');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'80');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'S6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Coupe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'S2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Rs2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Cabriolet');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'S8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'S4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Tt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'S3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Allroad Quattro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Rs4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Rs6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Q7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'R8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'S5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'V8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'200');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'100');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'90');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Tts');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Q5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A4 Allroad Quattro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Tt Rs');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Rs5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A1');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Rs3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Q3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'A6 Allroad Quattro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'S7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(7,	'Sq5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(8,	'Mini');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(8,	'Montego');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(8,	'Maestro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(8,	'Metro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(8,	'Mini Moke');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(9,	'Diesel');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Brooklands');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Turbo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Continental');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Azure');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Arnage');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Continental Gt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Continental Flying Spur');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Turbo R');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Mulsanne');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Eight');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Continental Gtc');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(10,	'Continental Supersports');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(11,	'Freeclimber Diesel');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Serie 3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Serie 5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Compact');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Serie 7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Serie 8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Z3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Z4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Z8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'X5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Serie 6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'X3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Serie 1');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'Z1');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'X6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(12,	'X1');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'Seville');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'Sts');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'El Dorado');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'Cts');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'Xlr');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'Srx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'Escalade');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(13,	'Bls');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Corvette');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Blazer');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Astro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Nubira');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Evanda');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Trans Sport');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Camaro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Matiz');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Alero');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Tahoe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Tacuma');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Trailblazer');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Kalos');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Aveo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Lacetti');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Epica');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Captiva');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Hhr');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Cruze');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Spark');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Orlando');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Volt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(14,	'Malibu');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Vision');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'300m');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Grand Voyager');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Viper');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Neon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Voyager');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Stratus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Sebring');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Sebring 200c');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'New Yorker');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Pt Cruiser');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Crossfire');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'300c');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Le Baron');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(15,	'Saratoga');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Xantia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Xm');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Ax');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Zx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Evasion');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Saxo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Xsara');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Xsara Picasso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C3 Pluriel');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C1');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Grand C4 Picasso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C4 Picasso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Ccrosser');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C15');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Jumper');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Jumpy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Berlingo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Bx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C25');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Cx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Gsa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Visa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Lna');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'2cv');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Nemo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C4 Sedan');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Berlingo First');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C3 Picasso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Ds3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Czero');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Ds4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Ds5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'C4 Aircross');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(16,	'Celysee');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(17,	'Corvette');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(18,	'Contac');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(18,	'Logan');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(18,	'Sandero');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(18,	'Duster');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(18,	'Lodgy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Nexia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Aranos');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Lanos');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Nubira');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Compact');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Nubira Compact');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Leganza');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Evanda');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Matiz');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Tacuma');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Kalos');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(19,	'Lacetti');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(21,	'Applause');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(21,	'Charade');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(21,	'Rocky');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(21,	'Feroza');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(21,	'Terios');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(21,	'Sirion');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(22,	'Serie Xj');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(22,	'Xj');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(22,	'Double Six');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(22,	'Six');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(22,	'Series Iii');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(23,	'Viper');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(23,	'Caliber');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(23,	'Nitro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(23,	'Avenger');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(23,	'Journey');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'F355');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'360');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'F430');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'F512 M');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'550 Maranello');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'575m Maranello');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'599');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'456');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'456m');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'612');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'F50');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'Enzo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'Superamerica');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'430');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'348');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'Testarossa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'512');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'355');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'F40');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'412');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'Mondial');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'328');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'California');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'458');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(24,	'Ff');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Croma');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Cinquecento');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Seicento');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Punto');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Grande Punto');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Panda');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Tipo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Coupe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Uno');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Ulysse');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Tempra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Marea');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Barchetta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Bravo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Stilo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Brava');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Palio Weekend');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'600');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Multipla');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Idea');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Sedici');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Linea');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'500');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Fiorino');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Ducato');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Doblo Cargo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Doblo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Strada');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Regata');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Talento');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Argenta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Ritmo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Punto Classic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Qubo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Punto Evo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'500c');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Freemont');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'Panda Classic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(25,	'500l');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Maverick');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Escort');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Focus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Mondeo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Scorpio');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Fiesta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Probe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Explorer');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Galaxy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Ka');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Puma');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Cougar');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Focus Cmax');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Fusion');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Streetka');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Cmax');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Smax');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Transit');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Courier');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Ranger');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Sierra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Orion');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Capri');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Granada');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Kuga');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Grand Cmax');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Bmax');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(26,	'Tourneo Custom');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(27,	'Exceed');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(27,	'Santamo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(27,	'Super Exceed');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Accord');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Civic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Crx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Prelude');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Nsx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Legend');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Crv');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Hrv');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Logo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'S2000');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Stream');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Jazz');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Frv');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Concerto');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Insight');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(29,	'Crz');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(30,	'H2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(30,	'H3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(30,	'H3t');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Lantra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Sonata');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Elantra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Accent');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Scoupe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Coupe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Atos');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'H1');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Atos Prime');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Xg');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Trajet');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Santa Fe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Terracan');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Matrix');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Getz');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Tucson');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'I30');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Pony');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Grandeur');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'I10');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'I800');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Sonata Fl');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Ix55');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'I20');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Ix35');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Ix20');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Genesis');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'I40');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(31,	'Veloster');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(32,	'G');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(32,	'Ex');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(32,	'Fx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(32,	'M');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(33,	'Elba');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(33,	'Minitre');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(34,	'Trooper');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(34,	'Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(34,	'D Max');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(34,	'Rodeo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(34,	'Dmax');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(34,	'Trroper');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(35,	'Daily');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(35,	'Massif');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(36,	'Daily');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(36,	'Duty');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(37,	'Serie Xj');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(37,	'Serie Xk');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(37,	'Xj');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(37,	'Stype');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(37,	'Xf');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(37,	'Xtype');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(38,	'Wrangler');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(38,	'Cherokee');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(38,	'Grand Cherokee');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(38,	'Commander');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(38,	'Compass');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(38,	'Wrangler Unlimited');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(38,	'Patriot');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Sportage');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Sephia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Sephia Ii');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Pride');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Clarus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Shuma');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Carnival');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Joice');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Magentis');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Carens');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Rio');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Cerato');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Sorento');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Opirus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Picanto');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Ceed');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Ceed Sporty Wagon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Proceed');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'K2500 Frontier');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'K2500');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Soul');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Venga');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Optima');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(39,	'Ceed Sportswagon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'Samara');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'Niva');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'Sagona');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'Stawra 2110');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'214');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'Kalina');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'Serie 2100');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(40,	'Priora');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(41,	'Gallardo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(41,	'Murcielago');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(41,	'Aventador');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Delta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'K');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Y10');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Dedra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Lybra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Z');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Y');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Ypsilon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Thesis');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Phedra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Musa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Thema');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Zeta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Kappa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Trevi');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Prisma');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'A112');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Ypsilon Elefantino');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(42,	'Voyager');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(43,	'Range Rover');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(43,	'Defender');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(43,	'Discovery');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(43,	'Freelander');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(43,	'Range Rover Sport');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(43,	'Discovery 4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(43,	'Range Rover Evoque');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(44,	'Maxus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Ls400');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Ls430');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Gs300');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Is200');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Rx300');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Gs430');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Gs460');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Sc430');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Is300');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Is250');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Rx400h');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Is220d');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Rx350');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Gs450h');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Ls460');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Ls600h');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Ls');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Gs');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Is');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Sc');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Rx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(45,	'Ct');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(46,	'Elise');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(46,	'Exige');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(47,	'Bolero Pickup');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(47,	'Goa Pickup');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(47,	'Goa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(47,	'Cj');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(47,	'Pikup');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(47,	'Thar');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Ghibli');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Shamal');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Quattroporte');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'3200 Gt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Coupe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Spyder');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Gransport');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Granturismo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'430');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Biturbo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'228');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'224');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(48,	'Grancabrio');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(49,	'Maybach');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Xedos 6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'626');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'121');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Xedos 9');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'323');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mx3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Rx7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mx5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mazda3');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mpv');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Demio');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Premacy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Tribute');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mazda6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mazda2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Rx8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mazda5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Cx7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Serie B');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'B2500');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Bt50');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Mx6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'929');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(50,	'Cx5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase C');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase E');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Sl');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase S');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Cl');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase G');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Slk');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase V');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Viano');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Clk');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase A');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase M');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Vaneo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Slklasse');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Slr Mclaren');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Cls');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase R');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Gl');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase B');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'100d');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'140d');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'180d');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Sprinter');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Vito');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Transporter');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'280');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'220');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'200');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'190');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'600');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'400');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Sl R129');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'300');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'500');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'420');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'260');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'230');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Clc');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Clase Glk');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(51,	'Sls Amg');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Mgf');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Tf');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Zr');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Zs');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Zt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Ztt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Mini');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Countryman');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(52,	'Paceman');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Montero');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Galant');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Colt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Space Wagon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Space Runner');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Space Gear');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'3000 Gt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Carisma');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Eclipse');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Space Star');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Montero Sport');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Montero Io');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Outlander');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Lancer');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Grandis');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'L200');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Canter');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'300 Gt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Asx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(54,	'Imiev');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(55,	'44');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(55,	'Plus 8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(55,	'Aero 8');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(55,	'V6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(55,	'Roadster');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(55,	'4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(55,	'Plus 4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Terrano Ii');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Terrano');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Micra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Sunny');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Primera');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Serena');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Patrol');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Maxima Qx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'200 Sx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'300 Zx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Patrol Gr');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'100 Nx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Almera');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Pathfinder');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Almera Tino');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Xtrail');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'350z');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Murano');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Note');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Qashqai');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Tiida');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Vanette');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Trade');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Vanette Cargo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Pickup');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Navara');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Cabstar E');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Cabstar');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Maxima');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Camion');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Prairie');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Bluebird');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Np300 Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Qashqai2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Pixo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Gtr');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'370z');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Cube');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Juke');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Leaf');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(56,	'Evalia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Astra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Vectra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Calibra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Corsa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Omega');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Frontera');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Tigra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Monterey');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Sintra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Zafira');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Agila');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Speedster');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Signum');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Meriva');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Antara');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Gt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Combo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Movano');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Vivaro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Kadett');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Monza');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Senator');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Rekord');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Manta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Ascona');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Insignia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Zafira Tourer');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Ampera');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Mokka');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(57,	'Adam');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'306');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'605');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'106');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'205');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'405');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'406');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'806');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'807');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'407');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'307');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'206');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'607');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'308');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'307 Sw');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'206 Sw');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'407 Sw');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'1007');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'107');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'207');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'4007');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'Boxer');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'Partner');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'J5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'604');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'505');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'309');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'Bipper');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'Partner Origin');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'3008');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'5008');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'Rcz');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'508');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'Ion');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'208');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(58,	'4008');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(59,	'Trans Sport');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(59,	'Firebird');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(59,	'Trans Am');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'911');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'Boxster');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'Cayenne');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'Carrera Gt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'Cayman');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'928');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'968');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'944');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'924');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'Panamera');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(60,	'918');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Megane');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Safrane');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Laguna');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Clio');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Twingo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Nevada');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Espace');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Spider');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Scenic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Grand Espace');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Avantime');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Vel Satis');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Grand Scenic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Clio Campus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Modus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Express');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Trafic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Master');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Kangoo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Mascott');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Master Propulsion');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Maxity');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R19');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R25');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R5');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R21');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Alpine');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Fuego');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R18');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R11');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R9');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'R6');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Grand Modus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Kangoo Combi');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Koleos');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Fluence');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Wind');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Latitude');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(61,	'Grand Kangoo Combi');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Siver Dawn');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Silver Spur');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Park Ward');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Silver Seraph');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Corniche');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Phantom');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Touring');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(62,	'Silvier');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'800');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'600');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'100');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'200');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'Coupe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'400');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'45');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'Cabriolet');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'25');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'Mini');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'75');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'Streetwise');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(63,	'Sd');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(64,	'900');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(64,	'93');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(64,	'9000');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(64,	'95');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(64,	'93x');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(64,	'94x');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(65,	'300');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(65,	'350');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(65,	'Anibal');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(65,	'Anibal Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Ibiza');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Cordoba');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Toledo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Marbella');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Alhambra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Arosa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Leon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Altea');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Altea Xl');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Altea Freetrack');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Terra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Inca');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Malaga');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Ronda');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Exeo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(66,	'Mii');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Felicia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Forman');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Octavia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Octavia Tour');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Fabia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Superb');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Roomster');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Scout');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Pickup');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Favorit');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'130');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'S');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Yeti');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Citigo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(67,	'Rapid');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(68,	'Smart');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(68,	'Citycoupe');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(68,	'Fortwo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(68,	'Cabrio');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(68,	'Crossblade');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(68,	'Roadster');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(68,	'Forfour');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Korando');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Family');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'K4d');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Musso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Korando Kj');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Rexton');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Rexton Ii');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Rodius');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Kyron');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Actyon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Sports Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Actyon Sports Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(69,	'Kodando');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Legacy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Impreza');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Svx');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Justy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Outback');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Forester');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'G3x Justy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'B9 Tribeca');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Xt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'1800');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Tribeca');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Wrx Sti');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Trezia');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Xv');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(70,	'Brz');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Maruti');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Swift');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Vitara');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Baleno');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Samurai');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Alto');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Wagon R');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Jimny');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Grand Vitara');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Ignis');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Liana');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Grand Vitara Xl7');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Sx4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Splash');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(71,	'Kizashi');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(72,	'Samba');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(72,	'Tagora');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(72,	'Solara');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(72,	'Horizon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Telcosport');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Telco');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Sumo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Safari');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Indica');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Indigo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Grand Safari');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Tl Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Xenon Pick Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Vista');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Xenon');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(73,	'Aria');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Carina E');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'4runner');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Camry');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Rav4');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Celica');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Supra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Paseo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Land Cruiser 80');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Land Cruiser 100');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Land Cruiser');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Land Cruiser 90');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Corolla');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Auris');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Avensis');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Picnic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Yaris');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Yaris Verso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Mr2');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Previa');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Prius');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Avensis Verso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Corolla Verso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Corolla Sedan');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Aygo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Hilux');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Dyna');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Land Cruiser 200');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Verso');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Iq');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Urban Cruiser');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(74,	'Gt86');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(75,	'100');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(75,	'121');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(76,	'214');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(76,	'110 Stawra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(76,	'111 Stawra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(76,	'215');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(76,	'112 Stawra');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Passat');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Golf');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Vento');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Polo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Corrado');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Sharan');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Lupo');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Bora');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Jetta');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'New Beetle');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Phaeton');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Touareg');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Touran');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Multivan');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Caddy');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Golf Plus');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Fox');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Eos');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Caravelle');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Tiguan');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Transporter');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Lt');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Taro');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Crafter');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'California');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Santana');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Scirocco');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Passat Cc');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Amarok');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Beetle');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Up');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(77,	'Cc');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'440');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'850');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'S70');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V70');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V70 Classic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'940');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'480');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'460');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'960');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'S90');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V90');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'Classic');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'S40');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V40');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V50');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V70 Xc');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'Xc70');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'C70');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'S80');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'S60');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'Xc90');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'C30');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'780');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'760');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'740');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'240');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'360');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'340');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'Xc60');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V60');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(78,	'V40 Cross Country');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(79,	'353');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(53,	'Mini');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(53,	'Countryman');
		INSERT INTO gip.vehicle_models (brand_id, alias) VALUES(53,	'Paceman');

			
		INSERT INTO gip.vehicle_damages (alias) VALUES('Con daños');
		INSERT INTO gip.vehicle_damages (alias) VALUES('Sin daños');
		
		INSERT INTO gip.attendeds (alias) VALUES('Atendido');
		INSERT INTO gip.attendeds (alias) VALUES('No atendido');
		INSERT INTO gip.attendeds (alias) VALUES('Rechazado');
		
		
		INSERT INTO gip.assistance_types (alias) VALUES('Detecta falla y solicita servico');
		INSERT INTO gip.assistance_types (alias) VALUES('Instalación señalización preventiva');
			
		INSERT INTO gip.transfer_places (alias) VALUES('Norte');
		INSERT INTO gip.transfer_places (alias) VALUES('Sur');	

  END IF;
END $$;*/