UPDATE ui.modules SET autoload=true WHERE id=1018;

INSERT INTO ui.modules(id, module_type_id, "name", description, default_view_type_id, default_system_permission_id, js_file, js_method_draw, js_method_callbacks, data_query, wss_topic, enabled, visible, autoload) VALUES
(402, 5, 'IMD', 'IMD', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),
(405, 5, 'Vel. Media', 'Vel. Media', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),
(406, 5, 'Videowall', 'Videowall', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),
(407, 5, 'Grabaciones', 'Grabaciones', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),
(408, 5, 'DAI Rio Verde', 'DAI Rio Verde', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),
(409, 5, 'Asterisk', 'Asterisk', 1, null, 'modules/externalApp.js', 'getView', NULL, NULL, NULL, true, true, NULL),

(910, 1, 'EquipmentForm', 'Equipment form', 2, null, 'modules/equipmentFormModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

(2018, 8, 'Selector Tree Module', 'Selector Tree Module', 1, null, 'modules/selectorModule.js', 'getView', 'loadData', NULL, NULL, true, true, true),

-- Synoptics
(600, 4, 'Metro', 'Metro', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(601, 4, 'CH Plano CT', 'CH Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(602, 4, 'CH Comunicaciones', 'CH Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(603, 4, 'CH Control tráfico', 'CH Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(604, 4, 'CH Energía', 'CH Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(605, 4, 'CH General', 'CH General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(606, 4, 'CH Iluminacion', 'CH Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(607, 4, 'CH PCI', 'CH PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(608, 4, 'CH Ventilación', 'CH Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(609, 4, 'CH UF CGBT', 'CH UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(610, 4, 'CH UF CSA', 'CH UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(611, 4, 'CH UF CSB ITS 1', 'CH UF CSB ITS 1', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(612, 4, 'CH UF CSB ITS 2', 'CH UF CSB ITS 2', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(613, 4, 'CH UF CSG', 'CH UF CSG', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(614, 4, 'CH UF CSV', 'CH UF CSV', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(615, 4, 'CAS Plano CT', 'CAS Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(616, 4, 'CAS Comunicaciones', 'CAS Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(617, 4, 'CAS Control tráfico', 'CAS Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(618, 4, 'CAS Energía', 'CAS Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(619, 4, 'CAS General', 'CAS General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(620, 4, 'CAS Iluminacion', 'CAS Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(621, 4, 'CAS PCI', 'CAS PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(622, 4, 'CAS Ventilación', 'CAS Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(623, 4, 'CAS UF CGBT A', 'CAS UF CGBT A', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(624, 4, 'CAS UF CGBT B', 'CAS UF CGBT B', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(625, 4, 'CAS UF CSA A', 'CAS UF CSA A', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(626, 4, 'CAS UF CSA B', 'CAS UF CSA B', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(627, 4, 'CAS UF CSB ITS 1', 'CAS UF CSB ITS A', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(628, 4, 'CAS UF CSB ITS 2', 'CAS UF CSB ITS B', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(629, 4, 'CAS UF CSG', 'CAS UF CSG', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(630, 4, 'CAS UF CSV', 'CAS UF CSV', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(631, 4, 'COR Plano CT', 'COR Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(632, 4, 'COR Comunicaciones', 'COR Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(633, 4, 'COR Control tráfico', 'COR Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(634, 4, 'COR Energía', 'COR Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(635, 4, 'COR General', 'COR General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(636, 4, 'COR Iluminacion', 'COR Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(637, 4, 'COR PCI', 'COR PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(638, 4, 'COR Ventilación', 'COR Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(639, 4, 'COR UF CGBT A', 'COR UF CGBT A', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(640, 4, 'COR UF CGBT B', 'COR UF CGBT B', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(641, 4, 'COR UF CSA A', 'COR UF CSA A', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(642, 4, 'COR UF CSA B', 'COR UF CSA B', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(643, 4, 'COR UF CSB ITS 1', 'COR UF CSB ITS A', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(644, 4, 'COR UF CSB ITS 2', 'COR UF CSB ITS B', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(645, 4, 'COR UF CSG 1', 'COR UF CSG 1', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(646, 4, 'COR UF CSG 2', 'COR UF CSG 2', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(647, 4, 'COR UF CSG 3', 'COR UF CSG 3', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(648, 4, 'COR UF CSV', 'COR UF CSV', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(649, 4, 'EST Plano CT', 'EST Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(650, 4, 'EST Comunicaciones', 'EST Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(651, 4, 'EST Control tráfico', 'EST Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(652, 4, 'EST Energía', 'EST Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(653, 4, 'EST General', 'EST General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(654, 4, 'EST Iluminacion', 'EST Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(655, 4, 'EST PCI', 'EST PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(656, 4, 'EST UF CGBT', 'EST UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(657, 4, 'EST UF CSA', 'EST UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(658, 4, 'EST UF CSB', 'EST UF CSB', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(659, 4, 'LQ Plano CT', 'LQ Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(660, 4, 'LQ Comunicaciones', 'LQ Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(661, 4, 'LQ Control tráfico', 'LQ Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(662, 4, 'LQ Energía', 'LQ Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(663, 4, 'LQ General', 'LQ General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(664, 4, 'LQ Iluminacion', 'LQ Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(665, 4, 'LQ PCI', 'LQ PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(666, 4, 'LQ Ventilación', 'LQ Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(667, 4, 'LQ UF CGBT', 'LQ UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(668, 4, 'LQ UF CSA', 'LQ UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(669, 4, 'LQ UF CSB', 'LQ UF CSB', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(670, 4, 'LQ UF CSG', 'LQ UF CSG', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(671, 4, 'LQ UF CSV CA', 'LQ UF CSV CA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(672, 4, 'LQ UF CSV MA', 'LQ UF CSV MA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(673, 4, 'MM Plano CT', 'MM Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(674, 4, 'MM Comunicaciones', 'MM Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(675, 4, 'MM Control tráfico', 'MM Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(676, 4, 'MM Energía', 'MM Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(677, 4, 'MM General', 'MM General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(678, 4, 'MM Iluminacion', 'MM Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(679, 4, 'MM PCI', 'MM PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(680, 4, 'MM Ventilación', 'MM Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(681, 4, 'MM UF CGBT', 'MM UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(682, 4, 'MM UF CSA', 'MM UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(683, 4, 'MM UF CSB ITS 1', 'MM UF CSB ITS 1', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(684, 4, 'MM UF CSB ITS 2', 'MM UF CSB ITS 2', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(685, 4, 'MM UF CSG', 'MM UF CSG', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(686, 4, 'MM UF CSV', 'MM UF CSV', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(687, 4, 'NG Plano CT', 'NG Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(688, 4, 'NG Comunicaciones', 'NG Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(689, 4, 'NG Control tráfico', 'NG Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(690, 4, 'NG Energía', 'NG Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(691, 4, 'NG General', 'NG General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(692, 4, 'NG Iluminacion', 'NG Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(693, 4, 'NG PCI', 'NG PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(694, 4, 'NG Ventilación', 'NG Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(695, 4, 'NG UF CGBT', 'NG UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(696, 4, 'NG UF CSA', 'NG UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(697, 4, 'NG UF CSB ITS 1', 'NG UF CSB ITS 1', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(698, 4, 'NG UF CSB ITS 2', 'NG UF CSB ITS 2', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(699, 4, 'NG UF CSG', 'NG UF CSG', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(700, 4, 'NG UF CSV', 'NG UF CSV', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(701, 4, 'RV Plano CT', 'RV Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(702, 4, 'RV Comunicaciones', 'RV Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(703, 4, 'RV Control tráfico', 'RV Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(704, 4, 'RV Energía', 'RV Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(705, 4, 'RV General', 'RV General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(706, 4, 'RV Iluminacion', 'RV Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(707, 4, 'RV PCI', 'RV PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(708, 4, 'RV Ventilación', 'RV Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(709, 4, 'RV UF CGBT', 'RV UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(710, 4, 'RV UF CSA', 'RV UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(711, 4, 'RV UF CSB', 'RV UF CSB', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(712, 4, 'RV UF CSV', 'RV UF CSV', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(713, 4, 'STM2 Plano CT', 'STM2 Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(714, 4, 'STM2 Comunicaciones', 'STM2 Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(715, 4, 'STM2 Control tráfico', 'STM2 Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(716, 4, 'STM2 Energía', 'STM2 Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(717, 4, 'STM2 General', 'STM2 General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(718, 4, 'STM2 Iluminacion', 'STM2 Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(719, 4, 'STM2 PCI', 'STM2 PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(720, 4, 'STM2 Ventilación', 'STM2 Ventilación', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(721, 4, 'STM2 UF CGBT', 'STM2 UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(722, 4, 'STM2 UF CSA', 'STM2 UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(723, 4, 'STM2 UF CSB ITS 1', 'STM2 UF CSB ITS 1', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(724, 4, 'STM2 UF CSB ITS 2', 'STM2 UF CSB ITS 2', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(725, 4, 'STM2 UF CSG', 'STM2 UF CSG', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(726, 4, 'STM2 UF CSV', 'STM2 UF CSV', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(727, 4, 'CH Plano CT', 'CH Plano CT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(728, 4, 'CH Comunicaciones', 'CH Comunicaciones', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(729, 4, 'CH Control tráfico', 'CH Control tráfico', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(730, 4, 'CH Energía', 'CH Energía', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(731, 4, 'CH General', 'CH General', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(732, 4, 'CH Iluminacion', 'CH Iluminacion', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(733, 4, 'CH PCI', 'CH PCI', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(734, 4, 'CH UF CGBT', 'CH UF CGBT', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(735, 4, 'CH UF CSA', 'CH UF CSA', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(736, 4, 'CH UF CSB', 'CH UF CSB', 1, null, 'modules/synopticModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),

-- Maps
(970, 3, 'Map', 'Map', 1, null, 'modules/mapModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(1920, 8, 'Selector Tree Module', 'Selector Tree Module', 1, null, 'modules/selectorModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6000, 9, 'NOGALES GIP - actions', 'Nogales GIP - actions', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6001, 9, 'NOGALES GIP - agents', 'Nogales GIP - agents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6002, 9, 'NOGALES GIP - assigned_pdas', 'Nogales GIP - assigned_pdas', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6003, 9, 'NOGALES GIP - assigned_resources', 'Nogales GIP - assigned_resources', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6004, 9, 'NOGALES GIP - assistance_types', 'Nogales GIP - assistance_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6005, 9, 'NOGALES GIP - atmospheric_states', 'Nogales GIP - atmospheric_states', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6006, 9, 'NOGALES GIP - attendeds', 'Nogales GIP - attendeds', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6007, 9, 'NOGALES GIP - causes', 'Nogales GIP - causes', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6008, 9, 'NOGALES GIP - conditions', 'Nogales GIP - conditions', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6009, 9, 'NOGALES GIP - elements', 'Nogales GIP - elements', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6010, 9, 'NOGALES GIP - genders', 'Nogales GIP - genders', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6011, 9, 'NOGALES GIP - incidents', 'Nogales GIP - incidents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6012, 9, 'NOGALES GIP - infrastructure_damages', 'Nogales GIP - infrastructure_damages', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6013, 9, 'NOGALES GIP - injury_levels', 'Nogales GIP - injury_levels', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6014, 9, 'NOGALES GIP - injury_types', 'Nogales GIP - injury_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6015, 9, 'NOGALES GIP - interrupt_agents', 'Nogales GIP - interrupt_agents', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6016, 9, 'NOGALES GIP - lanes', 'Nogales GIP - lanes', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6017, 9, 'NOGALES GIP - lanes_actions', 'Nogales GIP - lanes_actions', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6018, 9, 'NOGALES GIP - lanes_states', 'Nogales GIP - lanes_states', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6019, 9, 'NOGALES GIP - luminosities', 'Nogales GIP - luminosities', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6020, 9, 'NOGALES GIP - maneuvers', 'Nogales GIP - maneuvers', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6021, 9, 'NOGALES GIP - participant_assistance_types', 'Nogales GIP - participant_assistance_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6022, 9, 'NOGALES GIP - participant_transfer_places', 'Nogales GIP - participant_transfer_places', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6023, 9, 'NOGALES GIP - participant_types', 'Nogales GIP - participant_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6024, 9, 'NOGALES GIP - participants', 'Nogales GIP - participants', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6025, 9, 'NOGALES GIP - pdas', 'Nogales GIP - pdas', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6026, 9, 'NOGALES GIP - resources', 'Nogales GIP - resources', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6027, 9, 'NOGALES GIP - road_impacts', 'Nogales GIP - road_impacts', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6028, 9, 'NOGALES GIP - sources', 'Nogales GIP - sources', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6029, 9, 'NOGALES GIP - stages', 'Nogales GIP - stages', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6030, 9, 'NOGALES GIP - transfer_places', 'Nogales GIP - transfer_places', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6031, 9, 'NOGALES GIP - typologies', 'Nogales GIP - typologies', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6032, 9, 'NOGALES GIP - unavailable_lanes', 'Nogales GIP - unavailable_lanes', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6033, 9, 'NOGALES GIP - user_types', 'Nogales GIP - user_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6034, 9, 'NOGALES GIP - vehicle_brands', 'Nogales GIP - vehicle_brands', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6035, 9, 'NOGALES GIP - vehicle_damages', 'Nogales GIP - vehicle_damages', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6036, 9, 'NOGALES GIP - vehicle_models', 'Nogales GIP - vehicle_models', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6037, 9, 'NOGALES GIP - vehicle_types', 'Nogales GIP - vehicle_types', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL),
(6038, 9, 'NOGALES GIP - vehicles', 'Nogales GIP - vehicles', 2, null, 'modules/backOffice/backOfficeModule.js', 'getView', 'loadData', NULL, NULL, true, true, NULL);

INSERT INTO ui.module_actions(id, module_id, name, description, system_permission_id) VALUES
(91001, 910, 'view equipment', 'view equipment', NULL);

UPDATE ui.modules SET management_areas='["ManagementArea:1"]' WHERE id=1018;
UPDATE ui.modules SET management_areas='["ManagementArea:2"]' WHERE id=2018;
