DELETE FROM master.ims_incident_groups;

-- 
-- Table: conf.ims_incident_types
--
INSERT INTO master.ims_incident_groups (incident_group_id,alias,description,label_alias,label_description,enabled,visible,created_at,updated_at) VALUES
(1,'A','Accidente','LBL_IMS_INCIDENT_GROUP_TYPE_A', 'LBL_IMS_INCIDENT_GROUP_TYPE_A_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(2,'B','Indicente','LBL_IMS_INCIDENT_GROUP_TYPE_B', 'LBL_IMS_INCIDENT_GROUP_TYPE_B_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(3,'C','Objeto en la vía','LBL_IMS_INCIDENT_GROUP_TYPE_C', 'LBL_IMS_INCIDENT_GROUP_TYPE_C_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(4,'D','Congestión','LBL_IMS_INCIDENT_GROUP_TYPE_D', 'LBL_IMS_INCIDENT_GROUP_TYPE_D_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(5,'E','Vehículo Detenido','LBL_IMS_INCIDENT_GROUP_TYPE_E', 'LBL_IMS_INCIDENT_GROUP_TYPE_E_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(6,'F','Otro tipo de Incidente','LBL_IMS_INCIDENT_GROUP_TYPE_F', 'LBL_IMS_INCIDENT_GROUP_TYPE_F_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(7,'G','Meteorológico','LBL_IMS_INCIDENT_GROUP_TYPE_G', 'LBL_IMS_INCIDENT_GROUP_TYPE_G_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(8,'H','Incendio','LBL_IMS_INCIDENT_GROUP_TYPE_H', 'LBL_IMS_INCIDENT_GROUP_TYPE_H_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(9,'I','Situaciones Internas AVO','LBL_IMS_INCIDENT_GROUP_TYPE_I', 'LBL_IMS_INCIDENT_GROUP_TYPE_I_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(10,'J','Trabajos','LBL_IMS_INCIDENT_GROUP_TYPE_J', 'LBL_IMS_INCIDENT_GROUP_TYPE_J_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(11,'K','Requerimientos Externos','LBL_IMS_INCIDENT_GROUP_TYPE_K', 'LBL_IMS_INCIDENT_GROUP_TYPE_K_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
(12,'L','Infracciones','LBL_IMS_INCIDENT_GROUP_TYPE_L', 'LBL_IMS_INCIDENT_GROUP_TYPE_L_DESC',true,true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);