
-- 
-- Table: conf.ims_incident_type_tasks
--
INSERT INTO conf.ims_incident_type_tasks (incident_type_task_id, incident_type_id, incident_state_id, task_type_id, alias, description, mandatory, position, auto, enabled, visible, created_at, updated_at) VALUES
--(1, 1, 1, 5, 'ACKONWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(2, 1, 2, 5, 'CAMERA SELECTION', 'Camera Selection', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(3, 1, 2, 5, 'IDENTIFY ALARM CAUSE', 'Identify Alarm Cause', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(4, 1, 3, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(5, 1, 4, 5, 'DISPATCH IR', 'Dispatch IR', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(6, 1, 5, 5, 'VMS SIGNALLING', 'VMS Signalling', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(7, 1, 6, 5, 'INCIDENT SEVERITY', 'Identify Incident Severity', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(8, 1, 7, 5, 'VMS SIGNALLING', 'VMS Signalling', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(9, 1, 8, 5, 'ADDITIONAL INFORMATION', 'Additional information', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(10, 1, 8, 5, 'REVIEW INFORMATION', 'Review the provided information', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Person
(1, 1, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(6, 1, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 1, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 1, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 1, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 1, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 1, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 1, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 11, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Stopped vehicle
(13, 4, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(14, 4, 2, 5, 'RECORD WARNING ID', 'Record Warning ID', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 4, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 4, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 4, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 4, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 4, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 4, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 4, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 4, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 4, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 4, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 11, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 4, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 12, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Debris
(26, 2, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 2, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 2, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 2, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 2, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 2, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 2, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 2, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 2, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 2, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 2, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Reverse vehicle
(37, 5, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 5, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 5, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 5, 2, 5, 'ADVISE IR', 'Advise IR', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(41, 5, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 5, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 5, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 5, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Slow vehicle
(45, 3, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 3, 2, 5, 'RECORD WARNING ID', 'Record Warning ID', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 3, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 3, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 3, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 3, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(51, 3, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 3, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(53, 3, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(54, 3, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(55, 3, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(56, 3, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 11, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(57, 3, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 12, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Queue
(58, 6, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 6, 2, 5, 'RECORD WARNING ID', 'Record Warning ID', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(60, 6, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(61, 6, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(62, 6, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(63, 6, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(64, 6, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(65, 6, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(66, 6, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(67, 6, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(68, 6, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(69, 6, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 11, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(70, 6, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 12, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Visibilimeter
(71, 7, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(72, 7, 2, 5, 'RECORD WARNING ID', 'Record Warning ID', false, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(73, 7, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(74, 7, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(75, 7, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(76, 7, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(77, 7, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(78, 7, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(79, 7, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(80, 7, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(81, 7, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(82, 7, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 11, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(83, 7, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 12, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),


-- Person PTZ
(84, 8, 1, 1, 'PTZ', 'Point camera to the incident', true, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(85, 8, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(86, 8, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(87, 8, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(88, 8, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(89, 8, 2, 5, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 4, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(90, 8, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(91, 8, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(92, 8, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(93, 8, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(94, 8, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(95, 8, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(96, 8, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 11, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Person VMS
(97, 9, 1, 5, 'ACKNOWLEDGE', 'Acknowledge the incident', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(98, 9, 2, 5, 'DISPATCH IR', 'Dispatch IR', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(99, 9, 2, 5, 'RECORD IR ARRIVAL', 'Record IR arrival tim', true, 2, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100, 9, 2, 5, 'VERIFY INCIDENT', 'Verify incident', true, 3, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(101, 9, 2, 1, 'VMS RESPONSE PLAN', 'Implement VMS response plan', true, 4, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 9, 2, 5, 'CONTACT EMERGENCY', 'Contact Emergency Services', true, 5, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 9, 2, 5, 'CLASSIFY INCIDENT', 'Classify Incident type and severity', true, 6, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 9, 2, 5, 'NOTIFY WTOC', 'Notify WTOC', false, 7, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(105, 9, 2, 5, 'REVIEW VMS', 'Review  VMS Response Plan(s) in use', true, 8, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(106, 9, 2, 5, 'UPDATE INCIDENT', 'Update incident details', true, 9, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(107, 9, 2, 5, 'INCIDENT REVIEW', 'Incident review', true, 10, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(108, 9, 2, 5, 'TERMINATE VMS', 'Terminate VMS Response Plan(s)', true, 11, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

--(4, 2, 1, 5, 'NOTIFY', 'Notify Supervisor', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(5, 2, 2, 1, 'SIGNALLING', 'Automatic Signalling', true, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(6, 2, 3, 5, 'SIGNALLING', 'Manual Signalling', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(7, 3, 1, 5, 'NOTIFY', 'Notify Supervisor', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(8, 3, 2, 1, 'SIGNALLING', 'Automatic Signalling', true, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(9, 3, 3, 5, 'SIGNALLING', 'Manual Signalling', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(10, 4, 1, 5, 'NOTIFY', 'Notify Supervisor', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(11, 4, 2, 1, 'SIGNALLING', 'Automatic Signalling', true, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(12, 4, 3, 5, 'SIGNALLING', 'Manual Signalling', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(13, 5, 1, 5, 'NOTIFY', 'Notify Supervisor', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(14, 5, 2, 1, 'SIGNALLING', 'Automatic Signalling', true, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(15, 5, 3, 5, 'SIGNALLING', 'Manual Signalling', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(16, 6, 1, 5, 'NOTIFY', 'Notify Supervisor', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(17, 6, 2, 1, 'SIGNALLING', 'Automatic Signalling', true, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(18, 6, 3, 5, 'SIGNALLING', 'Manual Signalling', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(19, 7, 2, 1, 'SIGNALLING', 'Automatic Signalling', true, 1, true, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--(20, 7, 3, 5, 'SIGNALLING', 'Manual Signalling', true, 1, false, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
