INSERT INTO conf.management_area_elements (management_area_id, element_type_id, element_id, enabled, visible, created_at, updated_at) VALUES
(2, 9, 117, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 118, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 119, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 120, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 121, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 122, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 123, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 124, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 125, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 126, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 127, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 9, 128, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
