INSERT INTO ui.vms_libraries(id, name, description, label, enabled, visible) VALUES
(01, 'Librería mensajes', null, 'LBL_LIB_VMS', true, true);


INSERT INTO ui.vms_library_nodes(id, vms_library_id, name, description, label, signaling, enabled, visible) VALUES
(0101, 01, 'Generico', null, 'LBL_GENERIC', null, true, true),
	(0102, 01, 'Túnel_cerrado', null, 'Túnel_cerrado', '[{"zone":1,"graphics":[{"id":1,"value":142}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"TUNEL"},{"id":3,"value":"CERRADO"}]}]', true, true),
	(0103, 01, 'Lluvia', null, 'Lluvia', '[{"zone":1,"graphics":[{"id":1,"value":139}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"CON LLUVIA"},{"id":2,"value":"MODERE"},{"id":3,"value":"VELOCIDAD"}]}]', true, true),
	(0104, 01, 'Precaución_en_túnel', null, 'Precaución_en_túnel', '[{"zone":1,"graphics":[{"id":1,"value":141}]},{"zone":2,"align": "left","texts":[{"id":1,"value":""},{"id":2,"value":"PRECAUCION"},{"id":3,"value":"EN TUNEL"}]}]', true, true),
	(0105, 01, '01_Prueba_Panel', null, '01_Prueba_Panel', '[{"zone":1,"graphics":[{"id":1,"value":92}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"888888888888"},{"id":2,"value":"888888888888"},{"id":3,"value":"888888888888"}]}]', true, true),
	(0106, 01, 'Explotacion normal', null, 'Explotacion normal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":33,"alternance":54}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"NO ESTACIONAR","alternance":"UTILICE"},{"id":2,"value":"NI DETENERSE","alternance":"CINTURON DE"},{"id":3,"value":"EN TUNEL","alternance":"SEGURIDAD"}]}]', true, true ), 
	(0107, 01, 'Señalizacion lluvia', null, 'Señalizacion lluvia', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":73,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"CON LLUVIA","alternance":"MANTENGA"},{"id":2,"value":"CONDUZCA","alternance":"SU"},{"id":3,"value":"CON PRECAUCION","alternance":"DISTANCIA"}]}]', true, true ),
	(0108, 01, 'Señalizacion firme deslizante', null, 'Señalizacion firme deslizante', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":96,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PISTA DESLIZANTE","alternance":"PISTA DESLIZANTE"},{"id":2,"value":"MODERE","alternance":"MODERE"},{"id":3,"value":"VELOCIDAD","alternance":"VELOCIDAD"}]}]', true, true ),
	(0109, 01, 'Niebla', null, 'Niebla', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":138,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"NIEBLA","alternance":"MANTENGA"},{"id":2,"value":"MODERE","alternance":"SU"},{"id":3,"value":"VELOCIDAD","alternance":"DISTANCIA"}]}]', true, true ),
	(0110, 01, 'Viento', null, 'Viento', '[{"zone":1,"graphics":[{"id":1,"value":38}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"VIENTO"},{"id":2,"value":"MODERE"},{"id":3,"value":"VELOCIDAD"}]}]', true, true ),
	(0111, 01, 'Baja visibilidad', null, 'Baja visibilidad', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":55,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"MODERE"},{"id":2,"value":"VISIBILIDAD","alternance":"SU"},{"id":3,"value":"REDUCIDA","alternance":"VELOCIDAD"}]}]', true, true ),
	(0112, 01, 'Vehiculo circulando a velocidad anormalmente reducida', null, 'Vehiculo circulando a velocidad anormalmente reducida', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":47,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"MODERE"},{"id":2,"value":"VEHICULO","alternance":"SU"},{"id":3,"value":"LENTO","alternance":"VELOCIDAD"}]}]', true, true ),
	(0113, 01, 'Vehiculo circulando a velocidad excesiva', null, 'Vehiculo circulando a velocidad excesiva', '[{"zone":1,"graphics":[{"id":1,"value":92}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"MODERE"},{"id":2,"value":"SU"},{"id":3,"value":"VELOCIDAD"}]}]', true, true ),
	(0114, 01, 'Trafico lento', null, 'Trafico lento', '[{"zone":1,"graphics":[{"id":1,"value":136}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"TRAFICO LENTO"},{"id":2,"value":"REDUZCA"},{"id":3,"value":"VELOCIDAD"}]}]', true, true ),
	(0115, 01, 'Lluvia intesa/granizo', null, 'Lluvia intesa/granizo', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":73,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"LLUVIA INTENSA","alternance":"LLUVIA INTENSA"},{"id":2,"value":"REDUZCA","alternance":"REDUZCA"},{"id":3,"value":"VELOCIDAD","alternance":"VELOCIDAD"}]}]', true, true ),
	(0116, 01, 'Nieve', null, 'Nieve', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":140,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"NIEVE","alternance":"REDUZCA"},{"id":2,"value":"EN","alternance":"SU"},{"id":3,"value":"PISTA","alternance":"VELOCIDAD"}]}]', true, true ),
	(0117, 01, 'Hielo', null, 'Hielo', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":96,"alternance":47}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"HIELO","alternance":"REDUZCA"},{"id":2,"value":"EN","alternance":"SU"},{"id":3,"value":"PISTA","alternance":"VELOCIDAD"}]}]', true, true ),
	(0118, 01, 'Congestion - Alto flujo vehicular', null, 'Congestion - Alto flujo vehicular', '[{"zone":1,"graphics":[{"id":1,"value":136}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"POSIBLES"},{"id":2,"value":"RETENCIONES"},{"id":3,"value":"MODERE VELOCIDAD"}]}]', true, true ),
	(0119, 01, 'Obstáculo en berma derecha', null, 'Obstáculo en berma derecha', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":141,"alternance":88}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"OBSTACULO BERMA"},{"id":2,"value":"OBSTACULO","alternance":"REDUZCA"},{"id":3,"value":"EN BERMA","alternance":"VELOCIDAD"}]}]', true, true ),
	(0120, 01, 'Obstáculo en pista', null, 'Obstáculo en pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":141,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCION PISTA"},{"id":2,"value":"OBSTACULO","alternance":"CORTADA RESPETE"},{"id":3,"value":"EN PISTA","alternance":"SEÑALIZACION"}]}]', true, true ),
	(0121, 01, 'Obstáculo en pista ramal', null, 'Obstáculo en pista ramal', '[{"zone":1,"graphics":[{"id":1,"value":142}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"RAMAL CORTADO"},{"id":2,"value":"OBSTACULO"},{"id":3,"value":"EN PISTA"}]}]', true, true ),
	(0122, 01, 'Vehiculo en pista', null, 'Vehiculo en pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":5,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCION PISTA"},{"id":2,"value":"VEHICULO","alternance":"CORTADA RESPETE"},{"id":3,"value":"DETENIDO","alternance":"SEÑALIZACION"}]}]', true, true ),
	(0123, 01, 'Vehiculo en pista ramal', null, 'Obstáculo en pista ramal', '[{"zone":1,"graphics":[{"id":1,"value":142}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"RAMAL CORTADO"},{"id":2,"value":"VEHICULO"},{"id":3,"value":"EN PISTA"}]}]', true, true ),
	(0124, 01, 'Exceso de galibo', null, 'Exceso de galibo', '[{"zone":1,"graphics":[{"id":1,"value":23}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"PRECAUCION"},{"id":2,"value":"EXCESO DE"},{"id":3,"value":"GALIBO"}]}]', true, true ),
	(0125, 01, 'Inundacion parcial', null, 'Inundacion parcial', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":141,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCION PISTA"},{"id":2,"value":"ACUMULACION AGUA","alternance":"CORTADA RESPETE"},{"id":3,"value":"EN PISTA","alternance":"SEÑALIZACION"}]}]', true, true ),
	(0126, 01, 'Inundacion parcial ramal', null, 'Inundacion parcial ramal', '[{"zone":1,"graphics":[{"id":1,"value":142}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"RAMAL CORTADO"},{"id":2,"value":"ACUMULACION AGUA"},{"id":3,"value":"EN PISTA"}]}]', true, true ),
	(0127, 01, 'Inundacion toda la pista', null, 'Inundacion toda la pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"ACUMULACION AGUA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0128, 01, 'Inundacion toda la pista ramal', null, 'Inundacion toda la pista ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"ACUMULACION AGUA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0129, 01, 'Peatones en pista', null, 'Peatones en pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":141,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCION"},{"id":2,"value":"PEATON","alternance":"PEATON"},{"id":3,"value":"EN EL TUNEL","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0130, 01, 'Ciclista en pista', null, 'Ciclista en pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":141,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCION"},{"id":2,"value":"CICLISTA","alternance":"CICLISTA"},{"id":3,"value":"EN EL TUNEL","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0131, 01, 'Conduccion temerario', null, 'Conduccion temerario', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":92,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"","alternance":""},{"id":2,"value":"MODERE","alternance":"MODERE"},{"id":3,"value":"VELOCIDAD","alternance":"VELOCIDAD"}]}]', true, true ),
	(0132, 01, 'Conduccion en sentido contrario', null, 'Conduccion en sentido contrario', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":141,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"","alternance":""},{"id":2,"value":"VEHICULO","alternance":"PARE CON"},{"id":3,"value":"SENT. CONTRARIO","alternance":"SEGURIDAD"}]}]', true, true ),
	(0133, 01, 'Derrame de liquido', null, 'Derrame de liquido', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"DERRAME LIQUIDO","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0134, 01, 'Derrame de liquido ramal', null, 'Derrame de liquido ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"DERRAME LIQUIDO","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0135, 01, 'Obstaculo ocupando toda la pista', null, 'Obstaculo ocupando toda la pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"OBSTACULO","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0136, 01, 'Obstaculo ocupando toda la pista ramal', null, 'Obstaculo ocupando toda la pista ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"OBSTACULO TUNEL","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0137, 01, 'Vehiculo ocupando toda la pista', null, 'Vehiculo ocupando toda la pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"VEH. EN PISTA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0138, 01, 'Vehiculo ocupando toda la pista ramal', null, 'Vehiculo ocupando toda la pista ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"VEH. EN PISTA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0139, 01, 'Accidente', null, 'Accidente', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":137,"alternance":137}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCUION PISTA"},{"id":2,"value":"ACCIDENTE","alternance":"CORTADA RESPETE"},{"id":3,"value":"EN TUNEL","alternance":"SEÑALIZACION"}]}]', true, true ),
	(0140, 01, 'Accidente en ramal', null, 'Accidente en ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":137,"alternance":137}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"PRECAUCUION PISTA"},{"id":2,"value":"ACCIDENTE","alternance":"CORTADA RESPETE"},{"id":3,"value":"EN RAMAL","alternance":"SEÑALIZACION"}]}]', true, true ),
	(0141, 01, 'Accidente ramal cortado', null, 'Accidente ramal cortado', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"RAMAL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"ACCIDENTE","alternance":"RETENCIONES"},{"id":3,"value":"OCUPANDO CALZADA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0142, 01, 'Accidente tunel cortado', null, 'Accidente tunel cortado', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"ACCIDENTE","alternance":"RETENCIONES"},{"id":3,"value":"OCUPANDO CALZADA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0143, 01, 'Accidente tunel cortado 2', null, 'Accidente tunel cortado 2', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"ACCIDENTE","alternance":"RETENCIONES"},{"id":3,"value":"OCUPANDO CALZADA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0144, 01, 'Disturbios', null, 'Disturbios', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"DISTURBIOS","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0145, 01, 'Disturbios ramal', null, 'Disturbios ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL","alternance":"POSIBLES"},{"id":2,"value":"CORTADO POR","alternance":"RETENCIONES"},{"id":3,"value":"DISTURBIOS","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0146, 01, 'Contaminación inadmisible', null, 'Contaminación inadmisible', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR ALTA","alternance":"RETENCIONES"},{"id":3,"value":"CONTAMINACION","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0147, 01, 'Contaminación inadmisible ramal', null, 'Contaminación inadmisible ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR ALTA","alternance":"RETENCIONES"},{"id":3,"value":"CONTAMINACION","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0148, 01, 'Visibiliadad inadmisible', null, 'Visibilidad inadmisible', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR MUY BAJA","alternance":"RETENCIONES"},{"id":3,"value":"VISIBILIDAD","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0149, 01, 'Visibiliadad inadmisible ramal', null, 'Visibilidad inadmisible ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR MUY BAJA","alternance":"RETENCIONES"},{"id":3,"value":"VISIBILIDAD","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0150, 01, 'Atentado', null, 'Atentado', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR","alternance":"RETENCIONES"},{"id":3,"value":"INCIDENCIA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0151, 01, 'Atentado ramal', null, 'Atentado ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR","alternance":"RETENCIONES"},{"id":3,"value":"INCIDENCIA","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0152, 01, 'Incendio en interior del tunel', null, 'Incendio en interior del tunel', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR","alternance":"RETENCIONES"},{"id":3,"value":"INCENDIO","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0153, 01, 'Incendio en interior del ramal', null, 'Incendio en interior del ramal', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":142,"alternance":136}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"TUNEL CORTADO","alternance":"POSIBLES"},{"id":2,"value":"POR","alternance":"RETENCIONES"},{"id":3,"value":"INCENDIO","alternance":"MODERE VELOCIDAD"}]}]', true, true ),
	(0154, 01, 'Averia 01', null, 'Averia 01', '[{"zone":1,"graphics":[{"id":1,"value":88}]},{"zone":2,"align": "left","texts":[{"id":1,"value":"MODERE"},{"id":2,"value":"SU"},{"id":3,"value":"VELOCIDAD"}]}]', true, true ),
	(0155, 01, 'Animal vivo en pista', null, 'Animal vivo en pista', '[{"zone":1,"alternance_ms":3000,"graphics":[{"id":1,"value":141,"alternance":141}]},{"zone":2,"alternance_ms":3000,"align": "left","texts":[{"id":1,"value":"PRECAUCION","alternance":"ANIMAL EN TUNEL"},{"id":2,"value":"ANIMAL EN TUNEL","alternance":"MODERE VELOCIDAD"}]}]', true, true );



INSERT INTO ui.vms_library_hierarchies(vms_library_id, node_parent_id, node_child_id, enabled, visible) VALUES
(01, 0101, 0102, true, true),
(01, 0101, 0103, true, true),
(01, 0101, 0104, true, true),
(01, 0101, 0105, true, true),
(01, 0101, 0106, true, true),
(01, 0101, 0107, true, true),
(01, 0101, 0108, true, true),
(01, 0101, 0109, true, true),
(01, 0101, 0110, true, true),
(01, 0101, 0111, true, true),
(01, 0101, 0112, true, true),
(01, 0101, 0113, true, true),
(01, 0101, 0114, true, true),
(01, 0101, 0115, true, true),
(01, 0101, 0116, true, true),
(01, 0101, 0117, true, true),
(01, 0101, 0118, true, true),
(01, 0101, 0119, true, true),
(01, 0101, 0120, true, true),
(01, 0101, 0121, true, true),
(01, 0101, 0122, true, true),
(01, 0101, 0123, true, true),
(01, 0101, 0124, true, true),
(01, 0101, 0125, true, true),
(01, 0101, 0126, true, true),
(01, 0101, 0127, true, true),
(01, 0101, 0128, true, true),
(01, 0101, 0129, true, true),
(01, 0101, 0130, true, true),
(01, 0101, 0131, true, true),
(01, 0101, 0132, true, true),
(01, 0101, 0133, true, true),
(01, 0101, 0134, true, true),
(01, 0101, 0135, true, true),
(01, 0101, 0136, true, true),
(01, 0101, 0137, true, true),
(01, 0101, 0138, true, true),
(01, 0101, 0139, true, true),
(01, 0101, 0140, true, true),
(01, 0101, 0141, true, true),
(01, 0101, 0142, true, true),
(01, 0101, 0143, true, true),
(01, 0101, 0144, true, true),
(01, 0101, 0145, true, true),
(01, 0101, 0146, true, true),
(01, 0101, 0147, true, true),
(01, 0101, 0148, true, true),
(01, 0101, 0149, true, true),
(01, 0101, 0150, true, true),
(01, 0101, 0151, true, true),
(01, 0101, 0152, true, true),
(01, 0101, 0153, true, true),
(01, 0101, 0154, true, true),
(01, 0101, 0155, true, true);


INSERT INTO ui.vms_library_element_subtypes(element_subtype_id, vms_library_id, enabled, visible) VALUES
('ElementSubtype:19:71', 1, true, true);